### ISSUE TITLE
New Folder won't be detected

### ISSUE THREAD

**Issue by clue404** [LukeSmithxyz/mutt-wizard#101]
Hi,

first of all. Thanks for this great wizard!

I am trying to get to use mutt more and more but I have a little problem. When I use the webmail application or my phone to send an E-Mail to my Archive folder it will automatically create an archive folder with the current year. Today the folder Archive.2019 was create but I am not able to see this one in my mutt folder list. 
What kind of sync do I need to perform to get newly created folders?

Thanks

**Comment by LukeSmithxyz** [comment]
Run the wizard and re-select the "autodetect mailboxes" option, provided you have run `offlineimap` at least once since the folder has been created. You can do this whenever folders have changed.

**Comment by clue404** [comment]
ah alright thanks. It's working
