### ISSUE TITLE
Can't Compose Messages When Starting Neomutt from <terminal> -e neomutt

### ISSUE THREAD

**Issue by JasonB579** [LukeSmithxyz/mutt-wizard#103]
I have a keybinding in my i3 configs for opening neomutt, where I use `urxvt -e neomutt`. Using these configs I run into an issue where I can't compose new messages.

I've tried with with xfce4-terminal, urxvt, and termite and I get the same result with each. If I start neomutt using `<terminal> -e neomutt` and try to create a new message, when it tries to open nvim it immediately throws an error saying `Aborted unmodified message`, seemingly after trying to start nvim and failing.

When I run neomutt from a terminal started normally, it works fine.

**Comment by LukeSmithxyz** [comment]
What is your global `$EDITOR` variable set to? You might want to manually set mutt's editor in the muttrc too.

On January 6, 2019 11:33:08 PM EST, Jason Blocklove <notifications@github.com> wrote:
>I have a keybinding in my i3 configs for opening neomutt, where I use
>`urxvt -e neomutt`. Using these configs I run into an issue where I
>can't compose new messages.
>
>I've tried with with xfce4-terminal, urxvt, and termite and I get the
>same result with each. If I start neomutt using `<terminal> -e neomutt`
>and try to create a new message, when it tries to open nvim it
>immediately throws an error saying `Aborted unmodified message`,
>seemingly after trying to start nvim and failing.
>
>When I run neomutt from a terminal started normally, it works fine.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LukeSmithxyz/mutt-wizard/issues/103

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JasonB579** [comment]
It was set to `nvim`. It seems like manually setting it worked for some reason... Thanks!
