### ISSUE TITLE
neomutt is not a mailbox

### ISSUE THREAD

**Issue by pala69** [LukeSmithxyz/mutt-wizard#105]
Hello,

I got the same error like the post from 18.03.2018

offlineimap -a pala-m1  runs without any error

under /home/pala/.mail/pala-m1 are the folders get from offlineimap.

after starting neomutt there in the statusline the error /home/pala/.mail/pala-m1 is not a mailbox.

I had no idea what to do

Thanks

**Comment by pala69** [comment]
Output from offlinemap -a pala-m1 --info

Folderlist:
 Archive
 Drafts
 INBOX
 INBOX/Hetzner
 INBOX/mbintern
 INBOX/Telekom
 Junk
 Sent
 Trash

Local repository 'pala-m1-local': type 'Maildir'
Folderlist:
 Trash.mailbox
 Trash
 Drafts
 Sent
 Archive
 INBOX.Telekom
 INBOX.mbintern
 INBOX
 Junk
 INBOX.Hetzner

the content from /home/pala/.mail/pala-m1

[Di Jan 08 22:39] pala@viking :~/.mail/pala-m1 $:  ls -la
insgesamt 48
drwxrwxr-x. 12 pala pala 4096  8. Jan 22:22 .
drwxrwxr-x.  3 pala pala 4096  8. Jan 22:22 ..
drwx------.  5 pala pala 4096  8. Jan 22:22 Archive
drwx------.  5 pala pala 4096  8. Jan 22:22 Drafts
drwx------.  5 pala pala 4096  8. Jan 22:22 INBOX
drwx------.  5 pala pala 4096  8. Jan 22:22 INBOX.Hetzner
drwx------.  5 pala pala 4096  8. Jan 22:22 INBOX.mbintern
drwx------.  5 pala pala 4096  8. Jan 22:22 INBOX.Telekom
drwx------.  5 pala pala 4096  8. Jan 22:22 Junk
drwx------.  5 pala pala 4096  8. Jan 22:22 Sent
drwx------.  5 pala pala 4096  8. Jan 22:22 Trash
drwx------.  5 pala pala 4096  8. Jan 22:22 Trash.mailbox

**Comment by 4andreas** [comment]
had same problem, until i figured out i dont have any mailboxes in my accounts/name.muttrc
add them manually or run mutt-wizard.sh -> Redetect mailboxes
mine seemed randomly ordered so had to edit them after

**Comment by LukeSmithxyz** [comment]
Provided you _have_G run the "redetect mailboxes" option, in this case you're going to have to go into `~/.config/mutt/accounts/` and manually edit your config file to set the INBOX.

I.e. something like:
```
set spoolfile = "+INBOX"
```
or which ever inbox you want to start on. This is because your mail server has these multiple inboxes and the wizard might not decide which one is the right one.
