### ISSUE TITLE
Running sh file gives me an error message 

### ISSUE THREAD

**Issue by MontyMooMan** [LukeSmithxyz/mutt-wizard#106]
"Unable to read response from dialog. Exiting." is what pops up whenever I try to run the sh from the terminal.
I do have neomutt installed; is this likely part of my problem?

Running Manjaro.

**Comment by LukeSmithxyz** [comment]
When you call it a "sh", you're not manually running it as
`sh mutt-wizard.sh` are you? This is a bash script. Be sure to execute
it with either `bash` or directly as `./mutt-wizard.sh`.

**Comment by MontyMooMan** [comment]
Thanks for the response Luke. The error is my own fault. I did not install all of the dependencies.  Sorry about that.
