### ISSUE TITLE
handle re-runs

### ISSUE THREAD

**Issue by halberom** [LukeSmithxyz/mutt-wizard#112]
Each time the script is run, purge the existing config files/dirs, or similar.  I borked the first run, by not having a valid gpg key, and then subsequent runs weren't populating files correctly - e.g. the [general] section, and the /tmp/name_boxes weren't being handled.

nice work, liking the youtube vids, picked up some nice tips.

**Comment by LukeSmithxyz** [comment]
Just manually select to delete an/all account(s). This will clean up all old configs. You are intended to be able to run the wizard multiple times not in the same sitting, so I'm not going to make "delete all old accounts" the default.
