### ISSUE TITLE
systemd service instead of mailsync.sh

### ISSUE THREAD

**Issue by luukvbaal** [LukeSmithxyz/mutt-wizard#113]
Any reason you're using a cronned mailsync.sh over systemd services as in [arch wiki](https://wiki.archlinux.org/index.php/OfflineIMAP#Running_offlineimap_in_the_background)? This method keeps the connection open and only syncs if changes have been detected rather than force sync every time it is run.
See: [mailsync.sh](https://ptpb.pw/SblI) vs [systemd-services](https://ptpb.pw/g86w) performance.

**Comment by LukeSmithxyz** [comment]
Many Linux distributions, Mac OS and BSD all do not use systemd. Making this the norm would break compatibility.

**Comment by luukvbaal** [comment]
Fair enough but the main functionality comes from daemonizing the offlineimap instance through the `.offlineimaprc` settings mentioned in the arch wiki. The same result could be achieved by autostarting offlinemap with this config at boot on OSX or BSD i.e. suggesting cron `@reboot` instead of every 5 minutes in the `mailsync.sh` comment.
