### ISSUE TITLE
Unable to check mail

### ISSUE THREAD

**Issue by xq42** [LukeSmithxyz/mutt-wizard#115]
As of 1/20/19, I'm suddenly unable to check mail using "o", "O", or ./mailsync.sh

So far as I know I made no changes, but the output of ./mailsync.sh is:

./mailsync.sh: 27: ./mailsync.sh: offlineimap: not found
./mailsync.sh: 41: ./mailsync.sh: notmuch: not found

Both offlineimap & notmuch are no longer installed...?

Trying to install offlineimap results in this:

sudo apt install offlineimap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 offlineimap : Depends: python-imaplib2 (>= 2.55) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I've not been able to determine how or why python-imaplib2 can't be installed. I've got another, essentially unmodified Debian 9 install where offlineimap works just fine so I'm just baffled...

I've no idea if you can help with this or have any insights, but I'm pretty well stuck if I cannot get past this.

FYI, I tried removing all mail files & directories and everything installed when ./mutt-wizard.sh is run, then set up a my main email account but that still didn't work...

Let me know if there's anything more I can post that might help!

**Comment by LukeSmithxyz** [comment]
Well this isn't really a problem for this repo and more of a question for your distro, but have you actually updated/upgraded all your packages recently?
