### ISSUE TITLE
no mbsync?

### ISSUE THREAD

**Issue by jungle-boogie** [LukeSmithxyz/mutt-wizard#125]
Hi Luke,

I used offlineimap for about a year or so but switched to mbsync/isync and have liked it since.
Have you tried it? Is there any reason you're sticking with offlineimap?

http://isync.sourceforge.net/mbsync.html

Thanks!

**Comment by LukeSmithxyz** [comment]
I've been trying to switch for months, but I have not consistent way to guess the structure of the remote mailboxes without offlineimap. mbsync/isync, from what I know, require you to manually set all of your mailboxes in your account to be able to sync each.

See here:
https://lukesmith.xyz/wishlist.html#imapdetect
