### ISSUE TITLE
Cronie existence should be checked to autosync option

### ISSUE THREAD

**Issue by ceylanb** [LukeSmithxyz/mutt-wizard#128]
When I try to enable auto sync, it doesn't work due to missing cronie package. I think, cronie existence should be checked or some explanation about the issue should be added to README.

**Comment by ceylanb** [comment]
Sorry I couldn't see the explanation about it in README. Even so, It is required to check existence of a cron manager when autosync is clicked.

**Comment by LukeSmithxyz** [comment]
Closing. It's already in the directions, but I'll be pushing some changes to the repo soon that will make it unnecessary anyway.
