### ISSUE TITLE
Can't build path of /etc/aliases

### ISSUE THREAD

**Issue by philipnelson99** [LukeSmithxyz/mutt-wizard#13]
Not exactly sure what's happening here. This is what happens when I open mutt
`Error: impossible to build path of 'etc/aliases'.`
`Error in /home/user/.config/mutt/muttrc, line 8: `
`source: errors in /home/user/.config/mutt/muttrc`
`Error: issue converting path to absolute (No such file or directory)Press any key to continue...`
`Error: issue converting path to absolute (No such file or directory)Error: issue converting path to absolute (No such file or directory)`

**Comment by LukeSmithxyz** [comment]
The system automatically sources a file where you can put aliases/address book info. It seems like you've deleted yours?

Either remove the line from the muttrc that sources it or just run
```
touch ~/.config/mutt/etc/aliases
```

**Comment by philipnelson99** [comment]
Okay, thank you Luke! I'm sorry I'm so incompetent. Mutt still isn't working quite right but it isn't your script, it's probably just me.

**Comment by LukeSmithxyz** [comment]
If you feel like you messed it all up, just rm `~/.offlineimaprc`, `~/.config/mutt` and reclone the repo
```
git clone https://github.com/lukesmithxyz/mutt-wizard ~/.config/mutt
```
and try again. Sounds like you at least deleted the etc/ folder which would've hurt other things too.

**Comment by philipnelson99** [comment]
It still isn't working for some reason. I cloned the entire repo into `~/.config/mutt`, and ran the script.
I also get an errror when I open mutt that says
`/var/mail/user is not a mailbox`
Mail on linux has always been a struggle for me, I'm gonna reopen the issue until I get this figured out.

**Comment by LukeSmithxyz** [comment]
Did you finalize the wizard by running the mailbox detector?

**Comment by philipnelson99** [comment]
Oh, well you know it works if you read. Thank you for the tool, I'm going to creep back into the shadows now because I can't read. Thanks Luke.
