### ISSUE TITLE
[SSL: WRONG_SSL_VERSION] wrong ssl version

### ISSUE THREAD

**Issue by ceylanb** [LukeSmithxyz/mutt-wizard#131]
I have come accros WRONG_SSL_VERSION error and I have solved it. The problem was about SSL version of the mail server (its configuration parameters come from domains.csv). In domains.csv there is no field for ssl version therefore line of "ssl_version = tls1_2" in "/autoconf/offlineimap_profile" should be removed or an ssl_version field added to domains.csv and corresponding configurations should be handled.

**Comment by LukeSmithxyz** [comment]
Closed after the switch to isync from offlineimap.
