### ISSUE TITLE
<check-stats> will not run in account switch macro

### ISSUE THREAD

**Issue by StormFireFox1** [LukeSmithxyz/mutt-wizard#133]
I have not modified the scripts generated by the wizard.
Every time that the `i2`, `i3`, ... macros are used to switch between accounts, `<check-stats>`, the function will not run. Instead, it seems as if neomutt interprets them as consecutive keystrokes with no meaning, since every time I switch accounts, the following text shows at the command part of neomutt:

`Open mailbox: heck-stats>`

Even putting the function in its own separate macro will not work, such as:
`macro index,pager iS '<check-stats>'`

**Comment by LukeSmithxyz** [comment]
That's strange. It works as intended on my accounts. It's possible that for some reason there's an error in quotation marks, or I haven't pushed a fix... Mine look like this:

```
macro index,pager i1 '<sync-mailbox><enter-command>source "/home/luke/.config/mutt"/accounts/luke.muttrc<enter><change-folder>!<enter>;<check-stats>'
macro index,pager i2 '<sync-mailbox><enter-command>source "/home/luke/.config/mutt"/accounts/archive.muttrc<enter><change-folder>!<enter>;<check-stats>'
```

And work perfectly, what exactly do your lines produced look like?

**Comment by StormFireFox1** [comment]
This is the file contents of `personal.muttrc`:

```
macro index,pager i3 '<sync-mailbox><enter-command>source "/home/ghost/.config/mutt"/accounts/gmail.muttrc<enter><change-folder>!<enter>;<check-stats>'
source /home/ghost/.config/mutt/accounts/gard-us.muttrc
macro index,pager i1 '<sync-mailbox><enter-command>source "/home/ghost/.config/mutt"/accounts/mail2.muttrc<enter><change-folder>!<enter>;<check-stats>'
macro index,pager i2 '<sync-mailbox><enter-command>source "/home/ghost/.config/mutt"/accounts/mail3.muttrc<enter><change-folder>!<enter>;<check-stats>'
macro index,pager iS '<check-stats>'
```

That last function was the one I added, same outcome.

**Comment by StormFireFox1** [comment]
Never mind, turns out that the neomutt version that my Kubuntu distribution installed was older, and perhaps did not contain the `<check-stats>` function. After upgrading the distribution, the problem has disappeared.
