### ISSUE TITLE
Unable to read response from dialogue 

### ISSUE THREAD

**Issue by TheLazyLemur** [LukeSmithxyz/mutt-wizard#135]
Using Solus 4.

**Comment by LukeSmithxyz** [comment]
What exact command are you using to run it?

Also, what does `ls -l /usr/bin/sh` show?

**Comment by deadpyxel** [comment]
I am having the same issue on Ubuntu 18.04 LTS

my output to `ls -l /usr/bin/sh` says:
```
ls: cannot access '/usr/bin/sh': No such file or directory
```

**Comment by LukeSmithxyz** [comment]
Run it explicitly as `bash mutt-wizard.sh` then.

The apparent problem is that however you are running the command, it's being run as `sh` rather than `bash`.

**Comment by deadpyxel** [comment]
I see, I was going to say that I am using `zsh` as my terminal. do you think that is the problem?

**Comment by TheLazyLemur** [comment]
Same problem here still On both Ubuntu 19.04 and Solus 4.
Output of ```ls -l /usr/bin/sh``` was ```rwxrwxrwx 1 root root 4 Apr 19 12:43 /usr/bin/sh -> dash```

**Comment by TheLazyLemur** [comment]
also just tested on my Arch VM and still have the same issue

**Comment by deadpyxel** [comment]
The gitlab version of this repo (that is in beta) is working for me, just finishing syncing the mailbox.

**Comment by LukeSmithxyz** [comment]
Now the Github version does not use dialog either, avoiding this and any other dialog problems. Closing.
