### ISSUE TITLE
How to create new folder

### ISSUE THREAD

**Issue by ngortheone** [LukeSmithxyz/mutt-wizard#136]
Hi @LukeSmithxyz 

I tried your wizard to get started with mutt.

I ran into a problem when I need to create a new folder in my mailbox. When I press `Shift + c` it says that creating new folders is only available for imap mailbox. I have configured an IMAP mailbox though..

I assume this is because there is `offlineimap` sitting in between mutt and my mail server. Hence the question - how can I create new folders in mutt such that they would also appear in on the server ( because I sometimes use web-ui) ?

Thanks

**Comment by LukeSmithxyz** [comment]
mutt-wizard has been rewritten and I suspect this issue is solved in that `offlineimap` is no longer used. `isync` is more flexible in sync rules. Although this binding has changed, I've tried creating folders via mutt now and it works.
