### ISSUE TITLE
Mutt and by extension NeoMutt unable to send mail

### ISSUE THREAD

**Issue by lukelane124** [LukeSmithxyz/mutt-wizard#139]
'''
Error in /home/lucas/.config/mutt/muttrc, line 33: goto-parent: no such function in map
Error in /home/lucas/.config/mutt/muttrc, line 35: top-page: no such function in map
Error in /home/lucas/.config/mutt/muttrc, line 36: bottom-page: no such function in map
Error in /home/lucas/.config/mutt/muttrc, line 93: index_author: no such object
Error in /home/lucas/.config/mutt/muttrc, line 94: index_number: no such object
Error in /home/lucas/.config/mutt/muttrc, line 95: index_subject: no such object
Error in /home/lucas/.config/mutt/muttrc, line 99: index_author: no such object
Error in /home/lucas/.config/mutt/muttrc, line 100: index_subject: no such object
source: errors in /home/lucas/.config/mutt/muttrc
Error sending message, child exited 127 (Exec error.).
Could not send the message.
'''
is the error I get when attempting to send mail with '$ bash -c "echo i am here|mutt -s good user@example.com"' email redacted for reasons.

**Comment by LukeSmithxyz** [comment]
All of the displayed errors are because you are using mutt with a config file for neomutt. Do you have any reason for thinking there is another problem?

**Comment by lukelane124** [comment]
When I attempt to send mail from neomutt I get a 127 exit code and a failed send.
I found some where to execute that line above to test. replacing mutt with neomut yields 'Error sending message, child exited 127 (Exec error.).
Could not send the message.'

**Comment by lukelane124** [comment]
![2019-04-19-120816_941x507_scrot](https://user-images.githubusercontent.com/9681522/56435082-c6214480-629c-11e9-91f4-1d126b44c8ba.png)

**Comment by LukeSmithxyz** [comment]
Do you not have `msmtp` installed?

**Comment by lukelane124** [comment]
Okay, after installing msmtp: I get a different error now, possibly due to msmtp not being installed during initial setup...
msmtp: evelope from address ...@....com not accepted by the server
msntp: server message: 530 5.7.0 Must issue a STARTTLS command first
msmtp: could not send mail.

Should I assume this is a config problem and just set everything back up?
