### ISSUE TITLE
[setup new account] - account folder no such file or directory

### ISSUE THREAD

**Issue by daebenji** [LukeSmithxyz/mutt-wizard#141]
using the latest mw:

it appears that the ~/.config/mutt/accounts folder was not created before adding a new Account when starting on a fresh system. Therefore the setup goes wrong (because it cannot store the accounts muttrc file), even script runs through it and doesn't complain.

the output of ./mv add says: /home/user/.config/mutt/accounts/ "no such file or directory"

**Comment by LukeSmithxyz** [comment]
Are you sure you're using the most recent version?

This should've been fixed in dbb68536393fbe62122339c446af3f21540cab35 about an hour ago.

**Comment by daebenji** [comment]
> Are you sure you're using the most recent version?
> 
> This should've been fixed in [dbb6853](https://github.com/LukeSmithxyz/mutt-wizard/commit/dbb68536393fbe62122339c446af3f21540cab35) about an hour ago.

Sorry, went for lunch and reported it the bug afterwards. thanks for the quick fix!
