### ISSUE TITLE
[REQUEST] khard as addressbook

### ISSUE THREAD

**Issue by hum6ug** [LukeSmithxyz/mutt-wizard#147]
Hi Luke,

first of all, thanks for the great wizard!

I just switch to the new version from AUR an realized the abook dependency. Wouldn't it be better to use something like [khard](https://github.com/scheibler/khard)? It has CardDAV support via [vdirsyncer](https://github.com/pimutils/vdirsyncer).

After a complete setup of vdirsyncer and khard one can use this to access Contacs from mutt:

```
set query_command= "khard email --parsable --search-in-source-files %s"
bind editor <Tab> complete-query
bind editor ^T    complete
macro index,pager A \
    "<pipe-message>khard add-email<return>" \
        "add the sender email address to khard"
```

**Comment by LukeSmithxyz** [comment]
Isn't carddav for syncing contacts? khard is a much bigger dependency and doesn't have the independent user interface that abook has.

I'm not particularly interested in giving the user the "ability" of syncing their contact information with a Google server. They can export their Google contacts and import them into abook file already, but the implicit point of using an email system like this is to localize email usage. Of course, if someone wants/needs compatibility with `vdirsyncer` they can easily add it as you say, but I don't really see a good reason for nudging people to that default.

**Comment by hum6ug** [comment]
Well okay.

I am definitely not suggesting to use it with Google. I have my own CardDAV Server and it would be perfect to use it together. But alright. I'll just implement it in my config
