### ISSUE TITLE
strange Mail Box name

### ISSUE THREAD

**Issue by peet1234** [LukeSmithxyz/mutt-wizard#149]
i'm using Gmail and I'm from Thai, my mail box have some strange name (see pic)
![2019-04-25_16-25](https://user-images.githubusercontent.com/37007880/56726611-4c47fa00-6779-11e9-92dc-0b2978e3f24a.png)

**Comment by LukeSmithxyz** [comment]
What is your `$LANG` variable?

I'd be interested if other people with non Latin mailbox names (CJK specially) have had similar problems.

**Comment by sarpik** [comment]
Hello, I've had my language set to `Lithuanian` in Gmail, and my mailboxes aren't even showing up on that account. I've changed the language to `English`, but had to remove the `~/.local/share/mail/<account>/` folder for a successful re-sync to happen.

Is it okay to rename mailboxes yourself in the `~/.local/share/mail/<account>/` folder?

**Comment by rakab** [comment]
I had similar problem with German umlauts. Here is how I fixed it for `offlineimap`:
First delete all folders from `.mail/your_mail/` dir, download following script and place it under `~/.config/mutt/` (or wherever you prefer):
https://gist.github.com/rakab/5353e203564113c9ea0f0ef8000530b3

Finally, edit `~/.offlineimaprc`, like this (Important lines are in bold):
<pre>
[general]
accounts = your_mail
starttls = yes
ssl = yes
pythonfile = ~/.config/mutt/credentials/imappwd.py
<b>pythonfile += ~/.config/mutt/utf7.py</b>

[Account gmx]

localrepository = gmx-local
remoterepository = gmx-remote

[Repository gmx-remote]
auth_mechanisms = LOGIN
type = IMAP
remoteuser = your@mail.com
remotepasseval = mailpasswd("your_mail")
remotehost = imap.your_mail.com
remoteport = your_port
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
<b>nametrans = lambda foldername: foldername.decode('imap4-utf-7').encode('utf-8')</b>

[Repository gmx-local]
type = Maildir
localfolders = ~/.mail/your_mail
<b>nametrans = lambda foldername: foldername.decode('utf-8').encode('imap4-utf-7')</b>

</pre>
After this mutt-wizard will correctly label the mailboxes.

**Comment by LukeSmithxyz** [comment]
With the default mutt-wizard settings for isync/mbsync you should be okay to manually move or rename a local mail directory (or manually `cp` mails, etc.). mbsync should create the corresponding folder remotely on next sync and delete whatever you delete.

@rakab Well this option isn't really applicable here anymore since mutt-wizard no longer uses offlineimap. I'll look for an equivalent setting for isync/mbsync.

**Comment by peet1234** [comment]
> What is your `$LANG` variable?
> 
> I'd be interested if other people with non Latin mailbox names (CJK specially) have had similar problems.

en_US

**Comment by LukeSmithxyz** [comment]
You don't have UTF-8 (`en_US.UTF-8`)? I think that could be a cause of the problem. Is there some reason you don't have it?

I would edit `/etc/locale.conf` and add/replace your `LANG` to `LANG=en_US.UTF-8`, rerun `locale-gen` and reboot.

**Comment by peet1234** [comment]
oh,  I'm sorry!
my locale.conf
LANG=en_US.UTF-8

can i have more than ones?
LANG=en_US.UTF-8,th_TH.UTF-8 (is that right?)

thank you for your reply
Pisit


in 19/04/26 01:52PM, Luke Smith wrote:

**Comment by isheshukov** [comment]
As far as i understand that feature is not implemented in isync
https://sourceforge.net/p/isync/mailman/message/32692991/
https://sourceforge.net/p/isync/mailman/message/34881043/

There is an [AUR package](https://aur.archlinux.org/packages/isync-utf8-mailboxes/) that presumably fixes this, but I haven't had any luck with it.

**Comment by LukeSmithxyz** [comment]
Okay, if this issue is inherent to `isync`, I'm going to close this issue as being beyond the scope of this repo.

I'll make a note of this disjunct in the README.
