### ISSUE TITLE
Error with decription of crendentials

### ISSUE THREAD

**Issue by KisuYami** [LukeSmithxyz/mutt-wizard#150]
Error:
    gpg: can't open '/home/reberti//.config/mutt/credentials/main.gpg': No such file or directory
    gpg: decrypt_message failed: No such file or directory
    msmtp: cannot read output of 'gpg -d --quiet --for-your-eyes-only --no-tty ~/.config/mutt/credentials/main.gpg | sed -e '$a\''

This error appears inside the neomutt itself, i have used pass init email, and the worked before the "great change". the credentials folders don't exist.

version from AUR.

**Comment by LukeSmithxyz** [comment]
The rewritten version of mutt-wizard is installed to your system, not your dotfiles. So remove all your obsolete dotfiles from the original mutt-wizard version. Backup what you need then:
```
rm -rf ~/.config/mutt ~/.config/msmtp ~/.msmtprc
```

**Comment by KisuYami** [comment]
Line found in .offliniemap
pythonfile = ~/.config/mutt/credentials/imappwd.py

**Comment by KisuYami** [comment]
Worked, thanks, i have deleted everything but the mstp files, i dind't know about them.

**Comment by LukeSmithxyz** [comment]
Okay great. Yeah sorry, I guess I didn't mention explicitly that the new version isn't supposed to be "backwards compatible".

**Comment by KisuYami** [comment]
I think that should be put explict that process with old files, and all the files that have to be modified(or removed) as you did here. Thanks and have a nice day.
