### ISSUE TITLE
mailsync fails if `~/.local/share/mail/<account>` exists

### ISSUE THREAD

**Issue by sarpik** [LukeSmithxyz/mutt-wizard#152]
I wanted to update to the new "make" version of `mw`, so I went throught the install steps.

Then I proceeded with `mw add` and tried adding my account. It failed. Twice. I then renamed the `~/.local/share/mail/` folder to test things out, reran the `mw add` and now it worked!

So it seems like `mbsync` somehow fails if mail already exists. The solution would probably be to either inform the user that the `mail` for the account already exists and that mbsync might fail, and maybe provide with a solution to rename the old folder, run mbsync, check if things work and then either keep as-is, merge the two folders or undo the rename.

Cheers!

**Comment by LukeSmithxyz** [comment]
Well, what was the error message? Mutt-wizard does check for identically named accounts, but only in the `accounts/` directory.

I've done what you describe many times in bug testing without an error.

**Comment by sarpik** [comment]
Can't reproduce this myself now. What I also changed was `~/.config/msmtp/config`. There were 2 duplicate accounts, and once I deleted that one, renamed the ~/.local/share/mail/<account>` folder, it worked. Might've been something different too - sorry for not exactly knowing why.

I suppose we can close this until I or someone else is able to reproduce.
