### ISSUE TITLE
Cannot refresh my mailbox directories

### ISSUE THREAD

**Issue by abdoulayeYATERA** [LukeSmithxyz/mutt-wizard#160]
Hey ! Nice new version !
I don't find the way to update the folder list of an account.
I just do it directly in the account rc file manually for the moment.
Is that wanted ? Or I miss something. 
Thank's!

**Comment by LukeSmithxyz** [comment]
The only reason this "feature" existed in the previous mutt-wizard was because it was necessary for installing and configuring offlineimap successfully.

Just change the `mailboxes` variable in the account muttrc files if you want to change what mailboxes are acknowledged.
