### ISSUE TITLE
Not much is not setup by the script

### ISSUE THREAD

**Issue by czarnoff** [LukeSmithxyz/mutt-wizard#164]
Not much wasn't working for me because it had never been used before on my system.  I was getting a hidden message requesting notmuch setup.  The setup could be run or a default notmuch rc file could be written by the script when mw add is executed.

**Comment by LukeSmithxyz** [comment]
Are you saying that `mailsync` was hanging waiting on `notmuch` or there was just a hidden/suppressed error?

**Comment by LukeSmithxyz** [comment]
Either way, I've added a conditional that checks to see if mutt is configured whenever an account is added, and if not, sets it up. I'll test it on a fresh install in a second, but it should be good.
