### ISSUE TITLE
Add libnotify as a dependency. (notify-send: not found)

### ISSUE THREAD

**Issue by oyren** [LukeSmithxyz/mutt-wizard#165]
Maybe you should add libnotify as a dependency in the readme, to avoid the following error for notification.
```
/usr/bin/mailsync: 13: /usr/bin/mailsync: notify-send: not found
```
In Debian and Ubuntu the package name is 'libnotify-bin'.

**Comment by LukeSmithxyz** [comment]
I'll make a note of it in the README.
