### ISSUE TITLE
git clone link

### ISSUE THREAD

**Issue by dcegielka** [LukeSmithxyz/mutt-wizard#167]
https://youtu.be/mPiQuWbF57M?t=111

`git clone` doesn't work? :)

```
git clone https://github.com/LukeSmithxyz/mutt-wizard
cd mutt-wizard
sudo make install
```
try (+.git):

`git clone https://github.com/LukeSmithxyz/mutt-wizard.git`

**Comment by mikeziri** [comment]
github https clones are allways with .git in the end. check the repo homepage and click on "Clone or download":

git clone **https://github.com/LukeSmithxyz/mutt-wizard.git**

**Comment by LukeSmithxyz** [comment]
What are you talking about? You've always been able to clone Github urls without the `.git` extension...
