### ISSUE TITLE
GPG failing during setup

### ISSUE THREAD

**Issue by jkeen871** [LukeSmithxyz/mutt-wizard#168]
I am seeing this issue durring setup 

gpg: error retrieving 'xxxx@gmail.com' via WKD: No data
gpg: xxxx@gmail.com: skipped: No data
gpg: [stdin]: encryption failed: No data

Im not sure if there are some prerequisite steps that should be performed?

**Comment by LukeSmithxyz** [comment]
Do you have a gpg key pair for the email address you gave `pass`?

**Comment by jkeen871** [comment]
No I dont have a GPG pair.  I've never used one.  I just use gmail.

**Comment by LukeSmithxyz** [comment]
A GPG key pair is required for pass.
