### ISSUE TITLE
Prompt the user to set MaxMessages in .mbsyncrc

### ISSUE THREAD

**Issue by iMouath** [LukeSmithxyz/mutt-wizard#171]
<details><summary>MaxMessages from man mbsync</summary>
<p>
Sets the maximum number of messages to keep in each Slave mailbox. 
This is useful for mailboxes where you keep a complete archive on the server, but want to mirror only the last messages (for instance, for mailing lists). 
The messages that were the first to arrive in the mailbox (independently of the actual date of the message) will be deleted first. 
Messages that are flagged (marked as important) and (by default) unread messages will not be automatically deleted. If count is 0, the maximum number of messages is unlimited (Default: 0).
</p>
</details>

Would be really helpful to set the option `MaxMessages` in `.mbsyncrc` during the account creation, or set a reasonable default.

**Comment by LukeSmithxyz** [comment]
Added.
