### ISSUE TITLE
Error sending message, child exited 78()

### ISSUE THREAD

**Issue by Minichota** [LukeSmithxyz/mutt-wizard#172]
When attempting to send a message, this error occurs

**Comment by LukeSmithxyz** [comment]
Send yourself a message with `msmtp` to see the exact error. Run:
```
echo "Some text" | msmtp your@email.address -a accountname
```
See what error it produces.

**Comment by Minichota** [comment]
> echo "Some text" | msmtp your@email.address -a accountname
Upon running this command I get this error:
 msmtp: account coding not found: no configuration file available
when I run:
mw ls
I get:
 1: coding

**Comment by LukeSmithxyz** [comment]
Attach your `~/.config/msmtp/config` file. What distro are you using? Did you get any errors on install?

**Comment by Minichota** [comment]
[config.txt](https://github.com/LukeSmithxyz/mutt-wizard/files/3123403/config.txt)
I'm using linux mint, I didn't recieve any errors on install

**Comment by LukeSmithxyz** [comment]
Oh a gmail account. Are you absolutely sure you've enabled "less secure" applications? I just retried mw with a standard gmail account and the default settings are working to send mail.

Your error is consistent with a problem in the msmtp config, but that is exactly the format that is working perfect for my machine...

It could be a problem with the internet connection you're on I suppose. Could you run `telnet smtp.gmail.com 587` and see if errors pop up?

**Comment by Minichota** [comment]
I'm certain I have enabled less secure applications.  When I ran telnet with your command I got this output then it didn't print anything else.
Trying 2607:f8b0:4001:c14::6d...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP 64sm13041185ite.42 - gsmtp

**Comment by LukeSmithxyz** [comment]
Well that looks like you're connecting successfully... I honestly can't tell you what's going wrong.

Actually, there is one thing I can think of: have you ever set up msmtp before? If you have another msmtp config file in `~/.msmtprc`, it might be taking precedence over the config in the `~/.config/msmtp/config` which `mw` creates. Delete `~/.msmtprc` and see if it works now...

**Comment by Minichota** [comment]
I don't seem to have a  ~/.msmtprc file.  I'm not sure what's wrong here

**Comment by LukeSmithxyz** [comment]
Here's my last crazy guess for now: Linux mint uses an old non-xdg-compliant version of msmtp. Try running this:

```
ln -s ~/.config/msmtp/config ~/.msmtprc
```

And if you can't send mail now, I just don't know.

**Comment by Minichota** [comment]
Okay, that didn't work but I just noticed I get some errors when I run neomutt.  They are as follows:
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 47: Function 'goto-parent' not available for menu 'browser'
Error in /home/ouji/.config/mutt/muttrc, line 2: source: file /usr/share/mutt-wizard/mutt-wizard.muttrc could not be sourced.
source: errors in /home/ouji/.config/mutt/muttrc
Press any key to continue...

**Comment by LukeSmithxyz** [comment]
Uh... did these errors only just now start happening? Do you not have neomutt installed?

**Comment by Minichota** [comment]
I believe these errors have been going for a while.  I do have neomutt installed.

**Comment by bruderbarna** [comment]
I experienced pretty much the same thing unfortunately (xubuntu 18.04 neomutt 20171215+dfsg.1-1). Possibly the goto-parent is not yet available in this fairly old version. I didn't check though.
If I have some time I'll try to figure out the exact cause of this, and if I manage to stumble upon all the time in the world I'll also make a seperate issue (if there is none) and a PR to fix this. There must be a substitute for goto-parent for older versions of neomutt that is also supported by newer versions (if my guess is correct about the version difference being the problem).

 I commented out line 47 of mutt-wizard.muttrc, and now I don't get errors. But I'm not able to move up a folder in the file manager with the h key, obviously.

I suppose the error in this file doesn't have anything to do with not being able to send mail.
The problem with sending mail however was fixed for me by symlinking the msmtp config file to ~/.msmtprc.

**Comment by LukeSmithxyz** [comment]
>  The problem with sending mail however was fixed for me by symlinking the msmtp config file to ~/.msmtprc.

That's the problem! Oh Lord, Ubuntu/Mint's repos must be uses version older than when `msmtp` added XDG compliance... Same issue as `goto-parent`.

For Ubuntu/Mint/Debian users, try this and it should fix your problem:

```
ln -s ~/.config/msmtp/config ~/.msmtprc
```

I'm having this run on such machines automatically for the time being.

It's ridiculous the amount of breakage that can come from using a "stable" version of software! I'm going to add a note about this on the readme.
