### ISSUE TITLE
"mw cron" does not detect crond on Void

### ISSUE THREAD

**Issue by joestandring** [LukeSmithxyz/mutt-wizard#177]
I've configured an account using `mw add` successfully, however I'm unable to run `mw cron` despite enableing and starting the service with sv.
This worked successfuly on my arch machine, so my guess is it may have something to do with using `ln -sf /etc/sv/cronie /var/service/` as opposed to `systemctl enable cronie.service`

**Comment by LukeSmithxyz** [comment]
Could you run `pgrep cron` and see what pops up?

**Comment by joestandring** [comment]
running `pgrep cron` returns:
```
641
3261
```

**Comment by LukeSmithxyz** [comment]
Oops, I meant `pgrep -l cron`.

**Comment by joestandring** [comment]
ok that shows `648 cronie-crond`

**Comment by LukeSmithxyz** [comment]
Okay. I've changed the cron check to be much more liberal so the most recenet version should work for you and other people on systems with different cron process names.
