### ISSUE TITLE
st is closed immediately when neomutt is launched

### ISSUE THREAD

**Issue by arminWel** [LukeSmithxyz/mutt-wizard#179]
When starting neomutt in st after running the setup, st will crash. However this is neither the case with a blank setup of neomutt or with an other terminal. I use the st setup from https://github.com/LukeSmithxyz/st. 

When running 
`st -e neomutt` 
it will prompt
`erresc: invalid color (null)
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  2242
  Current serial number in output stream:  2862`

If you know any potential source of failure, I'd be interested to hear.

**Comment by LukeSmithxyz** [comment]
Dup https://github.com/LukeSmithxyz/voidrice/issues/284
