### ISSUE TITLE
cron asks for pgp passphrase every time

### ISSUE THREAD

**Issue by joinemm** [LukeSmithxyz/mutt-wizard#180]
I set a cronjob to update my email using mw cron, but now every once in a while I get prompt to enter the openpgp password. This isn't the intended behaviour right?

**Comment by LukeSmithxyz** [comment]
Consult the readme. Either increase the cache time on your GPG key pair or install and set up a program like `pam-gnupg`: https://github.com/cruegge/pam-gnupg.

This ensures that you don't need to insert your password every time.
