### ISSUE TITLE
mbsync not working with gmail

### ISSUE THREAD

**Issue by richard134** [LukeSmithxyz/mutt-wizard#184]
When I try to sync my gmail using the mutt wizard I get the following error message,

```
Creating profiles for `USER`...DONE.
[SASL-XOAUTH2] - Requesting authID![SASL-XOAUTH2] - Requesting token
![SASL-XOAUTH2] - filling prompts
![SASL-XOAUTH2] - Requesting authID![SASL-XOAUTH2] - Requesting token
!Error: IMAP wants more steps despite successful SASL authentication.
```

If i add ```AuthMechs LOGIN``` to the ```~/.mbsyncrc``` config file, mbsync works as expected.

I have tried both with using a "App password" on an account with Two-factor authentication and on an account with the setting "access to less secure apps" enabled. Both with the same result.

**Comment by richard134** [comment]
I can add that everything works out of the box using cock.li as in your recent video post.

**Comment by LukeSmithxyz** [comment]
I can't replicate this. My gmail is working. Do you have a `@gmail.com` address or is it another email service that uses Google mail (like a business or university)?

So had you tried it without TFA by any chance?

**Comment by Rafmaninoff** [comment]
I can replicate this using my @gmail.com address. I have tried using an app password with 2FA enabled and also disabling 2FA. no success in getting it to work. it worked well with my other (@airmail.cc) email address.

**Comment by LukeSmithxyz** [comment]
Have you enabled IMAP in the Gmail settings menu?

**Comment by Rafmaninoff** [comment]
It is enabled, I fully updated my system and muttwizard to check again and it's still not working.

**Comment by ksuhiyp** [comment]
Same issue here, mbsync stopped syncing recently, I am using App password on 2FA

`Error: IMAP wants more steps despite successful SASL authentication.
`

**Comment by ksuhiyp** [comment]
@Rafmaninoff have you found any solution to this?

**Comment by liubianshi** [comment]
Same issue. Resolved by add `AuthMechs PLAIN` to the `~/.mbsyncrc`.

**Comment by ekhall** [comment]
Same issue here. Have tried with 2FA and without, including with app specific password. Even with @liubianshi 's AuthMechs above I'm getting either token failures or authentication failures. Using gmail with a personal domain.

**Comment by Sevastyan** [comment]
Try recompiling mutt with different SASL library.

**Comment by ksuhiyp** [comment]
Ok I've tried later on a whole new installation and it works!
