### ISSUE TITLE
Can't create account - Error 'ssl3_get_record'

### ISSUE THREAD

**Issue by cavemanr** [LukeSmithxyz/mutt-wizard#185]
Everytime I try to create an E-Mailaccount with the mutt-wizard I get this error message.
```
Socket error: secure connect to xyz.de (x.x.x.x:143): error:1408F10B:SSL routines:ssl3_get_record:wrong version number
Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.
```
My IMAP and SMTP server needs STARTTLS.

Any hints how I can setup an account?

**Comment by LukeSmithxyz** [comment]
It looks like someone had added your mailhost to the domains list with the encrypted server information. What is the domain of your email? I'll start rechecking these.

**Comment by cavemanr** [comment]
Hey Luke. There are several domains all hosted at one provider netcup. One of the Domains is itcave-de.netcup-mail.de. Do you need more Information?

**Comment by cavemanr** [comment]
Hey Luke. I think this problem is that openssl has no SSL3 support enabled.

**Comment by dadosch** [comment]
But why does it want to have SSL3 in the first place and not choose TLSv1.2? (I have the same problem btw)
