### ISSUE TITLE
Authentication error with university account

### ISSUE THREAD

**Issue by done-with-fish** [LukeSmithxyz/mutt-wizard#189]
I'm trying to use `mw` to add my university account. After typing and retyping my password during setup, I get the error

`IMAP command 'AUTHENTICATE PLAIN <authdata>' returned an error: NO [AUTHENTICATIONFAILED] Authentication failed`

I'm not sure what the issue is. I'm inputting the imap and smtp address correctly and the ports are correct. I've also checked that I typed in my password correctly by looking at the entry in `pass`.

**Comment by LukeSmithxyz** [comment]
What is the university and their email host?

Some universities require a "secondard password" to set up. If they host with Gmail, you might have to manually enable IMAP access in the settings menu.

**Comment by done-with-fish** [comment]
The account is with the math department at Duke University. IMAP/SMTP information (from the system administrator) as follows:

Incoming IMAP Server : imap.math.duke.edu
             Use SSL : yes
                Port : 993

Outgoing SMTP Server : smtp.math.duke.edu
         Use SSL/TLS : yes
                Port : 587
       Auth Required : yes

No Gmail hosting. I'll contact the sysadmin and ask if there's a "secondary" password.

**Comment by done-with-fish** [comment]
Turns out I needed to type the * part of my email *@math.duke.edu when prompted. Don't know why I didn't try that myself when troubleshooting! Problem fixed.
