### ISSUE TITLE
mutt-wizard problems

### ISSUE THREAD

**Issue by geoguy** [LukeSmithxyz/mutt-wizard#19]
Short intro -> love arch linux, i3, emacs, cli.  Been using mu4e for years but multiple email accounts are pain, don't get emacs 'contexts'.  Looked for alternative, found mutt, found your script 'mutt-wizard' gave it a try ... no success.  I'm not newbee, but not programmer (hydrogeologist by profession, english is still my primary language, not programmer speak..).

------------------------------------------------
Here is my original .offlineimaprc for this account ( I added line numbers for reference):

01.  accounts = frank
02.  maxsyncaccounts = 3

03.  [Account frank]
04.  localrepository = franklocal
05.  remoterepository = frankremote

06.  [Repository franklocal]
07.  type = Maildir
08.  localfolders = /mnt/Maildir/BGM/

09.  [Repository frankremote]
10.  type = IMAP
11.  remoteport = 143
12.  remotehost = imap.*****ndwa***.com
13.  remoteuser = frank@*****ndwa***.com
14.  remotepass = *****
15.  ssl = no
16.  maxconnections = 5
17.  realdelete = true
18.  truedelete = True

19.  sslcacertfile = /etc/ssl/certs/180123_*****ndwa***.com.key
------------------------------------------
Here is mutt-wizard .offlineimaprc for this account ( I added line numbers for reference):
01.  [general]
02.  accounts = frank
03.  starttls = yes
04.  ssl = yes
05.  pythonfile = ~/.config/mutt/credentials/imappwd.py

06.  [Account frank]

07.  localrepository = frank-local
08.  remoterepository = frank-remote

09.  [Repository frank-remote]
10.  type = IMAP
11.  remoteuser = frank@*****ndwa***.com
12.  sslcacerfile = /etc/ssl/cets/ca-certificates.crt
13.  remotepasseval = mailpasswd("frank")
14.   remotehost = imap.*****ndwa***.com
15.  port = 143
16.  sslcacertfile = /etc/ssl/certs/ca-certificates.crt

17.  [Repository frank-local]
18.  type = Maildir
19.  localfolders = ~/.mail/frank
=====================================================
Here are my questions:

A.  Line 15 of your file -> 'port = 143',  the port number kept coming up 993 until I found this,  I changed this to 'remoteport = 143',  -> no success

B.  Line 12 of your file -> 'sslcacerfile = /etc/ssl/cets/ca-certificates.crt', I think this is an error as there is no file by that name or directory, I removed it -> no success

C.  Line 16 of your file -> ' sslcacertfile = /etc/ssl/certs/ca-certificates.crt ' , I already have a certfile for this account, so I replaced this with my account (my Line 19 )->
' sslcacertfile = /etc/ssl/certs/180123_*****ndwa***.com.key ' -> no success

D.  changed lines 03 and 04 to -> ' starttls = no ' and  ' ssl = no ' -> no success

------
I get this error on offlineimap:
OfflineIMAP 7.1.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.14, OpenSSL 1.1.0g  2 Nov 2017
Account sync frank:
 *** Processing account frank
 Establishing connection to imap.*****ndw***.com:143 (frank-remote)
 ERROR: Could not connect via SSL to host 'imap.*****ndw***.com' and non-standard ssl port 143 configured. Make sure you connect to the correct port. Got: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)

----------------------------------
Thanks, any idea what I am doing wrong??
Thanks,
Geoguy

**Comment by geoguy** [comment]
sorry, on question 4.  changed those commands to starttls = no and ssl = no

**Comment by LukeSmithxyz** [comment]
I don't really understand your problem. What was the original error?

- First, you should **not** have a `remotepass =` line. The script generates a `remotepasseval =` line which calls the python decryption script. Don't add in your own password.
- Your email address isn't in the csv file, so I assume you added your information manually. Use 993 for the IMAP port, not 143, which is not secure. This is probably where your original error came from.
- I don't really understand why you changes your cert file? Did it not exist there on your ditribution?
