### ISSUE TITLE
w gives no users with a graphical login so mailsync won't run

### ISSUE THREAD

**Issue by desdic** [LukeSmithxyz/mutt-wizard#197]
Hi,

I'm using a all graphical login on arch and this line made the mailsync stop working

https://github.com/LukeSmithxyz/mutt-wizard/blob/c5e12600b919a9bebfb14c12421b4ab6d742a785/bin/mailsync#L5

w does not display any users but 'loginctl show-session $XDG_SESSION_ID' does

**Comment by Kr1ss-XD** [comment]
Could you post the output of `pgrep -cu "$USER"` ?

You should get a number back. If so, pls replace that line w/
```
pgrep -cu "$USER" >/dev/null || exit
```
and report back if it works for you. Thx.

The problem with `loginctl` is it would be incompatible on systems w/o systemd.

**Comment by desdic** [comment]
I do get a number
$ pgrep -cu "$USER"
92

**Comment by Kr1ss-XD** [comment]
Thx for the reply. I'll submit a patch later today.

**Comment by desdic** [comment]
Thanks :)
