### ISSUE TITLE
Segmentation fault when switching between accounts

### ISSUE THREAD

**Issue by dodbrew** [LukeSmithxyz/mutt-wizard#198]
Switching inboxes/accounts (keystroke `i1`, `i2`, `i3`, etc.) results in segfault and subsequent terminal crash regardless of the terminal emulator used. It's unclear whether this is an issue with mutt-wizard or neomutt itself.

Pulling the [latest](https://github.com/neomutt/neomutt/releases/tag/neomutt-20180716) neomutt release does not seem to solve the issue, however commenting out `unmailboxes *` in every muttrc files that get sourced upon switching between mail accounts gives expected behavior (no segfaults).

Similar issue: [#1550](https://github.com/neomutt/neomutt/issues/1550) from neomutt repo.

**Comment by Kr1ss-XD** [comment]
While the patch for this issue has been [merged](https://github.com/neomutt/neomutt/pull/1631) into the neomutt master branch, the latest release doesn't implement it as it came out about 9 months before. So when using a build from github master you _should_ not get this error.
In case you are on Arch, I would suggest to use the [AUR package](https://aur.archlinux.org/packages/neomutt-git/) (which pulls from the master branch).
Maybe there are other distros as well which provide you a development package.
