### ISSUE TITLE
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc on Ubuntu

### ISSUE THREAD

**Issue by deadpyxel** [LukeSmithxyz/mutt-wizard#201]
Hello,

Everytime I open neomutt I get the following error:

```
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 47: Function 'goto-parent' not available for menu 'browser'
Error in /home/user/.config/mutt/muttrc, line 2: source: file /usr/share/mutt-wizard/mutt-wizard.muttrc could not be sourced.
source: errors in /home/user/.config/mutt/muttrc
```
`neomutt` opens normally, but it seems that the Ubuntu build of `neomutt` does not know how to handle that command.

Is this the most probable option or there's a chance of `zsh` interfering with it?

**Comment by LukeSmithxyz** [comment]
See https://github.com/LukeSmithxyz/mutt-wizard/issues/172

If you're using and old version of neomutt, like the one that Ubuntu installs by default, you'll have to either manually install a new version or manually comment out the line.

I sort of wish there were a way of suppressing minor errors like this in neomutt, but I don't know of it.

**Comment by deadpyxel** [comment]
Thanks Luke, I'll look into that.
