### ISSUE TITLE
Password entry

### ISSUE THREAD

**Issue by Pwhitcomb** [LukeSmithxyz/mutt-wizard#204]
When new account is being created, when prompted for password, pass gives an error and loops over and over again. Fresh install of arch, larbs, and mutt wizard

**Comment by LukeSmithxyz** [comment]
Well, what's the error?

**Comment by Pwhitcomb** [comment]
With the loop in getpass, it just loops through the usage of pass. It won't show me the error code

**Comment by DaemonLee** [comment]
Going by your description, sounds very similar to the problem I was having. Although, killing it and scrolling up does tell me:
```
Error: You must run:
    pass init your-gpg-id
before you may use the password store.
```

Fixed it by just initin' pass before running the wizard.

**Comment by Kr1ss-XD** [comment]
Seems like u ran into an infinite loop; actually the script should be aborted (after outputting an info message) when the password store had not been initialized before running it.

This patch should fix that.
