### ISSUE TITLE
Cannot send mail mail if server doesn't allow STARTTLS over port 587

### ISSUE THREAD

**Issue by zacklofgren** [LukeSmithxyz/mutt-wizard#206]
I figured out why I couldn't send mail. I use mailbox.org as my provider, and STARTTLS on port 587 is not valid. It does SSL/TLS on 465.

[Per the Arch wiki](https://wiki.archlinux.org/index.php/Msmtp#Server_sent_empty_reply), the fix is to put "tls_starttls off" in the msmtp config file.

My suggestion is to make this an option in the wizard to ask if the server allows STARTTLS on 587 with like "If you don't know, no". 

I also think maybe this doesn't belong in the wizard, and I'm cool with adding it myself later. Edge cases like this might not belong in `mw`.

Also, I realized I hadn't spammed you (probably) and it was just copying to my sent folder, so I thought I did. Haha.

**Comment by LukeSmithxyz** [comment]
mutt-wizard stores the port numbers for each email provider and should address these problems. It might be whoever originally added your domain did so when 587 was the correct port.

What is your email provider/domain? I'll fix it.

**Comment by d9a** [comment]
The domain is zlofgren.com and the provider is mailbox.org. My domain isn't in the csv, so I manually added the imap and smtp servers during `mw add`. `tls_starttls off` is an additional step after `mutt-wizard` because even though I set port 465 for the smtp server during setup, it doesn't use that port for TLS.

**Comment by passaca** [comment]
I've had the same problem. The port is indeed officially 465 and STARTTLS needs to be set to "off" explicitly for it to work.

**Comment by LukeSmithxyz** [comment]
Yeah I suppose this is a general problem since mstp ports on 465 will never have starttls. I've added a bit to the wizard to add the needed line if that's the needed port.
