### ISSUE TITLE
Script adds [GMAIL] in patterns to all accounts

### ISSUE THREAD

**Issue by matstage** [LukeSmithxyz/mutt-wizard#208]
I used the mutt-wizard to add my Gmail account as my first account. 
When I added my second account, the patterns parameter shows "[Gmail]/All Mail" under the channel entry for it (a yahoo account). When I add a third account, the pattern still shows the same.

**Comment by LukeSmithxyz** [comment]
That's how Gmail names their boxes (or really tags or however they do it). This is intended behavior.
