### ISSUE TITLE
pam_gnupg clarifications

### ISSUE THREAD

**Issue by Vollblut** [LukeSmithxyz/mutt-wizard#209]
I'm using mutt/mutt-wizard extensively and tried to setup autounlock the passphrases at login with pam-gnupg. 
even though the .pam-gnupg is setup correctly, gpg-agent.conf is configured and so on, the mailsync cronjob still pesters me with the pinentry dialog every time it syncs. 
is there something amiss?

**Comment by kajzersoze** [comment]
I had the same problem with that `pam-gnupg`, solved it eventually but then it stopped working again, seems like if after some time you login as root with `su`, it stops working.

Anyway, I solved that by editing .zshrc, if you use bash you can use .bashrc
Add this line somewhere inside :
`export PASSWORD_STORE_GPG_OPTS="--pinentry-mode loopback --passphrase YOUR_PASSPHRASE"`

**Comment by yusufaktepe** [comment]
It works for me if I decrypt something before using mutt or git sign. So, I added this to my autostart script:

`echo ok | gpg -r mail@mail.com -e -o - | gpg -d >/dev/null 2>&1`

**Comment by LukeSmithxyz** [comment]
This isn't an issue with mutt-wizard, but with pam-gnupg. It's better to ask them.
