### ISSUE TITLE
Automatic update of IMAP folder

### ISSUE THREAD

**Issue by stefanocereda** [LukeSmithxyz/mutt-wizard#212]
Hi!
I'm new to all this mutt thing so I may be asking a very stupid question, but I could not find a solution.
I have use mutt-wizard (installed via AUR) to setup 3 accounts with isync, and they are all working fine.
I then deleted some folders directly from gmail web interface. I can still view those folders in mutt, and cannot find a way to delete them. Is there a way to have mutt (or isync) automatically get the updates to the folder structure?

**Comment by LukeSmithxyz** [comment]
Ah so isync has likely already deleted the local directories, the settings set in the mutt configs do not automatically update.
You can change them by opening up the account's config file in `~/.config/mutt/NUM-NAME.muttrc` and finding the `mailboxes` line. Just add or delete whatever boxes you want there.

**Comment by stefanocereda** [comment]
Perfect, thanks
