### ISSUE TITLE
Cannot send mail

### ISSUE THREAD

**Issue by Prathik-Jain** [LukeSmithxyz/mutt-wizard#214]
`Uploading message...` forever

![image](https://user-images.githubusercontent.com/25041441/58201700-57983200-7cf3-11e9-8cf7-d60f36e64b9a.png)

I use 
1. `live.com` from `domains.csv`
2. `mail.gandi.com` (993 and 465)

Am I missing something?

**Comment by juliorcx** [comment]
I have the same problem, but I have a Gmail account.

![sendingMessageForever](https://user-images.githubusercontent.com/50068895/58310928-1b0a2a80-7e08-11e9-96eb-d812db38eb5c.png)

And It doesn't send the mail.

**Comment by Prathik-Jain** [comment]
@LukeSmithxyz

**Comment by juliorcx** [comment]
I've tested now and it's working. @Prathik-Jain try it.

**Comment by Prathik-Jain** [comment]
@juliorcx thanks for checking. Works! Also we don't know what was causing the issue.

**Comment by juliorcx** [comment]
Yeah it's weird.

**Comment by Prathik-Jain** [comment]
Stuck again. @LukeSmithxyz  @juliorcx

**Comment by juliorcx** [comment]
Yes I see. May be there is a problem with msmtp.

**Comment by LukeSmithxyz** [comment]
Use port 587 as an smtp port, or if you have to use 465, you have to add `tls_starttls off` to your msmtp config file.

Be wary that some email providers block certain smtp ports for stupid reasons, so you might have to use another your mail host provides or send unencrypted mail on port 25.
