### ISSUE TITLE
mutt-wizard and Davmail - how to make it work!

### ISSUE THREAD

**Issue by praschdorff** [LukeSmithxyz/mutt-wizard#22]
the default configuration from neomutt will not work if you try to use mutt-wizard to connect to Davmail.
Davmail can be used to provide local IMAP and SMTP while beeing connected to a Microsoft Exchange Server.
Thereof it is possible to connect to a recent Microsoft Exchange using neomutt.
This is the setup to get offlineimap sync emails from our exchange server using Davmail.
Most important is to set remoteport entry which must be identical in Davmail.

```
[general]
ui = ttyui
starttls = no
ssl = no
accounts = workmail

[Account workmail]
localrepository = workmail-Local
remoterepository = workmail-Remote

[Repository workmail-Local]
type = Maildir
localfolders = ~/Mail/workmail

[Repository workmail-Remote]
type = IMAP
remotehost = localhost
remoteuser = <USERNAME>
remotepass = <PASSWORD>
remoteport = 1143
realdelete = no
ssl = no
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```

maybe this helps to make mutt-wizard smarter, when running Davmail?
If you run the current version of the installer, you will not get a working config as SSL is enabled and the remoteport is not set correctly.

PR

**Comment by LukeSmithxyz** [comment]
add this as a pull request if you want it added.
