### ISSUE TITLE
Cronjob not working

### ISSUE THREAD

**Issue by DocKDE** [LukeSmithxyz/mutt-wizard#220]
Hi,
First off I'd like to say thanks for the work on this, it really helped me a lot and I love the thing!
My issue is with the automatically set up cronjob not fetching email. I set it up with "mw cron" to fetch mails every 5 minutes and installed cronie to do the job. I set it to start up on boot and verified it runs. Nevertheless, nothing happens, regardless how long I wait and I have to fetch mail manually. 
It may be possible that I misunderstood how this is supposed to work but the cronjob should run in the background in time intervals I set so after that given time any new mail will show up in mutt automatically, right?

I would appreciate any help or explanation of what is going wrong or whether there is just something I don't get here.

**Comment by davidoskky** [comment]
If you are using pubblic wifi it is possible that pinging is blocked, therefore the check 
ping -q -c 1 1.1.1.1
will not pass.
Try running that ping to check if that is the problem.
I assume that you already checked your cron table to make sure the entry is there.
If that is not the problem try running the mailsync script line by line to check what the problem is.

**Comment by DocKDE** [comment]
The mailsync script runs without error when I execute it manually. It seems my problem is the crontab itself, I'd say. It definitely exists and looks like this:
[code]
*/5 * * * * export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus; export DISPLAY=:0; . $HOME/.profile; /usr/bin/mailsync
[/code]
I'm however at a loss as to why it looks that way. Wouldn't it be sufficient to just have it call /usr/bin/mailsync (which I just did by hand and it seemed to work fine)?

**Comment by LukeSmithxyz** [comment]
The other commands are needed to get environmental variables and ensure
that the notification displays and on the correct display.

Run the command `pgrep -u "yourusername"`; what is the output?

**Comment by DocKDE** [comment]
Output is these numbers:
`579
580
585
586
634
656
657
670
672
674
678
680
684
690
692
738
844
874
1391
1392
1588
1598
1619
2836
2848
2855
2858
2882
4432
4884
4902
5337
5339
8070
8094
9746
10279
10504
10628
11142
17915
17933
18061
18063`

**Comment by DocKDE** [comment]
Okay, I feel somewhat silly now, but after booting just now, the cronjob seems to have decided to just work. I don't rightly know why but I tested it and mail shows up properly after a couple of minutes now. I swear it didn't do that last time I checked :-/
Anyway, thank you for your replies!
