### ISSUE TITLE
Canceling out [ctrl+c] retains terminal color

### ISSUE THREAD

**Issue by rpgwaiter** [LukeSmithxyz/mutt-wizard#223]
When adding a new account with mw (not sure if it happens using other parts of the wizard), if you ctrl+c out of the program your terminal text will stay the color of the wizard prompt. Ideally, the terminal text would go back to whatever color it was before the wizard was ran.

**Comment by Kr1ss-XD** [comment]
:+1:
Nice catch :exclamation:
