### ISSUE TITLE
Duplicate sent messages

### ISSUE THREAD

**Issue by rbuchberger** [LukeSmithxyz/mutt-wizard#226]
I'm having an issue where all my sent messages go out twice, once when I hit 'y' to send, and again when I run mbsync. 

When I send myself an email via neomutt, it immediately arrives back in my inbox (according to fastmail's web client). Neomutt shows it in sent messages, but the web client doesn't. When I sync after that, in neomutt I only see one copy in both sent and inbox, but when I go to the web client I see it duplicated in both mailboxes. 

The hosting provider is fastmail with a custom domain name. I'm in the process of troubleshooting and will report back if I find anything, but I'm not super familiar with these tools. 

Thanks for the work!

**Comment by Kr1ss-XD** [comment]
Maybe it's worth trying to insert an
```
unset record
```
line into your account-specific `.muttrc` file (the one w/ the number leading its filename).
This prevents neomutt from saving a copy of outgoing mail in your `sent` folder. This is recommended e.g. for outlook to prevent duplicates, b/c the server saves its own copy.
Likely that's the same issue that you're having.

**Comment by LukeSmithxyz** [comment]
Yes, as Kr1ss alludes to, it probably is not you sending two messages, but fastmail apparently automatically adds sent mail to a sent folder, when typically that would be mutt's job in this case. By unsetting the `record` variable in mutt, it will no longer do this.

**Comment by rbuchberger** [comment]
Thanks guys. 

Commenting out `record` sort of works - only one email shows up in the inbox, but it never shows up in fastmail's sent folder. 

I tested with a 10 minute email instead of sending it back to myself, and everything works as expected; only one mail is sent and after syncing a single copy shows up in the sent folder on both clients. So apparently it only duplicates messages when I email myself, which I don't really see as a problem. 

Looking at the headers of the duplicated messages, the second one is super simple, less than 10 lines, and first one is really long with all the server handoffs, authentication info, spam ratings, and that sort of thing. Maybe fastmail has some optimization for local mailboxes that is getting tripped up by this setup.

I'll keep digging a bit, see if it happens with fastmail addresses that aren't mine. I don't think it's a mutt-wizard issue though, so I'll close this one. Luke, thanks a ton for putting this thing together!
