### ISSUE TITLE
notmuch searching only in current folder

### ISSUE THREAD

**Issue by MrZeroo00** [LukeSmithxyz/mutt-wizard#227]
Hi,

Thanks for this amazing wizard.

It seems like notmuch search using ctrl-f prints only matched emails in the current folder (since the macro is using the limit function of neomutt): if I am in my `Inbox` folder, the search function won't show emails matching the search expression that are in my `Archive` folder. 
Screenshots of the same search below in neomutt (4 emails shown) and in terminal (50 results).

Do you confirm this behaviour?

https://dsh.re/25d3a
https://dsh.re/705ba

**Comment by LukeSmithxyz** [comment]
Yes. That's how it is intended to work. It works like the limit option.

To search all possible mail would be a problem for some reasons. Notmuch can do that for mutt (you can look it up), but it would find mail and create it's own buffer and thus the mail would be viewable, but not editable or re-tagable or deletable, so it's less extensive. If you want that functionality you can add it to your muttrc. If you can find an option that doesn't do this, you're welcome to offer a PR if you find a search all accounts/mail option with neomutt.
