### ISSUE TITLE
Mw add generates empty config files

### ISSUE THREAD

**Issue by cedrak** [LukeSmithxyz/mutt-wizard#230]
Hello!
I'm trying to migrate to new mutt-wizard, but `tryconnect()` function fails log-on attempt. It seems that the problem lays in `askinfo()` function as it generates config files with no account configuration whatsoever:

```
$ cat ~/.mbsyncrc ~/.msmtprc ~/.config/msmtp/config 

defaults
auth	on
tls	on
tls_trust_file	/etc/ssl/certs/ca-certificates.crt
logfile	~/.config/msmtp/msmtp.log


defaults
auth	on
tls	on
tls_trust_file	/etc/ssl/certs/ca-certificates.crt
logfile	~/.config/msmtp/msmtp.log


```
**I've purged old config files and also mail dirs.**

I do not really know how to diagnose it further so I will just post some logs and system info:
```
$ mw add
Do you want to keep your mail for this account offline with mbsync? [yes/no]
	yes
Insert the email address that you want to autoconfigure for mutt/mbsync
	Email: ****@disroot.org

Searching for disroot.org in `domains.csv`...
Congrats! Server info has automatically been found, so you won't have to look anything up!
	IMAP server: disroot.org
	IMAP port: 993
	SMTP server: disroot.org
	SMTP port: 587
This data will be used by the wizard.
Enter the full name you want to be identified by on this account.
	Real name: ****
Enter a short, one-word identifier for this email account that will distinguish them from any other accounts you add.
	Account name: disroot
If your account has a special username different from your address, insert it now. Otherwise leave this prompt totally blank.
Most accounts will not have a separate login, so you should probably leave this blank.
	Login(?): 
If you want to limit the number of messages kept offline to a number, enter that number below. If you do not want to limit your mail and would like `mbsync` to sync all mail, press enter without typing a number.
	
Enter password for mutt-wizard-disroot: 
Retype password for mutt-wizard-disroot: 
Creating profiles for `disroot`...DONE.
muttrc created.
Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.
```

System info:
```
$ uname -a
Linux x60s 4.9.0-9-686-pae #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) i686 GNU/Linux
```
```
$ pass --version
============================================
= pass: the standard unix password manager =
=                                          =
=                  v1.6.5                  =
=                                          =
=             Jason A. Donenfeld           =
=               Jason@zx2c4.com            =
=                                          =
=      http://www.passwordstore.org/       =
============================================
```
```
$ msmtp --version
msmtp version 1.6.6
Platform: i686-pc-linux-gnu
TLS/SSL library: GnuTLS
Authentication library: GNU SASL
Supported authentication methods:
plain scram-sha-1 external gssapi cram-md5 digest-md5 login ntlm 
IDN support: enabled
NLS: enabled, LOCALEDIR is /usr/share/locale
Keyring support: none
System configuration file name: /etc/msmtprc
User configuration file name: ~/.msmtprc
```
```
$ isync --version
isync 1.2.1
```

**Comment by LukeSmithxyz** [comment]
It's not that your configuration files are not being generated, but if login fails, the wizard deletes the configuration section for the failed login to prevent breaking mbsync generally. That means something went wrong in your login.

This example `cat` command you give of your configs is way wrong though... I don't know if you copied it in error, but it looks like both of the files are `msmtp` config files! If you have no configured `mbsync` accounts, the `mbsyncrc` should be blank; it has no header.

**Comment by cedrak** [comment]
Thanks for clarifying, however I still do not really know how to diagnose what's going on wrong. Can you please give me some tips?

Regarding config files - mbsync config is indeed blank. Notice that I cat'ed 3 files - two of them are msmtp configs and I think both of them were generated during `mw add` run. The blank mbsync config was... well... concatenated at the end of the output ; )

**Comment by LukeSmithxyz** [comment]
All I can say is that there is some kind of problem logging in. You could try just manually creating a `mbsyncrc` and seeing what allows you to run `mbsync`, but I can't be sure. It could be that there is some kind of problem with your password not properly being escaped. There is a mbsync issue with abnormally long passwords out of mw's control.

If you want to try it manually, you can imitate what my config looks like. Obviously replace `luke` with the name you give your email account and `Host` and `Port` should be your IMAP server and port.

```
IMAPStore luke-remote
Host mail.lukesmith.xyz
Port  993
User luke
PassCmd "pass mutt-wizard-luke"
SSLType IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

MaildirStore luke-local
Subfolders Verbatim
Path ~/.local/share/mail/luke/
Inbox ~/.local/share/mail/luke/INBOX
Flatten .

Channel luke
Expunge Both
Master :luke-remote:
Slave :luke-local:
Patterns *
Create Both
SyncState *
# End profile
```

**Comment by cedrak** [comment]
Thanks for your help! 

After manual syncing `mw add` worked. I suspect that the issue were somewhere in the catalog naming, but I can't reproduce it anymore.
