### ISSUE TITLE
No promt to unlock Pass database

### ISSUE THREAD

**Issue by Vintodrimmer** [LukeSmithxyz/mutt-wizard#232]
Good day,

I'm running `Void Linux`, my terminal is `alacritty` and login shell is `dash`.

I experience 2 problems after using the latest git version of the `mutt-wizard`:
1. `Neomutt` doesn't give me any promt to decrypt my `pass` database so I can't receive or send mail.
2. Sending a message fails

Unless `pass` was recently unocked from the terminal, trying to retrieve the messages returns the following error:
```
Reading configuration file /home/eichhorn/.mbsyncrc
No channel specified. Try 'mbsync -h'
C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0gpg: decryption failed: No secret key

Skipping account teacher-remote, password command exited with status 2
```

While attempting to send mail results in the following prompt:
```
gpg: decryption failed: No secret key
msmtp: cannot read output of 'pass mutt-wizard-teacher'
```

Is it supposed to work that way, or is there some kind of error and GPG decryption promt doesn't show up for me?

---------

If the database was unlocked manually, getting new mail works flawlessly, but sending fails with the following message:
```
msmtp: the server sent an invalid reply
msmtp: could not send mail (account teacher from /home/eichhorn/.config/msmtp/config)

Output of the delivery process (all)
Error sending message, child exited 76 (Remote protocol error.).
```

This is university mail and I have copied the settings from the `Claws Mail` client, where sending works properly. 

Servers and ports are as follows:

```
IMAP Server: mail.uni-freiburg.de
Port: 993
SSL/TLS: On

SMTP Server: mail.uni-freiburg.de
Port: 465
SSL/TLS: On
```

Could you suggest some possible cause of the problem?

**Comment by LukeSmithxyz** [comment]
Potential causes:
- You don't actually have a GPG key pair for the email you configured pass to use.
- Void Linux has only `gpg2`, not `gpg` by default, while many distros link one to another. I take measures to avoid this problem, but you might want to symlink a `gpg` in your PATH to `gpg2`.
- You don't have a program install to input you GPG password. Like pinentry, etc.

**Comment by Vintodrimmer** [comment]
* No GPG key pair
Could you elaborate on this one, please?
I followed the prompts in generating one and there is a `mutt-wizard-teacher` entry in `pass` database with the appropriate password (the one to my email account).

* `gpg2` and not `gpg`
Created a symlink (`ln -s /usr/bin/gpg2 /usr/bin/gpg`), but it didn't help.

* `pinentry`
Comes with GPG. Have installed `pinentry-tty` to no avail.

Anything else that might cause this?

**Comment by matt-m95** [comment]
I was also getting this error on arch. I already use pass outside of mutt, I fixed this by using pinentry-gtk-2, edit `~/.gnupg/gpg-agent.conf` to include `pinentry-program /usr/bin/pinentry-gtk-2`.
I'll probably just setup pam-gnupg.

**Comment by Vintodrimmer** [comment]
Installing `pinentry-gtk-2` and specifying it in the `~/.gnupg/gpg-agent.conf` solved the first issue, thanks a lot!

Now I just need to figure out why sending mail fails.

**Comment by Vintodrimmer** [comment]
Fixed the second issue by adding 
`tls_starttls off` to the `~/.config/msmtp/config`.
