### ISSUE TITLE
Show flag_chars

### ISSUE THREAD

**Issue by mdosch** [LukeSmithxyz/mutt-wizard#239]
Thank you for this nice setup, it saved me a lot of time using it as a base for my own setup. One thing I am missing is that not all flag_chars are shown. E.g. if I tag messages they do not show the asterisk in front so I have no overview which messages are tagged. Would you consider to change the config to show all flag_chars?

**Comment by Kr1ss-XD** [comment]
FWIW, there were some suggestions in this [comment](https://github.com/LukeSmithxyz/mutt-wizard/issues/157#issuecomment-494216510) and ff. inside an earlier thread; maybe u find them useful.

**Comment by mdosch** [comment]
Thank you very much, this looks pretty promising. Will dig into that.

**Comment by mdosch** [comment]
Thanks, this is doing fine for me:

> set index_format="%2C %zs %zt %?X?A& ? %D %-15.15F %s (%-4.4c)"

**Comment by Kr1ss-XD** [comment]
:+1:  Fine.
