### ISSUE TITLE
Mutt does not remember mailboxes' sizes

### ISSUE THREAD

**Issue by drmtmych** [LukeSmithxyz/mutt-wizard#24]
When you open up mutt, you apparently use your 1st (default) account. And in that default account mutt correctly displays sizes of your mailboxes on sidebar right away. Therefore, it is capable of capturing those sizes while sourcing account's config.
Now you source your 2nd account. And mutt no longer displays correct sizes, except INBOX. It considers the others to be empty until you literally go to them (gs, gt etc.). Moreover, if you go back to your 1st account,  the same thing happens: you have to go to corresponding mailboxes to make sure they're non-empty.

I did not succeed in searching for an option which would make it remember contents of the whole tree after sourcing. Obviously,  the needed functionality is hidden under the hood. Maybe you have a better understanding of what's happening?

**Comment by LukeSmithxyz** [comment]
I've noticed this, but I'm not immediately sure what causes this or how to rectify it. I'll keep this open since I think it'd be nice if the system remembered it.

**Comment by LukeSmithxyz** [comment]
Alright, I actually set down to fix this an succeeded. All you need to do is run `<check-stats>` on account switch. The wizard will now add this command to run on switch for newly added accounts.

If you want to update your already existing accounts just add `;<check-stats>` to all your account macros in `~/.config/mutt/personal.muttrc` so they look like the line below:
```
macro index,pager i2 '<sync-mailbox><enter-command>source /home/luke/.config/mutt/accounts/gmail.muttrc<enter><change-folder>!<enter>;<check-stats>'
```
