### ISSUE TITLE
IMAP error with gmail

### ISSUE THREAD

**Issue by brckts** [LukeSmithxyz/mutt-wizard#240]
``
[SASL-XOAUTH2] - Requesting authID![SASL-XOAUTH2] - Requesting token
![SASL-XOAUTH2] - filling prompts
![SASL-XOAUTH2] - Requesting authID![SASL-XOAUTH2] - Requesting token
!Error: IMAP wants more steps despite successful SASL authentication.
``
pops out whenever I try to setup my gmail account, mw works fine when using other providers on the same machine.

**Comment by jlamoure** [comment]
Also experiencing this. Using 2FA with a Google Apps Password. Loading my Gmail works fine with: 

$ mutt -f imaps://imap.gmail.com

**Comment by jlamoure** [comment]
What worked for me was to add "AuthMech LOGIN" in ~/.mbsyncrc under where the server, etc is specified for Gmail.

**Comment by nodefive** [comment]
The problem is that when you are setting up the account the script won't write anything unless the first login succeeds. So I've edited the mw script itself, around line 60, and added there:

```
Host $imap
Port  $iport
User $login
PassCmd \"pass mutt-wizard-$title\"
SSLType $ssltype
**AuthMech LOGIN**
CertificateFile $sslcert
```

 Once the account was setup I've reverted as it was, in case I need to add another non OAuth acc

**Comment by johnnypea** [comment]
I did the same. Could you @LukeSmithxyz please add this line to the script? Thanks.
