### ISSUE TITLE
3 issues pertaining to mutt-wizard/mbsync functionality

### ISSUE THREAD

**Issue by atreyasha** [LukeSmithxyz/mutt-wizard#243]
Hello Luke and developers!

First of all thank you for this awesome tool, I saw it through your Youtube videos and have been using it since. Recently, I compiled certain minor issues which I was facing and thought it would be nice to make an issue/PR.

First off, my local system configuation:

```
OS: Arch Linux x86_64
mw-version: mutt-wizard-git r641.gd7dd9f8-1
isync-version: isync 1.3.1
```

1. For gmail, I believe the default name for the folder where deleted messages go is "[Gmail].Bin" instead of "[Gmail].Trash", at least for the English version. Perhaps this could be modified in the default gmail setup behaviour, otherwise messages pick up a "[Gmail].Trash" label and linger on in the inbox.

2. During syncing with remote IMAP servers, I noticed that deleted messages were not moved to a trash folder, rather they were copied into the trash folder, leaving one version behind in the remote inbox. After experimenting with the mbsync flags, I noticed that modifying the sync command to below fixed the problem:

```shell
$ mbsync -andfN
```

2. contd: The default behaviour of mbsync should be to activate all flags if none are specified. But somehow they don't get activated for me, therefore the need to manually activate them as above. This could be introduced as a default behaviour for mutt-wizard

3. Finally, when deleting an account using mutt-wizard, it might be good to introduce an additional option to delete all local caches pertaining to the particular account. That way, resetting the account would ensure that possible local cache conflicts would be eliminated. The user will of course be prompted for this, so it would not necessarily be risky.

Let me know your thoughts on these issues. If they are of interest, I would be more than happy to submit a pull request. Thanks again.

**Comment by exic** [comment]
4. If your Log-on is not successful, you can't retry with different settings, you have to type in everything again. I guess you should at least save everything and then let me try with different settings myself or at least not quit completely.

**Comment by f380cedric** [comment]
> 1. For gmail, I believe the default name for the folder where deleted messages go is "[Gmail].Bin" instead of "[Gmail].Trash", at least for the English version. Perhaps this could be modified in the default gmail setup behaviour, otherwise messages pick up a "[Gmail].Trash" label and linger on in the inbox.

Sadly, Gmail IMAP folder names are localized (names change with your Gmail localization settings).
From [here](https://stackoverflow.com/a/3201523/7890872), there is a workaround, but not sure isync supports it.

> 2. During syncing with remote IMAP servers, I noticed that deleted messages were not moved to a trash folder, rather they were copied into the trash folder, leaving one version behind in the remote inbox. After experimenting with the mbsync flags, I noticed that modifying the sync command to below fixed the problem:
> 
> ```shell
> $ mbsync -andfN
> ```

Strange, because, from the manual:
 - `-n, --new`: propagate newly appeared messages
 - `-d, --delete`: propagate message deletions
 - `-f, --flags`: propagate flag changes
 - `-N, --renew`: previously refused messages are re-evaluated for propagation

All theses flags are used to override `Sync` configuration keyword. But by default, if `Sync` is not specfied in the configuration file, it defaults to `Full`, meaning `-ndfN`.
mw is not specifying `Sync`, so it should do `Full`.

> 1. contd: The default behaviour of mbsync should be to activate all flags if none are specified. But somehow they don't get activated for me, therefore the need to manually activate them as above. This could be introduced as a default behaviour for mutt-wizard

That what it normally does by default. Do you have `Sync` in your .mbsync configuration file?
