### ISSUE TITLE
gmail account not working

### ISSUE THREAD

**Issue by watkinsr** [LukeSmithxyz/mutt-wizard#246]
One of my two gmail accounts does not authenticate(?) even though I am certain it is the password..

**Comment by watkinsr** [comment]
nvm, it was due to this: https://support.google.com/accounts/answer/6010255?p=lsa_blocked&hl=en-GB&visit_id=636968887760928302-286507405&rd=1

**Comment by davisi3** [comment]
How did you solve this?
