### ISSUE TITLE
Cronjob problem

### ISSUE THREAD

**Issue by richtan** [LukeSmithxyz/mutt-wizard#249]
The cronjob that the script adds seems to have a problem in it that doesn't allow the cronjob to run. **". \$HOME/.profile"** should be replaced with **"\$HOME/.profile"** (basically removing the dot). Cronjobs do not need an extra "source" command to run scripts.

**Comment by richtan** [comment]
I believe this is on line 281 in https://github.com/LukeSmithxyz/mutt-wizard/blob/master/bin/mw

**Comment by LukeSmithxyz** [comment]
Yeah thanks for the heads up. I had changed the format around a couple times and I will soon in a bit. I think the original reason the profile is sourced is actually irrelevant now, so I think I'll remove it anyway.

I'm about to add most of the junk in the cronjob to the mailsync script proper to avoid the ugliness.
