### ISSUE TITLE
Extra Sent folder

### ISSUE THREAD

**Issue by pgferro** [LukeSmithxyz/mutt-wizard#250]
Hi Luke,
just installed mutt through your script, everything is really nice, congrats and thanks !
The only glitch that I found is as per attached screenshot (outlook.com account), basically the original Sent folder in outlook is not used to store sent messages, instead a new Sent Messages folder is (created?) used.
Thanks again
![mutt](https://user-images.githubusercontent.com/14185233/60665661-c7aae380-9e6d-11e9-9c54-13986c54536f.png)

**Comment by Kr1ss-XD** [comment]
Well, there's a peculiarity of outlook.com, that outgoing mail is automatically copied to the account's `Sent` folder. I actually stumbled over the same thing.
So there's no need to configure (neo)mutt to also create a copy by itself.

To prevent this, you should be good after commenting out (or deleting) the line 
```
set record = [...]
```
in the account-specific config file, which most likely is
```
/home/<username>/.config/mutt/accounts/1-outlook.muttrc
```
if you haven't set up any other accounts.

**Comment by pgferro** [comment]
Thanks !
