### ISSUE TITLE
mutt-wizard and Qubes OS

### ISSUE THREAD

**Issue by praschdorff** [LukeSmithxyz/mutt-wizard#26]
I had to do some tweaks to be able to use mutt-wizard and setup offlineimap + neomutt under Qubes OS.
In Qubes OS I'm running SplitGPG which separates the GPG-keys into an own "AppVM".
For further information:

- Qubes OS: https://www.qubes-os.org/intro/
- SplitGPG: https://www.qubes-os.org/doc/split-gpg/

I had to do some changes so that mutt-wizard will use qubes-gpg-client instead of the default gpg2. 
Additionally I had to create the encrypted password manually after I've added my email-account via mutt-wizard

qubes-gpg-client -a --encrypt -r <NAME> ~/.config/mutt/credentials/<ACCOUNT>.gpg

<NAME> is used to identify the GPG-key you would like to use in the Vault-VM (SplitGPG-repository) and <ACCOUNT> is the name you gave the accont in mutt-wizard.

QUESTION:
how should I contribute as the setup is only for users running Qubes OS and I don't want to "damage" the scripts for all other users.
I'm thinking of adding the information to the qubes-docs repository (?) what do you think?

The following changes have been made to get mutt-wizard working under Qubes:

1) replace gpg2 with qubes-gpg-client in mutt-wizard.sh
2) replace gpg2 with qubes-gpg-client in credentials/getmuttpass
3) replace gpg2 with qubes-gpg-client in credentials/imappwd.py

**Comment by LukeSmithxyz** [comment]
I don't know anything about how Qubes does their stuff, but you're welcome to commit a .diff file that will allow Qubes users to patch the `mutt-wizard.sh` so it will work for them seamlessly. Just make a .diff file and put it in `autoconf/patches` or something like that and commit it to this repo.

**Comment by praschdorff** [comment]
Ok, as there are more dependencies (setting up GPG etc) I'll write a how-to
for the Qubes Docs (also @github) and try to create a diff-file which you
can place here, so that the credits for mutt-wizard goes to you.
Thanks for your work btw. ;-)

Am 03.03.2018 10:25 nachm. schrieb "Luke Smith" <notifications@github.com>:
