### ISSUE TITLE
adding notmuch (fast search) to mutt-wizard

### ISSUE THREAD

**Issue by praschdorff** [LukeSmithxyz/mutt-wizard#27]
As mutt-wizard is targeted towards newbie users, you might want to add notmuch to the setup/configuration process or at least mentioned it:
https://notmuchmail.org
If notmuch is installed you only need to do the following steps to get a fast email search on your commandline:

`notmuch setup && notmuch new`

**Comment by LukeSmithxyz** [comment]
I don't necessarily want to have this as part of the wizard itself, but I might add it to the documentation since the configs do map some notmuch shortcuts.

I don't want it to be a hard depencency though just because it's totally sensible to not use notmuch if you want.
