### ISSUE TITLE
$USER unset under Ubuntu (debian?) cron

### ISSUE THREAD

**Issue by twirrim** [LukeSmithxyz/mutt-wizard#270]
https://github.com/LukeSmithxyz/mutt-wizard/blob/856eea6d71a0a32cb9bea4ab704dc41f7619c18f/bin/mailsync#L10

I was noticing that under cron, the mailsync command wasn't running successfully.   Added `sendmail` and `mail` to the machine so that I'd get to see the messages from the cron entry, and saw it complaining about pgrep syntax.   Added `set -x` at the top and saw it was barfing out at the above referenced line, because $USER is unset.

```
+ pgrep -u 

Usage:
 pgrep [options] <pattern>

Options:
...
For more details see pgrep(1).
+ echo  not logged in; sync will not run.
 not logged in; sync will not run.
```

With $USER variable is unset, it's never going to recognise that I'm actually logged in.

These are the only variables that seem to be set (found by adding a cron entry for `env`)
```
HOME=/home/paul
LOGNAME=paul
PATH=/usr/bin:/bin
LANG=en_US.UTF-8
SHELL=/bin/sh
PWD=/home/paul
```
It looks like LOGNAME would work?  Not sure how things look on other distributions though.

**Comment by twirrim** [comment]
maybe an ugly hack, but I tacked this on at the start of the script.  There's still assumptions somewhat baked in to this:

```
if [ -z "$USER" ] && [ -n "$LOGNAME" ]; then
    USER=$LOGNAME
fi;
```

**Comment by Kr1ss-XD** [comment]
Or just replace that line with
```
pgrep -u "${USER:=LOGNAME}" >/dev/null || { echo "$USER" not logged in; sync will not run."; exit ;}
```
:question:

**Comment by twirrim** [comment]
> Or just replace that line (10) with
> 
> ```
> pgrep -u "${USER:=$LOGNAME}" >/dev/null || { echo "$USER" not logged in; sync will not run."; exit ;}
> ```

Oh neat, didn't know you could do that.  It's still making some assumptions, but no more than I already was with my example.

**Comment by Kr1ss-XD** [comment]
Yep we'd need to make sure `$LOGNAME` is actually properly set on every platform. Not sure about that.

**Comment by insanerwayner** [comment]
> Or just replace that line (10) with
> 
> ```
> pgrep -u "${USER:=$LOGNAME}" >/dev/null || { echo "$USER" not logged in; sync will not run."; exit ;}
> ```


Can confirm this worked to solve my issue in Pop!_OS 19.04

**Comment by Kr1ss-XD** [comment]
Yo, thx for mentioning this; fixed my comment. :wink:
