### ISSUE TITLE
[Mutt+larbs] .vimrc Goyo bug

### ISSUE THREAD

**Issue by nymann** [LukeSmithxyz/mutt-wizard#274]
When running mutt (configured with the mutt-wizard naturally) I encounter the following error when trying to send mails:

```
Error detected while processing BufReadPost Autocommands for "/tmp/neomutt*":
E492: Not an editor command: :Goyo \| set bg=light
Press ENTER or type command to continue
```

The .vimrc is untouched from the larbs/archi3 branch.

Not sure whether or not to create the issue here or in the larbs project, since neovim works in all other instances.

**Comment by mickdupreez** [comment]
i have the exact same issue

**Comment by mickdupreez** [comment]
lol literally just fixed it seconds later just re install msmtp
 fixed

**Comment by LukeSmithxyz** [comment]
I don't think msmtp should have anything to do with this.

The most likely cause of this is simply Goyo not being properly installed. My neovimrc should try to install its required plugins immediately the first time neovim it is opened, but you can do it manually by running `:PlugInstall`.

**Comment by mickdupreez** [comment]
thanks luke
