### ISSUE TITLE
Pipe Attachment Pathname

### ISSUE THREAD

**Issue by jessebett** [LukeSmithxyz/mutt-wizard#297]
Not sure if this is the correct place for this but I am using your mutt configuration (though an older, unupdated version) and I am wondering if I'm missing something obvious about the intended attachment workflow. I would like to "pipe" my attachments to other programs. Though not the attachment's contents through standard input, but the pathname into programs which expect that.

E.g. I have an `xlsx` file in an attachment and for some reason my default attachment opening configuration isn't handling it correctly. Now I know the correct response is to update my config with this extension. However, I wanted to avoid being distracted by configuration and just continue what I was doing. So it would be nice if I could do a quick `| open` since I know on my `open` command correctly handles this extension. Current `| : Pipe` command on the attachment view is not what I want, since this pipes the attachment content through standard input. I'd like something like pipe but would do `open {path/to/attachment}`

Is there an obvious way to achieve this with existing attachment command screen that I am just missing? If not, would it be possible / desirable to implement this feature?

(I apologize if the solution here is piping to something like a common program or otherwise as obvious. Still pretty new at basic unix things like piping.)

**Comment by f380cedric** [comment]
> Is there an obvious way to achieve this with existing attachment command screen that I am just missing? If not, would it be possible / desirable to implement this feature?

IMO, there is no such thing in neomutt, by default. You should configure your mailcap.

But you can write a macro to save the file then open it ([example](https://stackoverflow.com/a/21566216/7890872)).
