### ISSUE TITLE
Difficulties setting a timer in systemd

### ISSUE THREAD

**Issue by PeterPandaluki** [LukeSmithxyz/mutt-wizard#298]
Starting a systemd timer to run mbsync creates ownership problems with the encryption keys. The process exits with a warning "gpg: WARNING: unsafe ownership on homedir "

**Comment by grininmonkey** [comment]
Initially I tried adding the cron... but I discovered the following after I routed output to the journal...
```
awk: fatal: cannot open file `/root/.mbsyncrc' for reading (No such file or directory)
touch: cannot touch '/root/.config/mutt/.mailsynclastrun': No such file or directory
```
I think there is some more work to be done on what is generated in the mw scripts to be written to cron.... I didn't take too much time to attempt to figure out the "$HOME" not working there... before I tried some systemd stuff and ran into issues there...

So out of frustration... I quickly created an sh script with a loop and sleep 5m kicking of mailsync in it and added it to my short list of scripts on launch of awesomewm .... which works just fine...

If anything.... its a bandaid until I feel like getting smarter with it ;-)

**Comment by Kr1ss-XD** [comment]
I've actually written systemd-units to replace the cronjob, as I don't have a cron daemon on my system. Try them, if you like.

They are meant to be run in the user context, so place them inside `~/.config/systemd/user/` and start/enable them with
```
systemctl --user enable --now mailsync.timer
```
[mailsync-systemdunits.tar.gz](https://github.com/LukeSmithxyz/mutt-wizard/files/3686431/mailsync-systemdunits.tar.gz)

_Cheers !_
