### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by jarbus** [LukeSmithxyz/mutt-wizard#299]
I'm trying to connect to a university mail server, and am certain I'm inputting the right information. I'm able to login with a client like thunderbird to the server, however when I try to log in using MW I get the following error:

```
Cannot connect to [server address]: Connection refused
No working address found for [server address]
Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.
```

Is there anything I might be able to do to fix this?

**Comment by johns77** [comment]
You could write a minimal .mbsyncrc file and see if mbsync can connect, maybe you will at least get a more useful error message.

**Comment by jarbus** [comment]
I tried deleting .mbsyncrc and setting up an account without using mbsync, and got the following error:
Creating profiles for `test`...DONE.
IMAP command 'AUTHENTICATE PLAIN <authdata>' returned an error: NO authentication failure
Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.

**Comment by jarbus** [comment]
Nevermind, the issue was on my end, I didn't realize the account needed a username different than the email.
