### ISSUE TITLE
offlineimap asking for account passwords

### ISSUE THREAD

**Issue by lairdchris** [LukeSmithxyz/mutt-wizard#30]
Hi,
I finished configuring two accounts with the awesome script.
When I start offlineimap to sync the directories, I'm asked to enter the account passwords again, for both the 1und1-account and the GMail-account.

What am I doing wrong? Or is this intended?

gpg2 is installed, a key pair was created before.

`OfflineIMAP 7.1.2
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (system), Python v2.7.14, OpenSSL 1.0.2g  1 Mar 2016

Account sync xxxxxx:
 *** Processing account xxxxxx
 Establishing connection to imap.1und1.de:993 (xxxxxx-remote)
Enter password for account 'xxxxxx-remote':`

**Comment by LukeSmithxyz** [comment]
Hmm. Are you sure that you generated the GPG pair with the same email you gave as a recipient in the script?

**Comment by lairdchris** [comment]
Sorry, my fault!
I thought I pasted the password from another terminal using the mouse, but it seems that didn't work as expected.
After entering the password manually during the configuration process it's working...
