### ISSUE TITLE
urlview is not working like it should

### ISSUE THREAD

**Issue by kcallis** [LukeSmithxyz/mutt-wizard#301]
A couple of days ago, I inadvertently screwed up my **LARBS** configuration and ended up with the new changes like moving files from *~/.script* to *~/.local/bin*. Almost everything is working, but a slight issue with neomutt. Prior to changing my **LARBS** configuration, on the index, if I pressed v to open my list of html attachments and selected the HTML attachment, it would automatically open in **Firefox**. After the change, when I attempt to use v and pick a HTML attachment, for some reason, it attempts to open up the HTML file using **calibre**. I am assuming that **calibre** is trying to convert to an epub or something.

My ~/.urlview is

```bash
###############################################################################
# Urlview configuration file.
# man urlview  <Man page>
#
# Put this file in: $HOME/.urlview
# Put url_handler.sh in: /usr/bin
#
# You can call 'urlview' while in 'mutt' by pressing the Ctrl b keys.
# Put these macros in your $HOME/.muttrc file.
#
# macro index \cb |urlview\n
# macro pager \cb |urlview\n
#
# You can call 'urlview' while in 'tin' by pressing | then a for article,
# put urlview as the pipe command.
#
# Regular expression to use to match URLs.

#REGEXP (((http|https|ftp|gopher)|mailto):(//)?[^ >"\t]*|www\.[-a-z0-9.]+)[^ .,;\t>">\):]
REGEXP (((http|https|ftp|gopher)|mailto)[.:][^ >"\t]*|www\.[-a-z0-9.]+)[^ .,;\t>">\):]

# Command to invoke for selected URL.  Use lynx, netscape, or url_handler.sh
# shell script.  Alternatively, you can leave COMMAND unset and set the BROWSER
# environment variable instead.

#COMMAND lynx %s
#COMMAND netscape -remote 'openURL(%s)'
#COMMAND url_handler.sh
COMMAND linkhandler


# Quit urlview after launch
#QUITONLAUNCH
```
and even checked the *linkhandler* file:

```bash
#!/usr/bin/env sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it wll view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && { "$BROWSER"; exit; }

case "$1" in
        *mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*)
                setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 & ;;
        *png|*jpg|*jpe|*jpeg|*gif)
                curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
        *mp3|*flac|*opus|*mp3?source*)
                setsid tsp curl -LO "$1" >/dev/null 2>&1 & ;;
        *)
                if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR $1"
                else setsid "$BROWSER" "$1" >/dev/null 2>&1 & fi ;;
esac
```
I have also checked to make sure that my $BROWSER is firefox.

**Comment by LukeSmithxyz** [comment]
Ah `linkhandler` and `urlview` aren't the problem here: mutt-wizard doesn't use those (mutt-wizard and LARBS are non-overlapping). Instead it users a little shell wrapper `openfile` in this repository which just opens files with `xdg-open`.

The issue is `xdg-open`. For whatever reason, it thinks that calibre is your best browser. Look up how to change your default xdg programs and that will solve your problem.

**Comment by kcallis** [comment]
Thanks for the response. I did my research on xdg-open and played around with it. I then exit out from i3 and logged into my MATE desktop and make sure that the default applications were correct. Logging back into my i3 environment, I opened a link through mutt, and it opened up in Firefox as it was supposed to. I am not sure what was changed, but happy that is work correctly now!
