### ISSUE TITLE
mbsync deletes all non-recent emails

### ISSUE THREAD

**Issue by rayliu3798** [LukeSmithxyz/mutt-wizard#307]
I have run into this problem twice that every time I set up a new email account, mbsync would only sync a few recent emails and deletes the rest of them automatically, both master/slave. The delete emails were moved to 'deleted items' on both outlook.office365 and gmail. I tried to reconfigure the ~/.mbsyncrc but couldn't find the cause. Even I recover the emails on the server, every time I run mbsync would delete them again.

Here's what I have in my ~/.mbsync:
```
Channel ucalgary
Expunge Both
Master :ucalgary-remote:
Slave :ucalgary-local:
Patterns *
Create Both
SyncState *
MaxMessages 1000
Sync All
# End profile
```

**Comment by trissim** [comment]
I am also running into the same issue
