### ISSUE TITLE
Allow to send mails when offline

### ISSUE THREAD

**Issue by lukas-mertens** [LukeSmithxyz/mutt-wizard#311]
Following the principles of larbs, it would be great, if you could send mails to a queue when offline and later syncing them when online again. I found [msmtp-offline](https://github.com/venkytv/msmtp-offline), which should allow to do that pretty easily. It only has to be added to mw as a dependency and mw would have to do `set sendmail = "<path-to-msmtp-offline -a <mailbox>"` instead, as far as I understand. What do you think?

**Comment by LukeSmithxyz** [comment]
Well I've always sort of thought of that as being what the `Drafts` folder is for ;-)

I've thought of this before, but I don't think I want to add an additional dependency unless I can rely on it being in many different distros' repositories.

Making it optional would sort of be a headache too, so I'd rather just say that users can add it if they want, still using `mw`'s autobuild configs, but I can't reliably make them wrap around what would be required for this additional option.
