### ISSUE TITLE
Pinentry doesn't open properly in CLI only environment

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/mutt-wizard#318]
Similiar issue was mentioned here long time ago and it was already closed. It's original solution was to use pinentry-qt or pinentry-gtk instead of the tty or curses one but that's not really a solution when it comes to using mutt-wizard in terminal only environment like tmux session on remote server.

Mutt-wizard currently works 'fine' in terminal only environment in condition that user activate his gpg key (e.g. by "mbsync -a") before starting neomutt client. Problem starts when the gpg key times out. The tty or curses pinentry prompt just refuses to open inside neomutt client.

I already pulled a request where in '/usr/share/mutt-wizard.muttrc' I did edit the line 65 and replaced "mailsync -Va" with "mbsync -a". This is first step to be able atleast mbsync with terminal only pinentry. The problem still remains in sending an email with terminal only pinentry. As I mentioned before temporary solution for this is to activate gpg key before sending an email and send the email before the key times out.

**Comment by f380cedric** [comment]
Have you tried [this](https://wiki.archlinux.org/index.php/GnuPG#Configure_pinentry_to_use_the_correct_TTY)?
