### ISSUE TITLE
Please set ExpireUnread to decide outcome. Skipping mailbox.

### ISSUE THREAD

**Issue by ahmedselim2017** [LukeSmithxyz/mutt-wizard#319]
When I run mailsync it gives this. How can I set ExpireUnread to decide outcome?

I am using gmail with app password

**Comment by LukeSmithxyz** [comment]
You can add `ExpireUnread no` (or yes if you want) under the `MaxMessages` line in your `mbsyncrc` file. I think I'll make this default if it gives you an error. I guess you have a lot of unread emails!
