### ISSUE TITLE
Flags.

### ISSUE THREAD

**Issue by 11nightfury** [LukeSmithxyz/mutt-wizard#325]
D flag is for Delete, N is for New, O is for Old. What are r, *, and ! flags? Is r flag for forwarded mails?

In the help section F is bind to flag-message which toggles message's 'important' flag, but when I press F, I don't see any changes?

**Comment by LukeSmithxyz** [comment]
- `!` - flagged as important
- `r` - mails replied to
- `*` - tagged mail (for running commands on multiple emails)

Consult `man neomutt` or `man neomuttrc` for questions like this.

**Comment by rpietro** [comment]
@LukeSmithxyz I think the issue should still be open. F doesn't result in a flag, simply moves the cursor to the line below. Trying to flag it using w and then !  also doesn't work. I tried to force F to flag the email on muttrc, but that didn't work either. I then checked if there was anything under /usr/share/mutt-wizard that could be causing this behavior, but those files don't mention flags. 

Any thoughts?

**Comment by LukeSmithxyz** [comment]
Consult the `index_format` entry in the manual. You are flagging mail perfectly well, the issue is by default, the important flag is not displayed. You might want to replace the shared config line here:

```
set index_format="%2C %zs %?X?A& ? %D %-15.15F %s (%-4.4c)"
```

with this:
```
set index_format="%2C %Z %?X?A& ? %D %-15.15F %s (%-4.4c)"
```

Which will show all possible tags/status. I don't use this myself because I don't mark mail as important and it takes up a little more run, but I suppose I might want to make this the default for this kind of confusion.

**Comment by rpietro** [comment]
Thanks! Works perfectly now. Just for the record, I just found a [previous discussion](https://github.com/LukeSmithxyz/mutt-wizard/issues/157#issuecomment-494334883), where @Kr1ss-XD proposed a way of marking emails with color. For example:

> color index                  brightyellow  red        '~F'
> color index_author      brightgreen   red        '~F'
> color index_subject     white             red        '~F'

The only issue is that if you try to also tag messages (t) using the current light blue standard, that color won't show up. His other tip was to check out [neomuttrc(5)](https://manpages.debian.org/testing/neomutt/neomuttrc.5.en.html), which indeed has a ton of useful information.

@LukeSmithxyz you probably get this a lot, but thanks a ton for creating mutt-wizard, this is an awesome project.
