### ISSUE TITLE
NeoMutt 2019-11-11 "Unknown Mailbox" error

### ISSUE THREAD

**Issue by Vintodrimmer** [LukeSmithxyz/mutt-wizard#327]
Since today's update neomutt throws the following error:
```
❯ neomutt
Unknown Mailbox: /home/eichhorn/.local/share/mail/freiburg_teacher/freiburg_teacher
Error in /home/eichhorn/.config/mutt/accounts/1-freiburg_teacher.muttrc, line 24:
Error in /home/eichhorn/.config/mutt/muttrc, line 3: source: file /home/eichhorn/.config/mutt/accounts/1-freiburg_teacher.muttrc could not be sourced
source: errors in /home/eichhorn/.config/mutt/muttrc
Press any key to continue...
```

Line 24 contains the following:
```
mailboxes =freiburg_teacher ===================== "=INBOX" "=Drafts" "=Queue" "=Sent" "=Trash"
```

How should I fix it?

**Comment by Kr1ss-XD** [comment]
Seems that the support for those "pseudo-mailboxes" has been dropped. What I've done is to just create these missing files in the local mail spool so neomutt can find them.
In your case that would mean : 
```
$ touch /home/eichhorn/.local/share/mail/freiburg_teacher/{freiburg_teacher,====================}
```
and restart neomutt.
However, I'm not sure yet if this method leads to any unwanted side effects (though I haven't noticed any issues so far).

So If you don't mind the missing mailbox title in your sidebar, you could also just remove the `=freiburg_teacher ===================== ` part from your `1-freiburg_teache.muttrc` file.

**Comment by Vintodrimmer** [comment]
Thanks a lot!
I don't mind the lack of the title, since it stopped working 2 updates ago, but still showed all the subsequent folders, such as "Drafts" and "Queue".
Currently, all the folders are gone if the initial one doesn't exist.

Once again, thank you.
