### ISSUE TITLE
Neomutt update breaks mailboxes line?

### ISSUE THREAD

**Issue by hhh95** [LukeSmithxyz/mutt-wizard#329]
After todays update to neomutt, I got error messages when opening neomutt. I pinpointed it to the mailboxes line. Apparently what you used to as a trick to show a name for the mailboxes doesn't work anymore.

`mailboxes =gmail ===================== "=Drafts" "=[Google Mail].Trash"...`

has to be changed to

`mailboxes ="Drafts" "=[Google Mail].Trash"...`

I haven't found a way though to show the account name.

**Comment by Kr1ss-XD** [comment]
I did though, as stated in an [earlier ticket](https://github.com/LukeSmithxyz/mutt-wizard/issues/327#issuecomment-552566675).

I still haven't experienced any downsides (except that there are these otherwise useless empty files in the spool folder, but they don't really bother me).

**Comment by hhh95** [comment]
Oh I‘m sorry, I must have missed the earlier ticket. I‘ll mark this as done then.
