### ISSUE TITLE
Title of mailbox results in Error "Unknown Mailbox"

### ISSUE THREAD

**Issue by CheckmateIn2** [LukeSmithxyz/mutt-wizard#332]
The line inside of the account configuration (muttrc) setting the mailboxes:

`mailboxes =ACCOUNTNAME ========= "=INBOX" ... `

results in an error: 

`
Unknown Mailbox: /home/USER/.local/share/mail/account/ACCOUNTNAME
`

This leads to the sidebar at the left being empty (neither accountname, nor inbox etc. is shown).

**Comment by CheckmateIn2** [comment]
Just updated to the new version. 
The latest version does not add the account name and therefore the sidebar is not empty anymore (all folders shown). 

But unfortunately the name of the account still is not shown.
When switching between different accounts, the name is nowhere displayed. Is there any fix for that?

Thanks

**Comment by Kr1ss-XD** [comment]
https://github.com/LukeSmithxyz/mutt-wizard/issues/327
https://github.com/LukeSmithxyz/mutt-wizard/issues/329
