### ISSUE TITLE
Emails sent twice from neomutt (mutt-wizard)

### ISSUE THREAD

**Issue by prakash2033** [LukeSmithxyz/mutt-wizard#333]
I'm using this wonderful program neomutt (mutt-wizard) for my emails.

I have recently configured it on my new system and noticed the emails
are being sent twice for some reason, which you might understand better.
I presume, it is happening after the recent commit.

I would appreciate if you could please have a look at it on priority?

OR let me know how i can fix it on my own?

And once fixed, do i need to purge, pull latest and reinstall it from
mutt-wizard?

**Comment by LukeSmithxyz** [comment]
Are mails actually sent twice or is it that there are two copies of each mail in your Sent directory? There are some email providers that automatically add Sent mail there, thus you should change mutt's sent mail folder to `/dev/null` to prevent duplication.

**Comment by prakash2033** [comment]
The mails are actually sent twice.

**Comment by rom-dos** [comment]
I was having the same issue with duplicate emails being sent (specifically with a Gmail account), however, the issue was resolved with modifying the respective `muttrc` to use `set record = /dev/null`, as Luke suggested.
