### ISSUE TITLE
empty sidebar on NeoMutt 20191111

### ISSUE THREAD

**Issue by alembiq** [LukeSmithxyz/mutt-wizard#338]
i've updated my neomutt to: NeoMutt 20191111
and sidebar is just empty, so far confirmed on two computers
downgrading to neomutt_20180716 helped
however i'm not sure if it's a issue of package or mutt-wizard configuration :(

**Comment by LukeSmithxyz** [comment]
Can you check your account-specific muttrc file in
~/.config/mutt/accounts/ and post what content the `mailboxes` line has?

What is your email provider?

**Comment by alembiq** [comment]
for example  gmail
`mailboxes =gmail ======================= "=INBOX" "=[Gmail].Important" "=[Gmail].Starred" "=ACCESS" "=MONEY" "=WORK" "=Kickstarter" "=Patreon" "=[Gmail].Bin" "=[Gmail].Chats" "=[Gmail].Drafts"  "=[Gmail].Sent\ Mail" "=[Gmail].Spam"  
`

**Comment by LukeSmithxyz** [comment]
Okay, interesting. I just tested 2019111 and couldn't replicate.

So when you say "empty" there _is_ a space for the sidebar, but it doesn't have _anything_ in it?

**Comment by alembiq** [comment]
![mutt](https://user-images.githubusercontent.com/37374721/69580367-b7d69c00-0fd4-11ea-9b83-86a3330d3192.png)

exactly :(

**Comment by cemkeylan** [comment]
yeah, for some reason neomutt stopped reading non existing mailbox directories, in this case it is the =accountname ==========, if you delete them sidebar comes back.

**Comment by LukeSmithxyz** [comment]
That could definitely be it, but I think for other people it was giving an error first. Either way, that part should be removed.

**Comment by alembiq** [comment]
`mailboxes "=INBOX" "=[Gmail].Important" "=[Gmail].Starred" "=ACCESS" "=MONEY" "=WORK" "=Kickstarter" "=Patreon" "=[Gmail].Bin" "=[Gmail].Chats" "=[Gmail].Drafts"  "=[Gmail].Sent\ Mail" "=[Gmail].Spam" `

works :) thank you

**Comment by alembiq** [comment]
eh i should close it, before it's fixed - right? :)

**Comment by JBlocklove** [comment]
I feel like the empty sidebar issue has been resolved, but now there's no way to differentiate the mailboxes. Should a different issue be opened for that, should it be discussed here, or is it just something we're going to have to live with?

**Comment by LukeSmithxyz** [comment]
Yeah I think we'll have to deal with it for the time being. It's a shame the upstream isn't so flexible, but it'll be fine.

**Comment by TheScrawl** [comment]
if you want to still have a name and divider line, you just need to create an empty file in the mailbox directory that is named what you want the divider and identifier to be named
for example
in `~/.local/share/mail/mailbox-name/` run `touch mailboxname` and `touch "=========="`
then you can leave `=mailbox-name ===========` in the mailboxes line of the account config file and it will work. Make sure there is 1 more `=` in the config file than the filename has, for the declaration.
