### ISSUE TITLE
[MacOS] Cannot run offlineimap ( no accounts are defined )

### ISSUE THREAD

**Issue by meain** [LukeSmithxyz/mutt-wizard#34]
I am having issue when running `offlineimap`

```
OfflineIMAP 7.1.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.10, LibreSSL 2.2.7
ERROR: The account '' does not exist
ERROR: Exceptions occurred during the run!
ERROR: The account '' does not exist
No accounts are defined!
```

`~/.offlineimap`
```
[general]
accounts =
starttls = yes
ssl = yes
pythonfile = ~/.config/mutt/credentials/imappwd.py

[Account gmail]

localrepository = gmail-local
remoterepository = gmail-remote

[Repository gmail-remote]
auth_mechanisms = LOGIN
type = Gmail
remoteuser = abinsimon10@gmail.com
sslcacerfile = /etc/ssl/cets/ca-certificates.crt
remotepasseval = mailpasswd("gmail")
remoteport = 993
folderfilter = lambda foldername: foldername not in ['[Gmail]/All Mail']
sslcacertfile = /etc/ssl/certs/ca-certificates.crt

[Repository gmail-local]
type = Maildir
localfolders = ~/.mail/gmail
```

**Comment by LukeSmithxyz** [comment]
Well the problem is clearly for some reason your account name `gmail` was not added to the `accounts =` line, although I have no idea why. You should be able to just change it to `accounts = gmail` and it will work; I just can't immediately think of why it failed to add it in the first place.

Did you manually edit the file any?

**Comment by meain** [comment]
No,  I had not manually edited any files.

**Comment by LukeSmithxyz** [comment]
Okay. If you manually add in `gmail` to the line does it work for you?

W.r.t. the cause of the problem, are you using BSD by any chance? Or MacOS? It's possible that the different varieties of `sed` are not adding this line correctly.

**Comment by meain** [comment]
Oh, I am on `MacOS`. I'll look into it and maybe submit a PR if I can get it fixed.

Btw, that issue gets solved when I manually add `gmail` but then there is some certificate issue which again from what I have understood so far is again an issue specific to `MacOS`

```
OfflineIMAP 7.1.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.10, LibreSSL 2.2.7
Account sync gmail:
 ERROR: CA certfile for repository 'gmail-remote' couldn't be found.  No such file: '/etc/ssl/certs/ca-certificates.crt'
ERROR: Exceptions occurred during the run!
ERROR: CA certfile for repository 'gmail-remote' couldn't be found.  No such file: '/etc/ssl/certs/ca-certificates.crt'

Traceback:
  File "/usr/local/Cellar/offlineimap/7.1.5_1/libexec/offlineimap/accounts.py", line 268, in syncrunner
    self.remoterepos = Repository(self, 'remote')
  File "/usr/local/Cellar/offlineimap/7.1.5_1/libexec/offlineimap/repository/__init__.py", line 84, in __new__
    return repo(name, account)
  File "/usr/local/Cellar/offlineimap/7.1.5_1/libexec/offlineimap/repository/Gmail.py", line 33, in __init__
    IMAPRepository.__init__(self, reposname, account)
  File "/usr/local/Cellar/offlineimap/7.1.5_1/libexec/offlineimap/repository/IMAP.py", line 42, in __init__
    self.imapserver = imapserver.IMAPServer(self)
  File "/usr/local/Cellar/offlineimap/7.1.5_1/libexec/offlineimap/imapserver.py", line 101, in __init__
    self.sslcacertfile = repos.getsslcacertfile()
  File "/usr/local/Cellar/offlineimap/7.1.5_1/libexec/offlineimap/repository/IMAP.py", line 277, in getsslcacertfile
    raise OfflineImapError(reason, OfflineImapError.ERROR.REPO)
```

**Comment by meain** [comment]
Solved the certificate issue with http://rudolfochrist.github.io/blog/2015/03/21/offlineimap-with-ssl-files-on-osx/

**Comment by LukeSmithxyz** [comment]
Okay great. It actually looks like OSX compatibility is only a couple of lines away, which is closer than I anticipated. Can you send mail, etc. and get the other functionality once you change those few things?

**Comment by meain** [comment]
Toke me some time to sync up my mail.

I am not yet able to get it working. 
Hitting this when opening `neomutt`
```
/var/mail/meain: No such file or directory (errno = 2)
```

**Comment by meain** [comment]
I do have this though

```
.offlineimap
├── Account-gmail
│   └── LocalStatus-sqlite
├── Repository-gmail-local
│   ├── FolderValidity
│   └── UIDMapping
├── Repository-gmail-remote
│   ├── FolderValidity
│   └── UIDMapping
└── mbnames
```

**Comment by LukeSmithxyz** [comment]
Did you run the "Autodetect mailboxes" option after running `offlineimap`? You'll get that error if you haven't run the autodetect option. Of course it might be another difference between Mac and GNU sed.

**Comment by meain** [comment]
Hit one more issue when trying to send mail.

Getting `no authenticators available` when sending email. 

Can be fixed by adding this to `muttrc`. [SO](https://github.com/Homebrew/legacy-homebrew/issues/33419)
```
set smtp_authenticators = 'gssapi:login'
```

**Comment by meain** [comment]
Few more stuff for anyone trying to set this up on `MacOS`

You might have to do `brew install iproute2mac` for `ip` command and change line 11 in `~/.config/mutt/mailsync.sh` to 
```
ping -q -c 1 `ip r | grep default | cut -d ' ' -f 3` >/dev/null || exit
```
