### ISSUE TITLE
STATUSBAR: parameter null or not set

### ISSUE THREAD

**Issue by ekollof** [LukeSmithxyz/mutt-wizard#340]
Mailsync seems to be broken for me.

```
magrathea:mutt-wizard:% crontab -l                                                                                                                                <master ✗>
* */1 * * * /usr/bin/imapfilter

*/5 * * * * export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus; export DISPLAY=:0; . $HOME/.profile; /usr/bin/mailsync
magrathea:mutt-wizard:%  export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus; export DISPLAY=:0; . $HOME/.profile; /usr/bin/mailsync                     <master ✗>
/usr/bin/mailsync: line 51: STATUSBAR: parameter null or not set
```

**Comment by Salastil** [comment]
Seems related to this commit: https://github.com/LukeSmithxyz/mutt-wizard/commit/7698abb0f9fc236b578e3ec6caa31867de019c6e

A simple workaround would be to specify the status bar manually by editing /usr/bin/mailsync and changing lines 51 and 61 whatever bar you're using. In my case it is i3blocks. Furthermore I would verify that the -RTMIN signal corresponds to what signal the mail statusbar is assigned to. It appears LARBS deploys it to 12 but if you wrote your own like I did it will nail whatever is camping on signal 12. In my case a "Now Playing:" blocklet for mpv. 

`pkill -RTMIN+12 i3blocks >/dev/null 2>&1`

I don't know how dwm or other statusbars handle the RTMIN signals so don't blindly copy and paste.

**Comment by LukeSmithxyz** [comment]
Fixed. I didn't expect the `pkill` command  to halt the whole script if `STATUSBAR` wasn't defined. It's been relegated to a subshell now which should fix the problem.
