### ISSUE TITLE
Unknown Mailbox: /home/kjell/.local/share/mail/kjell/INBOX.MMo-Battleforce.net

### ISSUE THREAD

**Issue by AtomToast** [LukeSmithxyz/mutt-wizard#342]
I just installed mutt-wizard/neomutt for the very first time.
The installation went successfully though when then starting neomutt there appears this error:  
```
Unknown Mailbox: /home/kjell/.local/share/mail/kjell/INBOX.MMo-Battleforce.net
Error in /home/kjell/.config/mutt/accounts/1-kjell.muttrc, line 24:
Error in /home/kjell/.config/mutt/muttrc, line 3: source: file /home/kjell/.config/mutt/accounts/1-kjell.muttrc could not be sourced
source: errors in /home/kjell/.config/mutt/muttrc
```

also in neomutt only the folders up to but excluding the on that threw the error are now rendered. The autogenerated shortcuts also stop there. In total it only manages about 14 lines

Overall I have 54 folders. Most of them are really old and I wouldn't have an issue deleting this one if it causes any issue since I don't even know what it was for anymore.   

Something I noticed was that this folder seems to be the only one with a dot in the name. That might have something to do with it.  

I don't really want to post the whole configuration file because it contains personal information.

**Comment by atreyasha** [comment]
Same issue for me, detailed upstream in neomutt as [#1958](https://github.com/neomutt/neomutt/issues/1958)

I believe there is no official solution as yet, only user-developed hacks

**Comment by AtomToast** [comment]
Well, this is my first install. I don't have a version to downgrade back on. My config also never contained anything like the configuration with all the ==========.  

So basically I really only have the option of removing the mailbox. I will try that and report back

**Comment by AtomToast** [comment]
Alright so a few observations:  

- Removing the failing mailbox fixed the problem  
- Adding a dot to other mailbox names then causes the same issue for them.

So it does seem to be caused by the dot in the name.  

Also on a kind of unrelated note neomutt seems to not be able to handle my imported mailboxes properly and just gave the shortcuts to the first few folders instead of the correctly named, INBOX, Sent, etc

**Comment by Kr1ss-XD** [comment]
The '`.`' is interpreted as a path divider in mailbox names (meaning `INBOX.MMo-Battleforce.net` would describe a mailbox named `net` in a subfolder `MMo-Battleforce.net` which would be supposed to be in the `INBOX` folder). Basically the same like '`/`' in local file paths.
You could try to escape the conflicting '`.`' by prepending it with a '`\`', though I haven't tested that myself:

 - edit `~/.config/mutt/accounts/1-kjell.muttrc` at line 24
 - change `INBOX.MMo-Battleforce.net` to `INBOX.MMo-Battleforce\.net`

If that works out as I'm imagining, this should also enable the other missing folders, as @atreyasha already mentioned.

**Comment by AtomToast** [comment]
That did not work. It gives the exact same error, the backslash is also not displayed in the error

**Comment by atreyasha** [comment]
@AtomToast I just checked and there are other bugs related to the latest neomutt release, such as screen flickering documented [here](https://github.com/neomutt/neomutt/pull/1974), which I personally also experienced. A PR has been merged for it but I believe they have not released it into the main distro repositories.

I would recommend either manually compiling an older neomutt version or perhaps using the `downgrade` AUR [package](https://aur.archlinux.org/packages/downgrade/) (if you are using an arch-based distro). You might need to temporarily disable signing of packages for this, as detailed [here](https://bbs.archlinux.org/viewtopic.php?id=159353).

**Comment by AtomToast** [comment]
I personally don't have an issue with just removing the folder since I really don't use it anymore.  
I mainly wanted to bring awareness to this issue

**Comment by rpietro** [comment]
@atreyasha confirming that your suggestion to downgrade to NeoMutt 2019-11-02 makes it work with mutt-wizard configurations and completely addresses the problem. I don't see a problem sticking with this version until the neomutt developers come up with a solution. 

Btw, [downgrader](https://aur.archlinux.org/packages/downgrader/) is a great way to downgrade neomutt.
