### ISSUE TITLE
be ablee to restore muttrc

### ISSUE THREAD

**Issue by ploum** [LukeSmithxyz/mutt-wizard#343]
I've tried to modify the muttrc, thinking I knew what I was doing. As I failed, I tried to restore the "original mw generated" muttrc. It didn't work so I'm guessing I modified it at some point.

I would like to be able to restore but mv has not option to regenerate the config.

**Comment by ChausseBenjamin** [comment]
Best option (unless you have very extensive configuration going on) would be to simply purge and add your account. How would mw know where to restore to?

Say you add `email1`, make configuration changes, add `email2`, and then make some more configuration. How would mw know when to restore or what to restore to? does it restore to the creation of `email1` and discard adding some customizations plus an email? Does it only store a backup of every edit made? That would unnecessarily compllicate things...

If you really want a way of reverting to previous configurations, I would suggest you make your own version control system. You could [setup a git bare repository](https://youtu.be/tBoLDpTWVOM). If you prefer an easier approach, you could always try [YADM](https://github.com/TheLocehiliosan/yadm) which uses said git bare repository in the background.
