### ISSUE TITLE
attach list not showing

### ISSUE THREAD

**Issue by rpolve** [LukeSmithxyz/mutt-wizard#344]
Hi,

When I press '?' in order to see the list of files to select, it doesn't show me anything.

This currently happens only with one account (Outlook), whereas my other account (Gmail) behaves correctly.

Attaching by absolute path still works, though.

**Comment by tzcrawford** [comment]
I experience this as well as with the <save-message> command used to move mail to another folder which you pick with the same user interface as the attachment list. The attachment issue applies to both my Outlook and university address while the mail moving issue applies only to my university email. This appears to be a version issue similar to the mailbox error in [issue 342](https://github.com/LukeSmithxyz/mutt-wizard/issues/342) and downgrading to the July 16 version in Arch linux seems to fix the issue at least temporarily.

**Comment by atreyasha** [comment]
Also referenced upstream in `neomutt` as [#1950](https://github.com/neomutt/neomutt/issues/1950)

**Comment by atreyasha** [comment]
Solved for me with NeoMutt 20200313
