### ISSUE TITLE
Use mailsync in keybinding instead of mbsync

### ISSUE THREAD

**Issue by pengux** [LukeSmithxyz/mutt-wizard#348]
Haven't read the code for mailsync but I'm guessing there's an advantage of using it compared to `mbsync -a`? Why shouldn't it be used for the kyebinding `macro index O`?

**Comment by LukeSmithxyz** [comment]
mailsync gives notifications and updates notmuch among other things. I suppose that it doesn't make that much of a difference if you are running it manually though.
