### ISSUE TITLE
Suppressing Autoview Messages

### ISSUE THREAD

**Issue by Itailevi420** [LukeSmithxyz/mutt-wizard#350]
Hello, first off **great** app. 
In every html like mail I get these messege:
```
 [-- Autoview using lynx -assume_charset='utf-8'-display_charset=utf-8 -dump  '/tmp/neomutt.html' --]
  ```
Maybe it's a silly question but this is how it supposed to look?
![page123](https://user-images.githubusercontent.com/50306464/71639910-0d176480-2c89-11ea-8838-791c2a0fa883.png)

**Comment by Kr1ss-XD** [comment]
That's a message from Neomutt about what command it is using to display the following attachment. It doesn't belong to the actual mail.

So yes, that's how it's supposed to look.

I think there's no way to not have these headers displayed, but if they really bother you, it's possible to define their fore-/background colors in the `muttrc` file.

Assuming your default background color is black, you could put a line like
```
color  attachment  black  black
```
into that file which would result in those lines being invisible.
If you already have a command starting with `color attachment` in your config, replace it with the one above.

**Comment by Itailevi420** [comment]
Thanks for the response

**Comment by LukeSmithxyz** [comment]
Come to think of it, if anyone knows of how to suppress that line, I suppose I'd be interested in doing it.

**Comment by Kr1ss-XD** [comment]
Maybe try
```
unset show_multipart_alternative
```
I think that could do the trick. I stumbled over this by accident :rofl:  :man_dancing: 
The variable may be set to `info`, to display these lines, `inline`, which makes neomutt show all alternatives (e.g. first text/plain and below text/html; also including the leading info lines) or unset to suppress them completely and only show the default alternative.

**Comment by itsdeadguy** [comment]
The answer to this is to `set display_filter` to `sed /something/or/other` or a script containing an expression such that it would remove the message.
Some searching led me to `sed -e '/^\[-- Autoview using .* --]$/d'` but this didn't work for me in neomutt, maybe it's badly written?

Here's a [relevant link to neomutt's reference](https://neomutt.org/guide/reference.html#3-84-%C2%A0display_filter)

**Comment by LukeSmithxyz** [comment]
Okay great. Thanks for the hint. It looks like `[` need to be triple escaped in a sed command and I don't know if `^` will work as intended, but this does seem to work for me.

I'll look into defaults for this. If I simply delete the line, I also want to delete the following lines to avoid continuous blank lines and so.

I'll play around with sensible defaults.

**Comment by itsdeadguy** [comment]
Here's something i found in the [gentoo forums](https://forums.gentoo.org/viewtopic-t-148115-start-0.html), which does work and removes the spaces
```
set display_filter="sed -e '/\\[-- Type: text.* --\\]/d' | sed -e '/\\[-- Autoview.* --\\]/d' | sed -e '/\\[-- Type.* --\\]/d' |  sed -e '/\\[-- .*unsupported.* --\\]/d' | sed -e '/\\[-- Attachment #[0-9] --\\]/d' | sed -e 's/Attachment #[0-9]: //g' | sed '/./,/^$/!d'"
```
