### ISSUE TITLE
abook integration interferes with goobook

### ISSUE THREAD

**Issue by ChausseBenjamin** [LukeSmithxyz/mutt-wizard#352]
As mentioned in [this previous issue](https://github.com/LukeSmithxyz/mutt-wizard/issues/71), it was suggested that someone whom wants to use goobook should install it manually.

I did accordingly but since mutt-wizard has pre-made bindings for abook, both interfere with eachother. I added the following command to my muttrc to enable goobook: 

```
# Goobook Configurations:
set query_command="goobook -c $HOME/.config/goobook/config query %s"
bind editor <Tab> complete-query
macro index,pager a "<pipe-message>goobook -c $HOME/.config/goobook/config add<return>" "add the sender address to Google contacts"
```

Yet, when I type `Q` (to query an email), the following occurs:

```
Waiting for response...sh: abook: command not found
(null)
```

And when I type `a` to add an email to my contacts, this occurs:

```
sh: abook: command not found
Press any key to continue...
sh: abook: command not found
Press any key to continue...
```

Is there a command I could send to mutt-wizard to disable abook when using goobook?

Thank!

**Comment by LukeSmithxyz** [comment]
You'd have to manually remove the abook commands from `/usr/local/share/mutt-wizard/mutt-wizard.muttrc`.
