### ISSUE TITLE
RFE: Implement Mozilla autoconfig

### ISSUE THREAD

**Issue by patrickbenkoetter** [LukeSmithxyz/mutt-wizard#354]
Have you ever considered implementing Mozillas autoconfig method to retrieve configuration information and use that to create account config?

**Comment by LukeSmithxyz** [comment]
Have I thought about it? Yes. Have I done it? No. I was thinking to implement a trial and error procedure similar to it at least.

**Comment by patrickbenkoetter** [comment]
I'm one of the people behind https://automx.org. If you need a test server to run your script against, let me know. I think it would be nice to see us team up for this.
