### ISSUE TITLE
Let's Encrypt mail providers fail to synchronize

### ISSUE THREAD

**Issue by GovanifY** [LukeSmithxyz/mutt-wizard#355]
I have my own webmail provider, which does use Let's Encrypt for its TLS certificates. It seems your script unfortunately fails to find any Let's Encrypt root certificate which makes mbsync fail with the error "unable to get local issuer certificate".

I was able to get by by very dirtily hardcoding my certificate in the script. I am using the standard `ca-certificates` from Gentoo packages which seems to miss them.
Do you think anoption for retrieving the root certificate should be included?

**Comment by LukeSmithxyz** [comment]
I can't tell you what's wrong on your side, but I'll go ahead and say that I use Let's Encrypt and it works fine. Are you sure you have all the mail subdomains properly configured?

**Comment by GovanifY** [comment]
I'm sure about that, I don't use any subdomains actually. The certificates are indeed valid but the cross signing root identity by DST is not present in my distribution by default, nor the ICSG X1 root for that matter. It should be the standard ca-certificates/mozilla which does leave me puzzled though, especially since my website works fine in any browser.

**Comment by mrchainman** [comment]
I had the same problem. i fixed it by saving my ssl cert locally and pointing mbsync and msmtp to it. i forked mutt-wizard and added the option to use a custom certificate file, you can find it here:
https://github.com/mrchainman/mutt-wizard
Luke, may I know why you don't want to merge my pull request?

**Comment by AndreSouzaAbreu** [comment]
@GovanifY  and @mrchainman  I'm facing the same problem. Can you tell me how do I get the ssl cert from my webserver and how do I make neomutt use them? I guess I should put it on /etc/ssl/ca-certificates, but I'm not sure

**Comment by mrchainman** [comment]
> @GovanifY and @mrchainman I'm facing the same problem. Can you tell me how do I get the ssl cert from my webserver and how do I make neomutt use them? I guess I should put it on /etc/ssl/ca-certificates, but I'm not sure

You can look at my fork for how to do it

**Comment by AndreSouzaAbreu** [comment]
> > @GovanifY and @mrchainman I'm facing the same problem. Can you tell me how do I get the ssl cert from my webserver and how do I make neomutt use them? I guess I should put it on /etc/ssl/ca-certificates, but I'm not sure
> 
> You can look at my fork for how to do it

I'm getting the error `error:1408F10B:SSL routines:ssl3_get_record:wrong version number`. I pointed to the full of path of SSL file. Don't know why this is happening
