### ISSUE TITLE
Change .mbsyncrc to a XDG location

### ISSUE THREAD

**Issue by aleprovencio** [LukeSmithxyz/mutt-wizard#356]
Hi,
I'm aware that `isync` is not `XDG-dirs` compliant by default, but a common hack is to place it somewhere inside `$XDG_CONFIG_HOME` (usually inside `~/.config/neomutt`) and call this file as an argument for `mbsync -c $file`.

I think this feels more aligned with the rest of the code, and BTW thanks for it :)

**Comment by LukeSmithxyz** [comment]
That would also require a shell alias if running it manually and a bunch of ugliness. I'm not going to move mbsync into `config` until it's fixed upstream; it just causes more problems.

**Comment by aleprovencio** [comment]
Alright, definitely the best case scenario is upstream working on it.
