### ISSUE TITLE
Bug (?): Cronjob not working if .profile not present

### ISSUE THREAD

**Issue by niklassc7** [LukeSmithxyz/mutt-wizard#357]
I've noticed that the cronjob created by the script imports `. $HOME/.profile;`.
In my case, because I didn't have `.profile` this caused the cronjob to not work. Deleting the part `. $HOME/.profile;` fixed that though and I thought I'd notice you in case others have that problem too.
Maybe the script could check that or it could go into the readme.

**Comment by LukeSmithxyz** [comment]
I believe this issue should be finished as the cron command should no longer need any information from the profile.
