### ISSUE TITLE
Nested folders are not shown

### ISSUE THREAD

**Issue by ngortheone** [LukeSmithxyz/mutt-wizard#359]
I have a folder structure 
`Inbox/FolderA/FolderB`

In side bar I see `Inbox` and `Inbox.FolderA`, but I don't see `FolderB` at all.
When I look inside `~/.local/share/mail/myaccount/` I see FolderB where it is supposed to be.
So it is mutt's configuration problem.

Please help to troubleshoot

**Comment by ngortheone** [comment]
I also fount that account configuration file had
`mailboxes` variable with a list of folders, and but subfolder `folderB` was not there. I wonder why?

**Comment by zoraj** [comment]
I have the same issue, mutt can't even display Inbox/FolderA. How did you do to display FolderA ?

**Comment by ngortheone** [comment]
Hey @LukeSmithxyz 

(With my troll mask on) - mutt is bloat!
You should use nmh,mmh, or my favorite [mblaze](https://github.com/leahneukirchen/mblaze)
(Mask off) Sorry, couldn't help myself :) Keep up awesome work!


@zoraj you need to tell mutt explicitly what your folders are. You can use a script to auto-discover your folders at mutts startup.
It is easier if you use things like mbysnc to have a local copy of your email account. Otherwise you need to poke IMAP server to get the list of folders.
