### ISSUE TITLE
(?!) "Please enter the passphrase to unlock the OpenPGP secret key: "

### ISSUE THREAD

**Issue by BinhKhang** [LukeSmithxyz/mutt-wizard#361]
I encouter two problems:
1. when I try to sign in, a pop-up window appears and asks passphrase to unlock the OpenPGP secret key, but I do not know what thing to put in.
2. the popup window  always contains the first entered email, while I have been trying to sign in by another email.

**Comment by LukeSmithxyz** [comment]
This is to unlock your GPG key so you an decrypt your encrypted passwords. Read the documentation and install pam-gnupg if you want to avoid it.
