### ISSUE TITLE
Mailsync not sending notifications anymore

### ISSUE THREAD

**Issue by JBlocklove** [LukeSmithxyz/mutt-wizard#366]
For some reason mailsync no longer gives me any notifications. `notify-send` still works just fine if I run it manually, and all of my other notifications are working, but `mailsync` just no longer gives me anything. This has been going on for a little while now and I can't seem to figure out what's going on.

Distribution: Arch Linux
Kernel: 5.5.2-arch1-1
Notifications: Dunst

**Comment by LukeSmithxyz** [comment]
Are you running mailsync manually or are you talking about it running as
a cronjob?

**Comment by JBlocklove** [comment]
I have it running as a cronjob, but I've also been testing it manually and I don't get notifications either way.

**Comment by LukeSmithxyz** [comment]
Okay. I guess you're using the most recent bulid? Well I just made a change that I thought would _fix_ this issue for good.

What distro do you have? What's your notification manager?

**Comment by JBlocklove** [comment]
Yeah, I pulled and rebuilt yesterday after your most recent commit. I'm on Arch and I'm using Dunst for notifications.

**Comment by JBlocklove** [comment]
I just reinstalled again and redid my cronjob and whatnot. Ultimately nothing should have changed, but I seem to get my notifications now, so I think it was just a short-term bug with my system.

**Comment by JBlocklove** [comment]
I stand corrected, apparently it worked once and then never again.

**Comment by LukeSmithxyz** [comment]
Okay. I've noticed an issue where I get notifications, but much later than when the mail is synced. I'll have to determine why.

Are you using multiple displays? This might actually affect a change because the sync command now automatically assumes a particular display?

**Comment by JBlocklove** [comment]
I predominantly just use my laptop display. Every once in a while I connect to an external monitor, but I'm not getting notifications consistently enough to know if that has an effect. I'm getting them occasionally now, but not always and it seems to never send them when I sync from neomutt itself.

**Comment by thepenguinthatwants** [comment]
I also have same problem. Using arch linux and notify-send works and cronie, but it doesnt generate any dunst messages.

cronie status, can see that there are new emails tho.

**Comment by thepenguinthatwants** [comment]
After trying it a bit  fetching by keybinding o sets the dunst to show about new emails.

**Comment by thepenguinthatwants** [comment]
```
		(crontab -l; echo "*/$minnum * * * * $(type mailsync | cut -d' ' -f3)") | crontab - &&
			echo "Cronjob added. Mail will sync every $minnum minutes. Be sure you have your cron manager running."
	fi ;}
```
As there doesnt seem to be any notifications generated automatically? Would it be possible that its running on root? Instead of normal user so it doesnt show any outputs?

**Comment by JBlocklove** [comment]
I've updated a few times now and reinstalled dunst as well as the initial cronjob that's done through `mw`. Cron is now delivering my notifications fine, as well as neomutt when I sync an individual mailbox. However, when I use `O` to sync all mailboxes I don't get any notifications. This seems to be the only problem that my system has at this point.

**Comment by LukeSmithxyz** [comment]
> As there doesnt seem to be any notifications generated automatically? Would it be possible that its running on root? Instead of normal user so it doesnt show any outputs?
Unless you're running `sudo mw cron`, which I doubt, cron entries are added as your normal user. You can check your crontabs yourself.

> I've updated a few times now and reinstalled dunst as well as the initial cronjob that's done through `mw`. Cron is now delivering my notifications fine, as well as neomutt when I sync an individual mailbox. However, when I use `O` to sync all mailboxes I don't get any notifications. This seems to be the only problem that my system has at this point.
Yeah the `O` binding is only bound to `mbsync`, not `mailsync` by default, so notifications won't show. This is because `mailsync` will not properly prompt for passwords in some circumstances and because if you have mutt open, it's sort of superfluous to get notifications about changes you can see.

**Comment by JBlocklove** [comment]
I modified the `O` binding then, apparently, since mine is mapped to `mailsync -a`

Your reasoning makes sense, though, so maybe I'll change it back.

**Comment by sleeperzjf** [comment]
Same thing here, all my other notifications work fine. 
But mailsync doesn't send notifications.
However, if I manually run `mailsync`, it did send notifications.
Any solution??
