### ISSUE TITLE
Feature proposal: Edit number amount of stored email

### ISSUE THREAD

**Issue by deadpyxel** [LukeSmithxyz/mutt-wizard#375]
## Detailed Description

What I am proposing is another option in the `mutt-wizard` menu where you can reconfigure the amount of email stored, and to prevent unwanted removal or loss of backup, said function would ask you to select a place to move the "clipped" email. It should work in a FIFO manner, just like when you configure it for the first time. Something like an ability to move said backup via `mutt-wizard` could also work.

## Context

So, currently I use one email account as a hub for some secondary accounts, which has increased the amount of mail stored a lot. My scenario is that I have 1 work email, this "hub email", university email all setup with `mutt-wizard`, all working fine and dandy. What is starting to be an issue is the space it is taking (around 10Gb). Would be nice to be able to reconfigure the amount of allowed storage to deal with this issue.

**Comment by LukeSmithxyz** [comment]
What's wrong with just changing the mine in the mbsyncrc?

**Comment by deadpyxel** [comment]
That worked well, I wasn't aware of that. I'll be closing the issue since the feature is not needed.
