### ISSUE TITLE
It doesnt show all the emails in the inbox?

### ISSUE THREAD

**Issue by thepenguinthatwants** [LukeSmithxyz/mutt-wizard#377]
It should sync automatically all the emails but for now it only syncs like 33? How should it work? Should it be capable to download over 1000 emails? 

`If you want to limit the number of messages kept offline to a number, enter that number below. If you do not want to limit your mail and would like `mbsync` to sync all mail, press enter without typing a number.`
I didnt enter any numbers so I thought it should load them all so I could easily filter and delete obsolete emails.

Also is it possible to trigger syncing emails from neomutt? Or is the cron the preferred way? or a tmux pane to run mbsync command?

**Comment by thepenguinthatwants** [comment]
Oh so it doesnt work on outlook but it worked on gmail.

**Comment by f380cedric** [comment]
> I didnt enter any numbers so I thought it should load them all so I could easily filter and delete obsolete emails.

It is what it is supposed to do.

> Oh so it doesnt work on outlook but it worked on gmail.

Run `mbsync <outlook-account-name>` in a terminal and check if there is any warning.
Some (all?) IMAP servers built by Microsoft are capricious. Try with `PipelineDepth 1` ([source](https://wiki.archlinux.org/index.php/isync#BAD_Command_with_Exchange_2003)), it worked for me.

> Also is it possible to trigger syncing emails from neomutt? Or is the cron the preferred way? or a tmux pane to run mbsync command?

You can manually trigger the IMAP synchronization via `o` or `O` (defined [here](https://github.com/LukeSmithxyz/mutt-wizard/blob/e69a7ad311e94c29a1e4b7e593a8630b09573ea2/bin/mw#L95) and [here](https://github.com/LukeSmithxyz/mutt-wizard/blob/e69a7ad311e94c29a1e4b7e593a8630b09573ea2/share/mutt-wizard.muttrc#L68)). The former will sync the current account, the latter every accounts.
