### ISSUE TITLE
error when typing mw

### ISSUE THREAD

**Issue by koltea** [LukeSmithxyz/mutt-wizard#379]
hi, i just installed mutt-wizard. i got all the needed dependencies and all the stuff it needs but when i run mw i got this error

```
/usr/local/bin/mw: line 89: syntax error near unexpected token `('
/usr/local/bin/mw: line 89: `set status_format="-%r-"$from": %D [Msgs:%?M?%M/?%m%?n? New:%n?%?o? Old:%o?%?d? Del:%d?%?F? Flag:%F?%?t? Tag:%t?%?p? Post:%p?%?b? Inc:%b?%?l? %l?]---(%s/%S)-%>-(
%P)---"'
```

**Comment by LukeSmithxyz** [comment]
Sorry, I allowed an error in the git version. Just download the newest commits and it will be fixed.
