### ISSUE TITLE
Colorscheme change when sending email

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/mutt-wizard#383]
I use neovim as my default `$EDITOR` and have a dark theme set as my colorscheme. However, when sending email, vim appears to have a light theme (which frankly is very irritating). Could someone help me out as to what can I do to revert the theme? 

Thank you.

**Comment by LukeSmithxyz** [comment]
How exactly do you change your scheme in your `init.vim`?

**Comment by paniash** [comment]
I use gruvbox

**Comment by paniash** [comment]
I use morhetz's gruvbox colorscheme. Here's the code for colorscheme in my init.vim,
```
let g:gruvbox_bold = 1
let g:gruvbox_italic = 1
let g:gruvbox_contrast_dark = 'hard'

set background=dark

colorscheme gruvbox
```

**Comment by LukeSmithxyz** [comment]
Okay. Well you'll basically have to replicate the needed vim commands in your vimrc for files in the mutt tmp directory. Here's my equivalent line:

```
autocmd BufRead,BufNewFile /tmp/neomutt* :Goyo | set bg=light
```

Closing because this is not a mutt-wizard issue.

**Comment by paniash** [comment]
Thank you. It works now.
