### ISSUE TITLE
gmail with mutt-wizard

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/mutt-wizard#388]
seems that in gmail, when mutt-wizard syncs and downloads it to offline, and you read & delete emails from mutt-wizard, and then again sync, the emails in Gmail don't actually get deleted, or marked as read, what happens is they get sent to All Mail, and stay as unread ... any idea how to bypass this? cuz my all mail keeps growing, while I'm actually reading/deleting messages from mutt-wizard, or is this the intended way for it to work?

https://0x0.st/iaFy.png
https://0x0.st/iaFt.png

**Comment by jonathf** [comment]
Go to settings at gmail.com. Go to "Forwarding and POP/IMAP". There should be an option there for what should be done when e-mails are deleted in IMAP. If it is set to archive, you could perhaps try to change it to either "move to trash" or "delete permanently".

(PS. I have non-english Gmail, so the names I am referring to might be a bit off.)
