### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by koltea** [LukeSmithxyz/mutt-wizard#389]
hi sir, im having an error after doing mbsync or even mailsync, im on fresh arch install and using gmail, here is the error.

`Socket error: secure read from imap.gmail.com error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading`

**Comment by s1ck-b0y** [comment]
[It seems to be](https://bbs.archlinux.org/viewtopic.php?id=253854) an error introduced on openssl-1.1.1.e-1; downgrading to 1.1.1.d-2 fixes it for now. Apparently, it will be reverted on 1.1.1f #https://github.com/openssl/openssl/pull/11400
However I believe it's a harmless warning.

**Comment by cenktaskin** [comment]
Hey there, thanks a lot for the great tool that made me able to use (neo)mutt!

I wanted to report that this error is still present, although it looks doesn't harm the functionality.
```
neomutt.x86_64                              5:20220629-2.fc37                @fedora                                                     
openssl-libs.x86_64                         1:3.0.5-3.fc37                   @fedora                                                     
openssl-pkcs11.x86_64                       0.4.12-2.fc37                    @fedora                                                     
openssl1.1.x86_64                           1:1.1.1q-2.fc37                  @fedora     
```
What I get from 
```sh
$ mw -Y
C: 1/1  B: 7/7  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Socket error: secure read from *******: error:0A000126:SSL routines::unexpected eof while reading
C: 0/1  B: 2/10  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Maildir notice: no UIDVALIDITY, creating new.
C: 1/1  B: 10/10  F: +1/1 *0/0 #0/0  N: +13621/13621 *0/0 #0/0
Socket error: secure read from *******: error:0A000126:SSL routines::unexpected eof while reading
```
Let me know if more logs would help.

Note: I don't have an idea what the 'Maildir notice' is for. Explanation is appreciated.

**Comment by chenle02** [comment]
I got the same issue, you may check here: https://stackoverflow.com/questions/72627218/openssl-error-messages-error0a000126ssl-routinesunexpected-eof-while-readin

**Comment by cenktaskin** [comment]
> I got the same issue, you may check here: https://stackoverflow.com/questions/72627218/openssl-error-messages-error0a000126ssl-routinesunexpected-eof-while-readin

If I'm not missing something, I didn't get the solution from the link.
But as far as I see from the openssl repo is not an uncommon issue, thanks.
