### ISSUE TITLE
Neomutt doesn't open

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/mutt-wizard#390]
After installing mutt-wizard, I download all my emails and then when I type `neomutt` in the terminal, it opens for about half a second before closing. I'm unable to figure out what the issue is.

**Comment by LukeSmithxyz** [comment]
Show your error logs or open st -e neomutt from another terminal and
show the message.

**Comment by paniash** [comment]
I get this message when I run `st -e neomutt` :
```
erresc: invalid color (null)
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  1698
  Current serial number in output stream:  1875
st exited with status code 1
```

**Comment by LukeSmithxyz** [comment]
Are you running LARBS? Install libxft-bgra and that will fix it.

**Comment by paniash** [comment]
No, not LARBS

**Comment by paniash** [comment]
Thanks, it works now. But what was the problem? It was working fine before before installing this package.

**Comment by LukeSmithxyz** [comment]
st was crashing when trying to render color emoji. It's actually a
libxft error, but suckless stuff will crash because of it. The package
you just installed has the fix.

**Comment by paniash** [comment]
Thank you very much, Luke!
