### ISSUE TITLE
Self Signed Certificate

### ISSUE THREAD

**Issue by jesperbakhandskemager** [LukeSmithxyz/mutt-wizard#394]
I'm running my own email server, and as you can see below i connect to it using it's local ip (I can't connect with the public ip from home).
And i get the following error when i try to add it.
 
SSL error connecting mail.emailserver.xyz (192.168.10.128:993): self signed certificate

**Comment by BertalanD** [comment]
I don't know whether you are still interested or have figured out a solution, but my PR #486 should fix this problem. 

If you didn't pay for a SSL certificate or set up Let's Encrypt, you can either disable cert signature checking, as suggested in [this comment](https://github.com/LukeSmithxyz/mutt-wizard/issues/479#issuecomment-652275090) that someone wrote to another Issue. This way, you still get the benefits of encrypted connections. but your client would not know if the server was compromised or you were maliciously routed to a different IP.

My solution lets you completely disable TLS encryption, which is totally adequate for a non-public network.
