### ISSUE TITLE
Notmuch search in all folders

### ISSUE THREAD

**Issue by cps1323** [LukeSmithxyz/mutt-wizard#398]
Is it possible to use the notmuch search in all folders? Currently it searches only in the active one.

**Comment by mancunius** [comment]
This is something I would like to see, too. Is there a solution?

**Comment by f380cedric** [comment]
Are you talking about the macro bound to `^f`?
If yes, then notmuch is searching in all folder.
But since the result is used in `<limit>`, it only filters messages showed in the current window.

To see messages from all mailboxes, you can bind the function `<vfolder-from-query>`  ([doc](https://neomutt.org/feature/notmuch#functions))

**Comment by mancunius** [comment]
Thank you. Please can you give me more detail on how to bind the function <vfolder-from-query> ? I've tried adding it as a set index,pager command in the config file but I get an error message on startup.

**Comment by f380cedric** [comment]
The syntax to bind functions is defined [here](https://neomutt.org/guide/configuration.html#bind) .
For example, if you want bind `esc+f` to `vfolder-from-query` in the pager and index mode:
```
bind index,pager \ef vfolder-from-query
```

If you want to use a key sequence (eg `ff`), you have to unbind the first letter (`f`) (`bind index,pager f noop`).

**Comment by gzbd** [comment]
I also wanted this feature. For me, below config worked.

`set nm_default_url = "notmuch:///home/your-home-dir/.local/share/mail"
set nm_query_type = "threads"

bind index,pager \Cf noop
bind index \Cf vfolder-from-query
`

**Comment by raduad** [comment]
@gzbd I tried your settings and they don't seem to work for me. I get no search results, just INBOX getting red :-)

**Comment by asakura42** [comment]
@f380cedric @gzbd Looks nice, but how can I modify Luke's command to make it work same?

This is his line: `macro index \Cf "<enter-command>unset wait_key<enter><shell-escape>printf 'Enter a search term to find with notmuch: '; read x; echo \$x >~/.cache/mutt_terms<enter><limit>~i \"\`notmuch search --output=messages \$(cat ~/.cache/mutt_terms) | head -n 600 | perl -le '@a=<>;s/\^id:// for@a;$,=\"|\";print@a' | perl -le '@a=<>; chomp@a; s/\\+/\\\\+/ for@a;print@a' \`\"<enter>" "show only messages matching a notmuch pattern"`

I mean, after Luke's command I can limit messages to all, but with @gzbd snippet I need to reload Neomutt. Also I want to search mail in that mail address where I am but in all folders, not in all my 3 mail addresses.
