### ISSUE TITLE
Tag releases for package managers to find tarballs

### ISSUE THREAD

**Issue by equwal** [LukeSmithxyz/mutt-wizard#402]
It would be helpful to put tagged releases on here so a package manager can download that tarball.

For example, here is a package download line from a gentoo ebuild:
`SRC_URI="ftp://bitreich.org/releases/sacc/${P}.tgz"`

where `${P}` is something like `pkg-version`.

This can be done on the command line with `git tag -a`. Of course this isn't strictly required, but it is generally helpful.

**Comment by Kr1ss-XD** [comment]
+1

Would also make it possible to create a non-VCS package for AUR.

**Comment by equwal** [comment]
On my fork it is demonstrated. Here is the process:
```shell
mutt-wizard $ git tag -a v0.1
mutt-wizard $ cd ..
$ car czf mutt-wizard-0.1.tar.gz
```
Go on the web interface and make a pre-release, uploading the `tar.gz`.
???
Profit

**Comment by motorto** [comment]
It's a shame that it's closed without Luke even saying anything would love to be able to package this to void but the lack of releases make this impossible ...
