### ISSUE TITLE
Further modifications to mailsync for macOS

### ISSUE THREAD

**Issue by bmclean2** [LukeSmithxyz/mutt-wizard#405]
In the mailsync script, the notify function adapts to macOS by using osascript, but the syncandnotify function still uses notify-send, which doesn't work on mac. This triggers the following error: "/usr/local/bin/mailsync: line 41: notify-send: command not found".

**Comment by LukeSmithxyz** [comment]
This should be fixed in https://github.com/LukeSmithxyz/mutt-wizard/commit/946abe8f5fc97524cb58b8049bf2b37e71f55901.
