### ISSUE TITLE
neomutt "... is not a mailbox" error

### ISSUE THREAD

**Issue by dax0** [LukeSmithxyz/mutt-wizard#41]
After running the wizard for the first time, setting up an email account (called daxmoe in this case), and running offlineimap, I'm getting an error within neomutt.

When I launch it, there are no emails to show, and it says "/home/dax/.mail/daxmoe is not a mailbox." at the bottom.

Let me know what other information you need.

**Comment by LukeSmithxyz** [comment]
Can you give me the output of `ls ~/.mail/daxmoe` and your `~/.config/mutt/accounts/daxmoe.muttrc`?

**Comment by dax0** [comment]
~/.mail/daxmoe

`INBOX`

~/.config/mutt/accounts/daxmoe.muttrc
```
# vim: filetype=neomuttrc
# muttrc file for account daxmoe
set realname = "Dax"
set from = "dax@dax.moe"
set smtp_url = "smtp://dax@dax.moe@mail.gandi.net:465/"
set sendmail = "/usr/bin/msmtp -a daxmoe"
set folder = "~/.mail/daxmoe"
set header_cache = ~/.config/mutt/accounts/daxmoe/cache/headers
set message_cachedir = ~/.config/mutt/accounts/daxmoe/cache/bodies
set certificate_file = ~/.config/mutt/accounts/daxmoe/certificates
source "~/.config/mutt/credentials/getmuttpass daxmoe |"

set mbox_type = Maildir
set ssl_starttls = yes
set ssl_force_tls = yes

bind index,pager gg noop
bind index,pager g noop
bind index gg first-entry
unmailboxes *
mailboxes =daxmoe =-------------------
set spoolfile = ""
set record = ""
set postponed = ""
```

**Comment by LukeSmithxyz** [comment]
Hmmm. Does your actual mailbox have only an INBOX and no other folders? If you don't know, give me the output of `offlineimap -a daxmoe --info`, the content under the `Folderlist:` heading.

Are there any errors when you just run `offlineimap -a daxmoe`?

**Comment by dax0** [comment]
I don't get any errors, no.

Under `FolderList:` when I run `offlineimap -a daxmoe --info`:

`INBOX`
`Sent`
`Trash`

**Comment by dax0** [comment]
Oh, the contents of that directory just changed . . .

Now it includes the other folders. I couldn't have missed it, I copied and pasted the output directly.

**Comment by dax0** [comment]
I abandoned this and went with a different mail client. Closing the issue.
