### ISSUE TITLE
Error sending message, child exited 76 (Remote protocol error.)

### ISSUE THREAD

**Issue by mjohanning99** [LukeSmithxyz/mutt-wizard#413]
I was trying to set up neomutt using the email I got with my webhosting as well; they give you a bunch of different ports (STARTSSL and TLS/SSL), I've tried all of them but still get the same error when trying to send an email, namely `Error sending message, child exited 76 (Remote protocol error.)`. 
I can view and download my messages just fine, but sending doesn't appear to work at all.

**Comment by LukeSmithxyz** [comment]
Try sending mail with msmtp manually and see the error.

**Comment by Jeytas** [comment]
> Try sending mail with msmtp manually and see the error.

The error it throws at me is this one:
```
msmtp: the server sent an empty reply
msmtp: could not send mail (account mjohanning from /home/sophon/.config/msmtp/config)
```

**Comment by PetrusZ** [comment]
Same problem here.

```
Apr 17 16:14:26 host=smtp.yandex.com tls=on auth=on user=gitea@codeplayer.org from=gitea@codeplayer.org recipients=watchtower@codeplayer.org errormsg='the server sent an empty reply' exitcode=EX_PROTOCOL
```

**Comment by PetrusZ** [comment]
It seems a proxy problem. msmtp can't work with proxy. I set proxy_host and proxy_port in msmtp config, then the mail can't send out.

**Comment by honeypieio** [comment]
I also came across this error on a fresh Arch installation

According to the [Arch wiki entry for msmtp](https://wiki.archlinux.org/index.php/Msmtp#Issues_with_TLS) to use TLS over port 465 you have to explicitly set `tls_starttls` to `off` in your msmtp config (`~/.config/msmtp/config`). After making this change the issue was resolved

**Comment by mjohanning99** [comment]
Thank you very much, @honeypieio. Adding `tls_starttls off` to my config has solved this issue and I am finally able to send mail as well as receive it! I'll mark this issue as closed then.
