### ISSUE TITLE
Not a valid email address

### ISSUE THREAD

**Issue by eleblanc** [LukeSmithxyz/mutt-wizard#418]
I've managed to install mutt-wizard on OpenBSD 6.6 (current) by using `gmake`, which is available via our package manager. That said, when I try to use `mw add`, I keep getting the following error:

`That is not a valid email address, please retype the desired email.`

It doesn't matter what I put as an email address, it keeps giving me that error.

**Comment by LukeSmithxyz** [comment]
Probably because your version of grep works differently. The default email regular expression is `.\+@.\+\\..\+` in mutt-wizard. If you echo your email address grepping for that, does it match the address?

**Comment by eleblanc** [comment]
I didn't think of grep! I went and installed gnugrep (ggrep) and changed all invocation of grep to ggrep in mw and it worked. Thanks!
