### ISSUE TITLE
Not issue - just suggestion

### ISSUE THREAD

**Issue by tzurita** [LukeSmithxyz/mutt-wizard#419]
I would add this line to mailsync.
[ -d "$HOME/.local/share/gnupg" ] && export GNUPGHOME="$HOME/.local/share/gnupg"

So your mailsync would look more like this.

```
# For individual configurations:
[ -d "$HOME/.local/share/password-store" ] && export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
[ -d "$HOME/.local/share/gnupg" ] && export GNUPGHOME="$HOME/.local/share/gnupg"
```

Issue I was having was relating to cron not reading the variables I had set in my $HOME/.profile so one set in the mailsync as a test all was well.

**Comment by lordskh** [comment]
I had the same issue and this fixed it. Perhaps you should submit a pull request.
