### ISSUE TITLE
Mailsync not working over SSH

### ISSUE THREAD

**Issue by aleksozolins** [LukeSmithxyz/mutt-wizard#422]
I'm not honestly sure this is a Mutt-Wizard problem, but if I run neomutt over ssh, mailsync invoked with "o" doesn't trigger a gpg password dialog. Instead, mbsync returns error for "no magic key". Captil "O" however does trigger a password dialog allowing me to check all my accounts.

Similar results trying to pass pam-gnupg to remote logins too. Any help appreciated.

**Comment by kroppt** [comment]
Even though this is outdated and for Gentoo, maybe this will give you some hints: https://wiki.gentoo.org/wiki/GnuPG/en#Changing_pinentry_for_SSH_logins

**Comment by aleksozolins** [comment]
> Even though this is outdated and for Gentoo, maybe this will give you some hints: https://wiki.gentoo.org/wiki/GnuPG/en#Changing_pinentry_for_SSH_logins

Thank you! That does it.
