### ISSUE TITLE
How to set default account?

### ISSUE THREAD

**Issue by christopherisnow** [LukeSmithxyz/mutt-wizard#427]
Wondering how to reset the default account and/or reorder setups with multiple accounts.

I originally set up 5 accounts with mw (thank you for making that so easy!) and deleted the first. mw then gave the remaining 4 new keybindings (i1-4 instead of the old i2-5). I subsequently changed keybinding numbers in the main muttrc (i.e. account 4-shortname = i1, etc.). 

All worked fine except neomutt still opens to a nonexistent account and asks me if I want to create a new mailbox.

How do I tell neomutt to open the account linked to i1 (with ~/.config/mutt/accounts/4-shortname.muttrc)? Is there a clean way to reorder the account numbering (4-shortname > 1-shortname) so keybindings are consistent with account numbers (i1 = 1-shortname, etc.)?

**Comment by LukeSmithxyz** [comment]
I mean there's not an automatic way to do it in the wizard. All you really need to do is change the macro bindings in the main muttrc and change which one is sourced when you first open the program. You can rename the directories as well to keep it clean if you want.

**Comment by christopherisnow** [comment]
OK thanks. How to "change which one is sourced when you first open the program"? Sorry, muttnovice here :)

**Comment by LukeSmithxyz** [comment]
For example, I have this line autogenerated by mutt-wizard in the muttrc:

```
source /home/luke/.config/mutt/accounts/1-luke.muttrc # mw-autogenerated
```

Which means my "1-luke.muttrc" account will be loaded when I start up. Just change that to the name of another file to load that one instead.
