### ISSUE TITLE
Feature requests 

### ISSUE THREAD

**Issue by ralpheeee88** [LukeSmithxyz/mutt-wizard#43]
pls consider implementing these feature:

Ctrl-R to mark all as read
`macro index \Cr "T~U<enter><tag-prefix><clear-flag>N<untag-pattern>.<enter>" "mark all messages as read"`

sync email
`macro index O "<shell-escape>offlineimap<enter>"           "run offlineimap to sync all mail"`
`macro index o "<shell-escape>offlineimap -qf INBOX<enter>" "run offlineimap to sync inbox"`

copy/move dialogs
`macro index C "<copy-message>?<toggle-mailboxes>" "copy a message to a mailbox"`
`macro index M "<save-message>?<toggle-mailboxes>" "move a message to a mailbox"i`

might also be interesting :  Viewing HTML [https://wiki.archlinux.org/index.php/Mutt#Viewing_HTML](url) and setting up mailcap  (both have been implemented in my configs and work great!)

**Comment by LukeSmithxyz** [comment]
Submit this as a pull request and I'll merge it.
