### ISSUE TITLE
Mailbox notification error

### ISSUE THREAD

**Issue by AlexSyssoyev** [LukeSmithxyz/mutt-wizard#430]
Hello, sorry for the the lot of issues Luke, just got into trying to use this and got little problems. When i use Mutt-wizard everything works perfectly, but when it comes  to update the dwmblocks icon it doesn't. 
I tried to look through closed issues and didn't find anything relevant, sorry if i'm being ignorant here.
When i executed mailbox at first i got this error:
```
find: '/home/user/.local/share/mail/*/INBOX/new/*': No such file or directory
```

I fixed this by changing INBOX to Inbox in the mailbox statusbar script, but after that error comes:
```
cat: /tmp/imapsyncicon_user: No such file or directory
```
What it can be?

Thank you for your patience.

**Comment by LukeSmithxyz** [comment]
Is that `cat` error message appearing in the statusbar or only on the command line? It shouldn't be a problem if it's only if you run it manually, but I might suppress it either way.

I see the issue with `INBOX` and that's easily fixable. Most email accounts use `INBOX`, but some use other case-configurations, so I'll have it matchable to any possible one.

**Comment by AlexSyssoyev** [comment]
Now that i have changed the ```INBOX``` directory it started working on dwmblocks perfectly, still have the cat error message when running it manually though, but it isn't an issue now.

**Comment by LukeSmithxyz** [comment]
It should be fixed now.

**Comment by AlexSyssoyev** [comment]
Excuse me, I tested it right now and got this error now. Is it something on my end?
```
find: '/home/razor/.local/share/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/*': No such file or directory
```
