### ISSUE TITLE
Mailsync doesn't send notifications when run as cronjob

### ISSUE THREAD

**Issue by Harjuu** [LukeSmithxyz/mutt-wizard#432]
If I run the mailsync script as a cronjob I don't get notifications. If I run the script manually it works flawlessly, and I've been able to find where it fails:

```
 # Check account for new mail. Notify if there is new content.
 syncandnotify() {
     acc="$(echo "$account" | sed "s/.*\///")"
     mbsync -c "$HOME/.config/mbsync/mbsyncrc" "$acc"
     new=$(find "$HOME/.local/share/mail/$acc/INBOX/new/" "$HOME/.local/share/mail/$acc/Inbox/new/" "$HOME/.local/share/mail/$acc/inbox/new/" -type -newer "$HOME/.config/mutt/.mailsynclastrun" 2> /dev/null)
     newcount=$(echo "$new" | sed '/^\s*$/d' | wc -l)

     notify-send "Before" &

     if [ "$newcount" -gt "0" ]; then

         notify-send "After" &

         notify "$acc" "$newcount" &
         for file in $new; do
             # Extract subject and sender from mail.
             from=$(awk '/^From: / && ++n ==1,/^\<.*\>:/' "$file" | perl -CS -MEncode -ne 'print       decode("MIME-Header", $_)' | awk '{ $1=""; if (NF>=3)$NF=""; print $0 }' | sed 's/^[[:blank:]]      *[\"'\''\<]*//;s/[\"'\''\>]*[[:blank:]]*$//')
             subject=$(awk '/^Subject: / && ++n == 1,/^\<.*\>: / && ++i == 2' "$file" | head -n-      1 | perl -CS -MEncode -ne 'print decode("MIME-Header", $_)' | sed 's/^Subject: //' | sed 's/^{[      [:blank:]]*[\"'\''\<]*//;s/[\"'\''\>]*[[:blank:]]*$//' | tr -d '\n')
             notify-send --app-name="mutt-wizard" "📧$from:" "$subject" &
         done
     fi
 }

```

The "Before" message gets through but not the "After" message, so it fails to pass the if statement. Somehow it fails to detect the new mail if run as a cronjob, but it does when run manually. No idea why

**Comment by samedamci** [comment]
I have the same issue.

**Comment by y0rune** [comment]
I had problem with notyfication and I deleted the export DISPLAY and changed line:

new=$(find "$HOME/.local/share/mail/$acc/INBOX/new/" "$HOME/.local/share/mail/$acc/Inbox/new/" "$HOME/.local/share/mail/$acc/inbox/new/" -type f -newer "$HOME/.config/mutt/.mailsynclastrun" 2> /dev/null)  
-> 
new=$(find $(ls $HOME/.local/share/mail/$acc/* | grep -i inbox | sed 's/\://')/new -type f -newer "$HOME/.config/mutt/.mailsynclastrun" 2> /dev/null)

**Comment by samedamci** [comment]
> I had problem with notyfication and I deleted the export DISPLAY and changed $new.
> 
> Link to PR: #434

Still not working for me, script don't downloading new mails when runned in cron. 🤔

**Comment by samedamci** [comment]
I found the solution. When I changed shebang to `#!/bin/sh -l` it started working and mails are now downloading and I receive notifications.

**Comment by luizpssouza** [comment]
On my side, I resolved adding the **export** to dbuss environment variable

![image](https://user-images.githubusercontent.com/10930771/83340570-4d1e5a00-a2b0-11ea-89e5-1a76863a7951.png)

**Comment by g-w1** [comment]
I had this problem too and i found that I had to do this for it to work (I am on larbs) [IMPORTANT_NOTE.md](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/cron/IMPORTANT_NOTE.md)
I added this before the cron cmd ```bash
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus; export DISPLAY=:0; . $HOME/.zprofile;  then_command_goes_here```

**Comment by thepenguinthatwants** [comment]
#!/bin/sh -l
DAMN THIS WORKED..
