### ISSUE TITLE
Mutt tries to reply to the deleted mail when switching account without syncing

### ISSUE THREAD

**Issue by ivanp7** [LukeSmithxyz/mutt-wizard#435]
Steps to reproduce:
1. mark some messages as deleted ('D')
2. switch account ('i<number>')
Expected behavior: mutt asks if the deleted messages should be purged, then switches to another account.

**Comment by LukeSmithxyz** [comment]
Okay I see. Generally, you should press S to save/update your mailbox
changes before switching, but I'll look into what's causing this because
I don't think the reply issue should be happening.

**Comment by jarbus** [comment]
Oh my god, I thought I was going mad. Thanks for the alternative with pressing S @LukeSmithxyz, it nearly made my mailbox unusable.
