### ISSUE TITLE
default programs for attachments?

### ISSUE THREAD

**Issue by sleeeeeeper** [LukeSmithxyz/mutt-wizard#439]
Can I set default programs for opening attachments?

**Comment by Kr1ss-XD** [comment]
Those are defined in the `mailcap` file. See [mailcap(4)](https://linux.die.net/man/4/mailcap) or [mailcap(5)](https://jlk.fjfi.cvut.cz/arch/manpages/man/extra/mailcap/mailcap.5.en), depending on your OS.

You can define the path to a (possibly mutt specific) mailcap file by setting the `mailcap_path` variable in your (neo)mutt configuration. Mutt-wizard sets it to `/usr/share/mutt-wizard/mailcap` by default.

**Comment by sleeperzjf** [comment]
@Kr1ss-XD Thanks a lot

**Comment by sleeeeeeper** [comment]
@Kr1ss-XD Thanks a lot!
