### ISSUE TITLE
Fastmail support

### ISSUE THREAD

**Issue by unchainedio** [LukeSmithxyz/mutt-wizard#442]
Hi,

i have a custom domain on fastmail.com

how should i enter it into mutt-wizard? 

i entered my custom domain and it cant tell that its a fastmail backend.  i enter the smtp and imap as below and i havent been able to get it to work.

https://www.fastmail.com/help/technical/servernamesandports.html

i created an app specific password and used that to setup mw and  it fails at the end with unable to logon with the app specific password.  havent been able yo get it working.

Any help appreciated

Enter password for mutt-wizard-fastmail: 
Retype password for mutt-wizard-fastmail: 
[master e4dff89] Add given password for mutt-wizard-fastmail to store.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 mutt-wizard-fastmail.gpg
Creating profiles for `fastmail`...DONE.
muttrc created.
gpg: decryption failed: No secret key
Skipping account fastmail-remote, password command exited with status 2
Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.

**Comment by f380cedric** [comment]
> Enter password for mutt-wizard-fastmail:
> [...]
> gpg: decryption failed: No secret key

Did it ask for your gpg key passphrase? Is the key loaded and unlocked into you gpg-agent?
gpg complaints that it cannot decrypt the pass file (containing your fastmail password) because it did not receive the secret key to decrypt it.
Most of the time, it is because the key is not already unlocked *and* because gpg has no entrance to request user input via pinentry.

Easiest way to check is to open a terminal, `pass <pass-name> > /dev/null` (it will ask for your gpg passphrase), and retry with mw.

**Comment by unchainedio** [comment]
> > Enter password for mutt-wizard-fastmail:
> > [...]
> > gpg: decryption failed: No secret key
> 
> Did it ask for your gpg key passphrase? Is the key loaded and unlocked into you gpg-agent?
> gpg complaints that it cannot decrypt the pass file (containing your fastmail password) because it did not receive the secret key to decrypt it.
> Most of the time, it is because the key is not already unlocked _and_ because gpg has no entrance to request user input via pinentry.
> 
> Easiest way to check is to open a terminal, `pass <pass-name> > /dev/null` (it will ask for your gpg passphrase), and retry with mw.

i am using yubikey for my pass gpg key, how do i get it to ask for the yubikey?

**Comment by f380cedric** [comment]
> i am using yubikey for my pass gpg key, how do i get it to ask for the yubikey?

Never, used. You have to enter a PIN to unlock your yubikey, no?
When you use pass, does it bring pinentry?

If yes, is the pinentry drawn in the terminal (via curse) or in its own window (gtk, qt or grc backend)?

If it is terminal based, [this](https://wiki.archlinux.org/index.php/GnuPG#Configure_pinentry_to_use_the_correct_TTY) may work, or try a graphical one.
