### ISSUE TITLE
local only folder

### ISSUE THREAD

**Issue by rjl6789** [LukeSmithxyz/mutt-wizard#449]
Hi, 

New to mutt / mutt-wizard. Is it possible to create a local only folder e.g if have a mail limit and want to store some emails just locally?

If it is, is this a feature of mutt-wizard, neomutt, the helper sync programs. Would anyone be able to help or point me to the correct man!

Thanks very much.

Kind regards 

Rob

**Comment by LukeSmithxyz** [comment]
Yeah. I do that. I do that, in fact.

You could manually create a directory in `~/.local/share/mail/<accountname>`, then open up `~/.mbsyncrc` and find the `Patterns` line. Suppose I name my local mailbox "offline," I would edit the line adding `!offline` to exclude it from being synced:

```
Patterns * !offline
```

Now to see your mailbox in mutt, edit your account profile in `~/.config/mutt/accounts/`. There should be a `mailboxes` command that lists your mail boxes. Add it there and it will appear in the sidebar. If you want to add a shortcut macro/binding to open it, model it after those in the file.

**Comment by rjl6789** [comment]
Thanks Luke - that's great. Will give it a whirl.  On another side note.  Whilst I acknowledge gmail is 'bad' - having 2 factor authentication on already I thought I'd give setting up an app password and using this with neomutt (i.e. ignored warning about 3rd party access - it is 'off').  It worked swimmingly.  So thanks for making that work nicely.  Proton mail also created absolutly fine - I get messages about sending passwords in the clear when syncing but assume that is because it's working with the bridge to connect.

Anyway - thanks again, this is a great way of getting into neomutt and associated mail tools... now time to learn how you made the magic happen!! (probably over months /years!)

Rob

**Comment by LukeSmithxyz** [comment]
Good to hear. Yeah it's easier than you think. Good to hear about 2FA, I
should probably add that to the documentation.
On 20/05/31 08:43AM, Rob wrote:
> Thanks Luke - that's great. Will give it a whirl.  On another side note.  Whilst I acknowledge gmail is 'bad' - having 2 factor authentication on already I thought I'd give setting up an app password and using this with neomutt (i.e. ignored warning about 3rd party access - it is 'off').  It worked swimmingly.  So thanks for making that work nicely.  Proton mail also created absolutly fine - I get messages about sending passwords in the clear when syncing but assume that is because it's working with the bridge to connect.
>
> Anyway - thanks again, this is a great way of getting into neomutt and associated mail tools... now time to learn how you made the magic happen!! (probably over months /years!)
>
> Rob
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/mutt-wizard/issues/449#issuecomment-636488406

--
https://lukesmith.xyz
