### ISSUE TITLE
Insecure and destructive /tmp usage

### ISSUE THREAD

**Issue by tokudan** [LukeSmithxyz/mutt-wizard#45]
The script uses /tmp in insecure and possibly destructive ways. Example:
```
rm -f /tmp/log /tmp/lognew
offlineimap --info -a $1 2&> /tmp/log
```
If another application or script is using /tmp/log or /tmp/lognew, this may delete another application's data.

Please consider using "mktemp -d" to create your own tmp-directory and use that.

**Comment by loweryaustin** [comment]
I've started a fix on this one. I'll have a pull request for it later this evening.

**Comment by LukeSmithxyz** [comment]
Forgot to say, I just integrated this change.
