### ISSUE TITLE
/bin/mw: line 284: title: parameter null or not set

### ISSUE THREAD

**Issue by magusr** [LukeSmithxyz/mutt-wizard#456]
i've lost all my emails messing about. mw add no longer works with protonmail. i am getting the following error.

/bin/mw: line 284: title: parameter null or not set

**Comment by pahlse** [comment]
I have the same problem. If I run "mw add" and type in my proton mail I get the error message. Could it be a bug?

**Comment by rjl6789** [comment]
Hi, the fix I proposed has been merged by Luke. Please can you clone/pull the latest master.  This should close the issue.

Kind Regards

**Comment by magusr** [comment]
able to add my proton account now but mbsync results in alot of conflicting changes.

**Comment by rjl6789** [comment]
Hi Magusr.

Can you clarify - are you adding an account that already existed?  I'm not sure what is meant by conflisting changes.  First off - is there a directory `$HOME/.local/share/mail/<the-account-name-you-entered>` ?

next - if you do a mbsync --list <the-account-name-you-entered> it should list the folders in your proton mail account. These should be mirrored by `find $HOME/.local/share/mail/<the-account-name-you-entered> -type d` ?

after that in your `$HOME/.config/mutt/accounts/<number>-<the-account-name-you-entered>.muttrc` there should be a line that mirrors those directories along the lines: `set mailboxes "=INBOX" "=trash" "=sent" "=archive" ?

If those are all there then mutt-wizard has done it's job - if not, something else has gone wrong!

Regards

**Comment by magusr** [comment]
not sure. i will remove everything and try again.  mbsync --list proto returns all the folders.

**Comment by magusr** [comment]
no luck.

**Comment by magusr** [comment]
it's fixed! i removed and added everything again.  thanks for the help! 

best regards,
