### ISSUE TITLE
Only "INBOX" showing in side panel

### ISSUE THREAD

**Issue by BadBrush** [LukeSmithxyz/mutt-wizard#459]
I get this error when running "neomutt" I haven't made any changes to the muttrc:
`Unknown Mailbox: /home/<user>/.local/share/mail/badbrush1/badbrush1
Error in /home/<user>/.config/mutt/accounts/1-badbrush1.muttrc, line 24:
Error in /home/<user>/.config/mutt/muttrc, line 3: source: file /home/<user>/.config/mutt/accounts/1-badbrush1.muttrc could not be sourced
source: errors in /home/<user>/.config/mutt/muttrc
`

- This is my muttrc:
`# vim: filetype=neomuttrc`
`source /usr/share/mutt-wizard/mutt-wizard.muttrc # mw-autogenerated`
`source /home/<user>/.config/mutt/accounts/1-badbrush1.muttrc # mw-autogenerated`
`macro index,pager i1 '<sync-mailbox><enter-command>source /home/<user>/.config/mutt/accounts/1-badbrush1.muttrc<enter><change-folder>!<enter>;<check-stats>' "switch to badbrush@mailbox.org" # mw-autogenerated
`

- This is what is on line 24 of the 1-mailbox.muttrc:
`mailboxes =badbrush1 ===================== "=Sent" "=Drafts" "=INBOX" "=Trash" "=Junk"
`

is there something wrong with the syntax?

**Comment by LukeSmithxyz** [comment]
Are you running a really old version of the script or something?

Yeah it used to be that we put in the account name and those ====== as dummy mailboxes so you'd know your currently active account, but an update to neomutt gave an error with dummy mailboxes.

Remove the =badbrush1 and the ====== and see if that makes it better.

**Comment by BadBrush** [comment]
Yeah it's probably an old version but downloading the current script produces the same results. It appears I can comment out the mailboxes line and get rid of the error. But I'm still left with only "INBOX" on the left panel even when (successfully) switching between Sent\Drafts\Trash\Junk

here's my entire 1-badbrush.muttrc file:
`# vim: filetype=neomuttrc`
`# muttrc file for account badbrush`
`set realname = "My Name"`
`set from = "badbrush@mailbox.org"`
`set sendmail = "msmtp -a badbrush"`
`alias me My Name <badbrush@mailbox.org>`
`set folder = "/home/<user>/.local/share/mail/badbrush"`
`set header_cache = /home/<user>/.cache/mutt-wizard/badbrush/headers`
`set message_cachedir = /home/<user>/.cache/mutt-wizard/badbrush/bodies`
`set mbox_type = Maildir`
`     `
`bind index,pager gg noop`
`bind index,pager g noop`
`bind index,pager M noop`
`bind index,pager C noop`
`bind index gg first-entry`
`macro index o "<shell-escape>mailsync -V badbrush<enter>" "run mbsync to sync badbrush"`
`unmailboxes *`
`     `
`set spoolfile = "+INBOX"`
`set record = "+Sent"`
`set postponed = "+Drafts"`
`set trash = "+Trash"`
`#mailboxes = "=Sent" "=Drafts" "=INBOX" "=Trash" "=Junk"`
`macro index,pager gi "<change-folder>=INBOX<enter>" "go to inbox" # mw-autogenerated`
`macro index,pager Mi "<save-message>=INBOX<enter>" "move mail to inbox" # mw-autogenerated`
`macro index,pager Ci "<copy-message>=INBOX<enter>" "copy mail to inbox" # mw-autogenerated`
`macro index,pager gs "<change-folder>=Sent<enter>" "go to sent" # mw-autogenerated`
`macro index,pager Ms "<save-message>=Sent<enter>" "move mail to sent" # mw-autogenerated`
`macro index,pager Cs "<copy-message>=Sent<enter>" "copy mail to sent" # mw-autogenerated`
`macro index,pager gd "<change-folder>=Drafts<enter>" "go to drafts" # mw-autogenerated`
`macro index,pager Md "<save-message>=Drafts<enter>" "move mail to drafts" # mw-autogenerated`
`macro index,pager Cd "<copy-message>=Drafts<enter>" "copy mail to drafts" # mw-autogenerated`
`macro index,pager gt "<change-folder>=Trash<enter>" "go to trash" # mw-autogenerated`
`macro index,pager Mt "<save-message>=Trash<enter>" "move mail to trash" # mw-autogenerated`
`macro index,pager Ct "<copy-message>=Trash<enter>" "copy mail to trash" # mw-autogenerated`
`macro index,pager gj "<change-folder>=Junk<enter>" "go to junk" # mw-autogenerated`
`macro index,pager Mj "<save-message>=Junk<enter>" "move mail to junk" # mw-autogenerated`
`macro index,pager Cj "<copy-message>=Junk<enter>" "copy mail to junk" # mw-autogenerated`

**Comment by LukeSmithxyz** [comment]
Well yeah, the mailboxes variable determines what mailboxes display on
the sidebar.

What does the new wizard produce in the mailboxes line and what
specifically is the error message when uncommented?
On 20/06/09 05:42PM, BadBrush wrote:
> Yeah it's probably an old version but downloading the current script produces the same results. It appears I can comment out the mailboxes line and get rid of the error. But I'm still left with only "INBOX" on the left panel even when (successfully) switching between Sent\Drafts\Trash\Junk
>
> here's my entire 1-badbrush.muttrc file:
> `# vim: filetype=neomuttrc`
> `# muttrc file for account badbrush`
> `set realname = "My Name"`
> `set from = "badbrush@mailbox.org"`
> `set sendmail = "msmtp -a badbrush"`
> `alias me My Name <badbrush@mailbox.org>`
> `set folder = "/home/<user>/.local/share/mail/badbrush"`
> `set header_cache = /home/<user>/.cache/mutt-wizard/badbrush/headers`
> `set message_cachedir = /home/<user>/.cache/mutt-wizard/badbrush/bodies`
> `set mbox_type = Maildir`
> `     `
> `bind index,pager gg noop`
> `bind index,pager g noop`
> `bind index,pager M noop`
> `bind index,pager C noop`
> `bind index gg first-entry`
> `macro index o "<shell-escape>mailsync -V badbrush<enter>" "run mbsync to sync badbrush"`
> `unmailboxes *`
> `     `
> `set spoolfile = "+INBOX"`
> `set record = "+Sent"`
> `set postponed = "+Drafts"`
> `set trash = "+Trash"`
> `#mailboxes = "=Sent" "=Drafts" "=INBOX" "=Trash" "=Junk"`
> `macro index,pager gi "<change-folder>=INBOX<enter>" "go to inbox" # mw-autogenerated`
> `macro index,pager Mi "<save-message>=INBOX<enter>" "move mail to inbox" # mw-autogenerated`
> `macro index,pager Ci "<copy-message>=INBOX<enter>" "copy mail to inbox" # mw-autogenerated`
> `macro index,pager gs "<change-folder>=Sent<enter>" "go to sent" # mw-autogenerated`
> `macro index,pager Ms "<save-message>=Sent<enter>" "move mail to sent" # mw-autogenerated`
> `macro index,pager Cs "<copy-message>=Sent<enter>" "copy mail to sent" # mw-autogenerated`
> `macro index,pager gd "<change-folder>=Drafts<enter>" "go to drafts" # mw-autogenerated`
> `macro index,pager Md "<save-message>=Drafts<enter>" "move mail to drafts" # mw-autogenerated`
> `macro index,pager Cd "<copy-message>=Drafts<enter>" "copy mail to drafts" # mw-autogenerated`
> `macro index,pager gt "<change-folder>=Trash<enter>" "go to trash" # mw-autogenerated`
> `macro index,pager Mt "<save-message>=Trash<enter>" "move mail to trash" # mw-autogenerated`
> `macro index,pager Ct "<copy-message>=Trash<enter>" "copy mail to trash" # mw-autogenerated`
> `macro index,pager gj "<change-folder>=Junk<enter>" "go to junk" # mw-autogenerated`
> `macro index,pager Mj "<save-message>=Junk<enter>" "move mail to junk" # mw-autogenerated`
> `macro index,pager Cj "<copy-message>=Junk<enter>" "copy mail to junk" # mw-autogenerated`
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/mutt-wizard/issues/459#issuecomment-641653361

--
https://lukesmith.xyz

**Comment by BadBrush** [comment]
It was really just as you said; my error was in thinking that the syntax should have been `mailboxes = "=NAMEOFBOX" "=NAMEOFBOX2"` instead of `mailboxes "=NAMEOFBOX" "=NAMEOFBOX2"` Thanks for the help
