### ISSUE TITLE
problem when changing password

### ISSUE THREAD

**Issue by winderickxeli** [LukeSmithxyz/mutt-wizard#46]
Hi luke

First off; I'm a big fan of your work. I convincing other colleagues to also use mutt in addition to your wizard. Most of the sysadmin are Linux or Mac users and are eager to try your wizard out.

Anyways I recently changed my password to something containing $ characters. Since the change I was no longer able to send mail. After some digging I found that getmuttpass uses double quotes to set the password.

When I altered the " to ' in getmuttpass, everything worked fine again. I just wanted to let you know.

Thanks again for the great software.

Eli

**Comment by LukeSmithxyz** [comment]
Great, thanks for the hint! I've updated it to include this.
