### ISSUE TITLE
Change account during email composing

### ISSUE THREAD

**Issue by pniedzwiedzinski** [LukeSmithxyz/mutt-wizard#468]
Hi,

Handy feature would be to have binding to change `From` field during email composing. This might work like with account changing, but with `f` instead of `i`. 

I would need that when I open mutt with a `mailto` link - now it uses the default account. 

I'm a mutt noob, but based on my research this could be done by `set from=<account info>` and maybe something more.

**Comment by LukeSmithxyz** [comment]
It would require a good bit more. You'd also have to change the SMTP
server information. If you just change the from address, it would be
trying to send from that user from your current email server/service.
On 20/06/15 12:00AM, Patryk Niedźwiedziński wrote:
> Hi,
>
> Handy feature would be to have binding to change `From` field during email composing. This might work like with account changing, but with `f` instead of `i`.
>
> I would need that when I open mutt with a `mailto` link - now it uses the default account.
>
> I'm a mutt noob, but based on my research this could be done by `set from=<account info>` and maybe something more.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/mutt-wizard/issues/468

--
https://lukesmith.xyz

**Comment by pniedzwiedzinski** [comment]
I think that I might have an idea how to do that. Maybe source only 10
lines of the account file? It didn't work but maybe I screwed
bindings...

```
bind compose f noop
macro compose f1 '<enter-command>source /home/pn/.config/mutt/accounts/my-trimmed-muttrc<enter>;'
```

**Comment by pniedzwiedzinski** [comment]
No! It worked but it doesn't update the displaying email (in `From`).
