### ISSUE TITLE
`dwmblocks` crashes when not handling mailsync's signal sending

### ISSUE THREAD

**Issue by CosmosAtlas** [LukeSmithxyz/mutt-wizard#469]
https://github.com/LukeSmithxyz/mutt-wizard/blob/5e2aa207a029783de72e692b4fb55a1576677ead/bin/mailsync#L57

It took me a while and almost went crazy until I came to this [issue](https://github.com/LukeSmithxyz/dwmblocks/issues/10) that it could be the same cron job in `mutt-wizzard` causing the crash to dwmblocks.  

I can't seem to think of a way to fix this issue, so maybe better documentation regarding this?

**Comment by LukeSmithxyz** [comment]
This is already in the README.
On 20/06/15 10:40AM, CosmosAtlas wrote:
> https://github.com/LukeSmithxyz/mutt-wizard/blob/5e2aa207a029783de72e692b4fb55a1576677ead/bin/mailsync#L57
>
> It took me a while and almost went crazy until I came to this [issue](https://github.com/LukeSmithxyz/dwmblocks/issues/10) that it could be the same cron job in `mutt-wizzard` causing the crash to dwmblocks.
>
> I can't seem to think of a way to fix this issue, so maybe better documentation regarding this?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/mutt-wizard/issues/469

--
https://lukesmith.xyz

**Comment by CosmosAtlas** [comment]
I spend the past 5 minutes trying to find the information in the README but no luck. 

Here are the repositories I've read (in LukeSmithxyz)
- dwm
- dwmblocks
- larbs
- mutt-wizard

Could you point me to the location please?

Also, I did'nt come through anything specific about the integration problem with `mailsync` and `dwmblocks`. I did read about the crashing issue when receiving unhandled signal in `dwmblocks` but IMO, given the effort I've put in to figure out the problem. I would suggest adding this information in *dwmblocks* readme so when someone else have the same problem they don't need to go through the struggle I had.

**Comment by LukeSmithxyz** [comment]
As you say yourself, this is already in the dwmblocks README. There is no other note to make of it because the two work out of the box with each other.

It is only people who manually remove the mail module from dwmblocks who would have this problem, and the information is clearly stated in its README.
