### ISSUE TITLE
IMAP accounts not working. Script gets stuck in detectMailboxes().

### ISSUE THREAD

**Issue by caonimah** [LukeSmithxyz/mutt-wizard#47]
Behavior: program just stops at the last step. Can't even terminate it with ctrl+c.

It seems that the program gets stuck at detectMailboxes(), because there are user subfolders in account/ and ~/.mail. But apparently, at least in my case, for non-gmail accounts, the offlineimap command from the last function couldn't find any boxes. Maybe that's why it can't get through detecMailboxes().

**Comment by LukeSmithxyz** [comment]
I'm trying to replicate your problem. I think you said on the forum you have a cock.li account right? What distro are you using?

**Comment by caonimah** [comment]
Ok, concretely in my system, when I install mutt, it needs to build just one further package besides mutt. 
However, to install neomutt, another 35 packages are required, although the majority of USE flags aren't even enabled yet.

**Comment by loweryaustin** [comment]
@caonimah can you get a trace of the process when it gets stuck? That could lead to some forward progress on determining what is not working. With strace installed, something like:
`strace -ttffvv -s 1000 -o mutt.trace /path/to/script`
That will trace the syscalls and create a new file for each new process that is forked while you go through the script.
When the process gets stuck we'd have a much better idea of what it is getting stuck on by reviewing the relevant trace information.
**NOTE**: When providing information from your trace, please be sure to audit it for sensitive information such as passwords etc. The strace tool can collect some of that private data.

**Comment by loweryaustin** [comment]
Or if you suspect that it's offlineimap that is having trouble you could run it with the -d flag that's mentioned in the man page.
