### ISSUE TITLE
Exchange server 

### ISSUE THREAD

**Issue by TheWorldOfCode** [LukeSmithxyz/mutt-wizard#473]
Hi
I have trouble connecting to an exchange server. I am using davmail as a gateway. 

I am setting the imap and smtp server to localhost and setting the ports to the same as in the davmail config.

I can see that the davmail recieves the requisted, but according to davmail the client closes the connection. 

I have tested the davmail with thunderbird and there it works. Do you have any suggests? 

An other thing. When I enters my email, it saids 
 gpg: error reading key: No public key. 
but it doesn't prevents the program to continue.

I have created a key for another email account. Can't I not used the same key for multiple accounts ?

**Comment by TheWorldOfCode** [comment]
I just forgot. I have also managed to setup the account in mutt.

**Comment by LukeSmithxyz** [comment]
Should be fixed. It was requiring a separate gpg private key.
