### ISSUE TITLE
Question: "Unable to get local issuer certificate", am I supposed to know something?

### ISSUE THREAD

**Issue by JoshuaCrewe** [LukeSmithxyz/mutt-wizard#479]
I have tried this wizard with both my work and home account. Work email is nothing fancy, just an IMAP server on cpanel while my home email is a zoho account. Both times I got the error `unable to get local issuer certificate` . At first I thought that my work email was set up a bit strange in the DNS but then when it didn't work with Zoho either I thought I must be missing something.

Should I be manually adding a certificate to my system? Where would I get the information for this certificate?

Running macOS 10.14.6
Cloned this repo today 
isync 1.3.1

**Comment by JoshuaCrewe** [comment]
I managed to get the certificate for my work email server with the following command : 

```
openssl s_client -connect imap.server.com:993 -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | head -n 27 > emailssl.crt
```

Then by modifying the `mw` script I could point to that cert file which appeared to get around the erorr I was seeing.

I am not sure how this is supposed to work though.

**Comment by f380cedric** [comment]
The certificates are valid? Most commonly, it is due to self or ill-signed certificates.
If there is no signature that match with one of your root CA, then there is no chain-of-trust and the certificate cannot be trusted.

To check the validity, you could try `openssl s_client -connect SERVERNAME:993 -verify_return_error -verify_hostname SERVERNAME </dev/null >/dev/null 2>&1 && echo "Valid Certificate"`
It should print  "Valid Certificate".

If it does not print that, the certificate cannot be trusted. If you trust it, then you have to extract it and ( add it to your trusted root CA OR configure msmtp + mbsync to trust it ).

If it is valid, then mbsync and msmtp are pointing to the wrong root CA bundle.

IMO, I would check whether the certificate is valid before messing up with software trusted list.

**Comment by JoshuaCrewe** [comment]
Thanks @f380cedric i will start there. When I told mbsync to trust the certificate the wizard did progress and looked like it all worked. I got all the mail in my inbox but not my other folders. I believe that there was a timeout issues which might be related.

I’ll start by verifying the certificate though. Thanks for your help!

**Comment by JoshuaCrewe** [comment]
So nothing resulted in "Valid Certificate" from that command. But I can connect to those IMAP servers on a secure port from other emial clients. So are they just ignoring the cert?

**Comment by JoshuaCrewe** [comment]
Perhaps I am misunderstanding something but : 

`openssl s_client -connect imap.gmail.com:993 -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate"`

Should echo "Valid Certificate" ? It doesn't though. What am I missing here?

**Comment by f380cedric** [comment]
> `openssl s_client -connect imap.gmail.com:993 -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate"`
> 
> Should echo "Valid Certificate" ? It doesn't though. What am I missing here?

And it does output "Valid Certificate" on my machine.

IMO, there are two options from here:
 1. There is no ca certificate store configured with openssl, meaning that openssl cannot trust any certificate, because it does not trust any CA (empty). There could be no ca store installed on your machine, or there is but openssl is misconfigured.
 2. You are behind a proxy, and your proxy performs MIMT. It happens inside *evil* company networks. If your machine is from the company, they (or you) may have installed their own certificate in the ca store of Keychain.

> So nothing resulted in "Valid Certificate" from that command. But I can connect to those IMAP servers on a secure port from other emial clients. So are they just ignoring the cert?

I am expecting that these mail clients are built for macOS and so use Apple's Framework to request the certificates from Keychain. Here, we have to use openssl, and it cannot use that framework.


So, for 1:
 - What is the value of `CertificateFile` in `~/.mbsyncrc`?
 - Have you installed openssl via homebrew?

If you installed it via homebrew, I am expecting it printed out the following output:

> A CA file has been bootstrapped using certificates from the system
> keychain. To add additional certificates, place .pem files in
>     $(brew --prefix)/etc/openssl/certs
> 
> and run
>     $(brew --prefix)/opt/openssl/bin/c_rehash

My guess: `CertificateFile` links to an empty file and is not $(brew --prefix)/etc/openssl/cert.pem (or something like this, check `brew info openssl`)

If it is not installed with homebrew, check the `CertificateFile`. If the file is empty, we may need to export the keychain certificates or try something else (eg configure msmtp and mbsync to trust the IMAP/SMTP servers).

For 2:
 - Add the company certificate to the openssl (or msmtp/mbsync) trusted list.


N.B.: I do not own a macOS machine, I am guessing.
P.S.: Could you try `openssl s_client -connect imap.gmail.com:993 -CAfile CERTFILE -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate"` with CERTFILE being the value of `CertificateFile`. Try also with `openssl s_client -connect imap.gmail.com:993 -CApath /dev/null -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate"`

**Comment by f380cedric** [comment]
I may have pushed too far with this one.

If you want a quick solution, try [this](https://wiki.archlinux.org/index.php/isync#Step_%231:_Get_the_certificates) (step 1 and 2) for mbsync (which does the same stuff than https://github.com/LukeSmithxyz/mutt-wizard/issues/479#issuecomment-651798394).
If msmtp also complains, try [this](https://marlam.de/msmtp/msmtp.html#Transport-Layer-Security) (get the fingerprint from msmtp and use tls_fingerprint in config file).

**Comment by JoshuaCrewe** [comment]
@f380cedric thanks for the comprehensive response, I was asleep when you wrote it which is why no response until now.

The easy one to clear up is **option 2** , behind a proxy. Although this is a work machine it is stock from Apple so no extra config from the company 🎉 

I tried two approaches given your feedback. The first was to get the cert for the mail server on my machine and point to it with `certificateFile` while the second was to take that certificate and trust it with the system. macOS has a keychain app where you can import a certificate and set the permissions. As far as I remember both of these were enough to get the wizard to run. The latter was the better approach as It didn't require editing the wizard scripts itsself.

This was enough to get `mbsybc` to work. Sort of. I got some other errors. Specifically errors in the `.muttrc` which said it couldn't find some of the folders.

`~/.config/mutt/accounts/1-work.muttrc` had the following line : 
```
mailboxes =spam =INBOX =new =cur =tmp =Archive =Drafts =Trash =Sent =heidi 
```
which caused problems because `=new`,`=cur` and `=tmp` didn't exist in the structure.

After resolving these it turned out that `msmtp` wasn't working properly which we can all guess why. After a little digging it was confirmed that it couldn't authenticate via SSL. To confirm this I added the following to `~/.config/msmtp/config` : 

```
tls_starttls off
tls_certcheck off
```
This allowed me to send email via msmtp. Does this mean that the connection will be encrypted but it won't check the validity of the certificate? Or will it use an unsecure port and try to upgrade if it can, but it won't be able to so the message will be unencrypted? The port `465` is specified in the work account block in this config file. I am not sure what will be happening here.

> Have you installed openssl via homebrew?

It looks like openssl is installed on my machine via homebrew which will be becuase of some other package on here, I don't remember specifically installing it. The cert file that I am pointing to is one that I created and stored temporarily in my downloads folder. I got it from `openssl s_client -connect imap.server.com:993 -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | head -n 27 > emailssl.crt` . This is the file that I installed on the server which allows `mbsync` to work but not `msmtp`.

I would like to know why one works but not the other. IMAP and SMTP don't use different certificates do they?

**Comment by JoshuaCrewe** [comment]
> P.S.: Could you try openssl s_client -connect imap.gmail.com:993 -CAfile CERTFILE -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate" with CERTFILE being the value of CertificateFile. Try also with openssl s_client -connect imap.gmail.com:993 -CApath /dev/null -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate"

Neither of those commands print anything. BTW I am not using gmail for this, I used their IMAP server as a test as I thought their certificate would be trusted what with them being so popular and all. So I substituted my work server into those commands you suggested.

**Comment by f380cedric** [comment]
> The easy one to clear up is **option 2** , behind a proxy. Although this is a work machine it is stock from Apple so no extra config from the company 

It does not need a lot of extra configuration, just adding the company certificate in keychain is enough for them to perform MITM.
You can try `openssl s_client -showcerts imap.gmail.com:993 < /dev/null | openssl x509 -text` and see if your company name appears in the output. The issuer should be "Google Trust Services".

> [...] while the second was to take that certificate and trust it with the system. macOS has a keychain app where you can import a certificate and set the permissions. As far as I remember both of these were enough to get the wizard to run. The latter was the better approach as It didn't require editing the wizard scripts itsself.
> 
> This was enough to get `mbsybc` to work.

Strange, I was not expecting that to work. Maybe you have something like [this](https://github.com/raggi/openssl-osx-ca) running to keep keychain and ca store synced?

>I got some other errors. Specifically errors in the `.muttrc` which said it couldn't find some of the folders.
> 
> `~/.config/mutt/accounts/1-work.muttrc` had the following line :
> 
> ```
> mailboxes =spam =INBOX =new =cur =tmp =Archive =Drafts =Trash =Sent =heidi 
> ```
> 
> which caused problems because `=new`,`=cur` and `=tmp` didn't exist in the structure.

Yeah, they should not be here. Maybe you went into a kind of dirty state that temporally created theses folders, but then were removed.
Remove `=new`, `=cur`, `=tmp` from mailboxes.

> After resolving these it turned out that `msmtp` wasn't working properly which we can all guess why. After a little digging it was confirmed that it couldn't authenticate via SSL. To confirm this I added the following to `~/.config/msmtp/config` :
> 
> ```
> tls_starttls off
> tls_certcheck off
> ```
> 
> This allowed me to send email via msmtp. Does this mean that the connection will be encrypted but it won't check the validity of the certificate? Or will it use an unsecure port and try to upgrade if it can, but it won't be able to so the message will be unencrypted? The port `465` is specified in the work account block in this config file. I am not sure what will be happening here.

Port 465 was to do SMTP over TLS (it is deprecated but still used).
STARTTLS is used to upgrade a plain text tunnel into an encrypted one (eg, you connect in plain to a server via port 587, then use STARTTLS protocol to upgrade the connection to an TLS encrypted one). By adding `tls_starttls off`, you tell that it should not use STARTTLS.

It is explained in the msmtp manual:

> A server can use TLS in one of two modes: via a STARTTLS
> command (the session starts  with  the  normal  protocol
> initialization, and TLS is then started using the protocol's STARTTLS command),
> or immediately (TLS is initialized before the normal protocol initialization;
> this requires a separate port). The first mode is the  default,
> but  you  can  switch  to  the  second mode by disabling tls_starttls.

If you still have `tls on` in the config, you are "safe" in the sense that it will use an encrypted tunnel, but won't verify the certificate. It does mean that you are vulnerable to MITM (by any evil person), so not so safe. It will be better if instead you ask to check the certificate validity and add the certificate as trusted.

> I would like to know why one works but not the other. IMAP and SMTP don't use different certificates do they?

They may. Eg, smtp.gmail.com and imap.gmail.com use different certificates.


> > P.S.: Could you try openssl s_client -connect imap.gmail.com:993 -CAfile CERTFILE -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate" with CERTFILE being the value of CertificateFile. Try also with openssl s_client -connect imap.gmail.com:993 -CApath /dev/null -verify_return_error -verify_hostname imap.gmail.com </dev/null >/dev/null 2>&1 && echo "Valid Certificate"
> 
> Neither of those commands print anything. BTW I am not using gmail for this, I used their IMAP server as a test as I thought their certificate would be trusted what with them being so popular and all [...]

So am I. It was to test if you did not have a bug that is present in old openssl version.

Going back to the msmtp issue, you should remove `tls_certcheck off`, then you can:
 - use the fingerprint method I mentioned in https://github.com/LukeSmithxyz/mutt-wizard/issues/479#issuecomment-652078908.
 - get the certificate of the SMTP service, put it somewhere and point `tls_trust_file` to that file in the msmtp config file.

**Comment by JoshuaCrewe** [comment]
GAH! @f380cedric sorry I completly missed your response!

> Strange, I was not expecting that to work. Maybe you have something like this running to keep keychain and ca store synced?

To be honest with you I don't think it did work. I think I left the change to the script in there which has confused things somewhat.

>It does not need a lot of extra configuration, just adding the company certificate in keychain is enough for them to perform MITM.

I essentially bought the laptop from Apple and unboxed it myself so the company hasn't done any extra configuration on this machine I shouldn't think. We aren't a huge company.

> Maybe you went into a kind of dirty state that temporally created theses folders, but then were removed.

This was my assumption too. Removing them obvs fixed the problem and I haven't found any more from not having them!

> Port 465 was to do SMTP over TLS (it is deprecated but still used).

Oh! So I should be using a different port for SMTP then, probably 587 ?

> Going back to the msmtp issue, you should remove tls_certcheck off, then you can
>
>    use the fingerprint method I mentioned in #479 (comment).
>   get the certificate of the SMTP service, put it somewhere and point tls_trust_file to that file in the msmtp config file.

I was able to get the certificate for my work account and add that to the certificate store then trust it. That works fine now. The same process didn't work for my personal email which is hosted with zoho. I will see if the fingerprint approach works with that one. Does the fingerprint not change regularly? I seem to remember this from when I did this setup myself. Will the certificates not expire and then this process will need to be repeated?

**Comment by JoshuaCrewe** [comment]
`echo 'hello' | msmtp -v -a home address@domain.com`

This results in the process hanging and eventually saying `the server sent an empty reply` . [The Arch Wiki](https://wiki.archlinux.org/index.php/Msmtp#Server_sent_empty_reply) suggests that ` this probably means the mail server doesn't support STARTTLS over port 587, but requires TLS over port 465` . I changed the port to `465` with `tls_starttls off` and got the same result. 

[Zoho does support TLS on 587](https://www.zoho.com/mail/help/zoho-smtp.html#alink3) so I don't quite know why this would be. Trusting the certificate or including the fingerprint doesn't seem to make a difference either.

**Comment by f380cedric** [comment]
> Oh! So I should be using a different port for SMTP then, probably 588 ?

No, I was just saying that using SMTPS (SMTP over TLS) on 465 is used by some, but is not standardized.
They preferred to push for plaintext 587 with possible STARTTLS (easier for retro-compatibility).
I was just giving extra information. Sorry for the confusion.

You should use the port and protocol specified by your email provider.

> I was able to get the certificate for my work account and add that to the certificate store then trust it.

How have you done that (mbsync and msmtp)?

> The same process didn't work for my personal email which is hosted with zoho. I will see if the fingerprint approach works with that one. Does the fingerprint not change regularly? I seem to remember this from when I did this setup myself. Will the certificates not expire and then this process will need to be repeated?



> `echo 'hello' | msmtp -v -a home address@domain.com`
> This results in the process hanging and eventually saying `the server sent an empty reply` .

This cannot work until you have a correct configuration.

> [Zoho does support TLS on 587](https://www.zoho.com/mail/help/zoho-smtp.html#alink3) so I don't quite know why this would be.

They support both (SMTPS on 465, SMTP + STARTTLS over 587). Just pick one and update your msmtp configuration accordingly (eg. port and protocol).

> Trusting the certificate or including the fingerprint doesn't seem to make a difference either.

If you want to trust a certificate, downloading it will be different if you use 465 or 587:
 - 465: `openssl s_client -connect smtp.zoho.eu:465 -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sed -ne '1,/-END CERTIFICATE-/p' > ~/choose_a_path/choose_a_filename.pem`
 - 587: `openssl s_client -connect smtp.zoho.eu:587 -starttls smtp -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sed -ne '1,/-END CERTIFICATE-/p' > ~/choose_a_path/choose_a_filename.pem`

But they seems to be the same certificate.

then use `tls_trust_file ~/choose_a_path/choose_a_filename.pem` (care to put it below the correct `account accountname` directive).

If you prefer the fingerprint:
 - `msmtp -a home --serverinfo --tls --tls-certcheck=off --tls-fingerprint=` and grap the tag after SHA256: (it is `7A:3F:E5:0B:AE:CC:CD:24:B4:D5:17:E9:D6:AD:38:D0:92:2B:3F:44:FE:5D:26:CA:AA:DC:99:58:4E:52:E4:EC` on my side for smtp.zoho.eu)
 - use `tls_fingerprint the_fingerprint` in your msmtp configuration file (care to put it below the correct `account accountname directive`)

If it still does not work, could you share you msmtp configuration? Please, **redact any personal/sensitive parts** (eg passwords, email addresses)!

> Does the fingerprint not change regularly? I seem to remember this from when I did this setup myself. Will the certificates not expire and then this process will need to be repeated?

The fingerprint is directly linked to the certificate. If they change the certificate (or renew due to expiration), then the fingerprint will be different.
But you will have the same issue by trusting the certificate directly. When they renew it, it will be a different one, and you will need to retrust it.

One solution is to trust one of the certificate authorities that delivered the certificate (and digitally signed it) instead of the server certificate.
But let's try to make it work first before figuring out how to handle expiration.

**Comment by JoshuaCrewe** [comment]
```
defaults
auth	on
tls	on
logfile	~/.config/msmtp/msmtp.log

account work
host imap.workdomain.uk
port 587
from work@workdomain.co.uk
user work@workdomain.co.uk
passwordeval "pass mutt-wizard-work"

account home
host smtp.zoho.eu
port 587
from home@home-email.co.uk
user home@home-email.co.uk
passwordeval "pass mutt-wizard-home"
```
☝️ This will result in an empty server response for home but work will function correctly. This is the starting point for the config which was given to me by the wizard.

```
account home
host smtp.zoho.eu
port 587
from home@home-email.co.uk
user home@home-email.co.uk
passwordeval "pass mutt-wizard-home"
tls_fingerprint 7A:3F:E5:0B:AE:CC:CD:24:B4:D5:17:E9:D6:AD:38:D0:92:2B:3F:44:FE:5D:26:CA:AA:DC:99:58:4E:52:E4:EC
```
☝️ will do the same. It will hang for a minute or two and then error out with an empty response from the server.

I tried to use the actual certificate but I couldn't get the dance right. I can get the certificate. In order to trust it I need to import it in to the keychain. But then I can't link to that trusted certificate as I can't find the file. If I link to the original certificate after trusting it hangs. If I link to an exported certificate from the keychain is says `cannot set X509 trust file`.

The fingerprint should work right?

```
account home
host smtp.zoho.eu
port 465
tls_starttls off
tls_fingerprint 7A:3F:E5:0B:AE:CC:CD:24:B4:D5:17:E9:D6:AD:38:D0:92:2B:3F:44:FE:5D:26:CA:AA:DC:99:58:4E:52:E4:EC
from home@home-email.co.uk
user home@home-email.co.uk
passwordeval "pass mutt-wizard-home"
```
☝️ also hangs with an empty server response.

**Comment by f380cedric** [comment]
What is the output of:

`echo 'are you working?' | msmtp --host=smtp.zoho.eu --from=your_email --port=587 --tls on --tls-starttls on --user your_email --passwordeval "pass mutt-wizard-home" --auth plain -v your_email`

**DONT** forget to redact sensitive information.


Didnt you have issues with the work account as well? How did you solve it? I do not see any workaround in your configuration file.

**Comment by JoshuaCrewe** [comment]
```
using account specified on command line
host = smtp.zoho.eu
port = 587
source ip = (not set)
proxy host = (not set)
proxy port = 0
socket = (not set)
timeout = off
protocol = smtp
domain = localhost
auth = choose
user = home@home-domain.co.uk
password = *
passwordeval = pass mutt-wizard-home
ntlmdomain = (not set)
tls = on
tls_starttls = on
tls_trust_file = system
tls_crl_file = (not set)
tls_fingerprint = (not set)
tls_key_file = (not set)
tls_cert_file = (not set)
tls_certcheck = on
tls_min_dh_prime_bits = (not set)
tls_priorities = (not set)
tls_host_override = (not set)
auto_from = off
maildomain = (not set)
from = home@home-domain.co.uk
set_from_header = auto
set_date_header = auto
remove_bcc_headers = on
undisclosed_recipients = off
dsn_notify = (not set)
dsn_return = (not set)
logfile = (not set)
logfile_time_format = (not set)
syslog = (not set)
aliases = (not set)
reading recipients from the command line
<-- 220 mx.zoho.eu SMTP Server ready 7 July, 2020 5:50:34 PM CEST
--> EHLO localhost
<-- 250-mx.zoho.eu Hello localhost (<ip information>)
<-- 250-STARTTLS
<-- 250 SIZE 53477376
--> STARTTLS
<-- 220 Ready to start TLS.
TLS session parameters:
    (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
TLS certificate information:
    Owner:
        Common Name: *.zoho.eu
    Issuer:
        Common Name: Thawte RSA CA 2018
        Organization: DigiCert Inc
        Organizational unit: www.digicert.com
        Country: US
    Validity:
        Activation time: Fri 29 Mar 00:00:00 2019
        Expiration time: Sun 28 Mar 13:00:00 2021
    Fingerprints:
        SHA256: 7A:3F:E5:0B:AE:CC:CD:24:B4:D5:17:E9:D6:AD:38:D0:92:2B:3F:44:FE:5D:26:CA:AA:DC:99:58:4E:52:E4:EC
        SHA1 (deprecated): 52:EF:12:89:43:52:4F:D2:26:F1:A2:BF:C5:0B:48:EB:9F:F2:73:FC
--> EHLO localhost
<-- 250-mx.zoho.eu Hello localhost (<ip information>)
<-- 250-AUTH LOGIN PLAIN
<-- 250 SIZE 53477376
--> AUTH PLAIN AG1lQGp...3RzIHBpbmUgcmVkIHBpbmU=
<-- 235 Authentication Successful
--> MAIL FROM:<home@home-domain.co.uk>
<-- 250 Sender <home@home-domain.co.uk> OK
--> RCPT TO:<home@home-domain.co.uk>
<-- 250 Recipient <home@home-domain.co.uk> OK
--> DATA
<-- 354 Ok Send data ending with <CRLF>.<CRLF>
--> From: home@home-domain.co.uk
--> Date: Tue, 07 Jul 2020 16:50:34 +0100
--> are you working?
--> .
msmtp: the server sent an empty reply
msmtp: could not send mail
```

I am pretty sure with the work account I got the certificate. Imported it to the keychain and trusted it. The Zoho certificate is a wild card which might be making a difference. I could remove the trust from the work one and see if that breaks.

I appreciate the time you are spending on this but equally you have gone above and beyond to help me with this. So thanks for that! Don't feel tied to continue if you have better things to be getting on with :)

**Comment by JoshuaCrewe** [comment]
Well I deleted the certificates in the keychain and the work email still sends 🤦 At this stage I think I want to buy a buy and push off out to sea.

I am thinking about nuking this set up and starting again to see if I can get back to a cleaner state.

**Comment by f380cedric** [comment]
@JoshuaCrewe change your password right now.
`AUTH method token` (here its `AUTH PLAIN <token>`) has to be redacted. It leaks your password.

**Comment by JoshuaCrewe** [comment]
That code is not what got printed out in my terminal. I should have written redacted but instead I kept it looking like the output. Thanks for the heads up though!

**Comment by f380cedric** [comment]
> ```
> --> STARTTLS
> <-- 220 Ready to start TLS.
> TLS session parameters:
>     (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
> TLS certificate information:
>     Owner:
>         Common Name: *.zoho.eu
>     Issuer:
>         Common Name: Thawte RSA CA 2018
>         Organization: DigiCert Inc
>         Organizational unit: www.digicert.com
>         Country: US
>     Validity:
>         Activation time: Fri 29 Mar 00:00:00 2019
>         Expiration time: Sun 28 Mar 13:00:00 2021
>     Fingerprints:
>         SHA256: 7A:3F:E5:0B:AE:CC:CD:24:B4:D5:17:E9:D6:AD:38:D0:92:2B:3F:44:FE:5D:26:CA:AA:DC:99:58:4E:52:E4:EC
>         SHA1 (deprecated): 52:EF:12:89:43:52:4F:D2:26:F1:A2:BF:C5:0B:48:EB:9F:F2:73:FC
> --> EHLO localhost

From this, I conclude that you do not have any issue with the certificate anymore. It asked for STARTTLS, and everything went fine.

> ```
> --> From: home@home-domain.co.uk
> --> Date: Tue, 07 Jul 2020 16:50:34 +0100
> --> are you working?
> --> .
> msmtp: the server sent an empty reply
> msmtp: could not send mail
> ``` 

Oops, my bad (half).
Seems that Zoho is strictly following RFC. So, we need a space between headers and body. Related to [this](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1650762.html) ([answer](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1653358.html))

Normally, this one should work: `echo -e '\nare you working?' | msmtp --host=smtp.zoho.eu --from=your_email --port=587 --tls=on --tls-starttls=on --user=your_email --passwordeval="pass mutt-wizard-home" --auth=on -v your_email`

> Well I deleted the certificates in the keychain and the work email still sends

Does the file `/usr/local/etc/openssl/cert.pem` or `/usr/local/etc/gnutls/cert.pem` exist?

**Comment by JoshuaCrewe** [comment]
> Normally, this one should work: echo -e '\nare you working?' | msmtp --host=smtp.zoho.eu --from=your_email --port=587 --tls=on --tls-starttls=on --user=your_email --passwordeval="pass mutt-wizard-home" --auth=on -v your_email

That works 🎉 

> Does the file /usr/local/etc/openssl/cert.pem or /usr/local/etc/gnutls/cert.pem exist?

They both exist yes.

I can send mail now. (It gave me an error which said it couldn't find a key to sign the email with, but when I change the config to not do that it works) Which has left me a little baffled as I feel like we are back where we started on this journey.

**Comment by f380cedric** [comment]
You are with the default mw configuration and everything is working fine now?
Or is there still something not working?

**Comment by JoshuaCrewe** [comment]
I am pretty sure that it was all working. It was using the default `mw` script at least. And you managed to get me to a point where I could send and receive emails. I needed to have the certificates on disk somewhere and have mbsync point to them for that to work. 

Work has taken over my time again so I haven't really been able to fiddle with this any more.

Thanks again for taking the time to troubleshoot this, I really appreciate it. I am going to close this now as all the information is on this thread now I reckon.
