### ISSUE TITLE
No secret key found

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/mutt-wizard#483]
For the initial setup, when I run `gpg --full-gen-key` and then `pass init <email>`, I get the following error:
`gpg: decryption failed: No secret key`.

I never faced this problem on Arch linux and am currently running Artix when this issue pops up. Also, I just realised that both `gpg` and `gpg2` are installed on my system. Is this the reason why I'm getting the above error?

Thanks!

**Comment by f380cedric** [comment]
> [...] both `gpg` and `gpg2` are installed on my system. Is this the reason why I'm getting the above error?

pass will use gpg2 if it exists, by design.

gpg and gpg2 should normally be the same on Artix, one is a symbolic link to the other.
Check that `gpg --list-secret-keys` and `gpg2 --list-secret-keys` return the same information.

If they do not, then you will need to regenerate (or import) keys using gpg2.
If they do, then:
 - are you using the same address email for `pass init` than the one associated with your gpg key?
 - does it ask for your passphrase?

`PASSWORD_STORE_GPG_OPTS="--verbose" pass init` may help here.

**Comment by paniash** [comment]
Thank you @f380cedric for your comment.
Yes, I get the same output for `gpg --list-secret-keys` and `gpg2 --list-secret-keys`.

I am using the same email-id for `pass init` as `gpg`. No, it does not ask for a passphrase. I get the following output when running `pass init <email>` :
```
Password store initialized for <email>
mutt-wizard-<name>: reencrypting to <key>
gpg: decryption failed: No secret key
```

**Comment by f380cedric** [comment]
> No, it does not ask for a passphrase. I get the following output when running `pass init <email>` :
> 
> ```
> Password store initialized for <email>
> mutt-wizard-<name>: reencrypting to <key>
> gpg: decryption failed: No secret key
> ```

And I guess the `<key>` is the keyid output by `gpg --list-secret-keys`?
Have you set up a passphrase when generating your gpg key pair?
If yes, it seems to be a pinentry issue.

From [Artix pinentry](https://gitea.artixlinux.org/artixlinux/packages/src/branch/master/pinentry/repos/core-x86_64/pinentry), it tries the gtk version if `/usr/lib/libgtk-x11-2.0.so.0` exists. I am assuming that you do not have this file (or no DISPLAY) and so, it tries the curse version.

If I am right, then try:

```sh
export GPG_TTY=$(tty)
pass init <email>
```

 It that does not work, try:
```sh
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null
pass init <email>
```
([from ArchLinux wiki](https://wiki.archlinux.org/index.php/GnuPG#Configure_pinentry_to_use_the_correct_TTY)).

It should work 🤞. If it does, you should put it in your shell rc file.

**Comment by paniash** [comment]
Sorry for the late reply, @f380cedric . 
> 
> If I am right, then try:
> 
> ```shell
> export GPG_TTY=$(tty)
> pass init <email>
> ```
> 
> It that does not work, try:
> 
> ```shell
> export GPG_TTY=$(tty)
> gpg-connect-agent updatestartuptty /bye >/dev/null
> pass init <email>
> ```

I tried the above methods but none of them have worked so far. I once again, tried setting up a `gpg --full-gen-key. Here is the entire log:
```
Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? O
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: /home/ashish/.gnupg/trustdb.gpg: trustdb created
gpg: key 84D15CD3D00FE19E marked as ultimately trusted
gpg: directory '/home/ashish/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/home/ashish/.gnupg/openpgp-revocs.d/1C0496FB5AA9A1D0CEB8626A84D15CD3D00F
public and secret key created and signed.
```
I then ran `pass init <email>` and I get this (without any password prompt):
```
mkdir: created directory '/home/ashish/.password-store/'
Password store initialized for <email>
```
I then setup mutt-wizard and get this:
```
[ashish@void ~]$ mw add
Do you want to keep your mail for this account offline with mbsync? [yes/no]
        yes
Insert the email address that you want to autoconfigure for mutt/mbsync
        Email: ashish.panigrahi@niser.ac.in
gpg: error reading key: No public key

Is your email hosted with Protonmail? [yes/no] no

Searching for niser.ac.in in `domains.csv`...
Congrats! Server info has automatically been found, so you won't have to look anything up!
        IMAP server: imap.gmail.com
        IMAP port: 993
        SMTP server: smtp.gmail.com
        SMTP port: 587
This data will be used by the wizard.
Enter the full name you want to be identified by on this account.
        Real name: Ashish Panigrahi
Enter a short, one-word identifier for this email account that will distinguish them from any other accounts you add.
        Account name: ashish
If your account has a special username different from your address, insert it now. Otherwise leave this prompt totally blank.
Most accounts will not have a separate login, so you should probably leave this blank.
        Login(?):
If you want to limit the number of messages kept offline to a number, enter that number below. If you do not want to limit your mail and would like `mbsync` to sync all mail, press enter without typing a number.

Enter password for mutt-wizard-ashish:
Retype password for mutt-wizard-ashish:
Creating profiles for `ashish`...DONE.
Mailboxes detected.
Setting default mailboxes for your Inbox, Sent, Drafts and Trash in mutt...
Setting up your keyboard shortcuts for jumping between mailboxes...
All done.
You should now be able to run `mbsync ashish` to begin to download your mail.
```
Notice that I'm getting a `gpg: error reading key: No public key` error message.

Then I download my email and test it by sending an email and I get this error message:
```
secret key 'ashish.panigrahi@niser.ac.in' not found: End of file.
```
I am really lost at this point as to how to rectify this issue.

**Comment by f380cedric** [comment]
> I am really lost at this point as to how to rectify this issue.

mw will not work until you are able to interact with pass, and hence interact with gpg and pinentry.

Do you use extra configuration for pass or gpg?

try (1):

```sh
export GPG_TTY=$(tty)
gpg-connect-agent reloadagent /bye
pass generate testfile 20
gpg --verbose -d /home/ashish/.password-store/testfile.gpg
rm /home/ashish/.password-store/testfile.gpg
```

Does it print the password? Does it ask for passphrase to unlock your gpg private key?


If not, check that the key-id output is the correct one (or if you find something helpful).
What we can try is to force the pinentry type:
 - add in `~/.gnupg/gpg-agent.conf`

 ```
 pinentry-program /usr/bin/pinentry-curses
 ```
 
 - retry (1)
 - if not working, try another pinentry in your .conf (list: `ls /usr/bin/pinentry-*`, skip `-tty`)

Is it a X session or tty-only? Do you use Gnome (gnome keyring) or KDE?

**Comment by paniash** [comment]
I don't have any extra configuration for pass and gpg, just the defaults.

> try (1):
> 
> ```shell
> export GPG_TTY=$(tty)
> gpg-connect-agent reloadagent /bye
> pass generate testfile 20
> gpg --verbose -d /home/ashish/.password-store/testfile.gpg
> rm /home/ashish/.password-store/testfile.gpg
> ```

I did this and got the following output:
```
[ashish@void ~]$ pass init panigrahi.ashish1999@gmail.com
Password store initialized for panigrahi.ashish1999@gmail.com
[ashish@void ~]$ pass generate testfile 20
The generated password for testfile is:
z_QHMYB]<X+kj'37Vd#Z
[ashish@void ~]$ gpg --verbose -d /home/ashish/.password-store/testfile.gpg
gpg: public key is CE704A1E77F11110
gpg: using subkey CE704A1E77F11110 instead of primary key 4DBE3205E300BACD
gpg: pinentry launched (12105 gtk2 1.1.0 /dev/pts/2 st-256color :0)
gpg: using subkey CE704A1E77F11110 instead of primary key 4DBE3205E300BACD
gpg: encrypted with 2048-bit RSA key, ID CE704A1E77F11110, created 2020-07-08
      "Ashish Panigrahi (for mutt-wizard) <panigrahi.ashish1999@gmail.com>"
gpg: AES256 encrypted data
gpg: original file name=''
z_QHMYB]<X+kj'37Vd#Z
[ashish@void ~]$ rm /home/ashish/.password-store/testfile.gpg
removed '/home/ashish/.password-store/testfile.gpg'
```
Yes, it did ask for my passphrase to unlock my gpg private key.
This error is in my X-session. Haven't tried on tty though. I don't know about the keyring since I'm on dwm.

**Comment by LukeSmithxyz** [comment]
Do you have `$PASSWORD_STORE_DIR` or `$GNUPGHOME` set to anything?

**Comment by paniash** [comment]
I did have it set earlier in my `.profile` but I removed those and tried setting up my gpg key pairs. I still get the same error.

**Comment by f380cedric** [comment]
Ok, the issue you had in https://github.com/LukeSmithxyz/mutt-wizard/issues/483#issue-650639862 is quite different from https://github.com/LukeSmithxyz/mutt-wizard/issues/483#issuecomment-653874650.

It does not seems to be a pass issue anymore. You was able to run mbsync. I did not see it, oops (sorry).


> ```
> Insert the email address that you want to autoconfigure for mutt/mbsync
>         Email: ashish.panigrahi@niser.ac.in
> gpg: error reading key: No public key
> ```
> [...]
> Notice that I'm getting a `gpg: error reading key: No public key` error message.
> 
> Then I download my email and test it by sending an email and I get this error message:
> 
> ```
> secret key 'ashish.panigrahi@niser.ac.in' not found: End of file.
> ```

The `gpg: error reading key: No public key` is because it is looking for a gpg key for `ashish.panigrahi@niser.ac.in` (the email you are trying to setup),
but your gpg keys are for `"Ashish Panigrahi (for mutt-wizard) <panigrahi.ashish1999@gmail.com>"`.
From https://github.com/LukeSmithxyz/mutt-wizard/blob/c4144ffb7c479830acf579caa05e9f85f71b36aa/bin/mw#L140, `keyid` will be empty. But mw still tries to setup autosign and encryption etc.
I am expecting that if no `gpg_default_key` is set (but sign + encryption are activated), gpg will just search for a keys associated with the email(s) in the mail headers. IMO, that is why you got `secret key 'ashish.panigrahi@niser.ac.in' not found: End of file.`.

So, if at the end of the day, you successfully set up your stuff to get as https://github.com/LukeSmithxyz/mutt-wizard/issues/483#issuecomment-653874650, then try to replace (in your `.config/mutt/accounts/<number>-<accountname>.muttrc`):

```
set crypt_autosign = yes
set crypt_opportunistic_encrypt = yes
set pgp_self_encrypt = yes
set pgp_default_key  = # I am expecting this to be empty in your case (it should not)
```
to 

```
set crypt_autosign = no
set crypt_opportunistic_encrypt = no
set pgp_self_encrypt = no
#set pgp_default_key  = # I am expecting this to be empty in your case (it should not)
```

Reload and retry.

**Comment by paniash** [comment]
Thank you very much @f380cedric. I set the options as `no` as you suggested and it worked! Also `set pgp_default_key = ` was in fact empty in my case. However I don't understand, is the gpg associated email-id and the email-id I'm setting up mutt-wizard for, supposed to be the same?

**Comment by f380cedric** [comment]
> However I don't understand, is the gpg associated email-id and the email-id I'm setting up mutt-wizard for, supposed to be the same?

Not necessary. It depends on what you are trying to achieve.
If you want to sign and/or encrypt (to self) your mails with gpg, then you need a gpg pair associated with the email-id.
It is possible to link a pair to multiple mails (by adding an uid).

I wont expect that users have all their configured mails associated with a gpg pair (one pair for multiple accounts or one pair per accounts).
There are some email addresses where you have no intention (or do not want) to sign for example.

IMO, it is a bug, mw should check if there is a keyid, and if there is not,
print a warning and do something (eg ask the user to create one, to specify an id, or disable the autosign/encrypt_to_self).

**Comment by paniash** [comment]
I see. Thanks a lot @f380cedric for your help! I really appreciate it :)
