### ISSUE TITLE
Handle email addresses with no pgp keys.

### ISSUE THREAD

**Issue by f380cedric** [LukeSmithxyz/mutt-wizard#491]
From issue #483, if there is no gpg pair associated to the email address,
`keyid` will be empty → `pgp_default_key` will be empty.
It does not go well with `crypt_autosign` and `pgp_self_encrypt` set (sending mails will fail).

It would be great if:
 - mw throws a warning
 - mw takes actions (eg disable auto signing and self encryption)

**Comment by smartding** [comment]
mw does show a warning when adding a new mail account which doesn't have an associated gpg pair. 
It says "gpg: error reading key: No public key".

But the `gpg_default_key` is empty for the account, and I can't sent mails.

**Comment by f380cedric** [comment]
The warning is printed by gpg, not by mw. I think the message is not clear. It is clear when you directly use gpg. But when gpg is called via another script (eg mw), then you lost that clearness because you have no idea what is happening behind the scene.

For your issue, please refer to https://github.com/LukeSmithxyz/mutt-wizard/issues/483#issuecomment-655579949
