### ISSUE TITLE
No notification on new mail

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/mutt-wizard#495]
I'm running `mailsync` as a cronjob and whenever I receive any new email, the expected behaviour is to send a notification through `notify-send` but I don't see any notifications. Is this default behaviour?

Thanks in advance:)

**Comment by f380cedric** [comment]
Could it be related to #470?

**Comment by thepenguinthatwants** [comment]
There have being quite many similar issues ongoing.
Might also be related to this https://github.com/LukeSmithxyz/mutt-wizard/issues/282

**Comment by paniash** [comment]
Ok, so here's what I did.
I commented out the `export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus` in `/usr/bin/mailsync`. I then added the same line at the end of my `.profile`.

This seems to have rectified the issue which I still don't understand how it worked. If someone could explain, that would be great. 

Also, I have run into a minor issue after doing the above. I have some applications autostart  through `.xprofile` when I log in through lightdm. This includes `nm-applet` and for some reason after I log in, I have 2 instances of `nm-applet` running.

Here is my `.xprofile` : 
```
#!/bin/sh

# This file runs when a DM logs into a graphical session
# If you use startx/xinit like a Chad, this file will also be source

mpd &		# starts music player daemon
picom &		# starts compositor
dunst &		# starts notification daemon
remaps &	# maps caplock to escape
xwallpaper --zoom /home/ashish/.config/wall.png & 	# sets wallpaper
unclutter &	# removes mouse cursor when not in use
sleep 5 && dwmblocks &	# statusbar
nm-applet & 	# starts nm-applet

```

**Comment by f380cedric** [comment]
Does it work if you comment it in `/usr/bin/mailsync` **but don't** add it in `.profile`? Or you have to set it in `.profile` to make it work?

**Comment by paniash** [comment]
> Does it work if you comment it in `/usr/bin/mailsync` **but don't** add it in `.profile`? Or you have to set it in `.profile` to make it work?

Yes, I did just that and it seems to work perfectly. `nm-applet` works fine and I get the notifications for my emails! Yet, I don't understand what the issue was when I hadn't uncommented the line in `/usr/bin/mailsync`. Thanks @f380cedric!

**Comment by f380cedric** [comment]
I suspect that your `DBUS_SESSION_BUS_ADDRESS` is not the one written in `mailsync`, but something random.
That is common behavior with non-systemd session.

On the cron side, when a dbus communication is needed and the `DBUS_SESSION_BUS_ADDRESS` is set to a wrong value,
the communication fails.
However, if it is not set, then "autolaunch" triggers. From dbus-launch manual:

> If DBUS_SESSION_BUS_ADDRESS is not set for a process that tries to use D-Bus, by default the process will attempt to
> invoke dbus-launch with the --autolaunch option to start up a new session bus or find the existing bus address on the X
> display or in a file in ~/.dbus/session-bus/ 
>
> Whenever an autolaunch occurs, the application that had to start a new bus will be in its own little world; it can effectively
> end up starting a whole new session if it tries to use a lot of bus services. This can be suboptimal or even totally broken,
> depending on the app and what it tries to do.

And it seems that, in your case, it works.

Or the default cron configuration in your system exports the correct `DBUS_SESSION_BUS_ADDRESS`.

DISCLAIMER: I don't know much about DBUS, I may be wrong.

**Comment by paniash** [comment]
Oh, ok thanks for the responce @f380cedric!
