### ISSUE TITLE
Is there a way to set signature just like gmail?

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/mutt-wizard#496]
I was wondering if there is a way to set up a signature at the end of emails in mutt-wizard just like gmail.

Thanks:)

**Comment by Kr1ss-XD** [comment]
There is. It's literally called the [signature](https://neomutt.org/guide/reference.html#signature) setting.

**Comment by paniash** [comment]
Ah, thanks a lot @Kr1ss-XD.
