### ISSUE TITLE
pam-gunpg doesn't work

### ISSUE THREAD

**Issue by Wjinlei** [LukeSmithxyz/mutt-wizard#501]
I know this question should not be asked here，But I really can't find a solution, so I came to ask if you have any suggestions? Because I also use arch linux and dwm.

I have added in 

> 1./etc/pam.d/system-local-login
`auth     optional  pam_gnupg.so
session  optional  pam_gnupg.so`

> 2 ~/.gunpg/gpg-agent.conf
`allow-preset-passphrase
max-cache-ttl 86400`

> 3 ~/.pam-gnupg
`My Keygrip`

But mailsync still requires me to enter a password after I restart.

Did i do something wrong？ Thank you

**Comment by gimmelemons** [comment]
I have similar configuration. I get this problem too. I have to re-enter password every 30 min.

**Comment by f380cedric** [comment]
From pam-gnupg README, pam configuration has to be included in several files depending on your configuration: 

> The module implements PAM's `auth` and `session` functions. `auth` stores the
> passphrase and tries to send it to `gpg-agent`. If that fails, e.g. due to the
> agent not running, `session` (optionally) starts it and sends the passphrase
> again.
> 
> How to include the module in PAM's config depends on your distribution. You
> generally need to add the lines
> 
>     auth     optional  pam_gnupg.so
>     session  optional  pam_gnupg.so
> 
> in the appropriate place(s). For graphical sessions, that should usually be
> somewhere at the end of your display manager's config, e.g.
> `/etc/pam.d/lightdm`, `/etc/pam.d/lxdm`, `/etc/pam.d/sddm`, etc.
> 
> On Arch, I also added it to `/etc/pam.d/system-local-login` for console logins.
> Additionally, I have
> 
>     auth     optional  pam_gnupg.so
> 
> in `/etc/pam.d/i3lock`, so I can clear the password cache when locking the
> screen (via `gpg-connect-agent --no-autostart reloadagent /bye`), and have my
> keys unlocked automatically afterwards. The `session` line is not needed here,
> since i3lock only authenticates the user, but does not open a new session.

Verify that your configuration are ok w.r.t that README.

**Comment by gimmelemons** [comment]
I have followed the README. I added 
`auth     optional  pam_gnupg.so`
`session  optional  pam_gnupg.so`
 to `/etc/pam.d/system-local-login`. 

I don't need to add it to `/etc/pam.d/system-login` do I ?..

Distro - Arch, with dwm

**Comment by f380cedric** [comment]
> I don't need to add it to `/etc/pam.d/system-login` do I ?..

In theory, no.
How do you login? Do you use a DM or you use the tty?
If you use the tty, then it should be ok.

But in your case, it reset each 30 min no?
Seems more to be an issue with gpg-agent, `max-cache-ttl` and `default-cache-ttl` values.

You can check these values using `gpgconf --list-options gpg-agent | grep -F ttl`.
You can read it as "name:[...]:default_value::[current_value]".

**Comment by gimmelemons** [comment]
I use tty to login..

This is what I have in `~/.gnupg/gpg-agent.conf` 
```
allow-preset-passphrase
max-cache-ttl 86400
```
According to the [README](https://github.com/cruegge/pam-gnupg), 

> preset passphrases do not expire after default-cache-ttl but after max-cache-ttl

This is what the output of `gpgconf --list-options gpg-agent | grep -F ttl` looks like:
```
default-cache-ttl:24:0:expire cached PINs after N seconds:3:3:N:600::
default-cache-ttl-ssh:24:1:expire SSH keys after N seconds:3:3:N:1800::
max-cache-ttl:24:2:set maximum PIN cache lifetime to N seconds:3:3:N:7200::86400
max-cache-ttl-ssh:24:2:set maximum SSH key lifetime to N seconds:3:3:N:7200::
```

**Comment by f380cedric** [comment]
Your mailsync cron is configured to run every 10 minutes or less (the cron should appears using `crontab -l`)? If nothing ask for your gpg key for 10 min, its cached value is discarded and you have to reenter its passphrase.

**Comment by gimmelemons** [comment]
> Your mailsync cron is configured to run every 10 minutes or less (the cron should appears using crontab -l)?
Its set to 30 min.. `*/30 * * * * /usr/bin/mailsync`

**Comment by f380cedric** [comment]
> Its set to 30 min.. `*/30 * * * * /usr/bin/mailsync`

That is your issue here. From gpg-agent manual:

> --default-cache-ttl n
>        Set the time a cache entry is valid to n  seconds.   The
>        default  is 600 seconds.  Each time a cache entry is ac‐
>        cessed, the entry's timer is reset.  To set  an  entry's
>        maximum lifetime, use max-cache-ttl.  Note that a cached
>        passphrase may not evicted immediately from memory if no
>        client  requests  a  cache operation.  This is due to an
>        internal housekeeping function which is only  run  every
>        few seconds.
> 
> --max-cache-ttl n
>        Set the maximum time a cache entry is valid  to  n  sec‐
>        onds.   After  this  time  a cache entry will be expired
>        even if it has been accessed recently or  has  been  set
>        using  gpg-preset-passphrase.   The  default  is 2 hours
>        (7200 seconds).

If nothing ask for you gpg key for 600 seconds (10 minutes), then it expires.
In your `gpg-agent.conf`, add `default-cache-ttl x` where is is a number >= 1800 (30 minutes).

**Comment by Wjinlei** [comment]
I use dwm, ssh-agent dwm, but it still asks for my password every time I boot up, I don’t know what I did wrong

**Comment by f380cedric** [comment]
> I use dwm, ssh-agent dwm, but it still asks for my password every time I boot up, I don’t know what I did wrong

The passphrase to unlock your gpg key is the same as your passphrase to login?

**Comment by gimmelemons** [comment]
> In your `gpg-agent.conf`, add `default-cache-ttl x` where is is a number >= 1800 (30 minutes)

Aah. This works, thank you.

**Comment by Wjinlei** [comment]
> > I use dwm, ssh-agent dwm, but it still asks for my password every time I boot up, I don’t know what I did wrong
> 
> The passphrase to unlock your gpg key is the same as your passphrase to login?

Yes, they are the same. Is the usage of this program that you must enter a password once to decrypt gpg after booting? My current situation is that the password must be entered once when the machine is turned on, and then there is no need to enter it again, and the password will not need to be entered again until the next restart

**Comment by f380cedric** [comment]
> Is the usage of this program that you must enter a password once to decrypt gpg after booting? My current situation is that the password must be entered once when the machine is turned on, and then there is no need to enter it again, and the password will not need to be entered again until the next restart


It should automatically unlock your gpg after loging in. Of course, it will not work if you can login without entering your password.
It will also not work if you put the wrong keygrip in `.pam_gnupg`.

You can check your logs to see if pam_gnupg wrote something (eg `journalctl -b -g pam_gnupg`).

**Comment by Wjinlei** [comment]
> > Is the usage of this program that you must enter a password once to decrypt gpg after booting? My current situation is that the password must be entered once when the machine is turned on, and then there is no need to enter it again, and the password will not need to be entered again until the next restart
> 
> It should automatically unlock your gpg after loging in. Of course, it will not work if you can login without entering your password.
> It will also not work if you put the wrong keygrip in `.pam_gnupg`.
> 
> You can check your logs to see if pam_gnupg wrote something (eg `journalctl -b -g pam_gnupg`).

I didn't install the desktop environment, but dwm. When I boot up, I login the tty first, and then start dwm through startx. Does it matter?

Below is my `journalctl -b -g pam_gnupg`

```
-- Logs begin at Sat 2020-05-02 03:03:34 CST, end at Sat 2020-08-01 15:04:25 CST. --
Aug 01 15:01:32 manjaro audit[739]: USER_START pid=739 uid=0 auid=1000 ses=1 msg='op=PAM:session_open gra>
lines 1-2/2 (END)
```

**Comment by gimmelemons** [comment]
Mine started asking for password again.. Looking into the logs, I see

```
audit[497]: USER_AUTH pid=497 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_securetty,pam_tally2,pam_shells,pam_unix,pam_permit,pam_gnupg acct="name" exe="/usr/bin/login" hostname=username addr=? terminal=tty1 res=success'
kernel: audit: type=1100 audit(1596266664.119:41): pid=497 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_securetty,pam_tally2,pam_shells,pam_unix,pam_permit,pam_gnupg acct="name" exe="/usr/bin/login" hostname=username addr=? terminal=tty1 res=success'
login[497]: pam_gnupg(login:setcred): helper terminated with exit code 1
audit[497]: USER_START pid=497 uid=0 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_loginuid,pam_keyinit,pam_limits,pam_unix,pam_permit,pam_mail,pam_systemd,pam_env,pam_gnupg acct="name" exe="/usr/bin/login" hostname=username addr=? terminal=tty1 res=success'
```
This probably is a duplicate of [this](https://github.com/cruegge/pam-gnupg/issues/18#issue-651710429)
A lot of people seem to be facing this problem..
I think this discussion will be more fruitful if an issue is opened in pam-gnupg repo itself.

**Comment by Wjinlei** [comment]
> Mine started asking for password again.. Looking into the logs, I see
> 
> ```
> audit[497]: USER_AUTH pid=497 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_securetty,pam_tally2,pam_shells,pam_unix,pam_permit,pam_gnupg acct="name" exe="/usr/bin/login" hostname=username addr=? terminal=tty1 res=success'
> kernel: audit: type=1100 audit(1596266664.119:41): pid=497 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_securetty,pam_tally2,pam_shells,pam_unix,pam_permit,pam_gnupg acct="name" exe="/usr/bin/login" hostname=username addr=? terminal=tty1 res=success'
> login[497]: pam_gnupg(login:setcred): helper terminated with exit code 1
> audit[497]: USER_START pid=497 uid=0 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_loginuid,pam_keyinit,pam_limits,pam_unix,pam_permit,pam_mail,pam_systemd,pam_env,pam_gnupg acct="name" exe="/usr/bin/login" hostname=username addr=? terminal=tty1 res=success'
> ```
> 
> This probably is a duplicate of [this](https://github.com/cruegge/pam-gnupg/issues/18#issue-651710429)
> A lot of people seem to be facing this problem..
> I think this discussion will be more fruitful if an issue is opened in pam-gnupg repo itself.

Thank you, It can work normally, and now there is no need to enter a password again when starting up.

I need to add  
```
auth     optional  pam_gnupg.so<br/>
session  optional  pam_gnupg.so
```
to the end of the system-local-login file, not the beginning

and `gpg-agent-conf` add
```
allow-preset-passphrase 
default-cache-ttl 34560000
max-cache-ttl 34560000
```

I will close this question
