### ISSUE TITLE
'master Inbox cannot be opened' after restoring system backup

### ISSUE THREAD

**Issue by Ingvix** [LukeSmithxyz/mutt-wizard#502]
I just migrated to an encrypted filesystem and after that `mailsync` has been giving me that error and I haven't been able to sync my mails. I'm not sure what's different as I preserved all ownerships and permissions. I'm not sure though how they should be as I don't have a working account currently. I don't really even know if this is a local problem that it can't acccess some directory or if it's a remote one that it can't access. There's `INBOX` and `Inbox` dirs in `~/.local/share/mail/<account>/` so I'm not even really sure which one it might be complaining about. 

`INBOX` had 700 permissions so I tried changing it to 744 like the other dirs in the account directory but that didn't help it.

Any help would be appreciated.

**Comment by Ingvix** [comment]
One possibility I can also think of that I made the backup on the moment of it was syncing and the inbox is locked but I don't currently know how to remove that lock.

**Comment by Kr1ss-XD** [comment]
Assuming your IMAP server's status is good, and (all) your emails are saved on that server, I'd suggest to backup and delete (or rename) the local mail folder, create an empty folder with the same name and do a fresh sync.

Say your email account name is `account` :
```
mv ~/.local/share/mail/account{,~}
mkdir ~/.local/share/mail/account
mbsync -LC account
```

If the error was just the local mailbox being in an inconsistent state like you consider it possible, you should now have a new working one. In this case, you can safely delete the backup : 
```
rm -r ~/.local/share/mail/account~
```

If not, you'd still have the backup and could restore the previous state and investigate further : 
```
rm -r ~/.local/share/mail/account && mv ~/.local/share/mail/account{~,}
```

**Comment by Ingvix** [comment]
Yeah, I ended up resyncing everything and it's working now. I was just hoping a solution to avoid fetching everything all over again but ended up doing it anyway.
