### ISSUE TITLE
Wrong File Placement of pgpewrap in Debian Buster

### ISSUE THREAD

**Issue by djringjr** [LukeSmithxyz/mutt-wizard#503]
Error when sending mail:
sh: 1: /usr/libexec/neomutt/pgpewrap: not found

I am using Debian Buster.   There is no folder /usr/libexec/neomut/

Instead there is:

/usr/lib/neomutt/pgpewrap

Made symbolic link:
sudo ln -s /usr/lib/neomutt/pgpewrap /usr/libexec/neomutt/pgpewrap

Now it works OK.

Regards,

DR

**Comment by f380cedric** [comment]
Hi,

Sadly, it is not mutt-wizard fault, and it cannot solve it.
That is an issue with the neomutt package on Debian Buster.
It is up to the Debian packager to solve this.

It has already been reported on Debian bugtracker [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964720).
