### ISSUE TITLE
msmtp: could not send mail

### ISSUE THREAD

**Issue by klubinus** [LukeSmithxyz/mutt-wizard#506]
Whenever I try to send message from my personal domain email account from mutt I get an error  

msmtp: could not send mail (account ...)

Error sending message, child exited 74 (I/O error.)

the domain and email service are hosted by Domain.com 

I have another account in mutt that works perfectly and give no problem so I'm thinking it might be the host blocking the connection is there a way to prove that or to prevent that ? I dont want to migrate the service to a vps cause of the fees and I'm afraid me and my family would loose the content of the inboxes

**Comment by f380cedric** [comment]
Seems to be an issue with msmtp, but the error does not tell much.

Look at your msmtp log file (`~/.config/msmtp/msmtp.log`) and try to find out why it is throwing 74.

If your log is too big or does not tell much, you can always do:

```sh
msmtp -v -a account_name oneOfYour@email.address <<EOF
Subject: Test

Test.
EOF
```

The value for `account_name` can be found in your `~/.config/msmtp/config` (in the form `account account_name`).

If you need/want to pass the output here, you need to redact sensitive info (especially the part between `AUTH` and `Authentication {successful, failed}`)
