### ISSUE TITLE
msmtp fails: pinentry-curses not displayed

### ISSUE THREAD

**Issue by mtarunsai1999** [LukeSmithxyz/mutt-wizard#515]
```
gpg: decryption failed: No secret key
msmtp: cannot read output of  'pass mutt-wizard-tarung'
# (error code 78)
```
I recently edited gnupg config to use pinentry-curses instead of pinentry-gtk2. Mutt doesn't show the pinentry-curses window, but the above pass command works from other windows of the terminal emulator and even with passmenu (uses pinentry-curses). 

Is it hardcoded not to use curses window in mw? (I remember entering password into curses window in the past). Can someone please point me where to look?

**Comment by niklassc7** [comment]
Have you checked if pinentry is already running? I once had that problem that some other program or the cronjob would call pinentry in the background and that would block it from being executed. Just killing it in e.g. htop stops that.

**Comment by mtarunsai1999** [comment]
No pinentry is running in the background. As I said, I could use pass command everywhere else. Even mbsync works.

**Comment by f380cedric** [comment]
Have you tried https://github.com/LukeSmithxyz/mutt-wizard/issues/445#issuecomment-635899551?

**Comment by mtarunsai1999** [comment]
@f380cedric  as you suggested in that comment, setting GPG_TTY when calling mutt worked. But I wonder why pass command works in st without doing that. Anyway, thank you very much for the help.
