### ISSUE TITLE
Error with gmail import imported into outlook

### ISSUE THREAD

**Issue by Jonassenher** [LukeSmithxyz/mutt-wizard#517]
Hey Luke,
Really appreaciate your work. This seems like a so much better solution to me with many email accounts on a slow computer than something like Thunderbird.
There seems to be a problem, it has to do with the ability in Outlook Web App to integrate a Gmail account, so than one can send and receive Gmail mails in outlook. That way, Gmail sort of is imported as folders in Outlook.
I used your MW with Outlook, and it seems to be able to log in and import the email and all of that. However, when I write "neomutt" in the terminal to actually read the emails, I get this error message:
```
Unknown Mailbox: /home/jonas/.local/share/mail/privat/jonasf997@gmail.com.Spr&AOU-ktips
Fejl i /home/jonas/.config/mutt/accounts/1-privat.muttrc, linje 24: 
Fejl i /home/jonas/.config/mutt/muttrc, linje 17: source: file /home/jonas/.config/mutt/accounts/1-privat.muttrc could not be sourced
source: Fejl i /home/jonas/.config/mutt/muttrc
Tryk på en tast for at fortsætte ...
Lukker forbindelsen til outlook.office365.com ...
```
English translation:
```
Unknown Mailbox: /home/jonas/.local/share/mail/privat/jonasf997@gmail.com.Spr&AOU-ktips
Error in /home/jonas/.config/mutt/accounts/1-privat.muttrc, line 24: 
Error in /home/jonas/.config/mutt/muttrc, linje 17: source: file /home/jonas/.config/mutt/accounts/1-privat.muttrc could not be sourced
source: Error in /home/jonas/.config/mutt/muttrc
Press a button to continue ...
Closing the connection to outlook.office365.com ...
```
So I'm basically just doing as you asked for on the main page, reporting bugs.

I'll try deleting my gmail from my outlook and see if it works this time.

Again, continue your great work.

Best regards from Norway,
Jonas

**Comment by Jonassenher** [comment]
Now I deleted the Gmail link from Outlook, unfortunately it still doesn't work:
```
Unknown Mailbox: /home/jonas/.local/share/mail/privat/Archive.2018
Fejl i /home/jonas/.config/mutt/accounts/1-privat.muttrc, linje 24: 
Fejl i /home/jonas/.config/mutt/muttrc, linje 3: source: file /home/jonas/.config/mutt/accounts/1-privat.muttrc could not be sourced
source: Fejl i /home/jonas/.config/mutt/muttrc
Tryk på en tast for at fortsætte ...
```
The good thing is thing time I can actually read my email.

I suspect the error maybe coming from the Outook nested folders.

**Comment by Jonassenher** [comment]
`mbsync privat:Archive.2018` returns
```
C: 0/1  B: 0/1  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
Error: canonical mailbox name 'Archive.2018' contains flattened hierarchy delimiter
C: 1/1  B: 1/1  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
```

**Comment by f380cedric** [comment]
> ```
> Fejl i /home/jonas/.config/mutt/accounts/1-privat.muttrc, linje 24: 
> ```

There is something in line 24 in `1-privat.muttrc` that neomutt does not like.
What is written there?

> ```
> C: 0/1  B: 0/1  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
> Error: canonical mailbox name 'Archive.2018' contains flattened hierarchy delimiter
> C: 1/1  B: 1/1  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
> ```

That is because mbsync is configured with `Flatten .`,
meaning `folder/subfolder` in remote IMAP will be written locally as `folder.subfolder`.

Of course, it is not compatible with folder name that includes '.' in it.
3 options here:
 1. Rename IMAP folders to not include '.'.
 2. Remove `Flatten .` in mbsync config file (it will default to '/').
 3. Change the delimiter from '.' to another one that is not used in folder name (eg '_'),
 you will also need to `set sidebar_delim_chars='chosen_delimiter' in you muttrc.

In either cases, you will have to fix mailbox names in your muttrc.
