### ISSUE TITLE
'...is not a mailbox error'

### ISSUE THREAD

**Issue by guyfedwards** [LukeSmithxyz/mutt-wizard#52]
Getting '/home/guy/.mail/main/main is not a mailbox' error when trying to open synced mailbox.

Based on similar issue #41 , cmd outputs are as follows:

`$ ls ~/.mail/daxmoe`
```
'Flat 15'      '[Gmail].Drafts'     '[Gmail].Sent Mail'  '[Gmail].Starred'   Health   Personal      Receipts   Work
'[Gmail].Bin'  '[Gmail].Important'  '[Gmail].Spam'        Greenwich          INBOX   'Read Later'   Travel
```

`$ cat ~/.config/mutt/accounts/daxmoe.muttrc`
```
# vim: filetype=neomuttrc
# muttrc file for account main
set realname = "Guy Edwards"
set from = "guyfedwards@gmail.com"
set smtp_url = "smtp://guyfedwards@gmail.com@smtp.gmail.com:587/"
set sendmail = "/usr/bin/msmtp -a main"
set folder = "~/.mail/main"
set header_cache = ~/.config/mutt/accounts/main/cache/headers
set message_cachedir = ~/.config/mutt/accounts/main/cache/bodies
set certificate_file = ~/.config/mutt/accounts/main/certificates
source "~/.config/mutt/credentials/getmuttpass main |"

set mbox_type = Maildir
set ssl_starttls = yes
set ssl_force_tls = yes

bind index,pager gg noop
bind index,pager g noop
bind index gg first-entry
unmailboxes *
mailboxes =main =-------------------
set spoolfile = ""
set record = ""
set postponed = ""
```

`$ offlineimap -a main --info`
```
Folderlist:
 [Gmail]/All Mail (disabled)
 [Gmail]/Bin
 [Gmail]/Drafts
 [Gmail]/Important
 [Gmail]/Sent Mail
 [Gmail]/Spam
 [Gmail]/Starred
 INBOX
 Personal
 Read Later
 Receipts
 Travel
 Work

Local repository 'main-local': type 'Maildir'                                                                                                                                                   
Folderlist:                                                                                                                                                                                     
 Read Later
 [Gmail].Sent Mail
 Receipts
 [Gmail].Important
 [Gmail].Bin
 Travel
 Personal
 INBOX
 [Gmail].Starred
 [Gmail].Drafts
 Work
 [Gmail].Spam
```

No errors when running `offlineimap -a main`.

Any help would be greatly appreciated and thanks for creating mutt-wizard!

**Comment by guyfedwards** [comment]
Worked a treat, thanks @dax0

**Comment by runekaagaard** [comment]
Had same error and fix.

**Comment by francisdraco** [comment]
Hello guys, as you will understand from my question, I am a complete newbie.
How do I re-detect mailboxes? When I type the command "Redetect Mailboxes" in neomutt it tells me that redetect is an unknown command.

I appreciate your help very much !

**Comment by cdutsov** [comment]
> Hello guys, as you will understand from my question, I am a complete newbie.
> How do I re-detect mailboxes? When I type the command "Redetect Mailboxes" in neomutt it tells me that redetect is an unknown command.
> 
> I appreciate your help very much !

You can find the Redetect Mailboxes option in Luke's mutt-wizard.sh

**Comment by jlamoure** [comment]
> You can find the Redetect Mailboxes option in Luke's mutt-wizard.sh
Is this option still a thing now that mutt-wizard.sh has turned from script to system application? I'm having this issue (with infomaniak.com, not Gmail).
