### ISSUE TITLE
Move config files to .conf and passwords to .local

### ISSUE THREAD

**Issue by jcrcx** [LukeSmithxyz/mutt-wizard#527]
Hi there, 

I want to move `.mbsyncrc` and `.notmuch-config` to `$HOME/.conf` directory. But I don't know how. I've been modifying the `/bin/mw` script  to do so, but I still getting the error of `no such file or directory`.  May be it's me but it bothers me having those files in my home directory.

Also I want to change the `.password_store` to `.local/password_store/`

Thanks in advance

**Comment by Kr1ss-XD** [comment]
`notmuch` looks for an environment variable `$NOTMUCH_CONFIG`, as described in the manual (`notmuch(1)`). You can point this variable to your config file's path.

Similarly, you might set `$PASSWORD_STORE_DIR` to change the location of your pass data folder (see `pass(1)`)

As for `mbsync`, I'm not aware of any similar mechanism, **but** the mutt-wizard checks for `$MBSYNCRC`.

To apply a global solution however (i.e. one that works outside of `mw`/`neomutt`, you could consider to create an executable file with the name `mbsync` containing
```sh
#!/bin/sh
exec /usr/bin/mbsync -c ${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/mbsyncrc
```
and save it to a location in your `$PATH` that has priority above `/usr/bin` - e.g. `/usr/local/bin/mbsync` or `~/.local/bin/mbsync`.

**Comment by jcrcx** [comment]
> `notmuch` looks for an environment variable `$NOTMUCH_CONFIG`, as described in the manual (`notmuch(1)`). You can point this variable to your config file's path.
> 
> Similarly, you might set `$PASSWORD_STORE_DIR` to change the location of your pass data folder (see `pass(1)`)

This works! Thanks a lot :) Only the executable `mbsync` isn't working but there is no problem with one extra file on the home directory.

I'm closing this
