### ISSUE TITLE
A/I cannot save the sent mail to sent folders 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/mutt-wizard#528]
i have sent an test email to my self and then i cannot see the copy on sent mails .. 
how can we fix it that ?

**Comment by Kr1ss-XD** [comment]
You might want to have a look at the neomuttrc [manual](https://neomutt.org/man/neomuttrc). The relevant options should be `copy` and/or `record`.

How they need to be set depends on the behavior/configuration of your email provider. Just try out different settings; I suppose setting `copy` to `yes` and/or pointing `record` to your "sent" folder _should_ do the trick.
