### ISSUE TITLE
Cannot paste passwords from KeePassXC

### ISSUE THREAD

**Issue by un10able** [LukeSmithxyz/mutt-wizard#533]
This isn't really much of an issue with mutt-wizard itself, but is there any workaround to this? I use KeePassXC for all of my accounts and my passwords are too long to type in the terminal. I think pasting is pretty much not even an option in mw.

**Comment by Kr1ss-XD** [comment]
If your terminal emulator supports pasting, it should work in (neo)mutt, too.
