### ISSUE TITLE
Sync all vs cron job

### ISSUE THREAD

**Issue by se7en-x230** [LukeSmithxyz/mutt-wizard#535]
I have a very strange problem.
I have the exact same setup on desktop vs laptop.
Desktop has the cron - enable or disable an autosync via cronjob
Laptop doesn't but hast sync all in the menu 
Which is in itself not a big problem i just copied the crontab line to the cron on the laptop. */5 * * * * /usr/local/bin/mailsync >/dev/null 2>&1

BUT pacman -Ss mailsync is not installed on the laptop NOR on the Desktop. 
whereis mailsync shows /usr/local/bin/mailsync  on the desktop even so pacman doesn't show it intsalled ...
whereis mailsync on the laptop doesnt show anything ???

**Comment by Kr1ss-XD** [comment]
`mailsync` used to be part of `mutt-wizard` but has been removed on 07/09/2020, as well as implementation of the cron job.

You can sync your IMAP boxes with `mbsync`, which is a dependency of `mutt-wizard`.

**Comment by se7en-x230** [comment]
Thanks for the reply
