### ISSUE TITLE
mutt-wizard with -Y argument kicks me out from session

### ISSUE THREAD

**Issue by Dark-Matter7232** [LukeSmithxyz/mutt-wizard#540]
using mw with -Y argument kicks me out from dwm session

**Comment by LukeSmithxyz** [comment]
Does `-y my@email.com` work as intended? What is your `$STATUSBAR` variable set to?

**Comment by Dark-Matter7232** [comment]
both command do not work and the environment variable is set to dwmbar

**Comment by LukeSmithxyz** [comment]
Is dwmbar a script or what? Whatever it is it can't handle the kill signal. It's supposed to be used with dwmblocks or i3blocks to update the statusbar icon, but it looks like it's killing your process.

**Comment by Dark-Matter7232** [comment]
it was a mistake from my side, i changed the variable
