### ISSUE TITLE
Newest update breaks everything.

### ISSUE THREAD

**Issue by g-w1** [LukeSmithxyz/mutt-wizard#542]
Hi. I am on archlinux and the newest aur update to mutt-wizard-git broke it. Now whenever I run mutt-wizard with anything (mw sync, mw, mw add) nothing happens. I am pretty sure this originated in the argument parsing commands. maybe getopts.

Are you experiencing this too?

Thanks

**Comment by LukeSmithxyz** [comment]
Read the manual which has changed.
