### ISSUE TITLE
maildir and cachedir options - could be moved to config file?

### ISSUE THREAD

**Issue by pochua** [LukeSmithxyz/mutt-wizard#544]
Hi,
maildir and cachedir paths are hardcoded in main script mw, which makes it difficult to maintain if you want to have different storage place for your e-mails.
I keep my emails on encrypted volume, so need to edit main mutt-wizard program file after every update. 
Would you consider changing it?
thx

**Comment by LukeSmithxyz** [comment]
They already use XDG variables which you can change external to the script.

Even if you need to store the mail/cache somewhere different than the XDG locations, they default places are already out of your home, so there's really nothing keeping you from just linking `~/.local/share/mail` to the directory you really want to keep them in.

If I add in some extra `if` logic for these variables it sort of opens the Pandora's box of doing it for everything else. Most of the exceptions included in the script already to get XDG locations I'm not even a big fan of.

**Comment by pochua** [comment]
Ok, thank you very much for your answer and great work. Did not think about linking as easy workaround.
