### ISSUE TITLE
Mailbox names in sidebar are empty

### ISSUE THREAD

**Issue by AvianY** [LukeSmithxyz/mutt-wizard#548]
There are lines that can be selected and it works properly, but the names just aren't there. The number of emails are visible though.

**Comment by lukezifer** [comment]
I also came across this issue. It seems there was a change in the configuration in neomutt as discussed here: 
https://github.com/neomutt/neomutt/issues/2593
In the muttrc for the muttwizard, in `set sidebar_format`, the `%B` needs to be changed to `%D`. That did the trick for me.

**Comment by LukeSmithxyz** [comment]
Yeah, this should've been solved in c08cfd53. Update to the newest version of mutt-wizard.

**Comment by AvianY** [comment]
Actually, it's very interesting. For me, it works with %B and it doesn't work with %D.
I am using debian and the version it provides is 20180716, so that is probably the reason why.

Perhaps mutt-wizard should be detecting neomutt version and set the variable accordingly.
