### ISSUE TITLE
Mbsync -a via cron failing

### ISSUE THREAD

**Issue by tzurita** [LukeSmithxyz/mutt-wizard#551]
used to be able to do this with the mailsync script. Only thing that had to be done was to set GNUPGHOME first and it worked.  Anything missing here?

➜ crontab -l
*/5 * * * * export GNUPGHOME="/home/zuritat/.local/share/gnupg" ; sleep 5s && /usr/bin/mbsync -a

journalctl output.
Oct 19 10:01:01 borg-x1.dsolutions.com CROND[740253]: (root) CMD (run-parts /etc/cron.hourly)
Oct 19 10:05:01 borg-x1.dsolutions.com crond[740881]: pam_unix(crond:session): session opened for user zuritat(uid=1000) by (uid=0)
Oct 19 10:05:01 borg-x1.dsolutions.com CROND[740882]: (zuritat) CMD (export GNUPGHOME="/home/zuritat/.local/share/gnupg" ; sleep 5s && /usr/bin/mbsyn>
Oct 19 10:05:06 borg-x1.dsolutions.com CROND[740881]: (zuritat) CMDOUT (Error: mutt-wizard-dsolutions is not in the password store.)
Oct 19 10:05:06 borg-x1.dsolutions.com CROND[740881]: (zuritat) CMDOUT (Skipping account dsolutions-remote, password command exited with status 1)

**Comment by f380cedric** [comment]
Where is your password store stored?
If `PASSWORD_STORE_DIR` is empty or not set, pass will search in `$HOME/.password_store`.
I suspect your password store is somewhere else.
You will have to set `PASSWORD_STORE_DIR` accordingly in your cron.

**Comment by tzurita** [comment]
Thx, I fixed it by installing and configuring pam-gnupg

**Comment by f380cedric** [comment]
If the issue is fixed, could you close the ticket?

**Comment by tzurita** [comment]
Thanks all for helping
