### ISSUE TITLE
Shouldn't a misconfigured account lead to an error code?

### ISSUE THREAD

**Issue by inktrap** [LukeSmithxyz/mutt-wizard#556]
I was just surprised by this

```
	add) askinfo && getprofiles && writeinfo && getboxes && finalize || delete ;;
```

This leads to an error message, but the delete works and it is not mutt-wizards fault, it exits with 0.
Ideally we could capture the return value of the error, but all the functions are returning 1 during an error, so we could write:

```
	add) askinfo && getprofiles && writeinfo && getboxes && finalize || delete && exit 1 ;;
```

That would indicate to the user that something didn't work as intended and would also stop a script, if ``set -e`` is active.

**Comment by LukeSmithxyz** [comment]
Yeah I suppose I should put that in.

Since `mw` was originally a merely interactive script I guess I never felt the need for it, but I guess now that you can run it without interaction I'll add it.

**Comment by inktrap** [comment]
Thas was fast!
Nice! Thanks!

**Comment by inktrap** [comment]
Ah … I just realized that it should be more like

```
	add) askinfo && getprofiles && writeinfo && getboxes && finalize || (delete && exit 1) ;;
```

see #557 and line 5.
