### ISSUE TITLE
Mail not syncing as cronjob

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/mutt-wizard#560]
I set up mailboxes to automatically sync with cronie, yet it gives me the following error.
```
Oct 29 11:37:01 firstpad CROND[19264]: (lukerb52) CMD (/usr/bin/mw -Y)
Oct 29 11:37:01 firstpad CROND[19261]: (lukerb52) CMDOUT (`pass` must be installed and initialized to encrypt passwords.)
Oct 29 11:37:01 firstpad CROND[19261]: (lukerb52) CMDOUT (Be sure it is installed and run `pass init <yourgpgemail>`.)
Oct 29 11:37:01 firstpad CROND[19261]: (lukerb52) CMDOUT (If you don't have a GPG public private key pair, run `gpg --full-gen-key` first.)
```
Running `mw -Y` in the terminal works fine.

**Comment by f380cedric** [comment]
Could it be because you have `PASSWORD_STORE_DIR` set in your environment and cronie does not inherit it?

**Comment by lukerb52** [comment]
> Could it be because you have `PASSWORD_STORE_DIR` set in your environment and cronie does not inherit it?

Yes, that appeared to be the problem. I've fixed it by adding `. $HOME/.profile;`, so now my crontab line to update my mail every minute reads:

```
* * * * * . $HOME/.profile; /usr/bin/mw -Y
```

Make sure to use cronie as the user with the mail, not root (ie, run `crontab -e` not `sudo crontab -e`)
