### ISSUE TITLE
config moving files to .config

### ISSUE THREAD

**Issue by alembiq** [LukeSmithxyz/mutt-wizard#564]
shouldn't all the config files be in the $HOME/.config? 
i mean things like  .msmtprc (sure it's a symlink to .config, but why?), .password-store, .urlview etc

you've yourself advocated for empty $HOME :)  https://www.youtube.com/watch?v=yy8RoDSdhIQ

**Comment by LukeSmithxyz** [comment]
Talk to the developers of those programs. I'm not going to hardcode alternate locations not built into the programs.
