### ISSUE TITLE
Running the sudo make install wont work [macOS]

### ISSUE THREAD

**Issue by KoreyMoffett** [LukeSmithxyz/mutt-wizard#568]
﻿Below is the output when i run sudo make install

mkdir -p /usr/local/bin
for script in bin/*; do \
		cp -f $script /usr/local/bin/; \
		chmod 755 /usr/local/$script; \
	done
mkdir -p /usr/local/share/mutt-wizard
chmod 755 /usr/local/share/mutt-wizard
for shared in share/*; do \
		cp -f $shared /usr/local/share/mutt-wizard; \
		chmod 644 /usr/local/share/mutt-wizard/$(basename $shared); \
	done
mkdir -p /usr/local/share/man/man1
cp -f mw.1 /usr/local/share/man/man1/mw.1
chmod 644 /usr/local/share/man/man1/mw.1
if [ "/usr/local" ]; then \
		sed -iba 's:/usr/local:/usr/local:' /usr/local/share/mutt-wizard/mutt-wizard.muttrc; \
		rm -f /usr/local/share/mutt-wizard/mutt-wizard.muttrcba; \
		sed -iba 's:/usr/local:/usr/local:' /usr/local/bin/mw; \
		rm -f /usr/local/bin/mwba; \
		sed -iba 's:/usr/local:/usr/local:' /usr/local/share/man/man1/mw.1; \
		rm -f /usr/local/share/man/man1/mw.1ba; \
	fi

**Comment by KoreyMoffett** [comment]
I thought i fixed but i assumed to quickly

**Comment by LukeSmithxyz** [comment]
Well... what's broken?

**Comment by KoreyMoffett** [comment]
I'm sure honestly
