### ISSUE TITLE
Log-on not successful.

### ISSUE THREAD

**Issue by fesnavarro** [LukeSmithxyz/mutt-wizard#586]
I'm using Ubuntu 20.04.
These are my steps:

---
mw -a myemail@yahoo.com -x "password"

[master 0f38250] Add given password for mw-myemail@yahoo.com to store.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 mw-myemail@yahoo.com.gpg

Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.
---

It doesn't create any new register on pass,  any guess why?

**Comment by LukeSmithxyz** [comment]
If your password has special characters that have a special interpretation on your shell, you might want to escape them. For example, `!` might need to be `\!` on zsh, etc.

**Comment by fesnavarro** [comment]
Now, it worked like a charm. Thanks Luke !

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by fesnavarro** [comment]
Using \ solved
