### ISSUE TITLE
Aborted unmodified message

### ISSUE THREAD

**Issue by fesnavarro** [LukeSmithxyz/mutt-wizard#589]
Steps
m
to: blabla@there.com
subject: whatever

Aborted unmodified message

Is that something about the Editor?

**Comment by Kr1ss-XD** [comment]
This notice should appear when you opened the editor to compose a message but then close it without changing anything (<=> don't actually type any message).

You also see it if the `$editor` option is set to a command that cannot be found or executed.

- What does `:set editor?` yield ?
- If that is an actual editor, is that installed on your system ?
- If so, is the command's syntax correct ?

**Comment by fesnavarro** [comment]
> This notice should appear when you opened the editor to compose a message but then close it without changing anything (<=> don't actually type any message).
> 
> You also see it if the `$editor` option is set to a command that cannot be found or executed.
> 
> * What does `:set editor?` yield ?
> * If that is an actual editor, is that installed on your system ?
> * If so, is the command's syntax correct ?

It says editor="vim"
I changed it to the full path and now it works great!. Thank you

**Comment by Goth** [comment]
I have the same issue, where do you change the editor? 
`:set editor? vi`
