### ISSUE TITLE
MW does nothing at all

### ISSUE THREAD

**Issue by chnoack** [LukeSmithxyz/mutt-wizard#592]
Hi,
today I was keen on trying you mutt-wizzard. I've installed all dependencies and the mutt-wizzard itself. When start it, nothing happens. It return immediately without any output at all.

I'm on PopOS/Ubuntu 20.4 LTS in a zsh. You'll find the strace output here: [strace mw](http://gofile.me/3oLq0/cq0uSCjfg)

Any help appriciated.

Best regards from Dortmund, Germany

Christian

**Comment by LukeSmithxyz** [comment]
Read the manual.

**Comment by chnoack** [comment]
Sorry, I followed the instructions in your video. Obviously there have been some changes.

**Comment by LukeSmithxyz** [comment]
Yes. The script uses command line options now which make it scriptable. I suppose I should do an update video soon for other people confused.
