### ISSUE TITLE
Removing and re-adding an account does not work

### ISSUE THREAD

**Issue by chnoack** [LukeSmithxyz/mutt-wizard#593]
Adding an e-mail account the first time works fine (mw -a ...). When I remove the account (mw -d ...) I cannot add the same address again:

_Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard_

I tried this several times with different accounts.

**Comment by LukeSmithxyz** [comment]
Hmm. I suppose it could be possible that your mbsyncrc file underwent
some change that made it hard for the awk command to properly parse it.

Could you check or post your `~/.mbsyncrc`? If you want to delete and
readd all accounts, you can probably just delete the file.
