### ISSUE TITLE
Does this tool support setting up oauth credentials?

### ISSUE THREAD

**Issue by jackmac92** [LukeSmithxyz/mutt-wizard#594]
https://github.com/LukeSmithxyz/mutt-wizard/blob/59322fb546479f51045752e74c966b96d847cb81/share/mutt-wizard.muttrc#L11

I see oauth setups mentioned in a few issue comments, is that something you need to configure manually? I'm looking to have some accounts setup via regular pw/app password and at least one oauth account. Just curious if I'm overlooking something in the wizard that could help me with that, thanks!

**Comment by SentToDevNull** [comment]
If I remember correctly, `mutt` had just added xoauth last August, but `neomutt` (which this script is based on) doesn't yet have support for it.

The solution that I ended up using was `davmail` as an intermediary between `neomutt` and an Exchange server using oauth.

**Comment by f380cedric** [comment]
IMO, all 3 (`neomutt`, `msmtp` and `mbsync`) "support" oauth (the ones specified [here](http://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml)), but they do not handle getting or refreshing the token. You'll have to glue them with externals scripts as explained [here](https://github.com/neomutt/neomutt/issues/1362#issuecomment-776175034) and [there](https://neomutt.org/guide/optionalfeatures.html#6-%C2%A0oauthbearer-support).
