### ISSUE TITLE
Hotkeys for sent mailbox in gmail account wrong

### ISSUE THREAD

**Issue by nabakolu** [LukeSmithxyz/mutt-wizard#595]
I set up a gmail account and switching to the Sent mailbox with gs does not work.
In user@gmail.com.muttrc `macro index,pager gs "<change-folder>=[Gmail].Sent<enter>" "go to sent" # mw-autogenerated` 
is set instead of `macro index,pager gs "<change-folder>=[Gmail].Sent Mail<enter>" "go to sent"`
The same is true for the move and copy hotkeys

**Comment by LukeSmithxyz** [comment]
This should be fixed in a recent commit. Update and run it again.
