### ISSUE TITLE
No secret key

### ISSUE THREAD

**Issue by ZhangTianrong** [LukeSmithxyz/mutt-wizard#597]
When I execute `mw -y [EMAILADDR]` I get the response
```
gpg: decryption failed: No secret key
Skipping account [EMAILADDR]-remote, password command exited with status 2
```
I have to manually access the password through ` pass mw-[EMAILADDR]` once in a while. Is there a way to allow `mbsync` to bypass the password or prompt me for it?

I have referred to [this closed issue](https://github.com/LukeSmithxyz/mutt-wizard/issues/232#issue-452224070) but I am running without display, so I specified `pinentry-curses` or `pinentry-tty` instead of `pinentry-gtk2`. However it doesn't fix the problem and I am still not prompt to enter the key.

**Comment by LukeSmithxyz** [comment]
Well, setting up pam-gnupg would sidestep this problem. I honestly am not so sure about how to consistently unlock your key without the display.

If someone has a robust way of doing it, I will either add it to the README or build it into the script.

**Comment by ZhangTianrong** [comment]
> Well, setting up pam-gnupg would sidestep this problem. I honestly am not so sure about how to consistently unlock your key without the display.
> 
> If someone has a robust way of doing it, I will either add it to the README or build it into the script.

Thank you for the reply. I know this is not an issue with mutt-wizard. I will try the walkaround you mentioned.
