### ISSUE TITLE
Credentials not stored correctly or not asked at all

### ISSUE THREAD

**Issue by scattenlaeufer** [LukeSmithxyz/mutt-wizard#6]
I just tried to create an account using mutt-wizard and encountered some problems with my imap and smtp credentials:

First of all there seems to be noway to enter an user name for a mail account. Instead in `.offlineimaprc` the email adress is set as `remoteuser`, which won't work for any of my mail accounts. The smtp url gets created as `smtp://$from@:$smtp_port` (`$from` and `$smtp_port` are entered as the string values, not as variables. I just added them this way to make it more readable) and not as `smtp://$smtp_user:$smtp_pass@$smtp_url:$smtp_port`. Changing those settings the correct values manually made everything, so the rest seems to work as expected.

**Comment by LukeSmithxyz** [comment]
What distro are you using? What email domain were you trying to configure?
What do you mean by "username"? The script should prompt you for an email account. Did it not do that?

It seems like either have an unexpected variety of `sed` on your computer or you inputting the right things at the wrong prompts.

**Comment by scattenlaeufer** [comment]
I use Arch and I tried it with my university mail server once adding the
urls via your script and once by adding them to `domains.csv`. The later
attempt at least added the smtp url to the config file, but I still had
no way to add a user name for login.

All mail accounts I use have a separate user name to log into the
account and also to connect to the imap and smtp server. Using the mail
address as login does not work.

**Comment by LukeSmithxyz** [comment]
Ah. I see what you mean, okay. I hadn't implemented accounts with separate user/pass logins, or at least, the setup now will assume you need only an email and pass, but I suppose it will only take a few changes to make that work. I'll keep this issue open until that's done.
