### ISSUE TITLE
Office 365, Davmail, and the loss of university IMAP

### ISSUE THREAD

**Issue by ThSGM** [LukeSmithxyz/mutt-wizard#601]
@LukeSmithxyz many thanks for designing such a useful program. 

I'm not sure what the situation is where you are in the US, but here in the UK, we're facing an issue where departments are losing their departmental ITs, to be replaced by centralised IT. Consequently, a lot of universities have converted to Office 365, and have disabled IMAP. Most of us have given up in using programs like Mutt to control our emails. However, as I understand it, there is some hope in using Davmail [refs 1-5].

I managed to get incoming mail working with Davmail on a manual mutt/mbsync install following the references, but I struggled to get outgoing SMTP working. Moreover, it's unclear how it would work with mutt-wizard because your mbsync configurations are baked into `mw'. 

Is there any opportunity for you to look into how mutt-wizard can be setup with Office365 Exchange Protocols? With Microsoft basically taking over the university IT landscape here in the UK, this is probably quite important for a lot of people who are still willing to put up the good fight.

Refs:
[1] http://ri.itservices.manchester.ac.uk/~simonh/
[2] https://rjcb.wordpress.com/2016/12/09/davmail-and-o365/
[3] http://homepages.warwick.ac.uk/staff/Mike.Willis/o365/mutt.html
[4] https://jonathanh.co.uk/blog/exchange-mutt.html
[5][ Universities disabling IMAP in favour of Office365 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1645775)

**Comment by LukeSmithxyz** [comment]
I haven't really looked into Davmail, but this all sure looks like an
annoyance, but not too different from the Protonmail Bridge annoyance
that is already hardcoded into mutt-wizard as an option.

So it's doable, I would just have to understand exactly what's going on.
Obviously I can't easily test this because I don't have Davmail or an
account to use it with, but if you or someone else gets a working
configuration for sending and receiving, you can post it here and I can
go from there.

**Comment by LukeSmithxyz** [comment]
Actually, I'm looking at some of those links, and it looks like the Davmail default settings are basically the same as the Protonmail settings. It might sound crazy, but you *might* be able to just add your account with the `-p` option and it might work.

Or you could run it with `-p` and `-f` if it fails to force it and try to work from there.

**Comment by ThSGM** [comment]
I gave it a shot with using the -p tag and then using 127.0.0.1 and 127.0.0.1 with Davmail activated. However, it was nogo and indicated an unsuccessful log-on attempt. 

Here is the Davmail configuration I had. I could not get EWS to work. Using O365Modern seemed to work. 

![Screenshot from 2020-12-21 21-57-13](https://user-images.githubusercontent.com/3396578/102826497-abd82c00-43d8-11eb-9cf7-a6fabaf6fdb0.png)


Here was the configuration I had for the IMAP which seemed to work with Davmail activated. 

```
IMAPAccount work
# Address to connect to
Host 127.0.0.1
Port 1143
User myusername@myuni.ac.uk
#PassCmd "pass work/email"
Pass mypassword
SSLType None
AuthMechs LOGIN

IMAPStore work-remote
Account work

MaildirStore work-local
# Copy folder hierarchy
Subfolders Verbatim
# The trailing "/" is important
Path ~/.mail/work/
Inbox ~/.mail/work/inbox

Channel work
Master :work-remote:
Slave :work-local:
# Include everything
Patterns *
# Automatically create missing mailboxes, both locally and on the server
Create Both
# Save the synchronization state files in the relevant directory
SyncState *
Remove Slave            # Propagate mailbox deletions
MaxMessages 100
```
MBsync then successfully pulled things to my computer. 

The SMTP in muttrc I tried to use was this: 

```
set smtp_url="smtp://myusername@myuni.ac.uk@127.0.0.1:1025"
set smtp_authenticators = "login"
set ssl_starttls = yes 
set ssl_force_tls = no          # Gives 500 unrecognised command with yes 
```
which did not work. 

To be honest, I did not know what I was doing in large parts of the above. 

In regards to your ability to test---I have heard that some people can create an Exchange account and email and test there, but obviously it might not duplicate the same server conditions that other universities have set up.

**Comment by LukeSmithxyz** [comment]
If you try to send mail, what error do you get? Can you try sending mail directly on the command line with `msmtp` if you know how?

**Comment by ThSGM** [comment]
This will be about the mail collection issues. 

I gave it a shot with using the -p tag. It logged in successfully and seemed to setup the account. However upon running `mw -y myid@myuni.ac.uk` It did not seem to pull the mail correctly. The folders were correctly setup in `.local/mail/myid@myuni.co.uk` according tothe maildir scheme. However no emails were pulled and I obtained this relevant output information after running the mw -y command:

```
C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
C: 1/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
Found 0 total files (that's not much mail)
No new mail
```

The davmail log seems to give normal results that indicate a successful connection but I am not sure what I am looking for. 

Here is the Davmail configuration I had and used for the above. I could not get EWS to work. Using O365Modern seemed to work. 

![Screenshot from 2020-12-21 21-57-13](https://user-images.githubusercontent.com/3396578/102829094-3bcca480-43de-11eb-8ffa-eb3ccd8b40ff.png)

**Comment by ThSGM** [comment]
Here was the configuration I had for the IMAP which seemed to work with Davmail activated. 

```
IMAPAccount work
# Address to connect to
Host 127.0.0.1
Port 1143
User myusername@myuni.ac.uk
#PassCmd "pass work/email"
Pass mypassword
SSLType None
AuthMechs LOGIN

IMAPStore work-remote
Account work

MaildirStore work-local
# Copy folder hierarchy
Subfolders Verbatim
# The trailing "/" is important
Path ~/.mail/work/
Inbox ~/.mail/work/inbox

Channel work
Master :work-remote:
Slave :work-local:
# Include everything
Patterns *
# Automatically create missing mailboxes, both locally and on the server
Create Both
# Save the synchronization state files in the relevant directory
SyncState *
Remove Slave            # Propagate mailbox deletions
MaxMessages 100
```
MBsync then successfully pulled things to my computer. 

The SMTP in muttrc I tried to use was this: 

```
set smtp_url="smtp://myusername@myuni.ac.uk@127.0.0.1:1025"
set smtp_authenticators = "login"
set ssl_starttls = yes 
set ssl_force_tls = no          # Gives 500 unrecognised command with yes 
```
which did not work. 

To be honest, I did not know what I was doing in large parts of the above. 

In regards to your ability to test---I have heard that some people can create an Exchange account and email and test there, but obviously it might not duplicate the same server conditions that other universities have set up. 


> If you try to send mail, what error do you get? Can you try sending mail directly on the command line with `msmtp` if you know how?

I need to read up on this and give it a shot.

**Comment by nicewaffles** [comment]
I was able to get IMAP working through davmail fairly easily, just run it and make sure you have the right ports in mw. For SMTP, I just connect to smtp.office.com with port 587. Never could get sending to work through davmail. My place only shut off IMAP while leaving SMTP up, may differ for others though. Also, davmail does poorly with a huge amount of email, so if you try to download thousands at once it will probably crash (this may be out-of-memory problems on my end though).

**Comment by ThSGM** [comment]
> I was able to get IMAP working through davmail fairly easily, just run it and make sure you have the right ports in mw. For SMTP, I just connect to smtp.office.com with port 587. Never could get sending to work through davmail. My place only shut off IMAP while leaving SMTP up, may differ for others though. Also, davmail does poorly with a huge amount of email, so if you try to download thousands at once it will probably crash (this may be out-of-memory problems on my end though).

@nicewaffles can you let me know the details of your DavMail setup? 

I tried again to set it up with 

`mw -a myuser@myuni.ac.uk`

and the following config 
![Screenshot from 2021-01-02 09-40-29](https://user-images.githubusercontent.com/3396578/103454736-cff01300-4cde-11eb-8033-35354fd6ddbf.png)

but it fails with a 'log-on not successful'. I get the following log. 

![Screenshot from 2021-01-02 09-40-18](https://user-images.githubusercontent.com/3396578/103454741-e1391f80-4cde-11eb-999d-30f7613d13f0.png)

I remember the first time I used DavMail, my browser opened to a university authentication page. Is there a way we can reset this somehow? (ie. should I be deleted some cache files?)

**Comment by nicewaffles** [comment]
@ThSGM 
I run DavMail in server mode, I didn't use the GUI version. Here are the relevant davmail.properties lines:

`davmail.server=true`
`davmail.mode=EWS`
`davmail.url=https://outlook.office365.com/EWS/Exchange.asmx`
`davmail.imapPort=1143`

I also set up SSL, but that's probably unnecessary if you're running it on the machine you're trying to receive mail on. Also of note is that I had to set up and use an ''app password'' or whatever to log in, instead of using my regular password.

**Comment by LukeSmithxyz** [comment]
You know, it might work facing the local SMTP Davmail system if you add `tls off` to the profile's block in `~/.config/msmtp/config`.

**Comment by ThSGM** [comment]
> @ThSGM
> I run DavMail in server mode, I didn't use the GUI version. Here are the relevant davmail.properties lines:
> 
> `davmail.server=true`
> `davmail.mode=EWS`
> `davmail.url=https://outlook.office365.com/EWS/Exchange.asmx`
> `davmail.imapPort=1143`
> 
> I also set up SSL, but that's probably unnecessary if you're running it on the machine you're trying to receive mail on. Also of note is that I had to set up and use an ''app password'' or whatever to log in, instead of using my regular password.

@nicewaffles Can you possibly walk me through the steps of creating an app password? I do not think this is possible for our university's Office365 setup, but because of the myriad of variations of Office365, I just want to make sure. If you can provide a screenshot of the relevant page, this would be the most useful. 

I managed to get MBSync and Davmail working again with a fairly minimal configuration file so I'll document that here firstly. Then @LukeSmithxyz I'm hoping to get back to the issue of why mutt-wizard doesn't seem to play nice. 

**Davmail setup**

First, I set up the following `davmail.properties` file. 

```
# https://jonathanh.co.uk/blog/mutt-setup.html
# Don't allow remote connections
davmail.allowRemote=false

# Don't require client to use ssl when connecting
davmail.ssl.nosecurecaldav=false
davmail.ssl.nosecureimap=false
davmail.ssl.nosecureldap=false
davmail.ssl.nosecuresmtp=false

# Ports to listen on
davmail.caldavPort=1080
davmail.imapPort=1143
davmail.ldapPort=1389
davmail.smtpPort=1025

# Exchange details
davmail.mode=EWS
#davmail.defaultDomain=
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx

# Don't start GUI
davmail.server=true
# Delete messages immediately on IMAP STORE \Deleted flag
davmail.imapAutoExpunge=true
# When a message is sent, put it in the sent folder
davmail.smtpSaveInSent=false
# Send keepalive character during large folder and messages download
davmail.enableKeepAlive=true
```
I then start the server via: 

`davmail ~/.config/davmal.properties`

where you replace the above address with where the file is located. 

For some reason it worked with EWS here. I thought previously I had to use Office365Modern. 

**MBSync setup**

Then I created an MBSync configuration file as follows: 

```
IMAPAccount work
# Address to connect to
Host 127.0.0.1
Port 1143
User myuser@myuniversity.ac.uk
Pass mypassword
SSLType None
AuthMechs LOGIN

IMAPStore work-remote
Account work

MaildirStore work-local
# Copy folder hierarchy
Subfolders Verbatim
# The trailing "/" is important
Path ~/.mail/work/
Inbox ~/.mail/work/inbox

Channel work
Master :work-remote:
Slave :work-local:
# Include everything
Patterns *
# Automatically create missing mailboxes, both locally and on the server
Create Both
# Save the synchronization state files in the relevant directory
SyncState *
Remove Slave            # Propagate mailbox deletions
MaxMessages 100
```
I then created the `work` folder within` ~/.mail`

Finally I called via: 

`mbsync -c ~/.testmbsync work`

where `.testmbsync` is the configuration file.

**Comment by nicewaffles** [comment]
Here's how I got the app password:
- log in to Outlook with the account in question
- click on round account icon in upper right
- click View Account
- click Security Info
- click Add Method -> App Password

> @nicewaffles Can you possibly walk me through the steps of creating an app password? I do not think this is possible for our university's Office365 setup, but because of the myriad of variations of Office365, I just want to make sure. If you can provide a screenshot of the relevant page, this would be the most useful.

**Comment by LukeSmithxyz** [comment]
@ThSGM So does your msmtp work sending mail? Again, you'll probably have to disable tls in the settings at least.

**Comment by ThSGM** [comment]
> Here's how I got the app password: - log in to Outlook with the account in question - click on round account icon in upper right - click View Account - click Security Info - click Add Method -> App Password
> […](#)
> @nicewaffles Can you possibly walk me through the steps of creating an app password? I do not think this is possible for our university's Office365 setup, but because of the myriad of variations of Office365, I just want to make sure. If you can provide a screenshot of the relevant page, this would be the most useful.

I believe I don't have access then: 

![Screenshot from 2021-01-04 14-21-19 - 1](https://user-images.githubusercontent.com/3396578/103544536-28b6db80-4e98-11eb-86a5-70aa94a4858a.png)

**Comment by ThSGM** [comment]
@LukeSmithxyz 

Continuing and using the davmail configuration I noted [above](https://github.com/LukeSmithxyz/mutt-wizard/issues/601#issuecomment-753961018) and the following msmtp configuration file: 

```
# Work
account        work
host           localhost
port           1025
tls            off
tls_starttls   off
auth           on
user           myuser@myuniv.ac.uk 
password       My password
from            myuser@myuniv.ac.uk

```

I issue: 
`echo "hello world" | msmtp -C ~/.config/msmtp/config_bak -a work test@gmail.com`          

and obtain                                                            
```
msmtp: cannot use a secure authentication method
msmtp: could not send mail (account work from /home/trinh/.config/msmtp/config_bak)
```

**Comment by f380cedric** [comment]
Not sure about this one.
However, I think if you do not specify an auth method, msmtp will try different method depending on server/client capability + security.
Meaning, it will not try plaintext auth method by default if TLS is completely disabled.

Could you try by modifying `auth on` to `auth plain` (or any other method supported by the server)?

**Comment by ThSGM** [comment]
@f380cedric 

Holy moly that worked! I used the same config file as above

```
# Work
account        work
host           localhost
port           1025
tls            off
tls_starttls   off
auth           plain
user           myuser@myuniv.ac.uk 
password       My password
from            myuser@myuniv.ac.uk
```
and
 
```
printf "Subject: Test\n\r\nHello there username." | msmtp -C ~/.config/msmtp/config_bak -a work myemail@gmail.com
```

worked like a charm. 

I guess the next step is to get this integrated with mutt-wizard. 

...also at some point I would like to figure out what just happened.

**Comment by trinh** [comment]
@LukeSmithxyz Now that I have the manual mbsync and msmtp options, can you give me a brief rundown of the steps needed to link this into mutt-wizard? 

For example, I can probably duplicate most of the options in the muttrc file (which seems to be a source command) and then manually make a folder in the accounts folder. 

Alternatively if you have a look at the mbsync and msmtp options I've given above you might know of an easier way. I mainly just want to input these account setup details so that mw can handle everything.

**Comment by ThSGM** [comment]
@LukeSmithxyz Now that I have the manual mbsync and msmtp options, can you give me a brief rundown of the steps needed to link this into mutt-wizard?

For example, I can probably duplicate most of the options in the muttrc file (which seems to be a source command) and then manually make a folder in the accounts folder.

Alternatively if you have a look at the mbsync and msmtp options I've given above you might know of an easier way. I mainly just want to input these account setup details so that mw can handle everything.

**Comment by ThSGM** [comment]
I can confirm that I now have everything working with mutt-wizard, including both incoming and outgoing email. If people are in a similar situation as I was, I would suggest the following steps. 

1. First, get mbsync working with davmail manually using similar configuration files as suggested in the above posts. 
2. Second, get msmtp working, again with the configurations suggested above
3. Force the creation of a Mutt Wizard account using 

`mw -a youremail@yourdomain.co.uk -p -f`

I don't think the -p flag is necessary for reasons below. The -f flag forces the creation. 

4. Now there are a few files for you to sort out. 

```
~/.mbsyncrc
~/.msmtprc
~/.config/mutt/accounts/
```
Edit the configuration files so that they use the same options that you previously got working. 

Although some elements of how email work are still dark to me, the above instructions should suffice to get some people started. Mutt-Wizard is helpful because it includes nice options and configuration files for NeoMutt, but for non-standard configurations, I would suggest to people to try and implement mbsync and msmtrp separately.

I believe the issue cam now be closed.

**Comment by chenle02** [comment]
> The below applies to **not** using mutt-wizard but my previous configuration where I tried to set things up manually.
>
> Here was the configuration I had for the IMAP which seemed to work with Davmail activated.
>
> ```
> IMAPAccount work
> # Address to connect to
> Host 127.0.0.1
> Port 1143
> User myusername@myuni.ac.uk
> #PassCmd "pass work/email"
> Pass mypassword
> SSLType None
> AuthMechs LOGIN
>
> IMAPStore work-remote
> Account work
>
> MaildirStore work-local
> # Copy folder hierarchy
> Subfolders Verbatim
> # The trailing "/" is important
> Path ~/.mail/work/
> Inbox ~/.mail/work/inbox
>
> Channel work
> Master :work-remote:
> Slave :work-local:
> # Include everything
> Patterns *
> # Automatically create missing mailboxes, both locally and on the server
> Create Both
> # Save the synchronization state files in the relevant directory
> SyncState *
> Remove Slave            # Propagate mailbox deletions
> MaxMessages 100
> ```
>
> MBsync then successfully pulled things to my computer.
>
> The SMTP in muttrc I tried to use was this:
>
> ```
> set smtp_url="smtp://myusername@myuni.ac.uk@127.0.0.1:1025"
> set smtp_authenticators = "login"
> set ssl_starttls = yes
> set ssl_force_tls = no          # Gives 500 unrecognised command with yes
> ```
>
> which did not work.
>
> To be honest, I did not know what I was doing in large parts of the above.
>
> In regards to your ability to test---I have heard that some people can create an Exchange account and email and test there, but obviously it might not duplicate the same server conditions that other universities have set up.
>
> > If you try to send mail, what error do you get? Can you try sending mail directly on the command line with `msmtp` if you know how?
>
> I need to read up on this and give it a shot.

Holy Moly! I encountered this issue in the past few days. I manually set up msmtp, sending emails is fine. Then by the same setup here for davmail and .mbsynrc, I can receive email too! Thanks a lot!

**Comment by ErickChacon** [comment]
The way I got it working was using the following settings in the `davmail.properties` file:
```bash
davmail.mode=O365Interactive
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx
```
So I was able to log in on a browser. After that, the file `davmail.properties`  is automatically updated with the required configuration.

**Comment by pahlse** [comment]
Hi All,

Thanks to this thread I got my Uni email working with mutt-wizard. I deeply appreciate all the work!

My setup is slightly different because I set up davmail in server mode on a VPS with ssh encription between the server and the client. For anybody who would llike to do the same:

1. Install davmail on your server and copy the `davmail.properties` config file from [https://davmail.sourceforge.net/serversetup.html](https://davmail.sourceforge.net/serversetup.html). 
2. Make sure the following is set:
    ```
    davmail.mode=O365Manual
    davmail.url=https://outlook.office365.com/EWS/Exchange.asmx #This depends on your organization
    davmail.server=true
    davmail.allowRemote=true
    ```
    In order for mutt-wizard to connect to the davmail server, make sure that `davmail.server=true` and `davmail.allowRemote=true`. I had to set `davmail.mode=O365Manual`, `EWS` and `auto` didn't work for me.

3. Create a self-signed certificate according to [this](https://www.digitalocean.com/community/tutorials/how-to-setup-a-davmail-exchange-gateway-on-a-debian-7-vps) page (alternatively you can also follow [this](https://davmail.sourceforge.net/sslsetup.html) page). The server side should now be set up.

4. Since the certificate is self-signed you will have to manually add it to your `.mbsyncrc`. To get the cert run ([source](https://stackoverflow.com/questions/7885785/using-openssl-to-get-the-certificate-from-a-server)):
    ```
    openssl s_client -showcerts -connect www.your_website.com:1143 </dev/null`
    ```
5. Add the part with the cert to your `ca-certificates.crt`, or save it in a sperate file and reference this file in your `.mbsyncrc` under `CertificateFile`.
6. Force the creation of a mutt-wizard account:
    ```
    mw -a youremail@yourdomain.co.uk -p -f
    ```
7. In your `.mbsyncrc` make the following changes:
    ```
    IMAPStore university-remote
    Host yourdavmailserver.xyz
    Port 1143
    User youremail@yourdomail.co.uk
    PassCmd "pass youremail@yourdomail.co.uk"
    AuthMechs LOGIN
    SSLType IMAPS #This is important, since we have ssl encryption
    CertificateFile /path/to/your/davmail/cert.crt
    ```
8. When you run `mw -y university` for the first time, be ready to follow the oauth-login steps on your server. Davmail will guide you through the process. This is where the O365Manual setting comes into play. If everything worked untill now, you should now be able to sync your uni mail with mutt-wizard. The IMAP side is done!
9. To be able to send mail via SMTP change the following in your `.msmtprc`:
    ```
    account university 
    host yourdavmailserver.xyz
    port 1025
    from youremail@yourdomail.co.uk
    user youremail@yourdomail.co.uk
    passwordeval "pass youremail@yourdomail.co.uk"
    auth plain
    tls on
    tls_starttls off
    tls_trust_file	/path/to/your/davmail/cert.crt
    ```
10. You should now be able to send and receive emails from mutt. Congrats!

*Note*: If you get duplicates in your sent mail turn off sync for sent mail in your `.mbsyncrc`. Simply remove `Sent` from `Patterns`. This duplication happens because davmail also saves outgoing email to remote. By turning off snyc for the sent folder, you will get isync to save to local and davmail to save to remote. Not ideal, but good enough. ;-)
