### ISSUE TITLE
.signature missing (errno = 2)

### ISSUE THREAD

**Issue by CoderBasis** [LukeSmithxyz/mutt-wizard#606]
Hi!
I opened ran mutt-wizard today and I was prompted with /home/user/.signature: File or directory does not exist (errno = 2). Any ideas?

It seems that I am still able to send emails, but it just bugs me to see the error.

**Comment by LukeSmithxyz** [comment]
Sounds like mutt is looking for a signature file, but I don't think any of the mutt-wizard settings do that themselves. Had you added this line to your muttrc by yourself?

**Comment by CoderBasis** [comment]
What is weird is the fact that I haven’t touched my muttrc at all. Recently I tried to setup a syncing thingy according to the issue posted before this issue, but nothing other than that.

**Comment by LukeSmithxyz** [comment]
Could you check your muttrc and your profiles in `~/.config/mutt/accounts/` *and* `/usr/share/mutt-wizard/mutt-wizard.muttrc` for a line with something like `set signature` in it?

**Comment by CoderBasis** [comment]
Hi,
I checked for "signature" in both files, but no match unfortunately...

**Comment by Juliaria08** [comment]
Me too

**Comment by CoderBasis** [comment]
I solved it, sadly it was the issue I referred to in the beginning that caused this issue. 

Now this implies another issue, namely how to can I automatically sync my mail and get notified. It seems that larbs doesn't do this by default... Additionally pass doesn't seem to store my password after rebooting.

**Comment by derekperrin** [comment]
I have this same error. I updated mutt recently on Gentoo, but according to my git log I haven't touched my muttrc file in a very long time.

**Comment by SentToDevNull** [comment]
I get the same error as well, but it doesn't prevent me from composing/sending the email. I think the use of a signature file may be baked into `neomutt` (or at least just the newer releases since I don't remember this happening for older versions).

**Comment by Kr1ss-XD** [comment]
Looks like the default for `signature` is `~/.signature`, according to the `neomuttrc(5)` manual. If a user doesn't want to append any signature at all, they'd need e.g.

```muttrc
set signature = :|
```
or
```muttrc
unset signature
```

in their (neo)`muttrc`.

This refers to neomutt 20201127, the version currently distributed via Arch Linux repository. I believe the default of that option was unset, not too long ago.

**Comment by CoderBasis** [comment]
worked m?n 18 jan. 2021 kl. 14:41 skrev Kriss <notifications@github.com>:
Looks like the default for signature is ~/.signature, according to the neomuttrc(5) manual. If a user doesn't want to append any signature at all, they'd need e.g.
set signature = :|

or
unset signature

in their (neo)muttrc.
This refers to neomutt 20201127, the version currently distributed via Arch Linux repository. I believe the default of that option was unset, not too long ago.

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
