### ISSUE TITLE
Using mw to create POP3 accounts only

### ISSUE THREAD

**Issue by badger62** [LukeSmithxyz/mutt-wizard#609]
Hi
I am trying to create an email account that retrieves via POP3 only . However  it looks like mw defaults to creating IMAP accounts only. Is there a way to do this . I ask because my ISP's IMAP is bad . At the moment I am retrieving emails via IMAP successfully but I am unable to create email folders on the server from neomutt, this is an ISP problem part of the reason I stopped using IMAP with other email clients . It creates them locally but they do not show up in the sidebar . Is there a way of making folders that are local only visible and accessible on the sidebar ?

**Comment by LukeSmithxyz** [comment]
I've been seriously thinking about adding this, but I'm not personally familiar with a command-line program that uses POP equivalent to mbsync for IMAP. I'll look into it.

**Comment by Kr1ss-XD** [comment]
@LukeSmithxyz you might want to have a look at [mailwizard], which implements POP3 support via getmail. Maybe that's helpful; it has been forked _before_ your major refactoring though.

**Comment by LukeSmithxyz** [comment]
Oh yeah, I remember when he forked that. I'll look into `getmail`, since that's what he uses.

**Comment by LukeSmithxyz** [comment]
I think I'd prefer using `mpop` after some research. I don't have a pop server to test this out on though. If I get the time, I might get to it, but I'd have to familiarize myself with pop protocol.

Honestly I don't feel like this is a huge priory because I think 99% of people will always prefer IMAP nowadays, but I am open to adding it.

Another issue is logon testing. Right now, the script just tries to logon with `mbsync`. I'll probably need to devise another scripted way of testing logins that can work for imap and pop.

**Comment by Kr1ss-XD** [comment]
@LukeSmithxyz What about using `neomutt` itself as the POP3 client ?

**Comment by LukeSmithxyz** [comment]
To be clear, I mean for when the script itself tests the user logon to see if it's valid. Are you saying there's an easy neomutt login test that _doesn't_ bring up the full program? I've never thought to look I guess.

**Comment by Kr1ss-XD** [comment]
No I don't know either, sorry. I never used POP3 myself.

It was just a quick idea. Because POP3 email is stored locally anyways, it might be easier to not use a third party app when neomutt has the functionality integrated.

**Comment by PRESFIL** [comment]
> To be clear, I mean for when the script itself tests the user logon to see if it's valid.

@LukeSmithxyz , you can try search some solution with `curl` if `neomutt`s way will be too *crutchy* (if an extra dependency is not a problem for you).

**Comment by LukeSmithxyz** [comment]
I had written some functions in openssl to test logons, but I've never tried curl. I'll look into it, but I'm not familiar with its syntax. The important thing is that it returns the right error code.

**Comment by PRESFIL** [comment]
I came across [this][1] before writing a [PR][#612]. `curl` has as many as ~90 return codes. Foresight on their part. I thought `bash` needed a separate library for network stuff, but `curl` itself is a library as is, apparently :smile:.

[1]: http://web.archive.org/web/20200926000215/https://debian-administration.org/article/726/Performing_IMAP_queries_via_curl

**Comment by LukeSmithxyz** [comment]
I have pushed a change that now checks the login with curl. Works fine for me, but I want to see how generalizable it is. https://github.com/LukeSmithxyz/mutt-wizard/issues/614 might be an issue with it.

**Comment by PRESFIL** [comment]
> Works fine for me, but I want to see how generalizable it is. #614 might be an issue with it.

Yes, because it wasn't supposed to use POP3. :smiley:

I can try `curl` with my provider, but probably everything is arranged differently there, because `curl` allows you to work at the message level, and they are certainly different from IMAP.

**Comment by LukeSmithxyz** [comment]
Well yeah, I'm assuming that you'd be using a different port and also `pop://` or whatever. I'm not sure if there's something else that would be needed.

I mightt just set up a POP server and see how I can get it working if I have the time.

**Comment by LukeSmithxyz** [comment]
For info, still thinking about adding this.

The `curl` login is already integrated, so `mbsync` is also no longer a runtime dependency (which is good for people who do not need `mbsync` for offline accounts either).

I might set up a POP server today to test it.

**Comment by LukeSmithxyz** [comment]
I've added this. Run `mw` with the `-P` option. You can specify the pop server information with `-i` and `-I` as if it is an IMAP server. `mw` will still use a maildir to store the mail locally (one `INBOX`).

I've tested this on my own server and it works well, but make me aware of any other issues.

**Comment by LukeSmithxyz** [comment]
Oh, and it uses `mpop`.

**Comment by badger62** [comment]
@LukeSmithxyz  thanks , this looks great . I'll give it  try.
