### ISSUE TITLE
isync error: unrecognized sync state header

### ISSUE THREAD

**Issue by privacy313** [LukeSmithxyz/mutt-wizard#610]
I was previously using isync-git from the AUR, but after seeing it is outdated I moved over to isync 1.3.3-1 from the community repo.
Since this move isync is returning an error

`Error: unrecognized sync state header entry at /home/user/.local/share/mail/gmail/INBOX/.mbsyncstate:1`

**Comment by LukeSmithxyz** [comment]
I assume that the git version used some extra info in the file that the standard lacks. Not sure about it.

I won't tell you to do anything too risky, so I recommend coping your old inbox (or entire mail archive) to another safe directory, then resyncing/redownloading your mail if you don't have a million mails or something. If it works, you can remove the backup directory.

You could just delete the mbsyncstate file, but there's a chance you might duplicate or delete your mail depending on how mbsync does it.

**Comment by privacy313** [comment]
That worked perfectly. Thanks!
