### ISSUE TITLE
Consider querying Thunderbird-style autoconfig

### ISSUE THREAD

**Issue by zeorin** [LukeSmithxyz/mutt-wizard#613]
Thunderbird (and other mail clients) looks up the mail configuration for a mail account by looking in some well-known places for it:

https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration#Configuration_server_at_ISP

>Given the email address "fred@example.com", Thunderbird checks <https://autoconfig.example.com/mail/config-v1.1.xml?emailaddress=fred@example.com> (preferred) and <https://example.com/.well-known/autoconfig/mail/config-v1.1.xml> and the same URLs with http (see section SSL below). The results are used in this order of preference.

**Comment by LukeSmithxyz** [comment]
Well I suppose it's valid to ask what mail servers actually use this. I'm trying different major providers but haven't found one that does.

**Comment by zeorin** [comment]
cPanel sets this up by default. iRedMail has a module for it, too. Perhaps the major providers don't use it, but the long tail of self-hosted email servers could benefit from this.

Additionally, Exchange servers use a similar mechanism called autodiscover (including for IMAP & SMTP).

Then of course Mozilla maintains the ISPDB (similar to what you're bundling).

Here's some iRedMail documentation that describes how all these different methods are used by mail clients: https://docs.iredmail.org/iredmail-easy.autoconfig.autodiscover.html
