### ISSUE TITLE
Mail folders with spaces not configured properly by default

### ISSUE THREAD

**Issue by connor73837** [LukeSmithxyz/mutt-wizard#615]
Just set up mutt-wizard on a new computer and ran into this simple issue right out of the box.

My email has two folders with spaces in their names. In the automatically generated `~/.config/mutt/accounts/x.muttrc` those two folders had an extra set of double quotes about them on the mailboxes line. I fixed this by changing `"="abc def""` to `"=abc def"`, but it would be nice if this intervention had not been needed.

I figured I would open this issue so that out of the box it will 'just werk'.

Thanks

**Comment by LukeSmithxyz** [comment]
This is probably due a change made several days ago that streamlined how mailboxes are detected. I'll go ahead and fix this.

**Comment by LukeSmithxyz** [comment]
Could you give me a list of all of your mailbox names?

I actually think this might be something different than spaces alone.
