### ISSUE TITLE
Uninstall/Remove

### ISSUE THREAD

**Issue by josephgerth** [LukeSmithxyz/mutt-wizard#618]
My apologies if this is a dumb question. I am having some issues configuring neomutt with mutt-wizard, and I believe it will be best to start entirely over. I can easily remove neomutt; but I have no idea how to remove mutt-wizard. Or perhaps there is a way to remove all changes that mw has made and start over?

Thanks!

**Comment by imomaliev** [comment]
in mutt-wizard folder

`make uninstall`

**Comment by LukeSmithxyz** [comment]
Yes, just `sudo make uninstall`, you might also want to manually remove the user configuration files it creates in `~/.config/mbsync`, `~/.config/mutt` and `~/.config/msmtp`.
