### ISSUE TITLE
New folders created in neomutt showing on ISP webmail automaticaly but needs to be manually added to muttrc file for account 

### ISSUE THREAD

**Issue by badger62** [LukeSmithxyz/mutt-wizard#619]
Hi, When creating new mail boxes through the dialog that pops up when saving an email with "s" in the pager. The new mailbox shows up in the web interface of my ISP when I log in, containing the email that triggered the creation of a new mailbox but the mailbox is not added to my muttrc file for the mail . Is this expected behaviour? I can add them manually and all works OK . Is there  a way for neomutt to do this automatically?

**Comment by PRESFIL** [comment]
See #620 . You can try [this](https://github.com/LukeSmithxyz/mutt-wizard/issues/620#issuecomment-759557630).

**Comment by PRESFIL** [comment]
You can try [this](https://github.com/LukeSmithxyz/mutt-wizard/issues/620#issuecomment-761551939).

**Comment by SentToDevNull** [comment]
> You can try [this](https://github.com/LukeSmithxyz/mutt-wizard/issues/620#issuecomment-761551939).

Regarding this line:
```
mailboxes `mbsync -l mixayloff.dimaaylov@yandex.ru | sed -n ':b;s/\(.*\)$/'\''=\1'\'' /;H;$!{n;bb};g;s/\n/ /g;p'`
```

@PRESFIL Kudos to you for that regex. You mention that the solution has a drawback in that it prompts for a password. It should not. You might want to re-check your `pass` and `pam-gnupg` configuration it that is the case.

This is a good first step to address the issue, but one drawback not mentioned so far is that this solution causes mutt to only work when you're connected to the internet (defeating the purpose of mutt-wizard).

One solution would be to have the command run when fetching mail (e.g. `mw -y mail@box.com`), cache the results, and `cat` that cache instead of running the `mbsync` command above.

**Comment by SentToDevNull** [comment]
Here's a better idea than the one I proposed. Since mutt-wizard already fetches all mailboxes from the server anyways, just search for the locally:
```
mailboxes `cd ~/.local/share/mail/me@me.com; find . -mindepth 1 -type d | grep -ve cur -e new -e tmp | sed "s,^./,," | sed "s,^,\"/," | sed "s,$,\",g" | tr '\n' ' '`
```

**Comment by PRESFIL** [comment]
@SentToDevNull , I don't use - so for me the popup was a problem (like any password manager without without integration with `pam`).

> but one drawback not mentioned so far is that this solution causes mutt to only work when you're connected to the internet

You are absolutely right, but do it with `find` ... it looks like a pile of junk. I was thinking of writing a separate script for this, although you can try again to reduce what is there.

**Comment by PRESFIL** [comment]
There is an error in your implementation. You need to filter not just `cur|new|tmp`, but the paths where **these folders are at the tail**. I think you can get the best of both worlds this way:

```mutt
mailboxes `cd ~/.local/share/mail/me@me.com/ ; find . -mindepth 1 -type d | sed -n 's!./\(.*\)\(cur\|tmp\|new\)$!\1!p' | sort -u | sed -n ':b;s/\(.*\)$/'\''=\1'\'' /;H;$!{n;bb};g;s/\n/ /g;p'`
```

I do not give up my option because it also wraps all names in single quotes, which **prevents the syntax processing by mutt itself**.

**Comment by PRESFIL** [comment]
@SentToDevNull , can you send to devnull my email :smile_cat: ? [1](https://github.com/LukeSmithxyz/mutt-wizard/issues/619#issuecomment-761989817).

**Comment by SentToDevNull** [comment]
> There is an error in your implementation. You need to filter not just `cur|new|tmp`, but the paths where **these folders are at the tail**. I think you can get the best of both worlds this way:
> 
> ```
> mailboxes `cd ~/.local/share/mail/me@me.com/ ; find . -mindepth 1 -type d | sed -n 's!./\(.*\)\(cur\|tmp\|new\)$!\1!p' | sort -u | sed -n ':b;s/\(.*\)$/'\''=\1'\'' /;H;$!{n;bb};g;s/\n/ /g;p'`
> ```
> 
> I do not give up my option because it also wraps all names in single quotes, which **prevents the syntax processing by mutt itself**.

I like it! Do you want to bundle that into a pull request, or should I.

**Comment by PRESFIL** [comment]
> I like it! Do you want to bundle that into a pull request, or should I?

I'll think about it. It seems to me that if it is implemented for Maildir, it should also work for Online-IMAP. And for POP (which I haven't worked with). We need to find ways.

I also noticed an interesting feature: you can write `mailboxes '=INBOX'` before this expression, and they will be *pinned* at the beginning and will **not be duplicated**. It is convenient if you do not want to mix standard folders and your own (but not all standard folders are present - it depends on the ISP).

**Comment by PRESFIL** [comment]
@SentToDevNull , can you delete my email :smile_cat: ? [1](https://github.com/LukeSmithxyz/mutt-wizard/issues/619#issuecomment-761989817). It's all my inattention...

**Comment by SentToDevNull** [comment]
> @SentToDevNull , can you delete my email 😸 ? [1](https://github.com/LukeSmithxyz/mutt-wizard/issues/619#issuecomment-761989817). It's all my inattention...

Yep, no problem.

**Comment by PRESFIL** [comment]
This works for Vim with `nocompatible` and with `compatible`. But not for Vi. You can look in `:help index`.
