### ISSUE TITLE
Turning off the notification

### ISSUE THREAD

**Issue by freddiaN** [LukeSmithxyz/mutt-wizard#62]
is it possible to turn of the notification sound without removing `mpv` or deleting the `notify.opus` file?

**Comment by LukeSmithxyz** [comment]
Sure. It's just not in the menu. Just open up `~/.config/mutt/etc/mailsync.sh` and comment out the mpv command.

**Comment by freddiaN** [comment]
I guess that would still leave me with unstaged changes in the repo, which I tried to avoid... welp ¯\_(ツ)_/¯

**Comment by LukeSmithxyz** [comment]
Yeah well even if I added an option in the script that disabled it, it would still in effect be changing repo files. I guess the only other option would me breaking the sync script up and having put in the crontab incrementally, but that would make some other things a lot more difficult.

git has the ability to ignore local changes, etc. in a couple different ways. So I'd just go with that.
