### ISSUE TITLE
Deleting folders on the server causes error messages . What config file to amend to stop this?

### ISSUE THREAD

**Issue by badger62** [LukeSmithxyz/mutt-wizard#620]
Hi I deleted a number of old folders  on my ISP web interface for my account  after setting up mutt-wizard. Now the command  `mw -Y &` raises error messages. This is what might be expected. I have removed the deleted mailboxes from the line  `mailboxes` in the `muttrc` for the associated account . I looked around in the other `~/config` files  where some setting might be left from the initial install . Is there a line I can add to `muttrc` ? Please see the error output below (anonymised). 
Despite my constant questions I am really happy with mutt-wizard, I remember setting up Mutt in NetBSD about 15 years ago and I think it took me about a week, so this is an absolute Godsend. Thanks for all your work!!

`1]9948                                                                                              │
C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0C: 0/1  B: 0/15  M: +0│
/0 *0/0 #0/0  S: +C: 0/1  B: 0/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  B: 0/15  M: +0/0 *0/0 #0/0  S: +C: 0│
/1  B: 0/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  B: 0/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  B: 1/15  M: +0/0 *│
0/0 #0/0  S: +C: 0/1  B: 2/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  B: 3/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  │
B: 4/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  B: 5/15  M: +0/0 *0/0 #0/0  S: +2/2 *0/0 #0/0                 │
Error: channel my-email2.com: master Mailspring.Snoozed cannot be opened.               │
C: 0/1  B: 6/15  M: +0/0 *0/0 #0/0  S: +2/2 *0/0 #0/0                                                 │
Maildir notice: no UIDVALIDITY, creating new.                                                         │
C: 0/1  B: 7/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  B: 8/15  M: +0/0 *0/0 #0/0  S: +C: 0/1  B: 9/15  M: +0│
/0 *0/0 #0/0  S: +C: 0/1  B: 10/15  M: +0/0 *0/0 #0/0  S: C: 0/1  B: 11/15  M: +0/0 *0/0 #0/0  S: C: 0│
/1  B: 12/15  M: +0/0 *0/0 #0/0  S: C: 0/1  B: 13/15  M: +0/0 *0/0 #0/0  S: C: 0/1  B: 0/27  M: +0/0 *│
0/0 #0/0  S: +C: 0/1  B: 14/15  M: +0/0 *0/0 #0/0  S: C: 0/1  B: 0/27  M: +0/0 *0/1 #0/0  S: +C: 0/1  │
B: 0/27  M: +0/0 *0/1 #0/0  S: +C: 0/1  B: 0/27  M: +0/0 *0/1 #0/0  S: +C: 0/1  B: 15/15  M: +0/0 *0/0│
 #0/0  S: C: 1/1  B: 15/15  M: +0/0 *0/0 #0/0  S: +2/2 *0/0 #0/0                                      │
C: 0/1  B: 0/27  M: +0/0 *1/1 #0/0  S: +C: 0/1  B: 0/27  M: +0/0 *1/1 #0/0  S: +C: 0/1  B: 0/27  M: +0│
/0 *1/1 #0/0  S: +C: 0/1  B: 1/27  M: +0/0 *1/1 #0/0  S: +C: 0/1  B: 2/27  M: +0/0 *1/1 #0/0  S: +2/2 │
*0/0 #0/0                                                                                             │
Error: channel my-email1.com: master Archive cannot be opened.                              │
C: 0/1  B: 3/27  M: +0/0 *1/1 #0/0  S: +C: 0/1  B: 4/27  M: +0/0 *1/1 #0/0  S: +C: 0/1  B: 5/27  M: +0│
/0 *1/1 #0/0  S: +C: 0/1  B: 6/27  M: +0/0 *1/1 #0/0  S: +C: 0/1  B: 7/27  M: +0/0 *1/1 #0/0  S: +C: 0│
/1  B: 8/27  M: +0/0 *1/1 #0/0  S: +C: 0/1  B: 9/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0             │
Error: channel my-email1.com: master Mailspring cannot be opened.                           │
C: 0/1  B: 10/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0                                                │
Error: channel my-email1.com: master Mailspring.Snoozed cannot be opened.                   │
C: 0/1  B: 11/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0                                                │
Error: channel my-email1.com: master Mailspring/Snoozed cannot be opened.                   │
C: 0/1  B: 12/27  M: +0/0 *1/1 #0/0  S: C: 0/1  B: 13/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0        │
Error: channel my-email1.com: master N1-Snoozed cannot be opened.                           │
C: 0/1  B: 14/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0                                                │
Error: channel my-email1.com: master Peters cannot be opened.                               │
C: 0/1  B: 15/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0                                                │
Error: channel my-email1.com: master SPAM cannot be opened.                                 │
C: 0/1  B: 16/27  M: +0/0 *1/1 #0/0  S: C: 0/1  B: 17/27  M: +0/0 *1/1 #0/0  S: C: 0/1  B: 18/27  M: +│
0/0 *1/1 #0/0  S: C: 0/1  B: 19/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0                              │
Error: channel my-email1.com: master amazon.jp cannot be opened.                            │
C: 0/1  B: 20/27  M: +0/0 *1/1 #0/0  S: +2/2 *0/0 #0/0                                                │
Error: channel my-email1.com: master amazon/jp cannot be opened.                            │
C: 0/1  B: 21/27  M: +0/0 *1/1 #0/0  S: C: 0/1  B: 22/27  M: +0/0 *1/1 #0/0  S: C: 0/1  B: 23/27  M: +│
0/0 *1/1 #0/0  S: C: 0/1  B: 24/27  M: +0/0 *1/1 #0/0  S: C: 0/1  B: 25/27  M: +0/0 *1/1 #0/0  S: C: 0│
/1  B: 26/27  M: +0/0 *1/1 #0/0  S: C: 0/1  B: 27/27  M: +0/0 *1/1 #0/0  S: C: 1/1  B: 27/27  M: `

**Comment by badger62** [comment]
@LukeSmithxyz  Solved !  I removed the offending mailboxes in ~/.share/mail/<my-account>  and this stopped the error messages .  Still would be useful to know if this can be changed in one fall swoop in a config file .

**Comment by PRESFIL** [comment]
* about `mbsync` errors: I think the reason is in the `mbsync` config like here #617
* about `mutt`|`neomutt`: mailbox names are hardcoded now and you need to update their list every time you change the folder structure on the server, manually. Or, provide something like:

   ```muttrc
   mailboxes `find "~/.local/share/mail/$account/" -mindepth 1 -maxdepth 1 -type d`
   ```

You also said `~/.share/mail/` and it seems to me that maybe you now have the old `mw` / left settings from the old `mw` (I'm not familiar with the history of `mw`, so I can't say). Maybe that's why resetting the config helped.

**Comment by PRESFIL** [comment]
LOL, I [almost](https://neomutt.org/guide/advancedusage#note-11) guessed it! :smiley:

**Comment by PRESFIL** [comment]
Looks like `mutt` already have this [feature](https://gitlab.com/muttmua/mutt/-/wikis/MuttFaq/RemoteFolder#how-can-i-list-browse-remote-imap-folders)!

**Comment by PRESFIL** [comment]
I tried this and it works:

```
mailboxes `mbsync -l <current_mail_channel> | sed -n ':b;s/\(.*\)$/"=\1" /;$!{H;n;bb};g;s/\n/ /g;p'`
```

I don't like the option from the wiki because there are still parent paths of the mailbox root, not very convenient.

This solution has its drawbacks: it requires you to enter a password, and apparently it requests folders from the server, these folders **may differ** from what you currently have in your mailbox. `mutt` may complain about this if you do not pre-sync.
