### ISSUE TITLE
mbsync - master cannot be opened and slave not empty

### ISSUE THREAD

**Issue by 5833tP2** [LukeSmithxyz/mutt-wizard#621]
I've nuked a previous installation of `mutt-wizard` so I can start from scratch but each time I try to sync with the IMAP server, I get warnings about phantom folders. e.g.

```
Warning: channel me@mydomain.com: master folder-name1 cannot be opened and slave folder-name1 not empty.
Warning: channel me@mydomain.com: master folder-name2 cannot be opened and slave folder-name2 not empty.
Warning: channel me@mydomain.com: master folder-name3 cannot be opened and slave folder-name3 not empty.
```

`folder-name1` etc used to reside on the IMAP server as subfolders of INBOX, but I have since removed them. For whatever reason, `mutt-wizard` is still trying to sync with these non-existent folders. This is despite me starting from scratch, so I do not where it is getting these old settings from.

To remove a prior installation of `mutt-wizard` I've followed #618 and used `sudo make uninstall`, then manually removed `~/.config/mutt`, `~/config/msmtp` and `~/.mbsyncrc`.

When I reinstall and reconfigure `mutt-wizard`, the master/slave error messages reappear! I have double-checked the IMAP server and those folders are definitely not there.

So, where is `mutt-wizard` hiding its memory of these old folders?

**Comment by LukeSmithxyz** [comment]
~/.local/share/mail

**Comment by 5833tP2** [comment]
Well, there you go! perfect answer from The Man himself. Thanks, @LukeSmithxyz
