### ISSUE TITLE
log on not sucsessfull

### ISSUE THREAD

**Issue by Eddy-Arch** [LukeSmithxyz/mutt-wizard#622]
-log-
Give your email server's IMAP address (excluding the port number):
mail.eddster.xyz
Give your email server's SMTP address (excluding the port number):
mail.eddster.xyz
Enter password for mw-eddy@eddster.xyz:
Retype password for mw-eddy@eddster.xyz:
Log-on not successful.

**Comment by LukeSmithxyz** [comment]
What does your server log say?

**Comment by LER0ever** [comment]
Same here with G Suite account. If I pass `-f` to skip log on, `mbsync` logs in and syncs perfectly. Might be the logic of checking the login status in mw?

**Comment by Mertzenich** [comment]
I get the same issue using protonmail-bridge.

**Comment by dgrisham** [comment]
I hit the same issue twice, in two different ways:

1. On Arch using emailwiz, I didn't have the `/usr/share/dovecot/dh.pem` key on the server for encryption. You can generate this key with:

```
openssl dhparam 4096 > /usr/share/dovecot/dh.pem
```

2. I ended up moving emailwiz to Debian, then hit a similar issue. But this time, my local system's clock (the one I had mutt-wizard on) was behind, so the SSL certificate on the server was deemed invalid.

Those may or may not apply -- two additional debugging steps you can take are:

1. Run:

```
curl -w '%{http_code}' --location-trusted -s -m 5 --user <email_user>:<password> --url imaps://<imap_address> -v
```

The status code/verbose messages may give you some insight into the issue. That `curl` command is used by `mw` itself to get your mailboxes.

2. Edit `/bin/mw` and add `set -x` at the top, then rerun the command. You'll get to see everything that happens before/after the `Log on not successful` message. I did this myself, which is how I came up with the `curl` command above.
