### ISSUE TITLE
Local archiving of messages

### ISSUE THREAD

**Issue by asakura42** [LukeSmithxyz/mutt-wizard#627]
I don't know if my question applies to mutt-wizard, maybe this is neomutt or mbsync issue, anyway.

I want to save some mail only locally, that is, for example, have one folder that will not be synchronized with the server. Thus, the ideal option would be:
1) Copy the message(s) to the "Local Archive" folder
2) Neomutt automatically deletes these messages from the server
3) It does not upload messages from this folder to the server when updating

I don't clearly understand how this should work, but I hope the point is clear. Have you encountered a problem like this?

**Comment by tatsumoto-ren** [comment]
Agree. I wish mutt-wizard had these features:
* move messages to a different account
* move messages between folders inside one account
* move messages between an account and an offline folder

**Comment by LukeSmithxyz** [comment]
Well firstly, there are a lot of macros painstakingly added to mutt-wizard to allow moving/coping messages. E.g. pressing `Mj` moves a mail to junk, etc. If your email account has an "Archive" folder, `Ma` moves it there. Note that you can multiselect mails with space beforehand.

These macros are kept in `~/.config/mutt/accounts/number-youraccount.muttrc` and you can replicate them for new mailboxes that you create.

Let's take the use case of wanting to have a new offline and unsynced "Archive" mailbox. Here is what we would do:

1. Create the directory structure: `mkdir -p ~/.local/share/mail/account/Archive/{cur,new,tmp}`
2. Edit your account's individual config file adding the new "Archive" folder to the `mailboxes` command and copy and edit the macros at the bottom if you want them.
3. Edit `~/.config/mbsync/config` file to edit which directories are synced, change the value of `Patterns` to add `!Archive` to exclude it.
