### ISSUE TITLE
Mutt-Wizard Displays All Mailbox Folders As At Same Hierarchical Level

### ISSUE THREAD

**Issue by SentToDevNull** [LukeSmithxyz/mutt-wizard#628]
In most email setups, there is a hierarchy of directories, such as "INBOX", "INBOX->Financial", "INBOX->Church", "INBOX->Work->Events", etc.

The configuration with `mutt-wizard` displays in the directory sidebar everything at the same hierarchical level:
```
INBOX
Financial
Church
Work
Events
```

The default configuration as of now makes it quite difficult to navigate an inbox with any sort of hierarchy.

**Comment by PRESFIL** [comment]
It is narrowing [functionality](https://neomutt.org/feature/sidebar) of sidebar. You can disable it (or change delimiter).

* `'sidebar_short_path'`
* `'sidebar_delim_chars'`

**Comment by SentToDevNull** [comment]
> It is narrowing [functionality](https://neomutt.org/feature/sidebar) of sidebar. You can disable it (or change delimiter).
> 
> * `'sidebar_short_path'`
> * `'sidebar_delim_chars'`

Thanks! Here are some defaults that should be rolled into mutt-wizard's default muttrc to fix this issue:
```
# inbox directory hierarchy support
set sidebar_delim_chars = '/.'
set sidebar_sort_method = 'path'
set sidebar_folder_indent = yes
set sidebar_indent_string = '  '
```

**Comment by PRESFIL** [comment]
I think this is not a bug. Therefore, it may not be accepted:

>  I don't use an email address with hierarchical mailboxes, but I think there's a chance we might be able to survive without it.

[Source](https://github.com/LukeSmithxyz/mutt-wizard/pull/612#issuecomment-755395956).

But, I like this option. It looks like a compromise, at least for sidebar.
