### ISSUE TITLE
Wizard creates wrong Gmail mailbox names in <Gmail alias>.muttrc

### ISSUE THREAD

**Issue by theKnary** [LukeSmithxyz/mutt-wizard#63]
After using the wizard to configure mutt with a Gmail account, the `<Gmail alias>.muttrc` file created in `~/.config/mutt/accounts` contains incorrect mailbox names which throw errors when sending mail or changing mailboxes.

Default names don't work but editing the mailbox name in the mappings of `~/.config/mutt/accounts/<Gmail alias>.muttrc` creates new mailboxes which work in mutt.

**Comment by LukeSmithxyz** [comment]
Could you elaborate on what specific folders the script was improperly finding? I haven't been able to replicate this problem despite using two gmail accounts myself.

Could you also list the names of your folders/tags in your gmail? It's possible that due to a deceptive folder name, it's producing the wrong shortcuts.

**Comment by theKnary** [comment]
Well, as usual in the programming world, the problem was caused by user error instead of the program itself. Your can't fix stupid...

After reinstalling `neomutt` and `offlineIMAP`, I realized that it was a misconfiguration of `offlineIMAP` that was causing the issue. I did have to specify where my mail was in the various `.muttrc` files but like you said, gmail tag and folder names were creating odd mailbox names. I also hadn't run `offlineIMAP -a <account-alias>` after configuring my account with `mutt-wizard` to initialize mailboxes properly (which was suggested by `mutt-wizard` to do immediately after setting up an account), I had synced from within `neomutt`.

I recommend anyone using a Gmail account with `neomutt` or `offlineIMAP` to take a look at the Gmail configuration here [https://wiki.archlinux.org/index.php/OfflineIMAP#Gmail_configuration](url) for `offlineIMAP`, especially the name translation part that converts the remote repository tag/folder names to ones you specify for your local repository.

**Comment by LukeSmithxyz** [comment]
Okay, but if you follow the wizard directions without making another changes does the sync and mutt work or not? I can't really tell from your wording. You should be able to just run the wizard for a Gmail account and have it work without making further manual changes.

**Comment by theKnary** [comment]
Yes, everything works without any manual changes. I just had to undo what I had changed in config files.

**Comment by LukeSmithxyz** [comment]
Okay, gotcha. Great!
