### ISSUE TITLE
mw -a e@mail.com loop

### ISSUE THREAD

**Issue by se7en-x230** [LukeSmithxyz/mutt-wizard#632]
First run `pass init <yourgpgemail>` to set up a password archive.
(If you don't already have a GPG key pair, first run `gpg --full-gen-key`.)
 
I have done both an all dependencies + extras installed. I use mw on my desktop setup about a year ago and it worked fine.
This is a brand new minimal arch install with larbs.

any idea?

**Comment by JonBoyleCoding** [comment]
I'm having the same issue.

**Comment by JonBoyleCoding** [comment]
@se7en-x230 I think I've found the issue for me, perhaps this will be of help to you.

The message asks you to do `gpg --full-gen-key`, however with the gpg installed on my Arch system that's incorrect. The command is `gpg --full-generate-key`. This will ask you for a name and email address (this does not have to be the one you are using mw to access the email account for).

Then, you have to do `pass init <yourgpgemail>`, with the email from the previous stage.

After that, your mw commands should work. If it's the same issue as me that is!

Just for reference in case someone wants/needs to update the text, the check is here: https://github.com/LukeSmithxyz/mutt-wizard/blob/158f28b2940355f530ac592cdb9a9af3cd5c2959/bin/mw#L23

@se7en-x230 In case this isn't your issue, those lines check that the password store file exists (default `~/.password-store/.gpg_id`) and that if the command succeeds without error `gpg --list-secret-keys "$(cat "$PASSWORD_STORE_DIR/.gpg-id")` (replace $PASSWORD_STORE_DIR with your actual directory, the default if not changed). Check those commands out in the terminal to see if they work.

**Comment by se7en-x230** [comment]
Exellent thanks
