### ISSUE TITLE
gssapi is not a valid authenticator

### ISSUE THREAD

**Issue by jcrcx** [LukeSmithxyz/mutt-wizard#633]
I have been using mutt-wizard for a long time with two accounts in a gentoo installation. There is no problem using mutt, but a couple of days ago, it start to prompt the following:

`Error in /usr/local/share/mutt-wizard/mutt-wizard.muttrc, line 10: Option smtp_authenticators: gssapi is not a valid authenticator`
`Error in /home/jcrcx/.config/mutt/muttrc, line 2: source: file /usr/local/share/mutt-wizard/mutt-wizard.muttrc could not be sourced`
`source: errors in /home/jcrcx/.config/mutt/muttrc`
`Press any key to continue...`

Then I press enter, so I can use mutt as normal. But I don't know how to fix it.

Any thoughts?

**Comment by LukeSmithxyz** [comment]
Just edit `/usr/local/share/mutt-wizard/mutt-wizard.muttrc` and remove
the offending line manually and it should be fine. I'm trying to
remember why it's originally set like that but it shouldn't make a
difference at all for the default usage of mutt-wizard where you keep
mail offline.

I'm guessing Gentoo is using a newer version of neomutt maybe with
gssapi deprecated (or vice versa)? I might look into it.

**Comment by jcrcx** [comment]
Thanks Luke, 

I'm also thinking that is what you are saying 

> I'm guessing Gentoo is using a newer version of neomutt maybe with
gssapi deprecated (or vice versa)? I might look into it.

I've just remove the line, now it's fine.

Best,

Julio

**Comment by 187Qrly** [comment]
For future users using gentoo, as mentioned in [#604](https://github.com/LukeSmithxyz/mutt-wizard/issues/604): 
Add the `sasl` use flag to the package neomutt, for example in /etc/portage/package.use:
`mail-client/neomutt sasl`

**Comment by mahehsis** [comment]
> Just edit `/usr/local/share/mutt-wizard/mutt-wizard.muttrc` and remove
> the offending line manually and it should be fine. I'm trying to
> remember why it's originally set like that but it shouldn't make a
> difference at all for the default usage of mutt-wizard where you keep
> mail offline.
> 
> I'm guessing Gentoo is using a newer version of neomutt maybe with
> gssapi deprecated (or vice versa)? I might look into it.
> On 21/01/19 04:00PM, Julio Ramirez wrote:
> > I have been using mutt-wizard for a long time with two accounts in a gentoo installation. There is no problem using mutt, but a couple of days ago, it start to prompt the following:
> >
> > `Error in /usr/local/share/mutt-wizard/mutt-wizard.muttrc, line 10: Option smtp_authenticators: gssapi is not a valid authenticator`
> > `Error in /home/jcrcx/.config/mutt/muttrc, line 2: source: file /usr/local/share/mutt-wizard/mutt-wizard.muttrc could not be sourced`
> > `source: errors in /home/jcrcx/.config/mutt/muttrc`
> > `Press any key to continue...`
> >
> > Then I press enter, so I can use mutt as normal. But I don't know how to fix it.
> >
> > Any thoughts?
> >
> > --
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/LukeSmithxyz/mutt-wizard/issues/633
> 

Had this issue in Debian 11 as well. Quoting out that line in muttrc takes care of this.
