### ISSUE TITLE
Error after command 'offlineimap -a athena'

### ISSUE THREAD

**Issue by Newexplorer** [LukeSmithxyz/mutt-wizard#64]
OfflineIMAP 6.6.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync athena:
 *** Processing account athena
 Establishing connection to imap.gmail.com:993
gpg: decryption failed: No secret key
Enter password for account 'athena-remote':

**Comment by LukeSmithxyz** [comment]
Did you not insert a password when setting up via the wizard?

Does the file `~/.config/mutt/credentials/athena.gpg` exists? Can you run `gpg -d` on it? (Obviously don't show us the output, since your password should be there.)
