### ISSUE TITLE
INBOX folder created when syncing hotmail (instead of Inbox)

### ISSUE THREAD

**Issue by lc5415** [LukeSmithxyz/mutt-wizard#641]
I've just started using `mutt-wizard` with a hotmail account. After I set up my account, I was confused that there were no message in Inbox when I launched `neomutt`. After some digging I realised that under my account's folder (`$HOME/.local/share/mutt/accounts/my-account`), there were two inbox folders: __Inbox__ and __INBOX__. __INBOX__ had all my email and __Inbox__ was empty and neomutt was looking at __Inbox__ to list my email. I simply removed the __Inbox__ folder and renamed __INBOX__ to __Inbox__ and now I could see all my email properly in `neomutt`. Unfortunately, everytime I sync my email all the new content goes to __INBOX__. I think this is potentially a bug to do with the mutt-wizard, but I am not sure as I've just started using this tool yesterday and I've just read some bits of the source.

![pic-selected-210129-2331-53](https://user-images.githubusercontent.com/47890755/106338617-1ad45a80-628c-11eb-9681-85429caf2b1c.png)

**Comment by lc5415** [comment]
https://github.com/LukeSmithxyz/mutt-wizard/blob/b6928fe4a6fd39f4b2478a9e43773bdebd600ac3/bin/mw#L67

This seems like the line to blame. Is there any particular reason why INBOX is in caps, is this a good default setting (I assume it is). Is the right thing to do to change my `muttrc` files and tell them that the right inbox folder is __INBOX__?

**Comment by LukeSmithxyz** [comment]
I've changed it so that it automatically follows the capitalization of your detected inbox.

Strangely enough, I've always had a server with `Inbox`, but `INBOX` was always compatible. Not sure what's different with Hotmail.

**Comment by lc5415** [comment]
Thanks for the quick fix @LukeSmithxyz! Great work :)
