### ISSUE TITLE
How to select all/ delete all?

### ISSUE THREAD

**Issue by lc5415** [LukeSmithxyz/mutt-wizard#642]
I would like to search for a certain pattern (with CTRL-F using notmuch) then select all entries that match that search and delete them all at once (or select them all and then delete them all). Is it possible to do this? I've searched for a command like this in the neomutt binding lis but a command such as `delete-all` or `delete-all-pattern` does not seem to exist.

**Comment by LukeSmithxyz** [comment]
Add a binding if you want them.

**Comment by lc5415** [comment]
In case anyone wonders about this in the future the binding/macro to mark all entries displayed as deleted (or to-be deleted) is:
`macro index \CD "<delete-pattern>.<enter>"`

Where `\C` is CTRL
