### ISSUE TITLE
Some DeltaChat support

### ISSUE THREAD

**Issue by asakura42** [LukeSmithxyz/mutt-wizard#644]
I like DeltaChat because it uses mail for instant messaging which is interesting I think. DeltaChat creates new folder called `DeltaChat` and saves here all encrypted messages that receive and send. Messages here can read only DeltaChat so they are useless for default mail reading. 

Also today I had an issue:

1. I added new account
2. Did `mw -Y`
3. Deleted `"=DeltaChat"` from account's muttrc
4. Deleted folder `DeltaChat` from `~/.local/share/mail/m@i.l/`
5. Added `!DeltaChat` to mbsyncrc
6. Did `mw -Y`

I honestly thought that NeoMutt just won't update or smth that folder. But it deletes folder from server. Maybe I did something wrong?

**Comment by PRESFIL** [comment]
As far as I understand, `mbsync` is currently configured for two-way synchronization. So yes, deleting a folder will delete it on the server. You can specify a pattern in `.mbsyncrc` with an exclamation point to ignore the folder. See `mbsync(1)`.

**Comment by PRESFIL** [comment]
Oops. You've already done that. But it was necessary **not to perform the first synchronization** before adding this template. In this case, there will be the following sequence of actions:

1. `mw -a <email>`

**Comment by asakura42** [comment]
@PRESFIL  

> it was necessary **not to perform the first synchronization**

Haha lol 😐 But what (imagine) if I use mail for decades and want to delete some `Archive` folder with thousands of messages from NeoMutt but remain it on server? What should I do?

**Comment by PRESFIL** [comment]
Yes, you're right...
