### ISSUE TITLE
Unresolved issue: flattened mailbox name ... contains canonical hierarchy delimiter

### ISSUE THREAD

**Issue by dmsalomon** [LukeSmithxyz/mutt-wizard#648]
It appears that the issue mentioned in #546 is still unresolved, I have the exact same issue mentioned there with my Gmail accounts. This worked fine on my last machine I'm not sure what has gone wrong since then. I see that https://github.com/LukeSmithxyz/mutt-wizard/commit/9662299d4e508f4c6706c7c6709730f06e60aa52 was supposed to resolve the issue, but I still have the issue after downloading the latest version from the AUR.

I'm also seeing the mutt-wizard is incorrectly determining the mailbox file structure, eg,

    ~ ➜ ls ~/.local/share/mail/my.account@gmail.com 
    '[Gmail]'  INBOX 

instead of, 

    ~ ➜ ls ~/.local/share/mail/my.account@gmail.com 
    '[Gmail].Drafts'  '[Gmail].Important'  '[Gmail].Sent Mail' 
    '[Gmail].Spam'  '[Gmail].Starred'  '[Gmail].Trash'   INBOX

**Comment by Kr1ss-XD** [comment]
@dmsalomon you're stating

> I still have the issue after downloading the latest version from the AUR.

Did you install `mutt-wizard` or `mutt-wizard-git` ? Because only the latter one includes the commit you mentioned. The current release version doesn't, yet.

**Comment by dmsalomon** [comment]
I'm using `mutt-wizard-git`, and I have double checked that the version installed has https://github.com/LukeSmithxyz/mutt-wizard/commit/9662299d4e508f4c6706c7c6709730f06e60aa52 which I mentioned in the original post.

**Comment by LukeSmithxyz** [comment]
Check if it's fixed now. I dusted off my old Gmail to test it and it works for me.

I'm just going to get rid of the mailbox flattening altogether and let it mimic the native directories. The only reason I had it set any other way in the past is because the script did some other things differently, but I don't think it's relevant now.

**Comment by PRESFIL** [comment]
I think that ignoring intermediate directories ([a95ff5a](https://github.com/LukeSmithxyz/mutt-wizard/commit/a95ff5a471a991ba3acfc5995141fef85a37209a)) is not correct. A folder can contain both a child folder and mail. Here for example is a folder in my mailbox:

```sh
...
├── Drafts
│   ├── cur
│   ├── new
│   ├── template
│   │   ├── cur
│   │   ├── new
│   │   └── tmp
│   └── tmp
...
```

Is there any meaning from `grep -v HasChildren`? Something doesn't work without it? What does it do?
