### ISSUE TITLE
~/.mail/"account-name"/INBOX is not a mailbox

### ISSUE THREAD

**Issue by AxelBohm** [LukeSmithxyz/mutt-wizard#65]
In my "account-name".muttrc file was the following line:
set spoolfile = "+INBOX"
Somehow mutt is here case sensitive but changing it to 
set spoolfile = "+Inbox"
resolved the issue. 
(this only happened for my ymail account)

Interestingly enough for my other account it has to be all caps..

**Comment by LukeSmithxyz** [comment]
Yes. This is account dependent. 99% of services use `INBOX` as the inbox, but some others use a different capitalization scheme. What mail service are you using?

Originally, the Inbox was "automatically" detected, but the algorithm for detecting it didn't work properly in a lot of cases, so it's now assumed that `INBOX` is the correct value. I'll probably add in an ad hoc fix for this when I get the chance.

**Comment by LukeSmithxyz** [comment]
Okay, this should be fixed now. The script will now autodetect the Inbox regardless of capitalization. There's another kind of Inbox error, feel free to open another Issue.
