### ISSUE TITLE
Can't sync. fcron is not running

### ISSUE THREAD

**Issue by davisi3** [LukeSmithxyz/mutt-wizard#652]
Hi! I really like mutt-wizard but I can't sync automatically. I did `big sync` and got all my mails which is great. I wanted to set automatic sync every 1 minute but I got this:

~ took 2s ❯ mw -t 1
2021-02-16 23:16:36  INFO listing davis's fcrontab
Adding automatic mailsync every 1 minutes...
2021-02-16 23:16:36  INFO installing file /tmp/tmp.Zc0C5CKcVk for user davis
fcron is not running :
  modifications will be taken into account at its next execution.

I also sent test mail and I didn't recieve it.

**Comment by LukeSmithxyz** [comment]
Well, read your error message. Seems that your cronmanager isn't running, so you might want to start its system service.

On your failure to send, did the mail go to Junk or was it not received at all? What email provider do you have?

**Comment by davisi3** [comment]
It works perfectly :) I had to start cron service as you said. I write this from neomutt. wizard is great! Have a nice day, Luke! :)
