### ISSUE TITLE
gpg: decryption failed: No secret key

### ISSUE THREAD

**Issue by arawnx** [LukeSmithxyz/mutt-wizard#653]
Upon running `mw -y`, the error `gpg: decryption failed: No secret key` is returned. 

`gpg --list-secret-keys` returns:

```/home/narmyl/.gnupg/pubring.kbx
-------------------------------
sec   ... [SC]
      ...
uid           [ultimate] ... <...@gmail.com>
ssb   ... [E]
```

The solution proposed in #98 does not work.

**Comment by LukeSmithxyz** [comment]
Do you get the same error when you run `gpg -d ~/.loca/share/muttwizard/your@email.com`?

**Comment by arawnx** [comment]
That directory does not exist on my machine (Arch, running a fresh-ish install of LARBS). `~/.local/share/mail` has something similar, but nothing ending in `.gpg`.

**Comment by LukeSmithxyz** [comment]
Sorry, I'm stupid, that's the old location.

Try: `gpg -d ~/.password-store/your@email.com.gpg`

**Comment by arawnx** [comment]
This solves the issue (although I'm not sure how long that'll last—updates soon).

Future readers should note that I could only find this file in `~/.local/share/password-store/<so-and-so>@gmail.com.gpg`

**Comment by LukeSmithxyz** [comment]
Ah I see. This is nearly certainly causing people's issue in https://github.com/LukeSmithxyz/mutt-wizard/issues/650 too. I'll take care of it.

**Comment by LukeSmithxyz** [comment]
Wait, are you using LARBS as well?

**Comment by arawnx** [comment]
Yes I am

**Comment by arawnx** [comment]
This error returns after just a few minutes. Is there a way for the `gpg -d` command to be made to stay permanently?

**Comment by LukeSmithxyz** [comment]
Oh. Install and configure pam-gnupg. See the readme.

Looks like you for some reason don't have pinentry or a prompt to unlock
your gpg key.

**Comment by arawnx** [comment]
What service in `/etc/pam.d` should I add the `pam-gnupg` whitelist to?
