### ISSUE TITLE
backup script for maildirs?

### ISSUE THREAD

**Issue by christopherisnow** [LukeSmithxyz/mutt-wizard#660]
Not an "issue" per se, but I was wondering if Luke has a handy script (or tips) for backing up tarballs of mw-generated accounts in .local/share/mail.

It took me a while to figure out that naked maildirs shouldn't be copied with rsync along with the rest of the /home directory to an external hard drive. So far I've just been making a single tarball of the entire .local/share/mail folder and including that with the /home backup... perhaps there is a better way which assumes the directory structure automatically set up by mw?

**Comment by LukeSmithxyz** [comment]
This isn't really worth including in this project. I use rsync for all of this.
