### ISSUE TITLE
`redacted` is not a valid email address. Please retype the address:

### ISSUE THREAD

**Issue by GeorgiKarapetrov** [LukeSmithxyz/mutt-wizard#663]
$ `mw -a redacted`

> grep: Invalid range end
> \`redacted\` is not a valid email address. Please retype the address:`

The redacted address is valid, like bla@bla.bla.

My version of grep:
$  `grep --version | head -n 1`
>grep (GNU grep) 3.6

I noticed in the mw file, line 186, in `askinfo()`
`	while ! echo "$fulladdr" | grep -qE "^.+@.+\.[A-z]+$"; do`

The expression could be `"^.+@.+\.[a-Z]+$"` but maybe I am missing something.

(Off topic: I just want you to know that I appreciate the NotRelated rubric very much)

**Comment by LukeSmithxyz** [comment]
Does it work when you manually retype it when prompted?

What shell are you using? I suppose one of the characters in your email could be interpreted as special. If you quote the email address in the shell command does it work?

**Comment by GeorgiKarapetrov** [comment]
I am using `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`

I did not work for me when I manually retype or quote the address.

If you will see the output of `mw -a redacted`, it is `grep: Invalid range end`.
So it did work for me when I changed the script on line 186 with [a-Z] in place of [A-z]

I've never done a merge, but I can find out how and do a merge request if you want.

**Comment by GeorgiKarapetrov** [comment]
For some obscure reason my instance of grep thinks that `[a-Z]` is valid range, while [A-z] is not. This is an issue with my installation of grep.

**Comment by LukeSmithxyz** [comment]
Well, I'm sort of curious what the underlying problem might be because another person had emailed me with this issue. What distro are you using?

**Comment by GeorgiKarapetrov** [comment]
I'm using ArcoLinux. It's an Arch installer with a couple of custom repos on top.

grep is from the core Arch repo.

I curious myself, so please, let me know if you have an idea to get to the bottom of this.

**Comment by Kr1ss-XD** [comment]
I think this has something to do with the locale. UTF-8 seems to sort uppercase characters before lowercase.

I'm also on Arch, and `grep '[A-z]'` gives me that error on my default UTF-8 locale. If I set the locale to something without UTF-8, the command works. E.g.

```sh
LANG=C grep '[A-z]'
```

I'd suggest to either use d default locale (like `C`) with the grep commands, or to use

```sh
grep '[A-Za-z]'
```

**Comment by LukeSmithxyz** [comment]
I've already changed it to `[A-Za-z]` in the script. `[A-z]` works here where I have `LANG=en_US.UTF-8`.

**Comment by Kr1ss-XD** [comment]
:+1:
I missed that, sorry.

**Comment by GeorgiKarapetrov** [comment]
Like I said, LANG=en_US.utf8

I have a response from the grep team:

> My installation of grep thinks [a-Z] is a valid range, while [A-z] is not.

"That's because 'a' collates before 'Z' in your locale, but 'A' does not
collate before 'z'. If that's not what you want you can change your
locale, e.g., by setting LC_ALL="C" in your environment."
