### ISSUE TITLE
Mailbox not found

### ISSUE THREAD

**Issue by jblogs** [LukeSmithxyz/mutt-wizard#665]
Hi Luke

I have been using neomutt for sometime, there was an existing neomutt config...

Installed  mutt--wizard and setup an email account and sync'd it, all okay mail downloaded to mailbox...

started mutt and it does not find the the mailbox I get the error
Unable to open mailbox /var/spool/mail/paul

I have uninstalled neomutt and mutt-wizard removed all the old config files 
~/.config/mutt ~/.config/msmtp ~/.msmtprc ~/.offlineimaprc ~/.config/offlineimap ~/.mbsyncrc

Started all over and still get the same 
Unable to open mailbox /var/spool/mail/paul

Any idea what I am doing wrong......

**Comment by LukeSmithxyz** [comment]
Do you happen to have another muttrc that might override the one created
by the script, for example, in ~/.muttrc?

**Comment by jblogs** [comment]
No,  I deleted all the old configs

forgot to say I'm using LARBS

**Comment by LukeSmithxyz** [comment]
Do you have a `muttrc` file generated after the script? Does it source your primary mail account file in `~/.config/mutt/accounts/`?

**Comment by jblogs** [comment]
Yes it does 

mutt is reading the config file it has your key bindings,  I have created 2 accounts and pressing i1 and i2 switches accounts but mutt says no mailbox is open and INDEX is not listed

**Comment by jblogs** [comment]
I have installed / uninstalled this a number of times now removing all of the config files and mail data.  
When I start mutt either with neomutt or just mutt I get the error:
Unable to open mailbox /var/spool/mail/paul

What I have found is that installing mutt-wizard from the AUR puts its config files in 
/usr/local/share/mutt-wizard/mutt-wizard.muttrc 
and mutt-wizard-git puts them in 
/usr/share/mutt-wizard/mutt-wizard.muttrc then mutt gives an error not finding 
/usr/local/share/mutt-wizard/mutt-wizard.muttrc

I am getting an error when mw -Y 
IMAP error: mailbox name INBOX.xx contains server's hierarchy delimiter

I don't know what this error is but dunst gives a message that I have new emails when it completes 

I cannot think of anything else to try?

**Comment by LukeSmithxyz** [comment]
If you're switching between manual installation and the AUR, you'll have to manually change where it sources `mutt-wizard.muttrc`. The location is determined on the initial run and the AUR build and make install will install to different locations.

Yeah, the delimiter issue rears its head again again. That potentially made it impossible to detect the proper INBOX, hence your problem. Can you give me the contents of `~/.local/share/mail/your@email.com`?

**Comment by jblogs** [comment]
Thanks Luke

I think I am finally getting somewhere.  and its down to how the proper INBOX is detected

My servers INBOX is just 
INBOX
Archive
Drafts
Junk
Sent
Trash
the INBOX.X do not exist and I think when mutt starts and cannot find these it defaults to
 mailbox /var/spool/mail/pau

Do I change the settings in .mbssyncrc to detect the proper INBOX?

~/.local/share/mail/your@email.com
Archive
Drafts
INBOX
INBOX.Archive
INBOX.Drafts
INBOX.Junk
INBOX.Sent
INBOX.spam
INBOX.Trash
Junk
Sent
spam
Trash

**Comment by LukeSmithxyz** [comment]
Oh. So it looks like you removed the config files, but not the old mail directories from a previous run before the delimiter change. Delete or back up the mail archive and re-add the account and see what happens.

**Comment by jblogs** [comment]
Thank you Luke

I have edited the account config files so as they use the correct mailboxes and all is well now.

I did delete the old mail directories prior to re-installing, those are all the files that the mail sync created with:
mw -y me@email.com 

Cheers and thanks again for your help
