### ISSUE TITLE
header_cache: unknown variable

### ISSUE THREAD

**Issue by mbrohl** [LukeSmithxyz/mutt-wizard#666]
Hi,

I'm new to neomutt and mutt-wizard and have setup my first email account using the wizard (latest git clone install), with no problems.
Now when I start neomutt, I got the following error message (translated):

Error in /Users/<user>/.config/mutt/accounts/1-mail@domain.tld.muttrc, line 8: header_cache: unknown variable
Error in /Users/<user>/.config/mutt/muttrc, line 5: source: file /Users/<user>/.config/mutt/accounts/1-mail@domain.tld.muttrc could not be read
source: Error in /Users/<user>/.config/mutt/muttrc

The corresponding entry generated by mutt-wizard in the config file is:

set header_cache = /Users/<user>/.cache/mutt-wizard/mail@domain.tld/headers

$ neomutt -v
NeoMutt 20200925

(installed through mac ports)

Any idea what could be wrong?

Thanks,
Michael

**Comment by LukeSmithxyz** [comment]
Well my first reflex would be to say that you have an older version of neomutt which might not have that variable, but I'm pretty sure it's been in there fine since way before 2020.

I'm not sure how mac ports work, but if there is a way of getting a more recent version of the program I would.

I will say that that particular line is non-essential for most use-cases, so if nothing else, you can feel free to just delete it from the file. It is just supposed to speed up online connections.

**Comment by mbrohl** [comment]
Wow, thanks for the lightning speed response!

Just spotted this (neomutt -v):

compile settings:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme -gss -hcache -homespool +idn -inotify
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex -sasl
  +smime -sqlite +start_color +sun_attachment +typeahead

Just a guess, but could it be that the -hcache setting causes neomutt to have no header_cache support?

I think I can remove the line in the neomutt settings for now, thanks again!

**Comment by mbrohl** [comment]
Just in case this is helpful for others too: https://trac.macports.org/ticket/57972

**Comment by LukeSmithxyz** [comment]
Ah, you know what, that must be it. My build is `+hcache` (and I suppose every other main build because I haven't heard of this issue before).

**Comment by mbrohl** [comment]
Confirmed: you have to install the mac port with a database variant like mentioned in the issue link in my comment before:

sudo port install neomutt +db4 

instead of 

sudo port install neomutt

solved the issue for me. I git +hcache and the error is gone. Case closed :-)

Thanks again!
