### ISSUE TITLE
Protonmail with Bridge: msmtp: cannot use a secure authentication method

### ISSUE THREAD

**Issue by pauljamesharper** [LukeSmithxyz/mutt-wizard#667]
I can receive Protonmail emails. But I cannot send them . I also notice that both Protonmail and Gmail are getting Permission Denied errors trying to log to /home/user/.config/msmtp/msmtp.log,

How can I troubleshoot this?  Below is debug output sending from Protonmail to Gmail. 

` $ echo "Hello this is sending email using msmtp" | msmtp --debug -a user@protonmail.ch userj@gmail.com
ignoring system configuration file /etc/msmtprc: No such file or directory
loaded user configuration file /home/user/.msmtprc
using account user@protonmail.ch from /home/user/.msmtprc
host = 127.0.0.1
port = 1025
source ip = (not set)
proxy host = (not set)
proxy port = 0
timeout = off
protocol = smtp
domain = localhost
auth = choose
user = user@protonmail.ch
password = *
passwordeval = pass user@protonmail.ch
ntlmdomain = (not set)
tls = off
tls_starttls = on
tls_trust_file = /etc/ssl/certs/ca-certificates.crt
tls_crl_file = (not set)
tls_fingerprint = BE:EC:E1:8A:C4:9C:BA:7C:C6:4E:3B:B9:82:29:8B:FB:5D:90:E4:F5:35:E1:49:53:A5:58:54:8E:B4:E4:97:7B
tls_key_file = (not set)
tls_cert_file = (not set)
tls_certcheck = on
tls_min_dh_prime_bits = (not set)
tls_priorities = (not set)
auto_from = off
maildomain = (not set)
from = user@protonmail.ch
add_missing_from_header = on
add_missing_date_header = on
remove_bcc_headers = on
dsn_notify = (not set)
dsn_return = (not set)
logfile = /home/user/.config/msmtp/msmtp.log
logfile_time_format = (not set)
syslog = (not set)
aliases = (not set)
reading recipients from the command line
<-- 220 127.0.0.1 ESMTP Service Ready
--> EHLO localhost
<-- 250-Hello localhost
<-- 250-PIPELINING
<-- 250-8BITMIME
<-- 250-ENHANCEDSTATUSCODES
<-- 250-CHUNKING
<-- 250-STARTTLS
<-- 250 AUTH LOGIN PLAIN
msmtp: cannot use a secure authentication method
msmtp: could not send mail (account user@protonmail.ch from /home/user/.msmtprc)
msmtp: cannot log to /home/user/.config/msmtp/msmtp.log: cannot open: Permission denied
msmtp: log info was: host=127.0.0.1 tls=off auth=on user=user@protonmail.ch from=user@protonmail.ch recipients=user@gmail.com errormsg='cannot use a secure authentication method' exitcode=EX_UNAVAILABLE
`

**Comment by pahlse** [comment]
I have the exact same issue

**Comment by pahlse** [comment]
$ echo "Hello this is sending email using msmtp" | msmtp --debug -a user@protonmail.ch user@protonmail.ch
ignoring system configuration file /etc/msmtprc: No such file or directory
loaded user configuration file /home/user/.config/msmtp/config
using account user@protonmail.ch from /home/user/.config/msmtp/config
host = 127.0.0.1
port = 1025
source ip = (not set)
proxy host = (not set)
proxy port = 0
socket = (not set)
timeout = off
protocol = smtp
domain = localhost
auth = choose
user = user@protonmail.ch
password = *
passwordeval = pass user@protonmail.ch
ntlmdomain = (not set)
tls = off
tls_starttls = on
tls_trust_file = /etc/ssl/certs/ca-certificates.crt
tls_crl_file = (not set)
tls_fingerprint = A8:52:4B:51:B4:A5:7A:EF:8F:99:39:B5:E6:1B:43:67:21:F7:79:7F:AA:D8:3A:8D:22:23:3E:29:1E:E5:91:44
tls_key_file = (not set)
tls_cert_file = (not set)
tls_certcheck = on
tls_min_dh_prime_bits = (not set)
tls_priorities = (not set)
tls_host_override = (not set)
auto_from = off
maildomain = (not set)
from = user@protonmail.ch
set_from_header = auto
set_date_header = auto
remove_bcc_headers = on
undisclosed_recipients = off
dsn_notify = (not set)
dsn_return = (not set)
logfile = /home/user/.config/msmtp/msmtp.log
logfile_time_format = (not set)
syslog = (not set)
aliases = (not set)
reading recipients from the command line
<-- 220 127.0.0.1 ESMTP Service Ready
--> EHLO localhost
<-- 250-Hello localhost
<-- 250-PIPELINING
<-- 250-8BITMIME
<-- 250-ENHANCEDSTATUSCODES
<-- 250-CHUNKING
<-- 250-STARTTLS
<-- 250 AUTH PLAIN LOGIN
msmtp: cannot use a secure authentication method
msmtp: could not send mail (account user@protnmail.ch from /home/user/.config/msmtp/config)`

**Comment by LukeSmithxyz** [comment]
Eh, the issue is that msmtp is understandably picky about sending when you have no encryption to the server. In this case, since Protonmail Bridge is local, it refuses to send.

There is probably a setting to ignore this safety check, but I don't know it off the top of my head. I'll add it for Protonmail users when I run across it.

**Comment by LukeSmithxyz** [comment]
Adding `tls off` explicitly to the Protonmail block in the msmtp config *might* do it. I don't have PM so I can't check myself.

**Comment by pahlse** [comment]
I tried adding `tls off` with no luck. Strangly enough everything worked fine untill about 3 days ago.

**Comment by pahlse** [comment]
> Eh, the issue is that msmtp is understandably picky about sending when you have no encryption to the server. In this case, since Protonmail Bridge is local, it refuses to send.

Shouldn't the encyription not be a problem with PM bridge being local?

**Comment by LukeSmithxyz** [comment]
Lack of encryption is no problem here, but msmtp has a lot of extra safety checks built in to avoid user stupidity. E.g. they also require any config file that has a plaintext password to have restrictive permissions. We just need to turn the check off, but I don't immediately see a way to in the manual

**Comment by pauljamesharper** [comment]
Luke's comment gave me a clue. As did yours pahlse:

Basically I got it working with the same config as per msmtprc on davmail. And yes the risk of certificates is accepted because you are doing the connection locally on your machine. 

Forgot to mention I am on Debian 10.

My working config is sending email okay now. This would also work for Outlook 365 people using Davmail.  But I am still getting the weird:

`msmtp: cannot log to /home/username/.config/msmtp/msmtp.log: cannot open: Permission denied
`

Working config below. 
```
account username@protonmail.ch
host 127.0.0.1
port 1025
protocol smtp
from username@protonmail.ch
user username@protonmail.ch
passwordeval "pass username@protonmail.ch"
auth login
```

**Comment by LukeSmithxyz** [comment]
Are both the `protocol smtp` and `auth login` lines necessary? Can you remove the `protocol` line or either change the `auth` line to `auth on` (or delete it)?

**Comment by Kr1ss-XD** [comment]
@pauljamesharper 

Assuming your `~/.config/msmtp` is actually write protected, you might get rid of that error if you set
```conf
logfile		/var/log/mail/msmtp.log
```
or to some other writeable location in the global section of your config.

**Comment by pahlse** [comment]
Thank you pauljamesharper for posting your config. In the end I needed to change `auth on` to `auth login`. That did the trick. All the rest can be left unchanged.
Here is my config for sake of completion:

```
account user@protonmail.ch
host 127.0.0.1
port 1025
from user@protonmail.ch
user user@protonmail.ch
passwordeval "pass user@protonmail.ch"
auth login
tls_fingerprint A8:52:4B:51:B4:A5:7A:EF:8F:99:39:B5:E6:1B:43:67:21:F7:79:7F:AA:D8:3A:8D:22:23:3E:29:1E:E5:91:44
tls_trust_file	/etc/ssl/certs/ca-certificates.crt
logfile /home/elias/.config/msmtp/msmtp.log
```
