### ISSUE TITLE
mw add not working for me

### ISSUE THREAD

**Issue by Vikthor1** [LukeSmithxyz/mutt-wizard#668]
Hi there,

Full disclosure. I am new to Terminal/Alacritty/Fish Unix environment. I have a MacBook Pro 2020 Intel, with macOS Sur 11.2. I am currently running Brast-McKie's Nvim/Latex build for my academic writing, so wanted to add the email functionality to my NeoVim workflow.

Problem I can't add an email account using the mw add command.

- I installed mutt-wizard from your GitHub.
- Tried the 'mw add' command to add an account and it just brings me back to the main mw page.
- So I manually brew installed all the needed Dependencies (neomutt, curl, isync, smtp, pass).
- Closed Terminal.
- Tried again the 'mw add' command and still nothing.
- I also was able to generate the gpg key (although to be honest I don't know if I did it right) and still was not able to add an email account.

**Comment by LukeSmithxyz** [comment]
Commands have changed, as the help menu that keeps appearing in your face tells you. Read it or the manual.

**Comment by Vikthor1** [comment]
I did tried 
-a + my email and it tells me unknown command.

**Comment by Kr1ss-XD** [comment]
@Vikthor1 :  Please try `mw -a` instead of just `-a`.

The options listed in the help menu are meant to be used in combination with the program name, not standalone.

Also, please consult the [README](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/README.md).
