### ISSUE TITLE
integration with pass is not working properly for macOS. Consider changing to built-in keychain?

### ISSUE THREAD

**Issue by Vslow** [LukeSmithxyz/mutt-wizard#669]
Updates results in error:
> Skipping account XXXX, PassCmd exited with status 2

Sending email results in error:
> gpg: decryption failed: No secret key

May be consider changing for macOS to the built-in keychain commands:
- Setting the password `security add-generic-password -w -a [email address] -s [service, e.g. "mutt"]`
- Reading the password `security find-generic-password -w -a [email address] -s [service, e.g. "mutt"]`

**Comment by LukeSmithxyz** [comment]
Well, do you have a gpg secret key linked up with pass? If so, it might be that MacOS stores this in an idiosyncratic place, but I haven't heard of anyone else having this issue.

**Comment by Vslow** [comment]
If I request the password myself with `pass XXX@XXX` — there is a prompt to provide passphrase to unlock OpenGPG secret key and the password is successfully provided. And after I provide the passphrase, automated requests from mbsync or msmtp start to work for some time as well. When the time is reached to request the passphrase again, it stops working again.

I guess there is something wrong with prompting the passphrase to unlock OpenGPG secret key. Does the set up support it?

**Comment by f380cedric** [comment]
Seems related to https://github.com/LukeSmithxyz/mutt-wizard/issues/445#issuecomment-635899551 .
If the update is done in a background job not attached to a terminal, then It cannot request your passphrase without a GUI pinentry.
If it is done while attached to a terminal, maybe `GPG_TTY` is not set.
Either case, [increasing password cache](https://wiki.archlinux.org/index.php/GnuPG#Cache_passwords) or using [pam-gnupg](https://github.com/cruegge/pam-gnupg) should help.

**Comment by Vslow** [comment]
Thanks for answer. It is not working sending email and updating with `mw -Y`, so it is not working attached to a terminal. I am not really interested in using a background job.

I tried setting GPG_TTY, it didn’t help.

Using pam-gnupg should help, but I don’t see it as a solution. I don’t want to change my GPG configuration as I use it for other things. I’d rather use built-in tool for this specific use case abiding Unix philosophy. Do you mind me making a pull request to change it for macOS?

**Comment by soenkewindhausen** [comment]
I do have the same problem on Mac OS Big Sur. 
`gpg: Entschlüsselung fehlgeschlagen: No secret key`

Thanks for the help. I am nor sure what to do next...

**Comment by paulofaria** [comment]
@LukeSmithxyz what do you think about @Vslow's PR offer of using macOS's builtin keychain? I'm having the same issue, unfortunately. Thank you for this project, by the way.

**Comment by LukeSmithxyz** [comment]
I don't have mac or know anything about the different ways they do everything. If someone makes a PR on this that alleviates it for Mac users, I will add it provided it is simple.
