### ISSUE TITLE
New mails not being downloaded

### ISSUE THREAD

**Issue by cmF3** [LukeSmithxyz/mutt-wizard#670]
* Severside an emailwiz current master is running
* Clientside mutt-wizzard current master is used

When running mbsync or mw and new mail is present mbsync reports '1 mail added to database' but no mail is actually downloaded.

I have nailed down the problem by running mbsync -Dn to this:

```
Opening master box INBOX...
>>> 4 SELECT "INBOX"
Opening slave box INBOX...
[...]
Loading slave...
slave: 0 messages, 0 recent
* 1 FETCH (UID 1 FLAGS ())
* 2 FETCH (UID 2 FLAGS ())
* 3 FETCH (UID 3 FLAGS ())
* 4 FETCH (UID 4 FLAGS ())
* 5 FETCH (UID 5 FLAGS ())
5 OK Fetch completed (0.001 + 0.000 secs).
master: 6 messages, 0 recent
Synchronizing...
>>> 6 CLOSE
6 OK Close completed (0.001 + 0.000 secs).

```
The 5 FETCH commands with empty flags are 5 mails received by the server but not  being downloaded by mbsync.

Now in comparision on a healthy server mbsync -Dn looks like this

```
>>> 5 SELECT "INBOX"
Opening slave box INBOX...
[...]
Loading slave...
slave: 1102 messages, 0 recent
* 1 FETCH (UID 3161 FLAGS (\Seen NonJunk))
* 2 FETCH (UID 3162 FLAGS (\Seen))
* 3 FETCH (UID 3163 FLAGS (\Seen NonJunk))
* 4 FETCH (UID 3168 FLAGS (\Seen $label2 NonJunk))
[...]
* 100 FETCH (UID 610 FLAGS (\Seen))
56 OK Fetch completed.
master: 100 messages, 0 recent
Synchronizing...
>>> 57 CLOSE
57 OK Close completed.

[...]
```

As is obvious the email FLAGS field for the emailwiz server is empty while for the healthy server it is not. I strongly suspect that this is the issue.

However I don't know how to go forward from here. What are these FLAGS where are they coming from and why are they not set? Is this an emailwiz (dovecot?) issue?

**Comment by cmF3** [comment]
I just checked using a different mail client than mbsync and it downloads the emails just fine. So this must be an issue with mbsync

**Comment by LukeSmithxyz** [comment]
Have you had mutt-wizard installed for a while and just upgraded or did you just install this all?

**Comment by cmF3** [comment]
I have it installed for a while.

**Comment by LukeSmithxyz** [comment]
Okay. That might be it then. There have been some changes to how
mailboxes are detected and added which might interfere with previous
installs.

I recommend backing up your ~/.local/share/mail directories, then
deleting your accounts and readding them (possibly just deleting all old
mbsync/mutt/msmtp configs as well if that doesn't work).

It might be that as is, mw is getting confused with files from an
earlier version.

**Comment by cmF3** [comment]
I deleted
* ~/.local/share/mail
* ~/.mbsyncrc
* ~/.config/msmtp

and then recreated both email accounts from scratch. Now it works.
