### ISSUE TITLE
Some strange fold prefix with &?

### ISSUE THREAD

**Issue by nations-Xiong** [LukeSmithxyz/mutt-wizard#672]
When I open neomutt, I get some strange folds start with &.
![image](https://user-images.githubusercontent.com/57881922/110238578-534b1080-7f7d-11eb-9514-077fa9ba8e99.png)

**Comment by PRESFIL** [comment]
`isync` now does not supports mailboxes with nonlatin cymbols. In IMAP nonlatin symbols encoded with *IMAP's modified utf-7 encoding*, but `isync` now just ignores them. It is not `mw`'s bug.

Links:

* https://github.com/LukeSmithxyz/mutt-wizard/issues/149#issuecomment-488390918
* https://sourceforge.net/p/isync/bugs/47/
* https://sourceforge.net/p/isync/isync/merge-requests/3/

**Comment by OctopusET** [comment]
They merged PR. isync will be fixed soon.

**Comment by PRESFIL** [comment]
Could you please show link to the commit? I couldn't find anything similar. :eyes:

**Comment by OctopusET** [comment]
@PRESFIL https://sourceforge.net/p/isync/isync/merge-requests/3/
I thought it was merged but it wasn't. Sorry. You can try https://aur.archlinux.org/packages/isync-utf8-mailboxes/  If you are using arch based distro. Even if you aren't, that package is just using utf8 branch, so you could build it.

Mailbox names are fine with that branch.

**Comment by PRESFIL** [comment]
Oh, I already knew about this package. I'm just waiting for it to finally be accepted in the upstream.

**Comment by plokid** [comment]
Is this problem really solved?
