### ISSUE TITLE
Maybe not an issue???

### ISSUE THREAD

**Issue by kcallis** [LukeSmithxyz/mutt-wizard#673]
I was looking at my gmail account and in my All Mail, it states that I have about 120000 messages. I looked at the Pattern section in my mbsyncrc and noticed that there was an !"[Gmail]/All Mail", so it would seem that mbsync is blocking sync with my All Mail.

Now is there a reason that I can't get all of my All Mail messages synced to my laptop or am I missing something?

**Comment by LukeSmithxyz** [comment]
All Mail is a useless Gmail tag that doubles up all your email in an extra place. You can remove the restriction in the mbsync config file if you want, but you'll just be getting duplicates of all your other mail in an extra mailbox.
