### ISSUE TITLE
readlink illegal option on MacOS (big sur)

### ISSUE THREAD

**Issue by converge** [LukeSmithxyz/mutt-wizard#676]
Hi,
thanks for the awesome tool!

I'm using big sur and I wasn't able to download emails with the "o" option inside neomutt, the output was something like:

```
❯ neomutt
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

To fix this I did:
```
1. brew install coreutils
2. in the file /usr/local/bin/mailsync
3. I changed the line from
```

```bash
case "$(readlink -f /sbin/init)" in
```

to
```bash
case "$(greadlink -f /sbin/init)" in
```

I thought to create a PR, but don't know how we should handle the "coreutils" installation steps.

**Comment by soenkewindhausen** [comment]
I have the same Problem on Big Sur. 
`readlink: illegal option -- f
usage: readlink [-n] [file ...]
/usr/local/bin/mailsync: line 59: mbsync: command not found
`

@converge, installing coreutils and changing that file name did not work for me.  

this line (59) seems to be the problem

`   if [ -z "$opts" ]; then mbsync "$acc"; else mbsync "$opts" "$acc"; fi`

Thank you for your help

**Comment by converge** [comment]
@soenkewindhausen in your case sounds like `mbsync` is missing, are you able to run it via command line?
`mbsync -a` should download your emails if your account is properly setup.

**Comment by soenkewindhausen** [comment]
of course... Thank you very much! noob mistake. But i am trying :)

**Comment by LukeSmithxyz** [comment]
Okay. Since this line isn't relevant on Mac OS anyway I'll condition it or at least suppress the error.
