### ISSUE TITLE
.mbsync under .config not found

### ISSUE THREAD

**Issue by vod3** [LukeSmithxyz/mutt-wizard#677]
hey,

I used the `mw -t 15` option to add a cronjob, which seems to be working, but I got this error message in `systemctl status cronie`

`Mar 16 23:30:01 arch-laptop CROND[15000]: (user) CMDOUT (awk: fatal: cannot open file "/home/user/.mbsyncrc" for reading: No such file or directory)`

I'm using the MBSYNCRC Variable in my zshenv:
`export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"`

what am I missing?
thank you

**Comment by LukeSmithxyz** [comment]
Should be fixed now; get the newest commits.

Login/profile files have to be manually checked for environmental
variables. ~/.zshenv was not included in the filelist, but it is now.
