### ISSUE TITLE
gnupg pubring missing

### ISSUE THREAD

**Issue by vod3** [LukeSmithxyz/mutt-wizard#678]
after updating from mutt-wizard to mutt-wizard-git an hour ago, the gpg decryption stopped working:

```
Mar 17 01:00:01 arch-laptop CROND[22904]: (user) CMD (/usr/bin/mailsync)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) CMDOUT (gpg: keyblock resource '/gnupg/pubring.kbx': No such file or directory)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) CMDOUT (gpg: decryption failed: No secret key)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) Mar 17 01:00:01 arch-laptop CROND[22904]: (user) CMD (/usr/bin/mailsync)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) CMDOUT (gpg: keyblock resource '/gnupg/pubring.kbx': No such file or directory)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) CMDOUT (gpg: decryption failed: No secret key)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) CMDOUT (Skipping account mail-remote, PassCmd exited with status 2)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) CMDOUT (No new mail.)
Mar 17 01:00:01 arch-laptop CROND[22901]: pam_unix(crond:session): session closed for user
Mar 17 01:00:13 arch-laptop CROND[22902]: pam_unix(crond:session): session closed for user CMDOUT (Skipping account mail-remote, PassCmd exited with status 2)
Mar 17 01:00:01 arch-laptop CROND[22901]: (user) CMDOUT (No new mail.)
Mar 17 01:00:01 arch-laptop CROND[22901]: pam_unix(crond:session): session closed for user
Mar 17 01:00:13 arch-laptop CROND[22902]: pam_unix(crond:session): session closed for user
```

pam-gnupg and other gpg related programs work without any problems.
~/.local/share/gnupg/pubring.kbx exists

.zshenv contains:
```
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
```

**Comment by Kr1ss-XD** [comment]
Thank you @vod3. Could you please update `mutt-wizard-git` and try if that error has been resolved ?
Luke has [committed](https://github.com/LukeSmithxyz/mutt-wizard/commit/b9b3f7f685e4690a6756102e312172ee0830d016) a bug fix just about the time you switched packages.

I suspect the checkout you installed was from _before_ that commit.

**Comment by vod3** [comment]
Thanks Kriss,

I already used this commit, since I had a problem with the mbsync config, which was resolved by luke. But since then the gpg decrypt fails.

**Comment by Kr1ss-XD** [comment]
Let's see, obviously the cron job cannot locate the gnupg folder correctly. It looks at `/gnupg/pubring.kbx` - which suggests that the `$XDG_DATA_HOME` variable is not set in its environment.

If that's the (only) cause, you should be good after changing the `GNUPGHOME` definition in your shell config to something like : 

```sh
export GNUPGHOME="${XDG_DATA_HOME:-${HOME:/home/$LOGNAME}/.local/share}/gnupg"
```

**Comment by vod3** [comment]
Thank you for your answer, it worked!
Although I had to remove the /home/$LOGNAME, resulting in this line:
`export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"`

I initially thought that my
`export XDG_DATA_HOME="$HOME/.local/share"`
line would be enough, but I wonder why that doesn't work gnupg to be detected.

But again, thanks!

**Comment by Kr1ss-XD** [comment]
Thx for your feedback.

>I wonder why that doesn't work for gnupg to be detected.

Most likely because the code in the [mailsync](https://github.com/LukeSmithxyz/mutt-wizard/blob/b74966fa92475c5e21ad07a1b856e8b111c09a7b/bin/mailsync#L23) script does not source the full configuration but evaluates some variable assignments selectively.

In your `zshenv`, the definition of `GNUPGHOME` depends on another variable (`XDG_DATA_HOME`), which is **unset** in the context of `mailsync` when it's running as a cronjob.

My PR _should_ fix this.
