### ISSUE TITLE
.mbsyncrc: unknown keyword

### ISSUE THREAD

**Issue by longestmt** [LukeSmithxyz/mutt-wizard#682]
![image](https://user-images.githubusercontent.com/1509654/111730089-06055380-8847-11eb-87d9-eb6db673aef6.png)
Experienced an issue with my mbsync not running due to 'unknown keywords'. I just set mw on a computer the other day so I was confused.

I looked at .mbsyncrc and changed 'Near' (line 20) and 'Far' (line 21) to 'Master' and 'Slave' respectively. This solved the issue. Not sure where the verbiage got mixed up during the setup.

It's a protonmail account.

**Comment by PRESFIL** [comment]
I also tried to search for upstream but found nothing. Could you attach a link here to these changes from upstream?

**Comment by PRESFIL** [comment]
OK, it was very old time ago. [commit](https://sourceforge.net/p/isync/isync/ci/c8f402e43f9c6a3c685fe0f716ffda741beeac13/).
And it seems that this commit provided for backward compatibility.

Compatibility still exists (I just copied the source code and checked it out.). I shouldn't have made these edits too soon. In your distribution, these changes have not yet arrived.

**Comment by PRESFIL** [comment]
@LukeSmithxyz , can you revert these changes before backward compatibility is removed?

**Comment by LukeSmithxyz** [comment]
I guess I can revert these changes for the time being for slow release distros. Everyone else will be getting the annoying message in the meantime.
