### ISSUE TITLE
Can't remove mail accounts.

### ISSUE THREAD

**Issue by TornaxO7** [LukeSmithxyz/mutt-wizard#686]
I'm getting the following error message, if I try to remove a mail client:
![image](https://user-images.githubusercontent.com/50843046/112549027-710dd780-8dbd-11eb-8d0f-745d5b585973.png)

I just added it with `mw -a sambalakuja@gmail.com` and tried to remove it with `mw -d`.

**Comment by LukeSmithxyz** [comment]
You must be using an old version before that message was suppressed.

It is not an actual error either, your account should've been properly deleted.
