### ISSUE TITLE
Permission Issue Creating Temp Email File

### ISSUE THREAD

**Issue by BurnyBoi** [LukeSmithxyz/mutt-wizard#69]
I just successfully added one of my accounts using the wizard, but I noticed that when I attempt to send an email, it tries to make the temp file for the email, and I get a permission denied error, leaving me unable to continue with typing my message. When I exit neomutt, I see an error like the following:

sh: /tmp/neomutt-(blah): Permission Denied

I know this isn't an issue with the wizard, but any ideas why this happens? I'm so close to hopefully sending my first email with neomutt, and I'm stuck on this :/

**Comment by LukeSmithxyz** [comment]
Do you not have write permission on your `/tmp/` directory? What is the output of `ls -ld /tmp/`?

**Comment by BurnyBoi** [comment]
drwxrwxrwt 21 root root 580

That seems to be it then. I'm not familiar with how I would give myself constant write access to it.

**Comment by BurnyBoi** [comment]
Actually, when I look at the permissions again, it implies I do have access. It should be set so "Others" is "Read and Write". I can create a new file from thunar without any issue.

**Comment by LukeSmithxyz** [comment]
What distro are you using? It might be that you're using a distro that requires membership in a group to send mail depending on what build of neomutt you have... You might want to add your user to the `mail` group...

**Comment by BurnyBoi** [comment]
I'm using Parabola, which I happen to know you've used lol. Do you recall having to do this on Parabola?

**Comment by LukeSmithxyz** [comment]
Are you using Parabola OpenRC? If so, you might want to add your user to the mail group.

If you're using systemd Parabola, I'm not quite sure what the problem could be then... You might want to try installing `msmtp` and seeing if that helps (it will be used as the sendmail program).

**Comment by LukeSmithxyz** [comment]
You know what, I realized this could actually be something else: Do you have an `$EDITOR` variable set? The default settings will look to your `$EDITOR` variable for which if unset, the create-mail command will erroneously try to run the temp file as a program, which seems to be your error here.

Try it again after setting your `$EDITOR`.

**Comment by BurnyBoi** [comment]
Yeah, looks like that was it. It's a fairly new installation, so I didn't have it set.

**Comment by LukeSmithxyz** [comment]
Ah okay, great. I've added a note on this to the documentation now.
