### ISSUE TITLE
Suggestion: use implicit TLS for SMTP where possible

### ISSUE THREAD

**Issue by allan2** [LukeSmithxyz/mutt-wizard#692]
[RFC 8314](https://tools.ietf.org/html/rfc8314), released in 2018, says implicit TLS (on 465) is preferred over explicit (on 587).

The RFC states the transition period is "several years".
I think we should try to use implicit TLS where possible and mention it in the README.

Thoughts on setting 465 to the default SMTP port?

`~/.msmtprc`
```
# Sample account as generated when implicit TLS is supported. Works for Gmail
account foo@foo.com
host smtp.foo.com
port 465
from foo@foo.com
user foo@foo.com
passwordeval "pass foo@foo.com"
auth on
tls on               # this is new
tls_starttls_off     # make sure this is here too
tls_trustfile /etc/ssl/certs/ca-certificates.crt
logfile /home/foo/.config/msmtp/msmtp.log
```

**Comment by Thomi7** [comment]
I'm not into email standards but can say that I had a problem with my university account regarding that.

It's smtp on port 465 with tls on. I needed to add the `tls on` to my msmtprc.

**Comment by t-391** [comment]
I also am not familiar with email standards, but for my website host's email, sending email with SSL also required me to have this option in my config file.

**Comment by KesunyianAyam** [comment]
I think we should add a prompt to let users use either port 465 (implicit TLS) or port 587 (explicit TLS) or both, hence following RFC 8314 recommendations.

**Comment by LukeSmithxyz** [comment]
This is now the default setting.

However, many mail services are in domain.csv using 587 ports, which can use 465. If anyone using 465 wants to upgrade their provider, please open a PR making those changes. I might look at it later myself to see who offers implicit TLS now.

**Comment by allan2** [comment]
Thanks!
