### ISSUE TITLE
No inbox if subfolders within inbox

### ISSUE THREAD

**Issue by fr-an-kh** [LukeSmithxyz/mutt-wizard#698]
In some of my accounts (Mailcow) I've created subfolders within my inboxes. This fact leads to the problem that I can't see/navigate to my inbox folder it self. The keybinding 'g' 'i' only brings me into the alphanumeric first subfolder of my inbox.

In ~/.local/share/mail/me@mailbox.com/INBOX/new and ~/.local/share/mail/me@mailbox.com/INBOX/curr the mails are listed.

Is there a way to jump to the inbox itself?

**Comment by PRESFIL** [comment]
Do you mean this:https://github.com/LukeSmithxyz/mutt-wizard/issues/648

**Comment by ank0m** [comment]
> Do you mean this: [#648 (comment)](https://github.com/LukeSmithxyz/mutt-wizard/issues/648#issuecomment-774440455)

Yes, this is the behavior with my accounts which have sub folders within it's inboxes. The mentioned workaround did the trick for now. Thank you, mate.

**Comment by PRESFIL** [comment]
OK, but don't close the question for now, please.

**Comment by PRESFIL** [comment]
@LukeSmithxyz , May I ask what `grep -v HasChildren` was for? As I [wrote](https://github.com/LukeSmithxyz/mutt-wizard/issues/648#issuecomment-774440455), intermediate mailboxes are ignored, but they can contain letters. Some users had problems (#700, this issue).

**Comment by mannp** [comment]
I have the same issue just starting out with mutt wizard and not sure if what i have done is correct?

It seems the Inbox at the root hierarchy has not been created but the subs underneath that have.

I have check and the servers delimiter is a dot. 

`mailboxes **"=Trash" "=Spam" "=INBOX.microsoft-support" "=INBOX.catchall" "=Archives.2020" "=Drafts" "=Junk" "=Sent" "=Archive"`

to

`mailboxes **"=INBOX"** "=Trash" "=Spam" "=INBOX.microsoft-support" "=INBOX.catchall" "=Archives.2020" "=Drafts" "=Junk" "=Sent" "=Archive"`

Any direction would be much appreciated 👍🏻

**Comment by Kr1ss-XD** [comment]
@mannp : Would it work if you change `**"=INBOX"**` to just `"=INBOX"` (and leave the rest of the line as it is) ?

**Comment by mannp** [comment]
> @mannp : Would it work if you change `**"=INBOX"**` to just `"=INBOX"` (and leave the rest of the line as it is) ?

Hi @Kr1ss-XD apologies that's an md formatting issue on my part, I was trying to make the =INBOX bold :-/

I only have this in my account rc file;
`
mailboxes "=INBOX" "=Trash" "=Spam" ....... etc`

**Comment by Kr1ss-XD** [comment]
Oh, I see.

Using that curl command : 

```sh
curl --location-trusted --url imaps://HOST:PORT -su "USER:$(PASSCMD)"
```

(after replacing `HOST`, `PORT`, `USER` and `PASSCMD` with the according values from your `.mbsyncrc` file; for `PASSCMD` only the command without the quotation marks), could you verify that the name of your inbox is actually literally `INBOX` ?

Asking because it might be something like `Inbox` on the server.  The email server I use calls it like this, and I recall having problems until I changed that.  Not sure if that applies to your constellation, but that _might_ be the issue.

**Comment by mannp** [comment]
Thanks for following up @Kr1ss-XD 

This is the output of your command;

```
* LIST (\HasNoChildren \Trash) "." Trash
* LIST (\HasNoChildren \Junk) "." Spam
* LIST (\HasNoChildren) "." INBOX.microsoft-support
* LIST (\HasNoChildren) "." INBOX.catchall
* LIST (\HasChildren) "." Archives
* LIST (\HasNoChildren) "." Archives.2020
* LIST (\HasNoChildren \Drafts) "." Drafts
* LIST (\HasNoChildren \Junk) "." Junk
* LIST (\HasNoChildren \Sent) "." Sent
* LIST (\HasNoChildren \Archive) "." Archive
* LIST (\HasChildren) "." INBOX
```

**Comment by Kr1ss-XD** [comment]
OK, so that proves it's actually `INBOX` all capitals.  I'm afraid I'm out of ideas then, sorry. :pensive: 

I'm considering to setup a scenario like yours in a container plus fresh email account and see if I can reproduce that, to see what can be done about it.  Won't be able do to that today or tomorrow though.

**Comment by mannp** [comment]
> OK, so that proves it's actually `INBOX` all capitals. I'm afraid I'm out of ideas then, sorry. pensive
> 
> I'm considering to setup a scenario like yours in a container plus fresh email account and see if I can reproduce that, to see what can be done about it. Won't be able do to that today or tomorrow though.

Thanks for trying @Kr1ss-XD  :) fyi... its a mail-in-a-box account I am trying to configure.

Let me know if I can try anything else to narrow it down any.

**Comment by PRESFIL** [comment]
@mannp , i think problem in commit a95ff5a.
See [original messege](https://github.com/LukeSmithxyz/mutt-wizard/issues/698#issuecomment-812367596) and links in it.
See also [answer](https://github.com/LukeSmithxyz/mutt-wizard/issues/698#issuecomment-815096076).

I don't know why `grep -v HasChildren` is used, but it there for now. Maybe is is mistake.
@LukeSmithxyz , If there is any point in this grep, can it be removed?

Also [this](https://github.com/LukeSmithxyz/mutt-wizard/pull/719) PR remove `grep -v HasChildren` and ads mailboxes autodetection, if you interested.

**Comment by LukeSmithxyz** [comment]
The PR mentioned above was added.

**Comment by PRESFIL** [comment]
Apparently I made a mistake. He does not **remove**, but **corrects**.

That is, incorrectly defined mailboxes when creating an account are replaced with autodetected ones at startup.

I don't know why `grep -v HasChildren` is used, but it there for now. Maybe is is mistake.
[Now](https://github.com/LukeSmithxyz/mutt-wizard/blob/b6f0bd44267ea5a5f46ab27d4786ca72ae3511cd/bin/mw#L237) this value is used to create shortcuts in `muttrc`. If one of the `Sent|Drafts|Trash|Junk|Archive|Spam|Inbox`
mailboxes has an child mailbox, then it will not be included in the `mailboxes` and a shortcut will not be created for it.

Also it will be skipped in `finalize()`.
