### ISSUE TITLE
unmacro unknown command, muttrc could not be sourced

### ISSUE THREAD

**Issue by mzryz** [LukeSmithxyz/mutt-wizard#699]
after successfully creating a gpg key & running pass & mbsync:

pi@WY:~ $ neomutt
Error in /home/pi/.config/mutt/accounts/1-my@email.com.muttrc, line 21: unmacro: unknown command
Error in /home/pi/.config/mutt/muttrc, line 3: source: errors in /home/pi/.config/mutt/accounts/1-my@mail.com.muttrcsource: file /home/pi/.config/mutt/accounts/1-my@mail.com.muttrc could not be sourced.
source: errors in /home/pi/.config/mutt/muttrc
Press any key to continue...

< Then neomutt displays with 'no mailbox' 'no file or directory' >

I see it doesn't understand the unmacro, the OS is just base RapsbianOS which is Debian10 for Arm. Shell is Bash. I installed all the Debian pre-requisites as listed on Github.

**Comment by LukeSmithxyz** [comment]
Unfortunate. I'm guessing that the Debian version has not added this feature yet. It's a constant problem maintaining this with older versions, but the `unmacro` thing was only recently added.

You can manually remove the `unmacro` like and it should still work. I'll remove it from the template for the time being.
