### ISSUE TITLE
IMAP hierarchy delimiter errors & missing mail

### ISSUE THREAD

**Issue by mzryz** [LukeSmithxyz/mutt-wizard#700]
When running mbsync -a these errors occur for me:
`IMAP error: mailbox name INBOX.bla contains server's hierarchy delimiter`
`C: 0/1  B: 28/43  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0`

Then it seems to find new folders and downloads mail:
`Maildir notice: no UIDVALIDITY, creating new.`
`C: 0/1  B: 42/43  M: +0/0 *0/0 #0/0  S: +543/543 *0/0 #0/0`

(I do have a few sub-folders)

After mbsync completion launching neomutt does not display any folders/messages:

```
---NeoMutt: (no mailbox) [Msgs:0]---(reverse-date/date)
/home/pi/.local/share/mail/my@mail.com/INBOX.bla: No such file or directory (errno = 2)
```
FYI: I have re-installed Muttwizard since Lukes previous umacro edit.
system Raspbian/debian10 Pi3

**Comment by PRESFIL** [comment]
Did you removed mail account with `-d` / `-D` and recreated your account?

**Comment by mzryz** [comment]
Yes I did, tried twice.

**Comment by PRESFIL** [comment]
It looks like *dot* in `INBOX.bla` conflicts servers delimiter.

You can [check](https://github.com/LukeSmithxyz/mutt-wizard/issues/600#issuecomment-754545455) your provider's delimiter.

If it is *dot*, the only thing you can do is rename that folder on the server. It's strange that the provider even allowed to name it that at all.

After this commit a95ff5a `Flatten` no longer used and nothing to change on the `mutt-wizard` side.

**Comment by mzryz** [comment]
@PRESFIL 
Okay I ran the curl command and it returned '.' I assume this is what you mean by dot? And you are referring to the 'dot' in INBOX.bla? Well it is a little confusing as every single subfolder within the inbox is listed on the backend as INBOX.subfolder. I've added a photo to illustrate what I mean:

![Screenshot from 2021-04-03 14-02-31](https://user-images.githubusercontent.com/23113373/113479229-b7ca9400-9485-11eb-901a-5d38b1696b57.png)

**Comment by PRESFIL** [comment]
OK, you have `Website hosting` mailbox inside `INBOX` mailbox. And your server delimiter is `.`. `Website hosting` does not contain `.`.  I don't know what the problem is, because I can't see all the other mailboxes. You can view the entire list of boxes:

```sh
 curl -s --insecure --url "imaps://imap.<server>" --user '<email>' --request 'LIST "" "*"'
```

Do I understand correctly that the problem is not in the separators, but in the fact that `Website hosting` does not appear in `.local/share/mail/<mail>/INBOX/` now? Or are there no folders in `.local/share/mail/<mail>/`?

Have you looked into `.mbsyncrc`? Maybe there is something left from previous accounts?

**Comment by mzryz** [comment]
`* LIST (\HasChildren) "." INBOX
* LIST (\HasNoChildren) "." "INBOX.trip"
* LIST (\HasNoChildren) "." INBOX.solidstate
* LIST (\HasNoChildren \Trash) "." INBOX.Trash
* LIST (\HasNoChildren) "." INBOX.Settl
* LIST (\HasNoChildren \Junk) "." INBOX.spam
* LIST (\HasNoChildren) "." "INBOX.Eng"
* LIST (\HasNoChildren \Archive) "." INBOX.Archive
* LIST (\HasNoChildren) "." "INBOX.Website hosting"
* LIST (\HasNoChildren) "." INBOX.AM
* LIST (\HasNoChildren) "." INBOX.Queue
* LIST (\HasNoChildren) "." "INBOX.Apple Mail To Do"
* LIST (\HasNoChildren) "." "INBOX.Deleted Messages"
* LIST (\HasNoChildren) "." INBOX.Imm
* LIST (\HasNoChildren \Junk) "." INBOX.Junk
* LIST (\HasNoChildren \Sent) "." INBOX.Sent
* LIST (\HasNoChildren) "." INBOX.Amiga
* LIST (\HasNoChildren) "." INBOX.PCW
* LIST (\HasNoChildren) "." INBOX.Receipts
* LIST (\HasNoChildren) "." "INBOX.car stuff"
* LIST (\HasNoChildren \Drafts) "." INBOX.Drafts
* LIST (\HasNoChildren \Sent) "." "INBOX.Sent Messages"
`

**Comment by mzryz** [comment]
@PRESFIL I checked inside .local/share/mail/<mail>/INBOX/ - and all of the servers folders *have* been created. I checked inside 'INBOX' and it looks like there are MANY files, I assume the mail is there.

So perhaps there is an issue with muttrc?

**Comment by mzryz** [comment]
I tried removing the account once more and also recursively removing the account from .local/mail etc, I also had a theory it might be subfolders with long names like 'bla bla bla' with spaces.. removed a few of them. Inside neomutt it doesn't seem to show my main inbox, and I have no folders on the left side? weird.

![Screenshot from 2021-04-04 11-55-42 png](https://user-images.githubusercontent.com/23113373/113506485-13a42400-953d-11eb-8156-ac5e457cd7a8.jpg)

**Comment by mzryz** [comment]
By the way, last year I used Muttwizard and it asked me whether I'd like to store local emails or grab them dynamically (always online) and the always online/dynamic mode worked fine. This new version doesn't give the option anymore.

**Comment by PRESFIL** [comment]
OK, I used [this data](https://github.com/LukeSmithxyz/mutt-wizard/issues/700#issuecomment-813008255) from `curl` and ran it through the [pipeline that generates it in the current version](https://github.com/LukeSmithxyz/mutt-wizard/blob/52c46f4b98c50817f449b13537ff8763814614d5/bin/mw#L226).

```sh
cat | grep -v HasChildren | sed "s/.*\" //;s/\"//g" | tr -d ''
```

Input:
```
* LIST (\HasChildren) "." INBOX
* LIST (\HasNoChildren) "." "INBOX.trip"
* LIST (\HasNoChildren) "." INBOX.solidstate
* LIST (\HasNoChildren \Trash) "." INBOX.Trash
* LIST (\HasNoChildren) "." INBOX.Settl
* LIST (\HasNoChildren \Junk) "." INBOX.spam
* LIST (\HasNoChildren) "." "INBOX.Eng"
* LIST (\HasNoChildren \Archive) "." INBOX.Archive
* LIST (\HasNoChildren) "." "INBOX.Website hosting"
* LIST (\HasNoChildren) "." INBOX.AM
* LIST (\HasNoChildren) "." INBOX.Queue
* LIST (\HasNoChildren) "." "INBOX.Apple Mail To Do"
* LIST (\HasNoChildren) "." "INBOX.Deleted Messages"
* LIST (\HasNoChildren) "." INBOX.Imm
* LIST (\HasNoChildren \Junk) "." INBOX.Junk
* LIST (\HasNoChildren \Sent) "." INBOX.Sent
* LIST (\HasNoChildren) "." INBOX.Amiga
* LIST (\HasNoChildren) "." INBOX.PCW
* LIST (\HasNoChildren) "." INBOX.Receipts
* LIST (\HasNoChildren) "." "INBOX.car stuff"
* LIST (\HasNoChildren \Drafts) "." INBOX.Drafts
* LIST (\HasNoChildren \Sent) "." "INBOX.Sent Messages"
```

Output:
```
INBOX.trip
INBOX.solidstate
INBOX.Trash
INBOX.Settl
INBOX.spam
INBOX.Eng
INBOX.Archive
INBOX.Website hosting
INBOX.AM
INBOX.Queue
INBOX.Apple Mail To Do
INBOX.Deleted Messages
INBOX.Imm
INBOX.Junk
INBOX.Sent
INBOX.Amiga
INBOX.PCW
INBOX.Receipts
INBOX.car stuff
INBOX.Drafts
INBOX.Sent Messages
```

Looks like `INBOX` itself ignored. There are another similar issue #698 
Now you can add `INBOX` manuall to mailboxes variable inside `mutt`'s config, to see what happens to the neomutt sidebar.

**Comment by mzryz** [comment]
Good news @PRESFIL - I did as you said, adding an 'INBOX' setting to the mailbox's muttrc and it downloaded all my INBOX mail, upon opening Neomutt it does not default to INBOX for some reason, so I press 'c' '?' and select INBOX and all my mail is displayed!
Now the only two things that I would like to fix are: Still nothing is displayed in the sidebar, just the number of emails contained, but no mailbox names. Also if I could make it default to INBOX, then it will all be fixed :)

**Comment by PRESFIL** [comment]
I think the reason is like [here](https://github.com/LukeSmithxyz/mutt-wizard/issues/698#issuecomment-812367596).

> just the number of emails

Very strange. Maybe you have an old version of `mutt`/`neomutt` or something is wrong with the color theme of the terminal emulator.

You can try to search issues with "sidebar" search term. Some resent issues:

- https://github.com/LukeSmithxyz/mutt-wizard/issues/338
- https://github.com/LukeSmithxyz/mutt-wizard/issues/459
- https://github.com/LukeSmithxyz/mutt-wizard/issues/654

**Comment by mzryz** [comment]
@PRESFIL Thank you my friend - you are extremely kind and helpful :)
After reading those links, a comment from Luke solved the problem. Adding:
`set sidebar_format = '%B%?F? [%F]?%* %?N?%N/? %?S?%S?'`
To my muttrc fixed the sidebar missing names.

Now I dare ask, could you point me in the direction of how to set the default mailbox for neomutt? It seems to always default to 'INBOX.Receipts' rather than 'INBOX'.

Thank you again,

**Comment by mzryz** [comment]
@PRESFIL @LukeSmithxyz 
Thank you guys, now everything is working perfectly & I have learned a lot. As Luke says, removing all the unnessesary folders from spoolfile/macros allowed Neomutt to accept INBOX as default.

Cheers, I will close the thread :)
