### ISSUE TITLE
artix cannot unlock with pam-gnupg

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/mutt-wizard#701]
@LukeSmithxyz  dude how you unlock with pam-gnupg ? 
i am looking to ifnd a way and always when i log out is locked ... 
on arch was working fine ... what is the settings

**Comment by jemadux** [comment]
i asked on artix forum they gave me some [istructions ](https://forum.artixlinux.org/index.php/topic,2446.0.html)
but i tried to put on larbs and didnt work

**Comment by ank0m** [comment]
@jemadux If looked for a solution, too and stumbled upon the URL you've linked to. This works very well for me.

**Comment by engjpacheco** [comment]
Can you share you procedure, do the steps in te url but don't work

**Comment by fr-an-kh** [comment]
> Can you share you procedure, do the steps in te url but don't work

Sure, following are the steps I did:

# Edit/create ~/gnupg/gpg.conf:
use-agent

## Edit/create ~/.gnupg/gpg-agent.conf:
default-cache-ttl 31536000
max-cache-ttl 31536000

## Reload GPG agent:
gpg-connect-agent reloadagent /bye

## Edit xinitrc to automatically start GPG agent when starting X.org:
if [ -x /usr/bin/gpg-agent ]; then
 eval "$(/usr/bin/gpg-agent --daemon)"
fi

## Edit .bashrc and append the following lines:
GPG_TTY=$(tty)
export GPG_TTY

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi

After that everything worked as expected.

**Comment by fr-an-kh** [comment]
Source of the above is:
https://forum.artixlinux.org/index.php/topic,2446.msg16278.html#msg16278

**Comment by engjpacheco** [comment]
Thanks for responding, what the lined lines means?

**Comment by fr-an-kh** [comment]
You mean 

```
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
ssh-agent > /.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
eval "$(</.ssh-agent-thing)"
fi
```

???

That's for the SSH key manager which holds your keys and certificates in memory. Not explicitly need for the GnuPG part.

**Comment by engjpacheco** [comment]
Yeah, the Middle line makes me confused, so literally type the command like that and technically it's going to work right, gonna check that out, thanks 🙏
