### ISSUE TITLE
Disable mail notifications?

### ISSUE THREAD

**Issue by Tumetsu** [LukeSmithxyz/mutt-wizard#703]
Is it possible to have the mailsync fetch mails in the background but not notify about the new mails? I checked the `mailsync` script which does the notification. Is editing it the only way to do this? Or how would you suggest to setup Neomutt/mutt-wizard to do this?

**Comment by LukeSmithxyz** [comment]
There's no way to do this by default. You would just have to comment out the commands that run the notification commands. I might be open to adding this as an option though.

**Comment by LukeSmithxyz** [comment]
I will also say, one thing you could do is just set your cronjob to run `mbsync -a; notmuch new` instead.

**Comment by Tumetsu** [comment]
Thanks, I'll try to edit the crontab first :+1: 

That being said I think it would be nice to have control over notifications. However, I think I can get by with this method for now if I decide to keep using Neomutt.

**Comment by binarious** [comment]
> I will also say, one thing you could do is just set your cronjob to run `mbsync -a; notmuch new` instead.

This does not include the other useful features of `mailsync` (like checking if `mbsync` is still/already running). Would love an option to disable notifications :+1:.
