### ISSUE TITLE
smoov brain? - Log-on not successful. is not a valid account name.

### ISSUE THREAD

**Issue by timbeach** [LukeSmithxyz/mutt-wizard#706]
```
Log-on not successful.
 is not a valid account name.
```
I'm seeing this after entering 
```
mw -a "tim@timbeach.com"
Give your email server's IMAP address (excluding the port number):
mail.timbeach.com
Give your email server's SMTP address (excluding the port number):
mail.timbeach.com
Enter password for tim@timbeach.com:
Retype password for tim@timbeach.com:
```
What am I missing / what else can I check on? 
I set up my own email server which K-9 mail and Thunderbird can access without issue. 
I looked in ~/.config and there isn't any `mutt` directory.

**Comment by Kr1ss-XD** [comment]
This might sound silly, but are you sure you actually ran `mw -a <...>` ?

I'm asking because the only code in the `mw` script, that would output the error message you posted is the `delete()` function, which is only executed when you run one of `mw -d`, `-D` or `-X`.

**Comment by timbeach** [comment]
it was a TLS issue
sorry to spam the repo
