### ISSUE TITLE
NAZIS PWNED EPIC STYLE mbsync master slave far near

### ISSUE THREAD

**Issue by wuhei** [LukeSmithxyz/mutt-wizard#708]
mbsync complains about labels:

```
$ mbsync -l
Notice: Master/Slave are deprecated; use Far/Near instead.
No channel specified. Try 'mbsync -h'
zsh: exit 1     mbsync -l
```

update labels by editing ~/.mbysncrc or using this sed oneliner
```
$ sed -i 's|^Slave |Near |;s|^Master |Far |' "~/.mbsyncrc"
```

**Comment by LukeSmithxyz** [comment]
See closed issues. This can't be changed now because slow-release distros haven't change this and it would break all of them.
