### ISSUE TITLE
[Enhancement] Sync with google contatcts

### ISSUE THREAD

**Issue by lf-araujo** [LukeSmithxyz/mutt-wizard#71]
It would be useful to access google contacts as alias through goobook. 

Here is the archwiki entry: https://wiki.archlinux.org/index.php/Mutt#Goobook

**Comment by LukeSmithxyz** [comment]
There's nothing to add to this wizard. If people one this, they can add it manually. It doesn't make any sense to add and maintain a particular insular non-essential feature for one particular email provider.
