### ISSUE TITLE
Weird behaviour composing new/replying to email

### ISSUE THREAD

**Issue by ank0m** [LukeSmithxyz/mutt-wizard#711]
Yesterday I've set up a new PC using Artix (runit) base install and deployment using your LARBS script which went totally smoth.

Then configured neomutt using mw -a me@mail.com, passwordstore and GPG was done before.

Now when I want to compose a new mail I enter the recipients mail address and subject. After that I normally press "i" to write the email, but now I'm welcome by the following error message:

E21: Cannot make changes, 'modifiable' is off.

So I enter :x, enter.

After that I'm able te press "i" to enter my text and press:
ESC, :x

This takes me back to my composed mail, so once again ":x" and then I'm able to press "y" to send the email.

This error message as well as pressing time ":x" a second time I didn't encounter before.

I've no clue what went wrong and would be gracefully for any help.

Chears,
ank0m

PS: all dependencies listed in this repo are installed as well

**Comment by LukeSmithxyz** [comment]
This is a LARBS thing. Maybe I should make it clearer. LARBS uses Goyo in mutt to autocenter the mail writing prompt.

To make it seemless, I rebind some stuff and other things. Long story short, use `ZZ` and `ZQ` to save-quit/force quit from mail writing. I might want to add more binds for people who don't know about ZZ/ZQ.

**Comment by ank0m** [comment]
Thank for taking time to look into my issue. Learn something new (ZZ/ZQ)!

The issue (E21: Cannot make changes, 'modifiable' is off.) when I write a new mail is still present. On this PC I press 'm', enter recipients mail address and subject followed by ':q' as 'i' gives me the error above then 'i' to enter my message ...

On my other PC (Archlinux + LARBS) I press 'm', enter recipients mail address and subject then 'i' and write my message.

Only difference between both PC's is the other one runs Artix Linux instead of Arch.

Thanks for teaching me ZZ and ZQ bindings.

**Comment by mackeryd** [comment]
fhmbrg did you figure out the 'modifiable is off issue'? I am having thesame issue and it seems to be related to the goyo plugin somehow.

**Comment by fhmbrg** [comment]
@mackeryd just leave this screen `:q` and on the next one you can start composing new/reply to someone's mail `I/i`.

**Comment by mackeryd** [comment]
Yeah….but isn’t the point for it to automatically open with the goyo command? …it seems to be opening something else that has to be quit, and once quit is opening with the goyo command. I just can’t figure out what it is.
