### ISSUE TITLE
help needed.

### ISSUE THREAD

**Issue by KeneePatel** [LukeSmithxyz/mutt-wizard#715]
> What am i doing wrong

![image](https://user-images.githubusercontent.com/59523692/117532781-f0223c80-b006-11eb-878c-dde7ebbd9861.png)

**Comment by notbluu** [comment]
Your password might be wrong.

**Comment by KeneePatel** [comment]
I did make sure my password was right.

**Comment by Kr1ss-XD** [comment]
@KeneePatel Gmail might require some additional setup, see the first bullet point of this [README paragraph](https://github.com/LukeSmithxyz/mutt-wizard#watch-out-for-these-things).

Have you allowed "less secure" apps with your Google account and created an app password ?

If you haven't, please follow [this guide](https://support.google.com/accounts/answer/185833) from Google.

**Comment by KeneePatel** [comment]
Thank you for the help. It's working now.
