### ISSUE TITLE
Protonmail + hydroxide: TLS handshake failed: An unexpected TLS packet was received.

### ISSUE THREAD

**Issue by binex-dsk** [LukeSmithxyz/mutt-wizard#717]
I've got a protonmail account (free) and am using hydroxide as the SMTP and IMAP server.

When I try to send stuff with the default config, I get `msmtp: cannot use a secure authentication method`. When I turn `tls on`, I get `msmtp: the server does not support TLS via the STARTTLS command`. Then when I turn `tls_starttls off`, I get `msmtp: TLS handshake failed: An unexpected TLS packet was received.`

Searched online but couldn't find anything. Tried the solutions from #667, but with `auth login`, I just get `msmtp: the server does not support authentication method LOGIN`.

Current `msmtp` config:
```
account roachh@protonmail.com
host 127.0.0.1
port 1025
from roachh@protonmail.com
user roachh
passwordeval "pass roachh@protonmail.com"
auth on
tls on
tls_starttls off
tls_trust_file	/etc/ssl/certs/ca-certificates.crt
logfile /home/swirl/.config/msmtp/msmtp.log
```

**Comment by binex-dsk** [comment]
solution: host your own mail server

**Comment by hadibus** [comment]
I was getting this error message on my own mail server set up with email-wizard. I fixed it by setting tls_starttls to on. 

I have used Thunderbird for quite a while, and I keep finding answers by looking at the settings I have there.
