### ISSUE TITLE
Adding account with -p switch hangs

### ISSUE THREAD

**Issue by shawnyeager** [LukeSmithxyz/mutt-wizard#718]
```
~/D/mutt-wizard ❯❯❯ mw -a first@name.com -p                                  ✘ 1 master
NOTE: Protonmail users must install and configure Protonmail Bridge first for the first sync to work.
```

After running `mw init`, I run the above and `mw` hangs. I've tried multiple times. Without the `-p` switch, it proceeds as expected.

**Comment by LukeSmithxyz** [comment]
What's the status of Bridge? Do you have it up and running using the typical ports?

**Comment by shawnyeager** [comment]
I'm running it unmodified, yes.
