### ISSUE TITLE
Add note: Google will require you to turn on "Allow less secure apps" for Gmail to work.

### ISSUE THREAD

**Issue by naiveai** [LukeSmithxyz/mutt-wizard#72]
For us plebs who use Gmail. Perhaps I could do this separately, but I think it would be good to add a note in the README or create a file for special cases like this.

**Comment by naiveai** [comment]
I'm a complete idiot, I apologize.

**Comment by GrimKriegor** [comment]
Maybe this could be a more sensible approach for people concerned with the security of their Google account.

https://k9mail.github.io/documentation/accounts/providerSettings.html#gmail-google-mail

Or at least an alternative worthy of mention. Haven't tested it personally on Mutt though.
