### ISSUE TITLE
mbsync -a error "No channels defined" after adding accounts to mutt wizzard

### ISSUE THREAD

**Issue by Alcatraz077** [LukeSmithxyz/mutt-wizard#721]
Evening. 

Just installed PopOS to my main PC. Got mutt wizard installed, added some accounts. I can send email without issue, but if I try to run `mbsync -a`, it spits out: 

`No channels defined. Try 'man mbsync'`

The mbsync config file (`.mbsyncrc`) contains the following:

```
SyncState *
Sync New ReNew Flags
```

I'm not sure where I've gone wrong here. Thanks in advance for any help.

**Comment by eriteric** [comment]
same. 

I had to manually run mbsync once (as opposed to running it in mutt) to download any emails, but now it doesn't work anymore. .mbsyncrc file has always been empty as far as I know.

Don't know if this is related or not but none of my folders were mapped correctly, not even the inbox. Got 2 to show up by manually editing mutt  config and mail dir files.

Using rackspace email, their normal email not microsoft services.

**Comment by LukeSmithxyz** [comment]
Just run `ln -s ~/.config/msmtp/config ~/.msmtprc` for now.

Issue is that slower release distros don't have a version of MSMTP with XDG compatibility. The script automatically tests for Debian/Ubuntu by checking for `apt-get`, but no Pop OS! check yet.

I thought Pop used apt-get. What is it's package manageR?

**Comment by Kr1ss-XD** [comment]
They use APT.

Might just be that there's no `apt-get` command but only the newer `apt` one.

**Comment by Alcatraz077** [comment]
Thanks, will do. 

Pop uses apt, but apt-get does exist in a default install.

May 30, 2021 8:14:48 PM Luke Smith ***@***.***>:

**Comment by Alcatraz077** [comment]
Ran `ln -s ~/.config/msmtp/config ~/.msmtprc`, then `mbsync -a`, same error.

**Comment by Alcatraz077** [comment]
Ran `ln -s ~/.config/msmtp/config ~/.msmtprc`, then `mbsync -a`, same error.

**Comment by Kr1ss-XD** [comment]
@Alcatraz077 could you try

```sh
ln -s ~/.config/mbsyncrc ~/.mbsyncrc
```

instead please.

**Comment by Alcatraz077** [comment]
@Kr1ss-XD 

So just to make sure I didn't do anything wrong, I removed both the files and ran the following commands (with outputs):

```
alcatraz@pop-box:~$ rm .mbsyncrc 
alcatraz@pop-box:~$ rm .msmtprc 
alcatraz@pop-box:~$ ln -s ~/.config/msmtp/config ~/.msmtprc
alcatraz@pop-box:~$ ln -s ~/.config/mbsyncrc ~/.mbsyncrc
alcatraz@pop-box:~$ mbsync -a
Cannot open config file '/home/alcatraz/.mbsyncrc': No such file or directory
alcatraz@pop-box:~$ cat .mbsyncrc 
cat: .mbsyncrc: No such file or directory
```

So I'm not sure what's up.

**Comment by Kr1ss-XD** [comment]
Looking at your initial comment again, I think the actual problem is that somehow the mbsync config file hasn't been written correctly in the first place.

>The mbsync config file (.mbsyncrc) contains the following:
```mbsyncrc
SyncState *
Sync New ReNew Flags
```

That file should actually be a bit longer, and if this is all that was in it, that would explain why mbsync complained about `No channels defined`. That message is also what I get, when I run `mbsync -a` on an Ubuntu-LTS VM, with your `.mbsyncrc` file in place.

I was able to get an email account working on that box by just starting over and re-adding that account with the mutt-wizard.  That's what I would suggest you.

```sh
rm -f ~/.{mbsync,msmtprc} ~/.config/{msmtp/config,mbsyncrc}
mw -a <your@email.account>
# and enter the data it prompts you to input.
```

If everything went well, your `~/.mbsyncrc` should look similar to this :

```mbsyncrc
IMAPStore <user>@<domain>-remote
Host imap.<domain>
Port 993
User <user>@<domain>
PassCmd "pass <user>@<domain>"
AuthMechs LOGIN
SSLType IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

MaildirStore <user>@<domain>-local
Subfolders Verbatim
Path /home/<name>/.local/share/mail/<user>@<domain>/
Inbox /home/<name>/.local/share/mail/<user>@<domain>/INBOX

Channel <user>@<domain>
Expunge Both
Master :<user>@<domain>-remote:
Slave :<user>@<domain>-local:
Patterns * !"[Gmail]/All Mail"
Create Both
SyncState *
MaxMessages 0
ExpireUnread no
# End profile
```

**Comment by Alcatraz077** [comment]
Yep, that worked! Thanks so much!

**Comment by Kr1ss-XD** [comment]
Thank you for the response. Guess we can close the issue then ?

**Comment by Alcatraz077** [comment]
Yep, I'll close it on this end.
