### ISSUE TITLE
Swapping Mailbox Numbers

### ISSUE THREAD

**Issue by JonBoyleCoding** [LukeSmithxyz/mutt-wizard#724]
I've over time setup my mailboxes, but I would like to re-order the numbering for the shortcuts.

Is this possible with mutt-wizard directly? If not then I would like to request this as a feature.

To do so manually, do I only have to rename the files in the `.config/mutt` folder and edit the `muttrc` to change the shortcuts? Or will this affect mutt wizard in some form?

Thanks

**Comment by LukeSmithxyz** [comment]
This would require a lot of moving directories and changing files. Might produce a lot of bugs.

I suppose I could try to remove the numbers from the directories and files and it might be easier to dynamically number accounts.

**Comment by JonBoyleCoding** [comment]
That's fair enough - would rather lower bugs than a complex feature. Am I right that all I'd need to do is just rename the shortcuts in `.config/mutt` and this would be ok with mutt wizard?

**Comment by LukeSmithxyz** [comment]
I've removed the numbers from the filenames, so this should be a little easier to do nowadays. Just open `~/.config/mutt/muttrc` and change the shortcuts manually and that will be all you need now.
