### ISSUE TITLE
cannot press <Enter> ^M^M ??? (beginner)

### ISSUE THREAD

**Issue by molleweide** [LukeSmithxyz/mutt-wizard#726]
Hi,

I am trying to setup mw. Very exciting!!!!
When I try to add my email it asks me abouf IMAP address but from here I
cannot press ENTER. This also happens with the `pass` program.

So what happens is that ^M is printed instead.
I use Macos also btw. 

```
> mw -a myemail@emailson.com
Give your email server's IMAP address (excluding the port number):
mailin.telia.com^M^M^M
```

I am also learning `pass` as I mentionned and the same thing happens there:

```
pass rm test@test.com.tmp.6874.6788.21067.12896.--
Are you sure you would like to delete test@test.com.tmp.6874.6788.21067.12896.--? [y/N] y^M^M^M
```

**Comment by molleweide** [comment]
okay so I managed to supply server info via flags BUT i cannot press enter for supplying the password it seems.

**Comment by molleweide** [comment]
https://askubuntu.com/questions/441744/pressing-enter-produces-m-instead-of-a-newline

in this thread I found the answer. both pass and muttwizard seem to cause some shenanigans and I am not sure myself what happens :D

**Comment by LukeSmithxyz** [comment]
This is not a mutt-wizard problem, nor a pass problem. It's a MacOS problem. If `stty sane` solves your problem, you can put it in your shell's rc file to make it permanent.
