### ISSUE TITLE
Issue with sending email "Interrupted system call"

### ISSUE THREAD

**Issue by freddiaN** [LukeSmithxyz/mutt-wizard#73]
I've tried to send email via a cock.li email account, although it doesn't seem to actually send an email, it rather just gives me a "Interrupted system call" after 30 seconds of silence. I did make sure that I had msmtp installed.

**Comment by loweryaustin** [comment]
Is your computer able to reach the SMTP server that you're trying to send to? Try installing telnet and nmap to test it out. Then:
```
telnet mailserverdomain.tld 587
nmap -p 587 mailserverdomain.tld
```
To be sure you should double check what the mailserver domain is by checking the smtp_url of the following config:
`.config/mutt/accounts/accountname.muttrc`

**Comment by loweryaustin** [comment]
Honestly, your issue doesn't seem related to the mutt-wizard at all, but it would be interesting to see what is happening.

**Comment by freddiaN** [comment]
I used `nmap` and the `smtp_url` provided by the accounts `muttrc` file:
```
Starting Nmap 7.70 ( https://nmap.org ) at 2018-07-31 19:32 CEST
Nmap scan report for mail.cock.li (185.100.85.212)
Host is up (0.055s latency).
Other addresses for mail.cock.li (not scanned): 2a06:1700:0:b::c0cc
rDNS record for 185.100.85.212: cock.li

PORT    STATE    SERVICE
587/tcp filtered submission

Nmap done: 1 IP address (1 host up) scanned in 0.98 seconds
```
so `nmap` seems to do fine, however, `telnet` is stuck connecting (to what looks like is a IPv6 domain).

**Comment by loweryaustin** [comment]
Filtered is not good. That means that your connection is being blocked by a firewall.
https://nmap.org/book/man-port-scanning-basics.html

The cock.li server has blocked your connections via firewall.
Here is what it looks like when I try from my computer. This is what it should look like by the way:
```
Mac-mini-5:~ austinlowery$ dig +short mail.cock.li
185.100.85.212
Mac-mini-5:~ austinlowery$ telnet 185.100.85.212 587
Trying 185.100.85.212...
Connected to cock.li.
Escape character is '^]'.
220 cock.li ESMTP Postfix (Debian/GNU)
}^]
telnet> quit
Connection closed.
Mac-mini-5:~ austinlowery$ nmap -p 587 mail.cock.li

Starting Nmap 7.60 ( https://nmap.org ) at 2018-07-31 14:44 CDT
Nmap scan report for mail.cock.li (185.100.85.212)
Host is up (0.16s latency).
Other addresses for mail.cock.li (not scanned): 2a06:1700:0:b::c0cc
rDNS record for 185.100.85.212: cock.li

PORT    STATE SERVICE
587/tcp open  submission

Nmap done: 1 IP address (1 host up) scanned in 0.89 seconds
```
