### ISSUE TITLE
/mpop/configbu: No such file or directory

### ISSUE THREAD

**Issue by mannp** [LukeSmithxyz/mutt-wizard#730]
Hi there

First, thanks for creating mutt-wizard :)

I am having a few issues with server's hierarchy delimiter errors but while trying to delete and recreate an email account I got the following error?

```
❯ mw -D <email address>

/usr/bin/mw: line 177: /home/user/.config/mpop/configbu: No such file or directory
mv: cannot stat '/home/user/.config/mpop/configbu': No such file or directory
```

I am using the git version from arch aur as of today, the account is not a pop account and I didn't have mpop installed.

I installed mpop in case and got the same error....

**Comment by LukeSmithxyz** [comment]
That error shouldn't be causing any problems. I seem to remember
supressing it before, perhaps the AUR package is out of date?

Looks like it is properly suppressed in the code now. I might be
overlooking something though.

**Comment by mannp** [comment]
Not sure if it out of date, its the git one, but note there is no ref to a pop dependency from what I can see, but installing mpop for me gave me the same error still.

The account was deleted, so no issue there :)
