### ISSUE TITLE
Replicate color scheme in vim? 

### ISSUE THREAD

**Issue by mannp** [LukeSmithxyz/mutt-wizard#732]
Hi

I am trying to replicate the colors you have in the mutt-wizard theme in my vim config too and I am not sure where the relevant config is in the wizard?

Any pointers to what I might need to use?

Cheers

**Comment by Inesgor** [comment]
Hi.
If you installed mutt-wizard using git, you will find the colourscheme in `/usr/local/share/mutt-wizard/mutt-wizard.muttrc`. More specifically, line no. 93 onwards.

**Comment by mannp** [comment]
> Hi.
> If you installed mutt-wizard using git, you will find the colourscheme in `/usr/local/share/mutt-wizard/mutt-wizard.muttrc`. More specifically, line no. 93 onwards.

Hey thanks @Inesgor I didn't install via git, but instead arch aur but a fuzzy search found it in /usr/share/mutt-wizard/

Thanks for the pointer to the location, always disliked vim but giving it another go as neovim 👍🏻
