### ISSUE TITLE
Manual name/location of password gpg

### ISSUE THREAD

**Issue by Inesgor** [LukeSmithxyz/mutt-wizard#733]
Hi.
I have set up pass & have it classified. So my `~/.local/share/password-store` has folders & sub-folders based on categories. 
What i need is to move the mutt-wizard gpgs inside one of those folders, as these are the only password gpg files lying outside of my organised folders. I tried doing so manually, by editing the `passwordeval` field in `~/.config/msmtp/config` & also the `PassCmd` in `~/.config/mbsync/config` - pointing them to my own locations (sample: `PassCmd "pass web/emails/email1@site.tld"`). This however didn't work as `mw -Y` fails in authenticating.
My question to you is, what exactly did i miss. Also, would it be possible to add an option while adding these accounts, to specify a preexisting pass gpg file (something like `mw -g (pass web/emails/email1@site.tld) -a email1@site.tld`). 
Thank you.

**Comment by engjpacheco** [comment]
I have some similar issue. mw -Y don't ask me for the pass, but if I run pass myemail type my gpg phrase, then I can run mw -Y with no problems, but I don t know why

**Comment by lippfi** [comment]
Same issue
It will successfully launch if you add your custom path to `set imap_pass = ...` and functions `createpass()`, `getpass()`, `getboxes()` but I'm not sure if it is bug-free

I would love to see the custom path option in future releases

**Comment by cenktaskin** [comment]
Just bumped into the same problem. Is this somehow resolved? I already have a running instance of pass, that is using a gpg key via different e-mail. So I can't get mw to set up my account.

Cheers
