### ISSUE TITLE
[Suggestion] More than 9 email accounts

### ISSUE THREAD

**Issue by Inesgor** [LukeSmithxyz/mutt-wizard#734]
Hi again.
If we add more than 9 email accounts (for some reason), firstly neomutt throws warning about the keybinding because the 10th account in `~/.config/mutt/muttrc`,  has the keybinding of `i`. 
Suggestion: I manually changed the keybinding to `I10` (shift+i+1+0) & it worked. I suggest if this can be added in mutt-wizard as default action for double-digit nos. of account. (This is what  some cli IRC & XMPP clients, like mcabber, do by default for double-digit tabs)
Furthermore, the account configuration files in `~/.config/mutt/accounts`, which usually are named in the pattern `<number>-<email>.muttrc>, give no numbers 10th account onwards & are named as `-<email>.muttrc>. And entering `mw -l` shows only 9 accounts, as if the 10th account doesnt exist. So I suggest you to please fix this.
Thank you.

**Comment by LukeSmithxyz** [comment]
The real "solution" to people with many accounts is removing mw's tendency to separate accounts, instead allow users to use them all simultaneously without the bindings. While I'm open to an efficient way of doing this, I think 10+ accounts is niche enough to not make this change worth it for the hackiness required to do it.
