### ISSUE TITLE
sent folder created in home directory after sending email

### ISSUE THREAD

**Issue by vhsdream** [LukeSmithxyz/mutt-wizard#737]
I am using neomutt to sync my Gmail account that I set up using mutt wizard. I noticed a curious thing the other day as a folder called 'sent' was created in my home directory. It contains all of the emails I have sent from my laptop.

I have tried removing and re-adding my Gmail account (as well as a reinstall of neomutt and mutt wizard) but it keeps happening. My setup isn't special in any way, just a typical Arch install that otherwise works perfectly. All of my other gmail folders appear in the correct place under ~/.local/share/mail/<account>.

When I am at the 'review' message screen (or whatever it's called) I can see the field 'Fcc: ~/sent' but I don't know how to edit that field or delete it. Any tips?

![neomutt-sent](https://user-images.githubusercontent.com/67816022/125185197-372fd800-e1d8-11eb-9161-920d0ba5994e.png)

**Comment by t-391** [comment]
In your /home/user/.config/mutt/accounts/custom.muttrc,

Do you have any sort of line with "fcc hook"?
When you are in that compose screen (from your screenshot) hitting the key "f" should allow you to type a new value.

**Comment by vhsdream** [comment]
Thank you. Yes, pressing 'f' at that screen allows me to remove that, but it appears every time and I have to go through the process of removing it with each message. There is nothing about 'fcc hook' or fcc anything in my config. Is there an option I can add to the config which would remove it by default?

**Comment by t-391** [comment]
Okay, I think your problem is in this file:

/home/user/.config/mutt/accounts/custom.muttrc

You need a line that says this, maybe you accidentally commented it out:

`set record = "Sent"`


I commented mine out for a test, and surely enough FCC defaulted to ~/sent

**Comment by vhsdream** [comment]
OK, that works for me. I want to note that I did not comment anything out in my gmail.muttrc file though - the setting just did not exist. But since this is fixed for me, I'll close this issue. Thanks again!
