### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by CoderBasis** [LukeSmithxyz/mutt-wizard#739]
Hi!
I've been renewing my ssl certificates and when I'm checking in the server it says that it expires in something like 80 days. Still I cannot receive any emails, in neomutt I get prompted with "SSL certificate expired", but I can still send email. Meanwhile my website and searx instance are running just fine. What is wrong? I've resolved this issue once before but I cannot remember how, it happens like every 30 days even though I've been entering a cronjob in crontab to run every 30 days, as in Lukes video. Thanks for your patience.

**Comment by LukeSmithxyz** [comment]
Check your dovecot and postfix config files. They likely are calling a certificate in a file location that is obsolete. Especially if you have gotten certificates in common between multiple domains, it is likely that the file has moved.
