### ISSUE TITLE
Unable to open mailbox /var/spool/mail/username

### ISSUE THREAD

**Issue by t-391** [LukeSmithxyz/mutt-wizard#740]
I followed along with the tutorials (youtube video, and re-reading the man pages a few times) and checked through here on the closed issue pages. I don't really know what I did wrong. Any time I launch neomutt, it doesn't load an inbox and just says "unable to open mailbox /var/spool/mail/user".

mbsync -a seems work fine though.

How do I even begin to troubleshoot this one? The only thing I could think was maybe the output of neomutt -D:

set spoolfile = "/var/spool/mail/user"

but isn't supposed to point to something created by mutt-wizard? and if that's so, which config file controls this?

I did set spoolfile = /home/user/.local/share/mail/mailboxfile

It seems like that should have happened automatically because MAILDIR or some other variable is supposed to take care of it. Now I still get an error saying it can't open the mailbox, but it's pointed to the correct mailbox...

Edit2: And a little further yet. with:

`spoolfile = /home/user/.local/share/mail/mailboxfile/INBOX`

And now I can see my inbox but I think the pane on the left might be indicating it's actually my archive. I can probably play with this until I get it working right.

Edit3: I was able to get it working. I commented out the spoolfile line.
I edited /home/.config/mutt/accounts/custom.muttrc so that the "set folder" line pointed to my mailbox located in .local/share.

I also modified the folder names within the mailbox to match.

**Comment by hadibus** [comment]
I was seeing this same error message and I found in mutt's help (pressing "?") that i just needed to press "i 1" to access my first and only email configured for mutt by mutt-wizard. Kind of annoying to see the "Unable to open mailbox /var/spool/mail/username" message when mutt is opened instead of just going to my email, but I'm just happy I finally figured this out and can use mutt now.

**Comment by JoshuaDRose** [comment]
> I was seeing this same error message and I found in mutt's help (pressing "?") that i just needed to press "i 1" to access my first and only email configured for mutt by mutt-wizard. Kind of annoying to see the "Unable to open mailbox /var/spool/mail/username" message when mutt is opened instead of just going to my email, but I'm just happy I finally figured this out and can use mutt now.

Unfortunately this solution didn't work for me, any suggestions? :shrug:
