### ISSUE TITLE
 is not a valid account name

### ISSUE THREAD

**Issue by timbeach** [LukeSmithxyz/mutt-wizard#742]
I setup an email server on a vultr vps which have used successfully for a few months with clients like sylpheed and thunderbird. I've wanted to try mutt-wizard, but I am running into the problem described below.

Where should I look to get past this error: 
`Log-on not successful.`
` is not a valid account name.`

Here's what I've tried:
`$ mw -a user@domain.com`
`Give your email server's IMAP address (excluding the port number):`
`mail.domain.com`
`Give your email server's SMTP address (excluding the port number):`
`mail.domain.com`
`Enter password for user@domain.com:`
`Retype password for user@domain.com:`
`Log-on not successful.`
` is not a valid account name.`

I get the same error when I try to explicitly define the user, imagining that the " is not a valid account name" has to do with something like a variable not being assigned correctly.
`$ mw -a user@domain.com -u user -i mail.domain.com -s mail.domain.com -x <pw-here>`
`File '~/.local/share/password-store/user@domain.com.gpg' exists. Overwrite? (y/N) y`
`Log-on not successful.`
` is not a valid account name.`

Thanks

**Comment by MariusSwane** [comment]
Sounds like more or less the same issue as  https://github.com/LukeSmithxyz/mutt-wizard/issues/650, which never got resolved. For the record I still have this issue as well. Other clients work fine (thunderbird, K-9).

**Comment by Jocomol** [comment]
I just got the same problem with a gmail domain

**Comment by Jocomol** [comment]
I was able to add the account by running `mw -a mail@gmail.com -f -x "mypassword"`

**Comment by timbeach** [comment]
Thanks, @Jocomol .. this is working for me now
