### ISSUE TITLE
importing [user]@outlook.com addresses defaults to wrong Inbox name

### ISSUE THREAD

**Issue by joshdm42** [LukeSmithxyz/mutt-wizard#743]
when importing an `@outlook.com` email address with `mw -a [name]@outlook.com`, mutt-wizard uses `"=Inbox"` in its config files. 

This doesn't point to a real inbox, and so no emails are shown. 

Should instead be `"=INBOX"`, which correctly points to the outlook inbox and does show emails.

**Comment by emrakyz** [comment]
Thanks. It's also same for @hotmail.com. I also changed `"=Inbox"` with `"=INBOX"` in `~/.config/mutt/accounts/email@hotmail.com` to be able to see the inbox.
