### ISSUE TITLE
$TTY is empty, suppose to be $(tty)?

### ISSUE THREAD

**Issue by ZhanYF** [LukeSmithxyz/mutt-wizard#745]
In mailsync there is a line setting GPG_TTY:
`export GPG_TTY=$TTY`

However on both by OpenBSD and Debian box the variable $TTY is empty, perhaps you mean that line?
`export GPG_TTY=$(tty)`

**Comment by LukeSmithxyz** [comment]
$TTY works on my machine, but I suppose if $(tty) is more universal,
that would be advisible.

**Comment by ZhanYF** [comment]
I believe that is more universal, on all my linux boxes (debian10/arch), `$(tty)` is the way to go,
included in #744
