### ISSUE TITLE
POP3 configuration

### ISSUE THREAD

**Issue by TheMainMMan** [LukeSmithxyz/mutt-wizard#746]
What is the proper way of configuring the pop3 account ?
I had to add one by using -f, otherwise it was failing to validate with curl.

I have it working in the end, but I had to modify `mw` and manually add channel in `.mbsyncrc`
So, let's say the domain is whatever.xy, I add the account with
`mw -a username@whatever.xy -P -f`
Config files are all done except `.mbsyncrc`, launching `mpop` from terminal connects and fetches email.
But `mw -Y` doesn't, so I tried to manually add stuff to it
```
MaildirStore username@whatever.xy-local
Subfolders Verbatim
Path ~/.local/share/mail/username@whatever.xy/
Inbox ~/.local/share/mail/username@whatever.xy/INBOX

Channel username@whatever.xy
Master :username@whatever.xy-local:
Slave :username@whatever.xy:
Patterns *
Create Both
SyncState *
```

After that `mw -Y` doesn't complain about it but it doesn't invoke `mpop`, so I had to add `mpop` in `mw`

It works, but I feel I'm not doing something right, am I missing something ?

**Comment by LukeSmithxyz** [comment]
mbsync and therefore the `mw -Y/y` commands are only for IMAP accounts. Just run `mpop`.

**Comment by TheMainMMan** [comment]
Yeah but I don't get notification that way, this way I do.
But sure, I guess I can test for new mpop messages in a different way and notify.
