### ISSUE TITLE
Old messages are not there

### ISSUE THREAD

**Issue by ask1234560** [LukeSmithxyz/mutt-wizard#749]
Hello guys, thank you for making mutt-wizard.
```
os : Arch linux
mw version : 3.2.1.r55.gc8bbef5-2
```

I have been using mutt wizard for around 2 to 3 months. Currently i have added 4 email accounts. The 4 accounts are with gmail.

So, the issue is currently i have around 440 emails as in the below screenshot
![image](https://user-images.githubusercontent.com/25929911/128383145-e212b2cf-a8f5-4a3f-b9dc-484a12f20164.png)

But mutt only shows 50 as in the below screenshot
![image](https://user-images.githubusercontent.com/25929911/128383748-766c1540-af7b-45b5-935f-4b2d6c09b2e7.png)

How to fix this, the same issue is happening with my other account also.

**Comment by LukeSmithxyz** [comment]
You may've set a global maximum for the number of messages synced by mbsync.

Check your config (either in `~/.mbsyncrc` or `~/.config/mbsync/config`) and see if there is a `MaxMessages` line. Remove it or set it to `0`.

It's possible your distro has it in the global config as well, so adding `MaxMessages 0` to should remove the message limit.

**Comment by ask1234560** [comment]
Thanks luke
In `~/.mbsyncrc`  `MaxMessages` was there, i removed the line. Currently i sync mails using `mw -Y`, the current messages are not deleted but still old messages are not shown. Should i have to remove and add account to fix this.
