### ISSUE TITLE
No Messages in Hotmail Inbox

### ISSUE THREAD

**Issue by jaydip-c** [LukeSmithxyz/mutt-wizard#751]
I created my Hotmail account through mutt-wizard. Previously I created Gmail and GMX accounts successfully. But this time I find no messages in Hotmail Inbox, though I have thousands of emails in Hotmail. Here are the steps I did.

1. gpg --full-generate-key
2. pass init j**@hotmail.com
3. mw -a j**@hotmail.com
4. mw -y j**@hotmail.com
 
Now when I run neomutt, I find no messages in Inbox.

**Comment by jaydip-c** [comment]
Also when I run `mbsync -a` , it says, 

> C: 3/3  B: 52/52  F: +2/2 *2/2 #0/0  N: +8/8 *0/0 #0/0an INBOX?

**Comment by emrakyz** [comment]
I have solved the problem by changing `=Inbox` to `=INBOX` in ~/.config/mutt/accounts/your@email.com

**Comment by LukeSmithxyz** [comment]
Hotmail/Outlook seems to have both `Inbox` and `INBOX`, but uses `INBOX`. mw gets confused when it sees `Inbox` and may set it as the default.

As the poster above says, just change it to `INBOX` and it will be fine. I'll see if there's something automatic that can be done.
