### ISSUE TITLE
<mailadress>.muttrc seems to be messed up (a bit)

### ISSUE THREAD

**Issue by one7two99** [LukeSmithxyz/mutt-wizard#752]
Hello,

I am trying to setup my corporate office365 mailbox with neomutt.
using the script it seems that something in the muttrc config file for the mailbox is wrong.

from /home/user/.config/mutt/accounts/1-username@domain.com.muttrc 

[...]
ailboxes "=Credentials" "=Entw&APw-rfe" "=Gesendete Elemente" "=Postausgang" "=INBOX/Inbox_CC" "=INBOX/Inbox_Todo" "=INBOX/KIX" "=INBOX/Newsletter"
macro index,pager gS "<change-folder>=box_Todo
INBOX/KIX
INBOX/Newsletter
INBOX/SPAM
RSS-Abo<enter>" "go to spam"
macro index,pager MS ";<save-message>=box_Todo
INBOX/KIX
INBOX/Newsletter
INBOX/SPAM
RSS-Abo<enter>" "move mail to spam"
macro index,pager CS ";<copy-message>=box_Todo
INBOX/KIX
INBOX/Newsletter
INBOX/SPAM
RSS-Abo<enter>" "copy mail to spam"

As you can see it seems the folder names are merged with other config setting.
What exactly is the purpose of:
... "copy mail to spam"
... <copy message>
... <save-message>
... "go to spam"

and how do I need to cleanup the config file ?

One7two99

**Comment by LukeSmithxyz** [comment]
Looks like I merged an erroneous commit 8e5bb8bd095aaf9cb42997c243c4d4dc47f588a9 which introduced a bashism.

It's been fixed in 8239a7d5ca6807d395f787c8c940a08301eb61d7. Get the recent version and delete/readd your account and it should autogenerate fine.
