### ISSUE TITLE
Flags not being sent after archiving mail.

### ISSUE THREAD

**Issue by miluxmilux** [LukeSmithxyz/mutt-wizard#754]
Hi there!
I'm using the basic mutt-wizard that came with larbs, neomutt and isync.
I'm using IMAP with the Protonmail bridge, but I don't think it has anything to do with the problem.
Typically, I'll get a new e-mail, read it, and then go back to the inbox and move it to the archive (`l`, read, `h`, `Ma`, `S`, `<Enter>`)
```
macro index,pager Ma ";<save-message>=Archive<enter>" "move to archive"
```
Now, when I sync mail (`o`), the mail rightly moves to the Archive folder on the server, but the flag somehow doesn't get along. I now have an unread e-mail in the Archive folder in the Protonmail webmail. After some time, the flags are resychronized and the e-mail will also be marked as unread in `neomutt`. If I mark the message as unread in the inbox, sync and then archive, everything is well. 

I am not sure if the problem is in `neomutt` or with `isync`. When I mark the message as read and archive it, it lands in the `Archive/cur` folder, shouldn't it be in `Archive/new`?

I'm not sure where the problem is, or maybe I'm not using the right workflow to read and archive e-mail?

Has anyone had similar problems?

**Comment by LukeSmithxyz** [comment]
Well, for problems like this, you can fiddle with your mbsync settings, although the default in mw should be doing this already. I haven't seen this exactly before and it might be the result of a server-specific setting that you may or may not be able to change.

Thinking about it, it might be that with Protonmail's encryption settings, they might not be able to tell if a certain mail has actually been read unless it has been flagged as such in their own server.
