### ISSUE TITLE
"bodies" folder should be in mail_domain.tld, not mail@domain.tld

### ISSUE THREAD

**Issue by asakura42** [LukeSmithxyz/mutt-wizard#759]
It seems that neomutt creates folder `mail_domain.tld` in `$cachedir` (it's defined in your script: `set header_cache = $cachedir/$fulladdr/headers`)

But `mw` at other hand creates folder `mail@domain.tld` in `$cachedir`, not with `_` but with `@` (`mkdir -p "${muttrc%/*}" "$accdir" "$cachedir/$fulladdr/bodies" "${XDG_CONFIG_HOME:-$HOME/.config}/msmtp"` where `$fulladdr` is `mail@domain.tld`). Looks like that neomutt tries to load `$cachedir/mail_domain.tld/bodies` directory, but finds nothing because this directory is in `$cachedir/mail@domain.tld/`. I don't think it's major problem but anyway.

**Comment by LukeSmithxyz** [comment]
Hmm; I didn't know that mutt automatically changed @ to _, but it looks like it doesn't matter because it's smart enough to make, write and read the directories itself.

It's actually just superfluous for mw to create the directories. I had had it done manually, but I guess that's not necessary.
