### ISSUE TITLE
mailsync won't send out notifications as-is if used via cron

### ISSUE THREAD

**Issue by TheChymera** [LukeSmithxyz/mutt-wizard#763]
For notifications to get displayed, the `DBUS_SESSION_BUS_ADDRESS` env variable needs to be defined when `notify-send` is called. Environment varialbes are not inherited by sessions started with cron jobs.

This is not just pertinent for systemd (as the current version makes it sound), but, additionally, without systemd, the current pre-set value template for `DBUS_SESSION_BUS_ADDRESS` will not work: https://github.com/LukeSmithxyz/mutt-wizard/blob/685674c33e8ad0839d9eed7873df64e0314caa45/bin/mailsync#L40 .

On my system (OpenRC, Gentoo) the variable looks like `unix:abstract=/tmp/dbus-2TwZlNbdEP,guid=f9b68b9a5326...`. I have dug around a bit, and could not come up with any way to re-compute it.

The current solution I have put together passes the variable independently of mutt-wizard, and is based on [this solution](https://unix.stackexchange.com/a/111190/81037).

Briefly, I have the following script which is run when I launch my WM:

```shell
#!/bin/sh

touch $HOME/.config/sway/dbus
chmod 600 $HOME/.config/sway/dbus
env | grep DBUS_SESSION_BUS_ADDRESS > $HOME/.config/sway/dbus
echo 'export DBUS_SESSION_BUS_ADDRESS' >> $HOME/.config/sway/dbus

exit 0
```

and mailsync is recorded in crontab, as follows:

```shell
/5 * * * *  . "$HOME/.config/sway/dbus" && mailsync
```

It took me a while to figure out that this really can't easily be done in any other way, and this approach does not rely on any of the gnome or systemd-specific features of dbus — and should thus run regardless of the software set-up.

If there is indeed no better way to do this, maybe it would be a good idea to include a guide? If so, where would be the best way to put this @LukeSmithxyz ?

**Comment by LukeSmithxyz** [comment]
So what is the error if you just have the variable be manually assigned for OpenRC like it is for systemd? Does that not work?

**Comment by TheChymera** [comment]
@LukeSmithxyz it changes between login sessions, which is why it needs to be reassigned at startup as with the workflow I described above. For instance, right now it is `DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-t9NEKMsWY2,guid=540...e8f` (compare with value above).

It would be good to put this somewhere more visible, unless this could somehow be done by the mailsync script, which I don't see how it could be, since it would be running under cron...
