### ISSUE TITLE
Yahoo email doesn't sync even with 2 factor authentication enabled and app specific password used

### ISSUE THREAD

**Issue by TheHighGroundWins** [LukeSmithxyz/mutt-wizard#764]
`[user@HighGround ~]$ mw -a myAccount@yahoo.com
Enter password for myAccount@yahoo.com:
Retype password for myAccount@yahoo.com:
myAccount@yahoo.com (account #3) added successfully.`

`
[user@HighGround ~]$ mw -y myAccount@yahoo.com
Notice: Master/Slave are deprecated; use Far/Near instead.
Warning: lost track of 8062 pulled message(s)
IMAP command 'UID FETCH 5070 (BODY.PEEK[])' returned an error: NO [UNAVAILABLE] UID FETCH Service is temporarily not available
`

**Comment by LukeSmithxyz** [comment]
This isn't an isync problem, or a mutt-wizard problem, but a Yahoo! problem. They do a bunch of things weird and limit mail requests, etc. See sources like https://cs.mailstore.com/index.php?/Knowledgebase/Article/View/76/4/known-symptoms-when-archiving-yahoo-mailboxes or you can search for your error message.

The the best solution is to not use Yahoo!, but this is out of my control.

**Comment by TheHighGroundWins** [comment]
Oh I see. That's quite sad. Guess I'll start putting my Gmail in instead of my yahoo for signing up.
