### ISSUE TITLE
links with spaces

### ISSUE THREAD

**Issue by cshjsc** [LukeSmithxyz/mutt-wizard#766]
Hi,
I've had this problem multiple times
I receive an email which has a link and when it is separated by spaces or break lines I can't select it, if I try to highlight it and copy it with the mouse It will have pipes (|) in between
examples
`https://test.test/abcd&first second word`

```
https://test.test/abcd&first 
second word
```

**Comment by LukeSmithxyz** [comment]
You should really just have a talk with whoever is putting spaces in urls...

There's simply no way of making a regular expression for this that wouldn't produce millions of false positives.
