### ISSUE TITLE
Log-on not successful

### ISSUE THREAD

**Issue by tonypachino** [LukeSmithxyz/mutt-wizard#767]
when i'm doing mw -a myaccount@domain.com i'm keep getting the message log-on not successful

Where is the problem?

**Comment by rsaavedraxyz** [comment]
I had the same issue today. For some reason, passing the -f option makes it work as said in https://github.com/LukeSmithxyz/mutt-wizard/issues/622#issuecomment-761591377

**Comment by Zeioth** [comment]
I also have this issue and took me 30 min to figure out. Would be nice to document it if it's intended.
