### ISSUE TITLE
Not sure how to set up university email

### ISSUE THREAD

**Issue by Mango0x45** [LukeSmithxyz/mutt-wizard#768]
I've been using mutt wizard and neomutt for a bit, and I would like to add my university email to neomutt. My university uses outlook for email, but when you go to the webmail in your browser you get redirected to another page where you need to login with a student ID and password (which is the same as the email password). I've tried looking around for ways to get this email setup but I really have absolutely no idea how to make this work, and perhaps someone here knows what I can try to do.

**Comment by LukeSmithxyz** [comment]
You will probably use Outlook's imap/smtp servers, so you can input
those.

I can tell you at the University of Arizona, there was a special page
where we could set up an application password or IMAP password to
connect with third party applications, and I suspect that will be how it
will be if you cannot use your typical password.

Your university website will probably have SMTP and IMAP server
information if you go look for it and will probably tell you about
passwords as well.

**Comment by Mango0x45** [comment]
I know what the universities IMAP and SMTP servers are, I just can't seem to figure out how to set up the email (and I checked all the manuals the university has and none of the email-related ones have any useful information). The command I am currently using is this: `mw -a 'myimap@email' -u 'mynetid' -i 'imapserver' -I portnum -s 'smtpserver' -S portnum -x "mypassword"`, so I think I'm doing it correctly. If I cant do this via mutt-wizard how can I figure out how to do this the manual way?

**Comment by Mango0x45** [comment]
I tried that command and wasn't able to see any success. I first tried this:
```
curl -v --location-trusted -s -m 5 --user "email:password" --url "imaps://webmail.tudelft.nl:993"
```
but that just gave me:
```
* gss_init_sec_context() failed: No credentials were supplied, or the credentials were unavailable or inaccessible. No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000).
```
I then tried using my net ID instead of my email, and that gave me this:
```
> A002 AUTHENTICATE [RANDOM GIBBERISH]
< + [RANDOM GIBBERISH]
> [RANDOM GIBBERISH]
< A002 NO AUTHENTICATE failed.
```

**Comment by LukeSmithxyz** [comment]
See your information here: https://www.tudelft.nl/ict-handleidingen/e-mail-en-agenda

Their imap server is `imap.tudelft.nl` and smtp is `smtp-a.tudelft.nl`. Username should be your full email. There doesn't seem to be any application password.

**Comment by Mango0x45** [comment]
Yeah I saw that and already tried with both of those addresses with mutt-wizard and the imap one with the curl command (I probably should have been more specific with that), it seems to me that both the `webmail` and `imap` subdomains point to the same thing.

**Comment by LukeSmithxyz** [comment]
Okay. I'm going to close this issue because it seems service specific.

If doing via the command line is annoying, you might want to try doing it on Thunderbird following their directions and see what works. If you can get Thunderbird working, this will get working as well, but it might be clearer what is wrong on Thunderbird.
