### ISSUE TITLE
Mailboxes not configured right.

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/mutt-wizard#769]
I reset my neomutt settings, and upon a fresh mutt-wizard setup, neomutt doesn't display any mailboxes other than `Archive` (which is empty). This might be an issue in the muttrc for each account, and it probably shows Archive because it is the first alphabetically.

**Comment by LukeSmithxyz** [comment]
Okay. Yeah mailboxes are found dynamically now, but depending on what your email server names the boxes, I can see this might cause a problem.

Can you provide the exact names of your boxes as they exist as directories? I.e., show the results of `ls ~/.local/share/mail/your@emailaddr.com`?

**Comment by lukerb52** [comment]
`Archives  Archives.2018  Archives.2019  Drafts  INBOX  OUTBOX  Sent  Spam  Trash`

**Comment by PRESFIL** [comment]
It would also be helpful to see you what curl says about your mailboxes:

```sh
login=<your_login>
fulladdr=<your_full_email>
fulladdr=<your_protocol>
imap=<your_imap_server>
iport=<your_imap_port>
curl --location-trusted -s -m 5 --user "$login:$(pass "$fulladdr")" --url "${protocol:-imaps}://$imap:${iport:-993}"
```sh

**Comment by Tokariew** [comment]
By quick look it seems that code got to many `\` in `tr` part

**Comment by PRESFIL** [comment]
Could you show what you mean?

**Comment by Tokariew** [comment]
mailboxes in `.config/mutt/accounts` look like that for me
```
mailboxes `mdir=/home/tokariew/.local/share/mail/spamme@spam.edu.pl/; find $mdir -mindepth 1 -type d -name cur | sed -e 's:/cur$:":' -e "s:$mdir:\"=:" | sort | tr '\\n' ' '
````
And `tr` part of it have double `\` which don't work for me displaying only single inbox
after running it in terminal i get following output
```
"=Archive"
"=Cale dar"
"=Cale dar/Birthdays"
"=Cale dar/Polska &IBQ- d i wol e od pracy"
"=Cale dar/U ited Ki gdom holidays"
"=Co tacts"
"=Co versatio  History"
"=Deleted Items"
"=Deleted Items/Archive"
"=Drafts"
"=INBOX"
"=Jour al"
"=Ju k Email"
"=Notes"
"=Outbox"
"=Se t"
"=Se t Items"
"=Tasks"
"=Trash"
"=Wersje robocze"
```
You can clearly see that `tr '\\n' ' '` replace `n` to `space`
after removing single `\` from `tr` it's working fine for me

**Comment by PRESFIL** [comment]
Ok, thanks! As clear as a clear day.

Apparently, it was naively believed that in mutt escaping is required in this
context, as in Shell.

I will do PR.

**Comment by LukeSmithxyz** [comment]
I've discovered the actual issue here. The command is properly escaped in the current version of mw and I will not change it.

The issue is bash, and I will assume that everyone with this error is running a system that runs bash as `/bin/sh`. Bash does not deal with escaping this deep in a POSIX compliant fashion.

I'll revise the line to make it compatible with people running bash instead of a posix sh, but it isn't proper to change it to some bash-specific escape configuration.

**Comment by LukeSmithxyz** [comment]
I've simply removed the "feature" of dynamic mailboxes, which I wasn't really happy with in the first place because it hampers user customization. This avoids this problem.

**Comment by LukeSmithxyz** [comment]
To be clear, having one command that is both portable and acceptable to bash is not very easy in this particular place.
