### ISSUE TITLE
[Fix] SASL Authentication failed when sending email.

### ISSUE THREAD

**Issue by dankehidayat** [LukeSmithxyz/mutt-wizard#77]
So i remember on the previous commit, The setup is asking about `Gmail SMTP Server name` and `Gmail SMTP Port`.

 Then after this current version release, The setup doesn't ask you to manually add the `SMTP Server name/Port` thing, And so the email refusing to send because of the SASL Auth. So i search around the Internet and finally found the fix. 

So incase you have this problem too, just add these line to get it work.
```
 set imap_user = "JohnDoe@gmail.com"
 set imap_pass = "YourPassword"
 set smtp_url = "smtp://JohnDoe@smtp.gmail.com:587/"
 set smtp_pass = "YourPassword"
 set from = "JohnDoe@gmail.com"
 set realname = "John Doe"
```

**Comment by dankehidayat** [comment]
Of course it's Gmail.

**Comment by LukeSmithxyz** [comment]
As in "@google.com"? There are other Google mail domains.

I ask because the wizard shouldn't've asked your for your server info as the wizard has *always* had Google server information.

Is there something distinct about your Gmail account? Is it run by a university or business or something?

**Comment by dankehidayat** [comment]
It's just a personal account, I make this issue to help people that encounter the same problem as i did. And i showed to them how to fix it. You can close this issue now, but people might don't know this issue :(
