### ISSUE TITLE
Need a way to reset 'notmuch' Search, specifically the Xapian database.

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/mutt-wizard#770]
I recently reinstalled my OS while keeping my home directory, but changing my username. I reset as much of mutt as I could, but now I cannot get the notmuch search to work. This is what displays:

`Compiling search pattern...Cannot open Xapian database at /home/luke/.local/share/mail/.notmuch/xapian: Couldn't stat '/home/luke/.local/share/mail/.notmuch/xapian'`

A possible fix might be bringing back the "purge" option for just such occurrences as these.

**Comment by LukeSmithxyz** [comment]
Not really an issue with this repo if you're manually renaming directories. Just change the file location mentioned in the notmuch configuration file, which may be either in home or config.
