### ISSUE TITLE
Password-store

### ISSUE THREAD

**Issue by se7en-x230** [LukeSmithxyz/mutt-wizard#775]
where would I teach mw to search the password in a subfolder and not the root of password-store/

**Comment by LukeSmithxyz** [comment]
It only adds passwords to the root as is for simplicity's sake. I am open to having a mw subdirectory if there is demand for it and it doesn't interfere with anything else.

**Comment by se7en-x230** [comment]
I guess adding the subfolder to
`PassCmd "pass mutt/me@mail.org` in the .mbsyncrc file works.
