### ISSUE TITLE
Syncing not working

### ISSUE THREAD

**Issue by marhu98** [LukeSmithxyz/mutt-wizard#777]
The -Y option is not working "out of the box". When I run 
```
mw -Y
```

I get:
```
 For more details see pgrep(1).
 not logged in; sync will not run
```

I set up my account using mw -a, is there something missing? (I did run mbsync -a so I can see the email, although all the email appears under the draft folder for some reason).

**Comment by PRESFIL** [comment]
Looks like expression `"${USER:=$LOGNAME}"` return nothing in your environment.

Please, show values of the `USER` and `LOGNAME` variables:

```sh
echo $USER
echo $LOGNAME
```
