### ISSUE TITLE
Unable to recover from UIDVALIDITY change.

### ISSUE THREAD

**Issue by Goth** [LukeSmithxyz/mutt-wizard#779]
So I had to move 2 email accounts on a different server that was setup automatically and reconfigured all from the beginning.
Thunderbird and phones are configured but neomutt does no want to add the accounts back. 

Got this error: 
`C: 0/1  B: 0/5  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Error: channel iulian@georgescu.xyz, far side box INBOX: Unable to recover from UIDVALIDITY change.
C: 0/1  B: 3/5  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Error: channel iulian@georgescu.xyz, far side box Sent: UIDVALIDITY genuinely changed (at UID 2).
C: 0/1  B: 4/5  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Error: channel iulian@georgescu.xyz, far side box Trash: Unable to recover from UIDVALIDITY change.
C: 1/1  B: 5/5  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Press any key to continue...`

This is for both accounts.

**Comment by LukeSmithxyz** [comment]
Either delete the local `.uidvalidity` files and perhaps `.mbsyncstate` files in your local mail archive or delete and remake the whole directory (perhaps by readding the account in mutt-wizard).

Mbsync has this failsafe in place to avoid accidentally missyncking your mail.
