### ISSUE TITLE
Error Sending Mail After Adding A/I Account

### ISSUE THREAD

**Issue by BurnyBoi** [LukeSmithxyz/mutt-wizard#78]
I have added 2 different Autistici/Inventati accounts using mutt-wizard, but when I go to send an email with either account, the email cannot be sent. Upon pressing the key to send, the bottom of Neomutt says "connecting to smtp.autistici.org..." for about 5 minutes. After this, it says "SMTP session failed: read error".  I added a cock.li email using the wizard, and was able to start sending email without any other config.

There is 1 workaround that I know of, which is to comment out the "set smtp_url" line in the account's muttrc file, and then create a ~/.msmtprc file containing something like this:

account myemail
port 587
from myemail@autistici.org
user myemail@autistici.org
password [password in plain text]
auth on
tls on
tls_starttls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
host smtp.autistici.org
tls_certcheck on

This is not an ideal solution, since now I have my password in plain text, and my account information is being maintained in another file not controlled by mutt-wizard.

Some other things I tried individually include:
- in the "set smtp_url" line of the account's muttrc, change the port number from 465 to 587. This causes me to immediately get a 'SASL authentication failed' when sending.

- In the "set sendmail" line of the account's .muttrc, I tried adding the following on the end of the command to match what I have above in the msmtprc: "--tls=on --tls-starttls=on --tls-trust-file=/etc/ssl/certs/ca-certificates.crt --tls-certcheck=on". After adding this, I get the same result where it keeps saying it's connecting for 5 mins.

I know this isn't really a fault of the wizard, but any advice on how I can resolve this in a way that will pull my password from the keyring like everything else?

**Comment by LukeSmithxyz** [comment]
Well, you can add a `passwordeval` line to your msmtp file as stated [in the Arch wiki](https://wiki.archlinux.org/index.php/Msmtp#Password_management).

The Autistici/Inventati  server info didn't come from me, and obviously someone like me isn't going to have one of their accounts so I can't test it. I'm not sure why changing the port in the mutt config wouldn't work, but the msmtprc would.

Anyway, I think I still might add an automatic msmtprc generator eventually.

**Comment by LukeSmithxyz** [comment]
Here's the passwordeval line that you'd need. Replace `luke` with whatever your backend name for your email is. The `sed` command is to add a trailing newline, which is apparently necessary.
```
passwordeval "gpg -d --quiet --for-your-eyes-only --no-tty ~/.config/mutt/credentials/luke.gpg | sed -e '$a\'"
```
