### ISSUE TITLE
Only `Drafts` folder shows in sidebar, how do I add INBOX, Sent and all the rest?

### ISSUE THREAD

**Issue by JPcode05** [LukeSmithxyz/mutt-wizard#784]
When Neomutt loads, it correctly sends me to my Inbox, and I can switch boxes using gs, gd, gi, etc. However, only `Drafts` shows in the sidebar. Where's all the rest?

**Comment by PRESFIL** [comment]
Looks like it duplicate of https://github.com/LukeSmithxyz/mutt-wizard/issues/769.
We are all waiting until this [PR](https://github.com/LukeSmithxyz/mutt-wizard/pull/771) are merged.

You can manually remove extra backslash (`\`) from your current `~/.config/mutt/accounts/user@domain.net.muttrc`.
From `tr '\\n' ' '` to `tr '\n' ' '`

You can also apply changes from PR on `/usr/bin/mw` and recreate your account, to prove that
PR is working and confirm [there](https://github.com/LukeSmithxyz/mutt-wizard/pull/771) that it's working :smile:

**Comment by JPcode05** [comment]
> You can manually remove extra backslash (`\`) from your current `~/.config/mutt/accounts/user@domain.net.muttrc`. From `tr '\\n' ' '` to `tr '\n' ' '`

Thanks! It worked!
