### ISSUE TITLE
neomutt on android phone 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/mutt-wizard#785]
I just installed [arch](https://gist.github.com/RebelLion420/bd1c94e320c0c6c56e33a1dc75e5f4a2) on android phone 

photos that i am running arch  on phone 
https://postimg.cc/nCPPKvwQ
https://postimg.cc/hXQ32fHZ

I setup the pass + gpg , mutt-wizard and I am ready to sync with my email server .... 

guess what the my user is not logged in ... as showing in the picture .. 
( i used su - jemadux ) 
is there any way to bypass that security issue and will be work  ?

**Comment by LukeSmithxyz** [comment]
I don't know anything about Android. My only guess is that your phone lacks the command `pgrep`, which is used to see if the user is logged on. Either that or the way it works on Android is different.

Theoretically, I may be able to just remove that logon check without inconveniencing people.
