### ISSUE TITLE
Deleting an account should not remove the password from pass.

### ISSUE THREAD

**Issue by Randalix** [LukeSmithxyz/mutt-wizard#788]
If you delete a mail account  its password gets also removed from pass. This should not happen. 
Instead if you add an account it should be checked if there is an existing password saved in pass and use the existing password.

**Comment by LukeSmithxyz** [comment]
What? Why would the default functionality be to leave hanging unused passwords on a computer?

**Comment by PRESFIL** [comment]
Apparently some people use `pass` as their primary password manager, and
passwords should not be removed from there. Previously, it seems there was a
prefix `mw-`, but now without it, `mw` affects all passwords in the store.

Alternatively, `mw` could use a separate password storage, somewhere in
`.local/share/mutt-wizard`.

**Comment by Randalix** [comment]
> Alternatively, `mw` could use a separate password storage, somewhere in `.local/share/mutt-wizard`.
Or save the entered password in a pass subfolder for mutt-wizard .

**Comment by LukeSmithxyz** [comment]
It might be sensible to use a subfolder, but as it is, not deleting the passwords only causes issues. The only real issue as is is if someone has manually saved a password with the email address's name, which I would think unlikely, but it might be worth moving the encrypted files to a subdirectory for this reason.
