### ISSUE TITLE
a dot in short name cause it fail

### ISSUE THREAD

**Issue by p3ll1n0r3** [LukeSmithxyz/mutt-wizard#79]
Started creating a mailbox with the setup script, called the shortname "***.***.gmail"
OfflineImap synced the mailbox correctly, all directories looked ok.
But starting Neomutt, it fails miserably with ".... is not a mailbox"
I scratched my head for a long time and erased all configuration and run it again with a shortname  "mhgmail"... and resynced again , and now it works.

If  this is a valid issue, create a check in the setup script checking for a dot in the short and reject it.

**Comment by LukeSmithxyz** [comment]
Yeah this is sort of overdue. I've added a line that will check it to ensure that it's the format of a username.

Come to think of it, I might as well add similar checks to ensure valid email addresses just in case so I'll do that too.
