### ISSUE TITLE
No way to refresh folder list in the sidebar

### ISSUE THREAD

**Issue by ekollof** [LukeSmithxyz/mutt-wizard#790]
I know that list is generated with mw with account setup, but there doesn't seem to be a way to refresh the folder list other than nuking the account and setting it up again.

**Comment by PRESFIL** [comment]
Welcome. But this function is reverted by 29f264d [until an indefinite period](https://github.com/LukeSmithxyz/mutt-wizard/issues/769#issuecomment-956469836).

**Comment by LukeSmithxyz** [comment]
Change the `mailboxes` line in config file. If you don't know how to edit a config file, you shouldn't be using this. This tool is only for setting sensible defaults up.
