### ISSUE TITLE
Adding all email addresses to abook

### ISSUE THREAD

**Issue by gerazov** [LukeSmithxyz/mutt-wizard#793]
Mutt-wizard is great to make an easy transition from GUIs, e.g. Thunderbird, to the neomutt TUI, Is there a way to populate `abook` with all the emails in the mail folder? This would be very useful.

So far I've found [this binding](https://github.com/neomutt/neomutt/issues/2767) for adding the From: address automatically when opening messages:
```vim
set display_filter = "pee 'abook --add-email-quiet' 'cat -'"
```

And [this one](https://unix.stackexchange.com/questions/521167/add-to-addresses-from-sent-mail-to-abook) that allows (only the first) To: address to be added to abook using a macro:
```vim
macro index,pager,attach a  "<pipe-message>sed -e /^From/d -e s/To:/From:/ | abook --add-email<return>" "add the to: address to abook?"
```

And of course the `mutt-wizard`:
```html
macro index,pager a "<enter-command>set my_pipe_decode=\$pipe_decode pipe_decode<return><pipe-message>abook --add-email<return><enter-command>set pipe_decode=\$my_pipe_decode; unset my_pipe_decode<return>" "add the sender address to abook"
```

Is there a way to do this for all messages?

**Comment by sahidvelji** [comment]
See the section on Using Tags in the Neomutt "Advanced Usage" guide. Here's what I did a couple of months ago:
Shift+T # tag messages matching:
. <Enter> # tag all messages
; # tag-prefix operator. The next operation is applied to all tagged messages.
a # where "a" is bound as above, in your post. You should use --add-email-quiet here if you don't want to be prompted before each addition to abook.
