### ISSUE TITLE
Features I would like added into mutt-wizard

### ISSUE THREAD

**Issue by JPcode05** [LukeSmithxyz/mutt-wizard#794]
# More than 9 accounts

First, we shouldn't be limited to 9 accounts. Instead of having to press `i#` and be limited to 1-9, you should just be able to press `i` and have a list of all your accounts in an ordered list, then select one and change to it.

# README.md Changes

## Adding accounts
* `-i` and `-I` shouldn't just be limited to IMAP, but rather IMAP/POP instead. Those who add `-P` will be given a POP server that they select with `-i` and `-I`, and those who don't will be given IMAP instead. This change was already made when I just type `mw`.
* Add `mpop` to the main dependencies list, just saying that it's optional but required for POP just like how `isync` is required for IMAP.

Also, how do I update mutt-wizard without uninstalling my configs?

**Comment by joshuajeschek** [comment]
Hi, did anything come of the first suggestion?
The quick solution to support my 12+ mailboxes was to another set of shortcuts with a capital `I`.
However, a visual way to select the accounts would be great, as it can be quite difficult to remember all the numbers.
