### ISSUE TITLE
Mutt is not using Gmail's trash folder

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/mutt-wizard#797]
for some reason, mutt is not using gmail's trash folder anymore, instead it's creating a [Imap]Trash label, and because of it when I login to Gmail via browser, i have all my mutt deleted emails in [Imap/Trash](https://0x0.st/-7tJ.png) instead of Trash ... and the next time i sync, I have 2x Trash folder in Mutt ... this was not happening before, how do i fix it?

**Comment by elkoniu** [comment]
Yesterday I tried latest mutt-wizard and observed exactly the same behavior with my gmail account (used with app password).

**Comment by kronikpillow** [comment]
Still no feedback on how to fix this, this behavior wasnt present before

**Comment by LukeSmithxyz** [comment]
Change your trash variable in mutt.

**Comment by kronikpillow** [comment]
shouldn't the trash variable be changed in mutt-wizard itself? since most users who use gmail will have this bug ... also I;v tried, but i was unsuccesful
