### ISSUE TITLE
Can't run offlinemap after creating Gmail-account

### ISSUE THREAD

**Issue by praschdorff** [LukeSmithxyz/mutt-wizard#8]
thanks for the script and the idea to make mutt easier to use for beginners.
I tried to setup neomut using mutt-wizard but run into a problem that I can't run offlineimap after adding my gmail-account and reaching the step:

> The account "Gmail" has been added.
> Now finalize the installation, do the following:
> [...]

I opened a 2nd terminal and entered: offlineimap but run into several error messages:

[user@my-untrusted ~]$ offlineimap 
Traceback (most recent call last):
  File "/usr/bin/offlineimap", line 23, in <module>
    oi.run()
  File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 51, in run
    options, args = self.__parse_cmd_options()
  File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 199, in __parse_cmd_options
    config.set_if_not_exists('general', 'dry-run', 'False')
  File "/usr/lib/python2.7/site-packages/offlineimap/CustomConfig.py", line 132, in set_if_not_exists
    self.set(section, option, value)
  File "/usr/lib64/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/usr/lib64/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'

I thought that mutt-wizard will create the needed configuration files, but ~/.offlineimaprc is an empty file.

Any idea how to proced?

About my system:
I am running Qubes 4rc4 with a Fedora 26 based AppVM.
I have installed neomutt dialog, offlineimap and neomutt using these steps within the default fedora 26 template:

Install offlineimap and dialog:
dnf -y install dialog offlineimap dialog

to install neomutt in fedora:
Link: https://www.neomutt.org/distro/fedora
sudo dnf install dnf-plugins-core
sudo dnf copr enable flatcap/neomutt
sudo dnf -y install neomutt

OFFLINEIMAP:
Version: 6.7.0

DIALOG:
Version: 1.3-20170131

NEOMUTT:
Version: NeoMutt 20171215

System: Linux 4.9.56-21.pvops.qubes.x86_64 (x86_64)
ncurses: ncurses 6.0.20170212 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)

- P.

**Comment by praschdorff** [comment]
Is maybe this the correct way to setup GMAIL in Mutt:
https://hobo.house/2017/07/17/using-offlineimap-with-the-gmail-imap-api/

**Comment by ralpheeee88** [comment]
@praschdorff running into the same issue as you (when i try to list my email accounts no email accounts are found even though i tried to set gmail up....also when trying to setup gmail it asked me the smtp/imap configs which i had to add manually....hence the settings are not being auto detected....

**Comment by praschdorff** [comment]
Hello ralpheeee88,

I have been able to get a working installation with offlineimap and neomutt by configuring it manually.
I had to tell offlineimap where to find the certificates (in a fedora 26 installation):
sslcacertfile = /etc/ssl/certs/ca-bundle.crt

My configuration files for reference:
=============
~/.offlineimaprc
=============

[general]
accounts = Gmail

### GMAIL
[Account Gmail]
localrepository = Gmail-Local
remoterepository = Gmail-Remote
status_backend = sqlite
#postsynchook = notmuch new

[Repository Gmail-Remote]
type = IMAP
remotehost = imap.gmail.com
remoteuser = <USERNAME>@googlemail.com
# to access Gmail via IMAP create an App-Password for offlineimap
# Add an app-password  here:
# https://security.google.com/settings/security/apppasswords
remotepass = <GOOGLE-APP-PASSWORD>
sslcacertfile = /etc/ssl/certs/ca-bundle.crt
ssl = yes

[Repository Gmail-Local]
type = Maildir
localfolders = ~/Emails/Gmail
restoreatime = no



and my configuration for mutt:

========
~/.muttrc
========

### save and sync my sent messages
set record=~"/Emails/Gmail/[Google Mail].Gesendet"
set spoolfile=~/Emails/Gmail/INBOX
# set header cache
set header_cache=~/Localmail/hcache
# needed for maildir format
set mbox_type=Maildir
set folder=~/Emails/Gmail/
# IMAP and INBOX (this should map to any existing IMAP folders)
# I have disabled all other "labels" in GMAIL preferences like "All Emails" etc.
# tweak the mailboxes (folders) to your gmail localization.
# if you don't know the names, look into your maildir folder ~/Emails/Gmail in my case ;-)
mailboxes =INBOX \
="[Google Mail].Gesendet" \
="[Google Mail].Entw&APw-rfe" \
="[Google Mail].Papierkorb" \
="[Google Mail].Spam" \
=Archives \

#### SMTP
#### http://nickdesaulniers.github.io/blog/2016/06/18/mutt-gmail-ubuntu/
set realname = "<YOUR NAME>"
set from = "<USERNAME>@gmail.com"
set use_from = yes
set envelope_from = yes
set smtp_url = "smtps://<USERNAME>@gmail.com@smtp.gmail.com:465/"
set smtp_pass = "<YOUR-GMAIL-APP-PASSWORD>"
#### Other mutt settings:
#### SORTING
#### newest email on top
set sort = reverse-date-received
### threaded sorting according to the most recent e-mail in a thread
#set sort=threads
#set sort_browser=reverse-date
#set sort_aux=last-date-received

#### SIDEBAR
# Make the Sidebar visible by default
set sidebar_visible
# Sidebar Options
set sidebar_format = "%B%?F? [%F]?%* %?N?%N/?%S"
set mail_check_stats
# Use 'B' to switch the Sidebar on and off
bind index,pager B sidebar-toggle-visible


I hope this helps setting up mutt for you ;-)

- P

**Comment by praschdorff** [comment]
WARNING: While setting up offlineimap:
Don't delete your Maildir-directory completly and rerun offlineimap as this might cause to a situation where data will be deleted on the mailserver.
More information: https://github.com/OfflineIMAP/offlineimap/issues/333#issuecomment-227907749
-P

**Comment by LukeSmithxyz** [comment]
Gmail accounts should work out of the box. I've verified it myself.

It looks like your `~/.offlineimaprc` is not being generated. Did you close the *entire* repository? You need the whole repo in `~/.config/mutt` because the script builds config files based on the templates in that folder.

**Comment by praschdorff** [comment]
@LukeSmithxyz 
> You need the whole repo in ~/.config/mutt

What exactly do you mean? After installing neomutt/dialog/offlineimap I have created a new folder mutt to which I git-cloned your script.
I then started your script via ~/mutt/mutt-wizard.sh
Do I need to copy the content of the repository to ~/.config/mutt ?
- P

**Comment by LukeSmithxyz** [comment]
Yes.

**Comment by ZMASLO** [comment]
Having the same issue. I've git cloned repo to .config/mutt/mutt-wizzard then I performed run of script. But after running offlineimap I have same message as OP

**Comment by LukeSmithxyz** [comment]
The content does not go in `~/.config/mutt/muttwizard`, but in `~/.config/mutt`.

**Comment by praschdorff** [comment]
Ok, it's also mentioned in your README:

> `## Installation and Dependencies
> `[...]
> `the contents of this repo should go directly in `~/.config/mutt/` and run from there.

I'll delete my installation and retry.

- P

**Comment by ZMASLO** [comment]
I've changed dir to .config/mutt wiped configuration and created it from scratch but now I have following problem after running offlineimap:

```
OfflineIMAP 6.6.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Thread 'Account sync sylwaker' terminated with exception:
Traceback (most recent call last):
  File "/usr/share/offlineimap/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 249, in syncrunner
    self.localrepos  = Repository(self, 'local')
  File "/usr/share/offlineimap/offlineimap/repository/__init__.py", line 82, in __new__
    return repo(name, account)
  File "/usr/share/offlineimap/offlineimap/repository/Maildir.py", line 40, in __init__
    os.mkdir(self.root, 0o700)
OSError: [Errno 2] No such file or directory: '/home/zmaslo/.mail/sylwaker'


Last 3 debug messages logged for Account sync sylwaker prior to exception:
thread: Register new thread 'Account sync sylwaker' (account 'sylwaker')
imap: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
maildir: MaildirRepository initialized, sep is '.'
```

**Comment by ralpheeee88** [comment]
where do i signup for reading lessons? ...all working thxs @LukeSmithxyz

**Comment by LukeSmithxyz** [comment]
@ZMASLO What version of offlineimap do you have? If you did everything right it looks like offlineimap isn't creating directory structure, which it should do automatically.

What happens after running `mkdir -p /home/zmaslo/.mail/sylwaker/`?

**Comment by praschdorff** [comment]
I have delete my old config files and maildirs.
I have placed all files in ~/.config/mutt and run ~/.config/mutt/mutt-wizard.sh from there.
after adding my googlemail-adress I still had to manually choose IMAP and SMTP server, which is not a major deal.
On step 2 of the installation process where I should run offlineimap I run into an error, which I could fix by editing ~/.offlineimaprc:
I have removed:
sslcacerfile = /etc/ssl/cets/ca-certificates.crt
sslcacertfile = /etc/ssl/certs/ca-certificates.crt

and added (for a fedora 26 based installation):
sslcacertfile = /etc/ssl/certs/ca-bundle.crt

Then I was able to run offlineimap but run into an error as the maildir-directory was not yet created.
I run:
mkdir -p /home/user/.mail/Gmail

then I could run offlineimap, which also downloaded my mails.
Now I am stuck that I can open neomutt but there are no mails present.

I think mutt is looking into the wrong location as the status line says:
---NeoMutt: /var/spool/mail/user [Msgs:0]---(reverse-date/date)------------------------------------------(all)---

but  /var/spool/mail/user is an empty directory it seems the setup information from offlineimap is not pushed to the mutt configuration.
Maybe you can create a more detailed howto setup mutt-wizard, so that we can reproduce the steps on both sides?
- P

**Comment by LukeSmithxyz** [comment]
If it asked you for your IMAP/SMTP, that means that you didn't actually put `domains.csv` or the build files in the proper place.
```
rm -rf ~/.config/mutt/
rm ~/.offlineimap
git clone https://github.com/lukesmithxyz/mutt-wizard.git ~/.config/mutt/
~/.config/mutt/mutt-wizard.sh
```
+ Add an account in the wizard.
+ Start running `offlineimap`.
+ Choose the detect mailbox option

**Comment by ralpheeee88** [comment]
@LukeSmithxyz  what you using for an address book?

**Comment by praschdorff** [comment]
It seems that ~/.config/mutt/personal.muttrc is referencing to the correct sub mutt config file:

```
(...)
macro index,pager i1 '<sync-mailbox><enter-command>source /home/user/.config/mutt/accounts? /Gmail.muttrc<enter><change-folder>!<enter>
source /home/user/.config/mutt/accounts/Gmail.muttrc
```
/home/user/.config/mutt/accounts/Gmail.muttrc contains:
replaced  the correct information in the config file with MYNAME and MYUSERID.
So far everything looks good, but neomutt doesn't show any folders.
 
```
# vim: filetype=neomuttrc
# muttrc file for account Gmail
set realname = "MYNAME"
set from = "MYUSERID@googlemail.com"
set smtp_url = "smtp://MYUSERID@googlemail.com@:/"
set sendmail = "/usr/bin/msmtp -a Gmail"
set folder = "~/.mail/Gmail"
set header_cache = ~/.config/mutt/accounts/Gmail/cache/headers
set message_cachedir = ~/.config/mutt/accounts/Gmail/cache/bodies
set certificate_file = ~/.config/mutt/accounts/Gmail/certificates
source "~/.config/mutt/credentials/getmuttpass Gmail |"

set mbox_type = Maildir
set ssl_starttls = yes
set ssl_force_tls = yes

bind index,pager g noop
bind index gg first-entry
```
- P

**Comment by LukeSmithxyz** [comment]
So tell me what error you got when you tried to run the "Auto-detect mailboxes" option as in the instructions.

**Comment by praschdorff** [comment]
I'm retrying, cleanup old stuff:
```
rm -Rf ~/.mail
rm -Rf ~/.config/mutt
rm -Rf ~/.offlineimaprc
```
Running mutt-wizard from scratch:
```
git clone https://github.com/lukesmithxyz/mutt-wizard.git ~/.config/mutt/
rm -rf ~/.config/mutt/
rm ~/.offlineimap
git clone https://github.com/lukesmithxyz/mutt-wizard.git ~/.config/mutt/
~/.config/mutt/mutt-wizard.sh
#Choose 2: Add an Email Account
#Enter Email address for GPG ... USER@gmail.com ... Ok
#Enter Email for account setup ... USER@gmail.com ... Ok
#Enter Name ... MY NAME ... Ok
#Short one-word mailaccount-identifier ... Gmail ... Ok
#Enter password ... **** ... Ok
#Finalizing Your Account Screen (leaving this screen open)
#Launching another terminal:
offlineimap
#Popup-Window which asks for my GPG Password ... *** ... Ok
#offlineimap gets emails and ends with: 
#Account sync Gmail: *** Finished account 'Gmail' in x:yy
#Checking that I can see the emails under .mail:
ls ~/.mail
#Going back to mutt-wizard where the "Finalizing your account" window is waiting for me ... Ok
#Would you like to add another  email account ... No
#Launching 2) Auto-detect mailboxes
#Mailbox detect requirement ... Yes
#Mailbox detect complete and Info about shortcuts ... Ok
#Chose 6) Exit this wizard
#1st start of neomutt:
neomutt
```
Great, it's all there - it seems that the auto-detection of IMAP/SMTP is only working for @ gmail.com not @ googlemail.com which I have used now.
I have probably also messed up the 2nd installation step.
Happy to have mutt up and running, maybe my feedback can improve the howto. After knowing what t do everything is actually working.
Great work Luke! Looked for a supporter link on your page, to send a few bucks for <INSERT-FAVORITE-DRINK-HERE> but couldn't find anything.
- P

**Comment by LukeSmithxyz** [comment]
Okay great! I added googlemail.com to the domains list too for future use. I'll probably be putting more of the build files into the script itself for easiness's sake.

Oh yeah I have all the support link on the YouTube channel page: https://www.patreon.com/lukesmith and https://www.paypal.me/LukeMSmith

**Comment by ZMASLO** [comment]
@LukeSmithxyz after creating directories ._mail/sylwaker_ everythink works fine :+1: 
You may add feature to script to check that following dir exist :wink: 
Thank you for help :smile:
