### ISSUE TITLE
Notifications not always working on Wayland

### ISSUE THREAD

**Issue by BoostCookie** [LukeSmithxyz/mutt-wizard#800]
The notifications are not always working on Wayland. The program relies on xwayland running to find the display:
https://github.com/LukeSmithxyz/mutt-wizard/blob/e6087481ad26e7a328a11d9537dcce18982bbc5e/bin/mailsync#L42

On a Wayland session this `pgrep` returns nothing when no X11 program has been started yet.

**Comment by BoostCookie** [comment]
To be honest I don't get why this for loop over all displays is even there. Shouldn't it be enough to just take the current `$DISPLAY`?

**Comment by BoostCookie** [comment]
I want to add that
https://github.com/LukeSmithxyz/mutt-wizard/pull/662
did not fix it. There's no default fallback. It just checks whether `$pgrepoutput` is empty and if it is, no notification is sent.

**Comment by LukeSmithxyz** [comment]
I don't use wayland yet and I can't bugtest this. Just as a note... This has always been broken and it always will be.

This script has to deal with the herculean task of running not just on Xorg and Wayland, but Mac and BSD and most importantly as a cronjob where it is totally ignorant of user variables, display information, monitors, which tty you're on etc. This script is disgustingly hacky and I actually almost removed the notification feature this week.

I am pretty sure it works on Mac and maybe some systemd distros on Xorg. I think. It doesn't even run on my computer. Getting anything graphical to work with a cronjob is hard (impossible) enough, let alone on all these different systems.

**Comment by octaskin** [comment]
Anyone stumbled into this later it is rather easy to fix it for Wayland.
Just overwrite the notify function call as you wish
```sh
...
		export DISPLAY=$x
		notify-send --app-name="mutt-wizard" "New mail!" "📬 $2 new mail(s) in \`$1\` account."
	done; }
	;;
esac
notify() {
	notify-send --app-name="mutt-wizard" "New mail!" "📬 $2 new mail(s) in \`$1\` account."
}
# Check account for new mail. Notify if there is new content.
syncandnotify() {
...
```
Voila!
