### ISSUE TITLE
`Enter keyID for ____` Won't accept keyID.

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/mutt-wizard#801]
I can't encrypt emails now because this prompt that shows up when I try to encrypt them won't do anything. I get no confirmation or error, the question just loops.

**Comment by LukeSmithxyz** [comment]
If you're encrypting with PGP, don't select the `encrypt` option, but the `pgp` option. It's kind of confusing, but if I remember right, `encrypt` is actually looking for an RSA key id or something.
