### ISSUE TITLE
SMTP session failed: read error

### ISSUE THREAD

**Issue by BuddhiLW** [LukeSmithxyz/mutt-wizard#802]
I configured the mail by

```sh
mw -a my-mail@gmail.com
```

I was able to sync, visualize e-mails etc. But, I can't send an e-mail.

![pic-window-211213-1524-30](https://user-images.githubusercontent.com/59554283/145867489-970efa64-3ad4-4868-99b1-723dec50f3d1.png)

**Comment by schnippo** [comment]
###Same problem here but found a dirty workaround:
I had the same problem and solved it by adding 
```
set smtp_pass = `pass YOUR_EMAIL`
```
*manually* to my ~/.config/mutt/accounts/YOUR_EMAIL file.
It is a dirty workaround until I really understand the problem.
The inherent problem is that I have to unlock my gpg-keyring everytime I start a neomutt instance. A workaround for that would be using pam-gnupg to permanently unlock the gpg-keyring at login. I do not have this set up yet and it is not really a desirable way to solve our problem.

###A few hints at what might go wrong:
Seems that the mail sending command itself does not receive the password successfully.

Here we see how neomutt sends emails: 
https://github.com/LukeSmithxyz/mutt-wizard/blob/e6087481ad26e7a328a11d9537dcce18982bbc5e/bin/mw#L97

and here msmtp is trying to get the password:
https://github.com/LukeSmithxyz/mutt-wizard/blob/e6087481ad26e7a328a11d9537dcce18982bbc5e/bin/mw#L46

**Comment by BuddhiLW** [comment]
I recently reinstalled the OS etc, and it's working fine, now. The difference, regarding the installation, is that I used everything from the AUR, instead of building from GitHub.

Thanks for sharing @schnippo .
