### ISSUE TITLE
SSL error connecting imap.example.com: certificate has expired

### ISSUE THREAD

**Issue by Mark137618319** [LukeSmithxyz/mutt-wizard#803]
I am syncing mail with my own email address I created with emailwiz on neomutt, and I receive this message:

`SSL error connecting imap.example.com: certificate has expired`

I went to my server and ran certbot on both mail.example.com & imap.example.com to renew their certificates. Renewing was successful for both subdomains, and I went to the imap.example.com domain on my web browser and noticed only an HTTP connection after giving it a certificate. I reloaded the Dovecot service next. It is running active, but nothing has changed to solev the problem. I tried to sync my mail again and now this message displays:

`Error, certificate owner does not match hostname imap.example.com`

I learned that I can look at Postfix and Dovecot's config files to see where they are reading the certificate for IMAP, but I have no idea what lines they would be located in. I appreciate the help.

p.s. Using example.com as placeholder for private email.

**Comment by lonyelon** [comment]
I have the same problem

**Comment by lonyelon** [comment]
It is weird that that didn't work for you. If you have the same problem normally it would be solved with sshing into the server and running:
```sh
su -
certbot -d <your-domain>
systemctl reload dovectot
```

**Comment by lonyelon** [comment]
Shouldn't have closed this, experiencing this problem right now and my commands don't fix it, I'll post the solution once I figure this out.

**Comment by lonyelon** [comment]
Ok, so the commands can fix the issue in 99% percent of cases, but somehow in mine they didn't, here is the reason:

While renewing the certificates certbot may create another certificate, in my case:
```sh
root@localhost:~# certbot certificates
  Certificate Name: mail.lony.xyz-0001
...
  Certificate Name: mail.lony.xyz
...
```

If this somehow happens, you just have to revoke and delete both certificates:
```sh
 certbot revoke --cert-name <first cert name>
 certbot revoke --cert-name <second cert name>
 certbot delete --cert-name <first cert name>
 certbot delete --cert-name <second cert name>
 ```
 
 And then run the commands:
```sh
su -
certbot -d <your-domain>
systemctl reload dovecot
```

As said, this is very uncommon and the previous three commands will solve the problem in 99% of cases.

**Comment by Combowombo** [comment]
> It is weird that that didn't work for you. If you have the same problem normally it would be solved with sshing into the server and running:
> 
> ```shell
> su -
> certbot -d <your-domain>
> systemctl reload dovecot
> ```

This solved my issue, thank you!
