### ISSUE TITLE
problem with adding new account with script 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/mutt-wizard#808]
[![pic-selected-220104-1650-28.png](https://i.postimg.cc/tCPnTzj8/pic-selected-220104-1650-28.png)](https://postimg.cc/8jpzXMsb)
basically that i know for sure that i have one account jemadux@ with personal contact and the angelos@ with bussiness 
the angelos@ email hosted on hostgator . 

`mailsync
C: 0/1  B: 3/13  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
IMAP error: mailbox name INBOX.Archive contains server's hierarchy delimiter
C: 0/1  B: 4/13  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
IMAP error: mailbox name INBOX.Drafts contains server's hierarchy delimiter
C: 0/1  B: 5/13  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
IMAP error: mailbox name INBOX.Junk contains server's hierarchy delimiter
C: 0/1  B: 6/13  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
IMAP error: mailbox name INBOX.Sent contains server's hierarchy delimiter
C: 0/1  B: 7/13  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
IMAP error: mailbox name INBOX.Trash contains server's hierarchy delimiter
C: 0/1  B: 8/13  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
IMAP error: mailbox name INBOX.spam contains server's hierarchy delimiter
C: 0/1  B: 14/19  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
C: 1/1  B: 19/19  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
No new mail. `

any idea how to fix it ?

**Comment by LukeSmithxyz** [comment]
This is an mbsync issue based on (just at first glace) the fact that it uses `.` as a delimiter. You can check the `man mbsync` or their support.

The solution should be to add a `Flatten` command with a delimiter that isn't a period (I think). You'll also probably have to remove the local directories created and resync.
