### ISSUE TITLE
GPG description failed on Mac

### ISSUE THREAD

**Issue by darol100** [LukeSmithxyz/mutt-wizard#81]
I have tried to the installation of the wizard multiple times and it always get this error:

<img width="618" alt="screen shot 2018-09-06 at 8 09 02 pm" src="https://user-images.githubusercontent.com/6808460/45196577-dacf3180-b211-11e8-8d0b-f51c35d9db66.png">

Computer:  MacBook Pro 13-inch, 2017
I have installed all the depencies.

My GPG installation is located at: `/usr/local/bin/gpg`

 I tried to created soft  link by doing `sudo ln -s /usr/local/bin/gpg /usr/bin/gpg` but I got "Operation not permitted". This seem to be a Mac issue - [Cannot create a symlink inside of /usr/bin even as sudo
](https://stackoverflow.com/questions/36730549/cannot-create-a-symlink-inside-of-usr-bin-even-as-sudo)

Whenever I tried to open Mutt, I get this error `~/.mbox: No such file or directory (errno = 2)`

Have anyone run into this issue before?

**Comment by darol100** [comment]
Any thought on this? Maybe is an issue with Mac/OSX?

**Comment by LukeSmithxyz** [comment]
It sounds like a Mac problem, but I know there are Mac users around who have configured mutt with this. I don't own a Mac, so I can't troubleshoot it.

You could probably manually change all the instances of the `gpg2` command to simply `gpg`. This would be:

- around line 31 in the wizard script, change the `gpg2` at the beginning to `gpg`
- in the `credentials/imappwd.py` file, change the one instance of `gpg2` to `gpg`
- same thing in the `credentials/getmuttpass` file

**Comment by Jesse415** [comment]
I recieved the same error on my debian linux os. I do have /usr/bin/gpg though not sure what to do from here...

**Comment by seanoreillyza** [comment]
I needed to make the following tweaks to get the wizard going on macOS. 

### Fix gpg
Create a symlink called gpg2 to point to the version of gpg installed on macOS (on mine it was 2.2) 
```
ln -s /usr/local/bin/gpg /usr/local/bin/gpg2
```

### Install and link shred
I had to install `gshred` via `brew` to ensure that the password files in`tmp` are destroyed. 
```
brew install coreutils
ln -s /usr/local/bin/gshred /usr/local/bin/shred
```
```
