### ISSUE TITLE
Emails being resent upon using `mw -Y`

### ISSUE THREAD

**Issue by aflyingpumpkin** [LukeSmithxyz/mutt-wizard#813]
When I send an email, it will send the first time. Then, upon running `mw -Y` it sends out the email a second time.

Output of `mw -Y` after sending an email:
```
C: 1/1  B: 7/7  F: +1/1 *0/0 #0/0  N: +2/2 *1/1 #0/0
Processed 4 total files in almost no time.
Added 2 new messages to the database. Detected 1 file rename.
```

**Comment by LukeSmithxyz** [comment]
Issue like this are usually due to some email servers using an outbox. When you sync mails back into an outbox, they resend. Just remove the outbox from being synced by mbsync and this issue will not occur.
