### ISSUE TITLE
GMail accounts without "less secure" or removing two-factor authentication.

### ISSUE THREAD

**Issue by vinay-singh-in** [LukeSmithxyz/mutt-wizard#814]
The man page says under GMail accounts:

> Google will require you to allow "less-secure" (third party) applications or remove two-factor authentication in order to  access their IMAP servers to download your mail. If you use Gmail, be sure to handle this before running mutt-wizard <https://support.google.com/accounts/answer/6010255>.

Are there any negative side effects of using App Password?

**Comment by LukeSmithxyz** [comment]
They are annoying.
