### ISSUE TITLE
Add Microsoft Exchange Support

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/mutt-wizard#815]
I'm not sure what this would take, but some schools only let you use clients that support Microsoft Exchange. IMAP and POP don't work.

**Comment by LukeSmithxyz** [comment]
It would take a Richard Stallman with superpowers to convince these people not to use Microsoft Exchange.

I actually don't know anything about Microsoft Exchange. If they have the OATH(?) or whatever Gmail makes you use now, it's possible, but it requires the user to set stuff up. If it's some annoying alternate protocol like what Protonmail does, forget about it and hope Super Stallman comes to save the day.
