### ISSUE TITLE
Inbox Not Updating After Receiving Very Large Attachment

### ISSUE THREAD

**Issue by herrmoltke** [LukeSmithxyz/mutt-wizard#818]
I received a number of very large attachments from someone about a week ago, and since then my NeoMutt inbox has not been updating. When I run `mw -Y`, the message `Warning: lost track of ... pulled message(s)` appears, where the number of messages only increases.

I have verified that the problem is not with my email provider (ProtonMail), as the missing emails appear in the web client. I permanently deleted the emails, as well, but the problem has persisted.

I should note I am also able to send messages from the same email address, and my other accounts set up using mutt-wizard are able to receive emails, too.

Please let me know if there is any additional information I can provide to help debug this issue.

**Comment by LukeSmithxyz** [comment]
Ask `isync`/`mbsync`'s documentation or people for issues like this.
