### ISSUE TITLE
` is not a valid account name.` on outlook

### ISSUE THREAD

**Issue by TheChymera** [LukeSmithxyz/mutt-wizard#822]
I know, there's 2 issues about this already, but it seems to be a catch-all error for lots of different actual problems, most of them being typos. Here's hoping mine is too:

```console
mw -a first-and-last.name@uniusingoutlook.edu \
    -u idtheygaveme@uniusingoutlook.edu \
    -i outlook.office365.com -I 993 \
    -s smtp.office365.com -S 587 \
    -x "hunter2" -n "My Name"
```

gives me:

```
Log-on not successful.
 is not a valid account name.
```

I see there's a lot of unis which gave up on having their own mail servers and now use outlook — anybody else having this issue?

Using `=mutt-wizard-3.2.1` on Gentoo. Plenty of other accounts worked, but none of the others was outlook.

**Comment by yumiris** [comment]
Try adding the `-a first-and-last.name@uniusingoutlook.edu` as the *last* argument, i.e.

```sh
mw -u idtheygaveme@uniusingoutlook.edu \
   -i outlook.office365.com -I 993 \
   -s smtp.office365.com -S 587 \
   -x "hunter2" -n "My Name" \
   -a first-and-last.name@uniusingoutlook.edu
```

**Comment by TheChymera** [comment]
@yumiris thank you for the suggestion, but that does not seem to change anything :(

**Comment by yumiris** [comment]
It's been inconsistent for me as well -- what ended up working for me is the
following command:

    mw -f -n "Full Name" -a ***@***.***'

Maybe it's the double quotes for the full name, or having "-f" in the command.
Or it could be both... or it could be completely random luck.

I used to use https://github.com/ork/mutt-office365.git which worked very well.

On 22/02/21 11:32AM, Horea Christian wrote:
> @yumiris thank you for the suggestion, but that does not seem to change anything :(
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/mutt-wizard/issues/822#issuecomment-1047175526
> You are receiving this because you were mentioned.
> 
> Message ID: 

-- 
Emilian Roman

**Comment by TheChymera** [comment]
@yumiris well, for me it's very consistent in not working — also with the new sequence you suggested.

`-f` will of course force-create the mailboxes, but it still won't load anything from the actual email account, those are just some default folders mw hard-codes [here](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/bin/mw#L220). :(

**Comment by lukas-mertens** [comment]
I have got the same problem with my custom-domain e-mail address. I will try to take a look at the source code. From a first look it seems to be a problem with the way parameters are processed as the string "is not a valid account" appears only in the "delete"-function. I will take a look at it.

**Comment by lukas-mertens** [comment]
So I did some debugging and while adding a few log-statements it suddenly started to work for me. What I found out:

`checkbasics && askinfo && getboxes && getprofiles && finalize || { delete ; exit 1 ;} ;` is executed, whenever you add an account. That means whenever one of those steps fails it tries to delete everything it has done. It does fail for example, when you enter a wrong password or when your network dies. This leads to getboxes not succeeding (it tries to query which mailboxes you have) and therefore falling back to "delete". As the account was not created yet, "delete" prints an empty account-which is probably a bit misleading and could be improved for better ux. 

From what I can see, @TheChymera it fails at this exact position in code:
```sh
info="$(curl --location-trusted -s -m 5 --user "$login:$(pass $fulladdr)" --url "${protocol:-imaps}://$imap:${iport:-993}")"
[ -z "$info" ] && echo "Log-on not successful." && return 1     
```
You could check if you have curl installed, if your network-conditions are good, if "pass" is working correctly (try playing around with entering a password manually into pass and retrieving it) and if the other arguments are calculated correctly. Then you could try to execute the curl manually while supplying the correct arguments to get log output from curl. Don't forget to remove the silent-flag `-s`

**Comment by TheChymera** [comment]
I'm pretty sure it is two-factor authentication that's blocking the account setup...
