### ISSUE TITLE
`Deleted Messages` inbox created after deleting message on iOS, How do I block spam?

### ISSUE THREAD

**Issue by JPcode05** [LukeSmithxyz/mutt-wizard#823]
Since there was no automatic trash directory created when I set up emailwiz, I created it myself on iOS, then synced it. It wasn't recognized as a trash directory (and none of the messages in there actually got deleted). When I deleted a spam message, it got send to what I saw as a duplicate trash folder. When I checked back on my computer, the inbox was called `Deleted Messages`. How do tell my other client where the trash is?

Also, when I got the spam message, I couldn't figure out how to block the domain, so I watched [Luke's Video about his script](https://yewtu.be/watch?v=8GELGHKsa-k) which sent a message to the email server to block the domain or just the user.

Luke, can you please upload the source script, maybe to the source code for mutt-wizard so I can easily use it?

**Comment by LukeSmithxyz** [comment]
Check `man neomuttrc`. You'll want to set your trash variable as whatever your server uses it as (Deleted Messages), unless you can tell Apple to use a different trash dir on their side (unlikely since Apple is no fan of customization).

I'm not 100% happy with the script, but I'll generalize it in the future and make it more acceptable for common use.

**Comment by JPcode05** [comment]
> Check `man neomuttrc`. You'll want to set your trash variable as whatever your server uses it as (Deleted Messages), unless you can tell Apple to use a different trash dir on their side (unlikely since Apple is no fan of customization).
> 
> I'm not 100% happy with the script, but I'll generalize it in the future and make it more acceptable for common use.

Actually, when I removed and re-added the account in Apple Mail, it properly recognized the `Trash` folder as the Trash folder, leaving `Deleted Messages` as a regular folder.

Now how do I get rid of it in neomutt? (When I sync it re-adds the folder)

**Comment by LukeSmithxyz** [comment]
Oh I see.

In your account config in
***@***.***` you can remove it from
the boxes used and it won't show up in mutt.

You can also delete the directory in
***@***.***/`.

Now if it still tries to sync a ghost directory with Apple, go to the
file in `~/.config/mbsync/` and there's a like `Patterns` to which you
can add your unwanted mailbox, e.g.:


Patterns * !"[Gmail]/All Mail" !"Deleted Messages"
