### ISSUE TITLE
mailsync program will notify me that I have 3x new emails for every one new email on case-insensitive filesystems

### ISSUE THREAD

**Issue by scorgn** [LukeSmithxyz/mutt-wizard#828]
Hello,

I love what you've done with mutt-wizard, it makes getting into mutt a breeze.

I was playing around with the mailsync command and I noticed that it was showing I had 3 new emails for every 1 new email I got. I looked into it and found that it was because my filesystem is case-insensitive (as they are by default on Mac OS).

The mailsync program will find new email files using the [following snippet](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/bin/mailsync#L56-L63)

```
    new=$(find\
	"$HOME/.local/share/mail/$acc/INBOX/new/"\
	"$HOME/.local/share/mail/$acc/Inbox/new/"\
	"$HOME/.local/share/mail/$acc/inbox/new/"\
	"$HOME/.local/share/mail/$acc/INBOX/cur/"\
	"$HOME/.local/share/mail/$acc/Inbox/cur/"\
	"$HOME/.local/share/mail/$acc/inbox/cur/"\
	-type f -newer "${XDG_CONFIG_HOME:-$HOME/.config}/mutt/.mailsynclastrun" 2> /dev/null)
```

It looks like it's looking for the inbox directory by 3 different casings, so that it will work regardless of whether your inbox folder is cased as `inbox`, `Inbox`, or `INBOX`. The issue is that with case-insensitive filesystems, all three of those directories exist. So, when you use `find` with the three directories, it will find 3x matches for every match.

A solution I can think of would be to treat two separate files that have the same name but with different casing as the same file. We could do this with an associative array, as shown below.

```
declare -A unique_new
for file in $new; do
    lowercase_filename="$(echo "$file" | tr '[A-Z]' '[a-z]')"
    unique_new[$lowercase_filename]="$file"
done
```

It would loop through the new files, adding them to an associative array with the key as the lowercase version of the path and the value as the unaltered full filename. Each time it adds a new file to the array, any pre-existing duplicate file name with different casing would be overwritten. In the end you would have an array of paths that only contain case-insensitive unique filenames. You could use `$unique_new` as a normal array in the same exact manner that `$new` was used.

The only downside to this would be that if someone with a non case-sensitive filesystem actually has two new emails that have the same filename but with different casing, it would only see it as one. I don't believe this is a likely scenario though, but I could be wrong.

**Edit:** My solution actually wouldn't work for older versions of bash since associative arrays were introduced in bash 4, so maybe something similar without using associative arrays would be better.

**Comment by nakrule** [comment]
I confirm that I have the same issue on MacOS.
