### ISSUE TITLE
How to make connections over Tor

### ISSUE THREAD

**Issue by cantcuckthis** [LukeSmithxyz/mutt-wizard#829]
I've made the following changes in `.config/mutt/accounts/<account>.muttrc`
```bash
set sendmail = "torsocks -i msmtp -a <account>"
```
```bash
macro index o "<shell-escape>torsocks -i  mw -y <account><enter>" "run mbsync to sync <account>"
```

Is this all? Am I missing anything here? How about when the account is first added with `mw -a <account>`? Would it be sufficient then to just use `torsocks -i mw -a <account>`?

Thanks

**Comment by LukeSmithxyz** [comment]
I honestly have no clue as I'm not that familiar with Tor or torsocks.

You might want to manually edit the `mailsync` script which is run by `mw -y` and use `torsocks` around the `mbsync` command which is the actual sync.
