### ISSUE TITLE
PGP encrypted password

### ISSUE THREAD

**Issue by akegalj** [LukeSmithxyz/mutt-wizard#83]
I have just skimmed over the scripts - but doesn't this https://github.com/LukeSmithxyz/mutt-wizard/blob/b3122a2c2e3f4fe1f4d24b9d95b9e32319ba481d/mutt-wizard.sh#L206  means that we will have password in a plaintext (gpg decrypted) saved to the filesystem? (both in .muttrc and .msmtprc) 

I must be missing something (didn't try to install it)

**Comment by LukeSmithxyz** [comment]
No, no password is not saved in plaintext. The password for each account is stored in an encrypted file in `credentials/` which is decrypted with your key pair by offlineimap or msmtp. The line you quote doesn't have anything to do with the password anyway.
