### ISSUE TITLE
XDG base directory support for `.mbsyncrc`

### ISSUE THREAD

**Issue by yuandi42** [LukeSmithxyz/mutt-wizard#839]
Just getting started to use this tool, and I noticed that `.mbsyncrc` was created in my home directory. According to https://github.com/LukeSmithxyz/mutt-wizard/issues/810 , the generated mbsync configuration file should lie in `~/.config/mbsync`. So I simply `mkdir ~/.config/mbsync; mv ~/.mbsyncrc ~/.config/mbsync/config`, then run `mw -Y`. However, error occured:
```bash
awk: fatal: cannot open file `/home/blablabla/.mbsyncrc' for reading: No such file or directory
```
Quite confusing and I had to `ln -s ~/.config/mbsync/config ~/.mbsyncrc`. Since I'm using an arch-based distro, mbsync on my machine is modern and should have XDG base directory support out of box instead of shitting in my home directory. How to solve the problem?

**Comment by Kr1ss-XD** [comment]
Hi,

Even on Arch, the default location for `mbsync`'s config file is `~/.mbsyncrc` (as per the manual). `mw` makes use of the `-c <RC_PATH>` option though, and uses the `MBSYNCRC` environment variable for this, if defined.

Hence, it should suffice to set

```sh
export MBSYNCRC=${XDG_CONFIG_HOME:-~/.config}/mbsync/config
```

in your shell profile. You can then remove the symlink.

**Comment by LukeSmithxyz** [comment]
I may've misspoken on the other issue. I may've been thinking of the msmtprc which can go in either location. isync/mbsync doesn't look in `~/.config/` at all unless you do what Kr1ss mentioned using the `$MBSYNCRC` variable (which I do on my own machine to minimize home mess).
