### ISSUE TITLE
How to change pass to pash

### ISSUE THREAD

**Issue by Visone-Selektah** [LukeSmithxyz/mutt-wizard#840]
Hi!
Is it posible to use pash instead of pass?
I have pash configure and initialize.
Thanks!

**Comment by Visone-Selektah** [comment]
Hi!
First, thanks 4 your answer!!
That was the why of that question,the options of pash are a little different than those on pass.
Anyway, I'll try with simlinks or alias....
Thanks!!

**Comment by NikosAlexandris** [comment]
> Hi! First, thanks 4 your answer!! That was the why of that question,the options of pash are a little different than those on pass. Anyway, I'll try with simlinks or alias.... Thanks!!

@Visone-Selektah Did you succeed in using pash?
