### ISSUE TITLE
openfile: command not found.

### ISSUE THREAD

**Issue by delightfuldude** [LukeSmithxyz/mutt-wizard#842]
neomutt isn't able to open files since the latest update of mutt-wizard (orignal in german):
`sh: Zeile 1: openfile: Kommando nicht gefunden.
Bitte eine Taste drücken...
`
and translated:
`sh: line 1: openfile: command not found.
Please press a button...`

**Comment by Kr1ss-XD** [comment]
Hi, you might have to adapt your local `mailcap` file (probably `~/.config/mutt/mailcap`).  The location of the `openfile` script has been changed from `/usr/local/bin/` to `/usr/local/lib/' (respectively from `/usr/bin/` to `/usr/lib/` if you've installed from the AUR).

The correct path must be reflected in the `mailcap` file - there should be several references to `openfile`, three by default.  Just change `bin` to `lib` in all of them.

**Comment by delightfuldude** [comment]
@Kr1ss-XD thank you! This works! You made my day! 😀👍
