### ISSUE TITLE
6000 messages - an issue?

### ISSUE THREAD

**Issue by moziness** [LukeSmithxyz/mutt-wizard#847]
I ran the mutt wizard for the first time on my inbox, which has 6000 messages.  the refresh rate of the terminal inbox, is slow, it attempts to load the messages, and says "fetching...." and the scrolling "j" or "k" up and down the list is sluggish.

Any reason why this might be happening?  Is it trying to download everything for the first time?

**Comment by moziness** [comment]
Oh, and get this.... even when exiting from the help page going back to the inbox, it has to slowly reload each line of the inbox.  It takes about 30-45 secs just to do that, coming back out of the help "?" page.  Is this a setting I need to adjust?

**Comment by LukeSmithxyz** [comment]
I assume you are not actually using the offline mail thing with mutt-wizard?

There is a mutt setting to change how often you check a remote mailbox, which is probably the issue if your connection to your mail server is slow.

**Comment by moziness** [comment]
Hi Luke, much thanks for innovating in this space.  Really, it's awesome what you've contributed to the community.

I just installed it vanilla, and added one account.   However, I did the MW install on a system that already had neomutt installed, and a few settings in muttrc file, with one account.  Could that be it?

I would assume an East Coast US to a Germany server shouldn't be that slow though.  When I uninstall MW, the regular Neomutt inbox loads super fast.

Thanks again!

**Comment by LukeSmithxyz** [comment]
It's nearly certainly due to an interferring setting in your muttrc. I would back it up if you want and use a blank one.

**Comment by moziness** [comment]
I cleared it.  I have run install two mailboxes and am doing mw -Y to sync right now.  Will let you know how it goes!  

It's a bit of an adventure as I am not often doing command line work...

**Comment by moziness** [comment]
Seems to be working well, after the hour long sync (lots of messages).
