### ISSUE TITLE
Less secure apps disabled - update of gmail account setup or added instructions to README

### ISSUE THREAD

**Issue by gerazov** [LukeSmithxyz/mutt-wizard#849]
Since yesterday Google doesn't allow for less secure app access any more. This means that the current gmail setup in mutt-wizard doesn't work. No messages can be received nor sent from Gmail.

The link from the sending error suggests the following actions (I've reduced it to the relevant suggestions :slightly_smiling_face: ) :

> Step 2: Try these troubleshooting steps
>  -   Use an App Password: If you use 2-Step Verification, try signing in with an [App Password](https://support.google.com/accounts/answer/185833). Important: If you sign in with OAuth, use your regular Google password.
>  -   Allow less secure apps: If you don't use 2-Step Verification, you might need to[ allow less secure apps to access your account](https://support.google.com/accounts/answer/6010255).

There was #594 last year, with two proposed solutions using `curl` and `oauth2token`.

I tried to make it work using [oauth2.py](https://github.com/google/gmail-oauth2-tools/blob/master/python/oauth2.py) as suggested in the [neomutt](https://neomutt.org/guide/optionalfeatures.html#6-%C2%A0oauthbearer-support) optional features page. I converted the code to [Python3](https://github.com/gerazov/gmail-oauth2-tools) and made it work but muttrc settings seem do not apply as `mutt-wizard` is using isync and msmtp with their own config files: `~/.mbsyncrc` and `.config/msmtp/config`, which both point to `pass`. 

Finally I resorted to creating an application pass and updated the password in pass :sweat_smile: 

It would be helpful if the mutt-wizard Readme is updated with info on how to get gmail to work, at least with application passwords if not with oauth.

**Comment by ask1234560** [comment]
Hi, for all looking for using gmail without less secure apps. 

App password has to be used. Follow below steps -

- [Generate app password](https://www.youtube.com/watch?v=uVDq4VOBMNM)
- replace current password in pass with the app password generated, [refer this for help](https://unix.stackexchange.com/a/239548/402486)

For replacing app password with current password in pass -

- pass edit example@gmail.com
- enter new password and save

**Comment by ask1234560** [comment]
Also created a pull request with this.
