### ISSUE TITLE
gmx.com email appears not to be supported even with follow-up input requests

### ISSUE THREAD

**Issue by savaged** [LukeSmithxyz/mutt-wizard#851]
Using mw for the first time after following the readme instructions. I had not expected gmx.com emails to be supported for an automatic setup, however, I had expected to be offered CLI request for account information. Thanks for your work on this.

**Comment by LukeSmithxyz** [comment]
I had been using a GMX account without issue a bit ago. The wizard will try port 587 by default---perhaps GMX prefers 465 now, but their documentation says they offer both.
