### ISSUE TITLE
Certificate owner not matching hostname

### ISSUE THREAD

**Issue by sudoLife** [LukeSmithxyz/mutt-wizard#853]
I have a very weird company mail, in which the SSL certificate does not match the hostname.

Therefore, adding the a company account fails, since curl doesn't like that:
```
curl: (60) SSL: no alternative certificate subject name matches target host name 'geozondas.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
I tweaked mutt-wizard to get the above message, otherwise it would just say "Log-on not successful"

Passing an `--insecure` option to curl fixes the issue and the account is added successfully.

However, next mbsync complains about about the same thing. Setting `SSLType` to `None` and using a port for non-SSL connection solves this problem.

Finally, on sending an email, msmtp fails with `TLS certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected. `
Changing `auth login`, `tls off` and smtp server's port to that without an ssl connection in the msmtp config solves this issue.

Conventional clients (gmail tested so far) seem to just roll with the certificate issue, though warning that security is not guaranteed.
Should we fix this?

**Comment by LukeSmithxyz** [comment]
You might as well just post your work username and email here if you're going to turn off encrypted connections. There is nothing to fix, mutt-wizard is working perfectly.

Either your work's email is improperly and dangerously configured or you are putting the wrong domain/subdomain for mail.

Either way, you should immediately change your password (and your password on sites where you reuse that same password) since it's generally considered very bad to broadcast your password in an unencrypted channel over the internet.

**Comment by sudoLife** [comment]
@LukeSmithxyz it does work over SSL, the problem is that the certificate name matches the domain of a hosting provider, not ours. The company's website example.com is hosted on myhosting.com, the certificate that's configured somehow has myhosting.com instead of example.com. 

mutt-wizard refuses to configure using SSL when that is the case, that's why I turned it off to test that insecure connection works in principle. I would like to configure my email to use SSL here, but mutt won't let me do so. 

I'm not sure what the right solution is here.

**Comment by LukeSmithxyz** [comment]
The right solution is to immediately switch hosts to one that offers properly-configured SSL, or better yet, one where you actually have server access and can fix this yourself.

**It does not "work" over SSL if there is a domain mismatch.** Your client might even be accepting some encrypted channel to a server, but there is nothing preventing another mismatched domain name from attacking you by pretending to be the destination server once you allow connections to this improperly configured server.

I don't know what else to tell you.
