### ISSUE TITLE
Yahoo mail config

### ISSUE THREAD

**Issue by rechade** [LukeSmithxyz/mutt-wizard#857]
Thanks first of all for all your YT stuff and sharing these files!  

I think in  `.config/mutt/accounts/asdf@ymail.com.muttrc`
it should have
`set spoolfile = +Inbox`
`mailboxes "=Inbox" `...
I think one of the generated lines is in uppercase and causing problems with the real folder name.

**Comment by LukeSmithxyz** [comment]
Yeah I know Yahoo does things a little weird and might need manual intervention.

Out of curiousity, can you show the contents of `~/.local/share/mail/asdf@tmail.com/` to see the directories it creates?

**Comment by rechade** [comment]
exa --tree -D --level=3
.
├── Archive
│  ├── cur
│  ├── new
│  └── tmp
├── Bulk
│  ├── cur
│  ├── new
│  └── tmp
├── Draft
│  ├── cur
│  ├── new
│  └── tmp
├── Drafts
│  ├── cur
│  ├── new
│  └── tmp
├── gigs etc
│  ├── cur
│  ├── new
│  └── tmp
├── Inbox
│  ├── amazon
│  │  ├── cur
│  │  ├── new
│  │  └── tmp
│  ├── cur
│  ├── mixcloud
│  │  ├── cur
│  │  ├── new
│  │  └── tmp
│  ├── new
│  ├── tmp
│  └── twitter
│     ├── cur
│     ├── new
│     └── tmp
├── Sent
│  ├── cur
│  ├── new
│  └── tmp
├── Trash
│  ├── cur
│  ├── new
│  └── tmp
└── u3a
   ├── cur
   ├── new
   └── tmp

**Comment by rechade** [comment]
Cool thanks. (Looks like I moved the twitter folder though):
exa --tree -D --level=4
.
├── Archive
│  ├── cur
│  ├── new
│  └── tmp
├── Bulk
│  ├── cur
│  ├── new
│  └── tmp
├── Draft
│  ├── cur
│  ├── new
│  └── tmp
├── Drafts
│  ├── cur
│  ├── new
│  └── tmp
├── gigs etc
│  ├── cur
│  ├── new
│  └── tmp
├── Inbox
│  ├── amazon
│  │  ├── cur
│  │  ├── new
│  │  └── tmp
│  ├── cur
│  ├── mixcloud
│  │  ├── cur
│  │  ├── new
│  │  └── tmp
│  ├── new
│  ├── tmp
│  └── twitter
│     ├── cur
│     ├── new
│     └── tmp
├── Sent
│  ├── cur
│  ├── new
│  └── tmp
├── Trash
│  ├── cur
│  ├── new
│  └── tmp
└── u3a
   ├── cur
   ├── new
   └── tmp
