### ISSUE TITLE
msmtp log permission denied

### ISSUE THREAD

**Issue by lokesh1197** [LukeSmithxyz/mutt-wizard#859]
Here is a part of my /etc/apparmor.d/usr.bin.msmtp, I use ubuntu 20.04 btw
``` config
  /usr/bin/msmtp          mr,
  /etc/aliases            r,
  /etc/msmtprc            r,
  /etc/netrc              r,
  owner @{HOME}/.msmtp*   r,
  owner @{HOME}/.netrc    r,
  owner @{HOME}/.tls-crls r,

  owner @{HOME}/.msmtp*.log wk,
  /var/log/msmtp            wk,

  owner @{HOME}/**/.msmtprc        r,
  owner @{HOME}/**/dot_msmtprc     r,
  owner @{HOME}/.config/msmtp/*    r,
  owner @{HOME}/.cache/msmtp/*     r,
  owner @{HOME}/.cache/msmtp/*.log wk,
```
As per the [man page](https://manpages.ubuntu.com/manpages/kinetic/en/man5/apparmor.d.5.html), w -> write access, r -> read access. So for ubuntu users the log can't be written at `~/.config/msmtp/msmtp.log.

So ubuntu users will have to change the location of the log file manually or through mutt-wizard. Let me know if I should add an option for ubuntu users or just mention it in the readme

**Comment by LukeSmithxyz** [comment]
Not really interested in playing an armsrace with that silly program. This is an Apparmor problem, not a mutt-wizard problem.

Granted, now that I look at it, the log file *should* be in `~/.cache/`, not `~/.config/` for cleanliness's sake, so I'll move that, but judging by the file you posted, Apparmor will still prevent it.

**Comment by lokesh1197** [comment]
It will work at `~/.cache/msmtp/*.log`. In my build of mutt-wizard I have msmtp logs at `~/.cache/msmtp/abc@example.com.log` and it works fine.
