### ISSUE TITLE
[offlineimap] decoding error due to imap 4 encoding protocol

### ISSUE THREAD

**Issue by Dauliac** [LukeSmithxyz/mutt-wizard#86]
The imap protocol use `imap-4-utf-7` encoding but offline imap don't decode this to `utf-8`.
So folders with special charters look like this: ` '[Gmail].Messages envoy&AOk-s'`

You need to add script like this: https://gist.github.com/declanqian/2e5169660b5a888639ea
in .offlineimaprc pythonfile.

Have fun Mr Smith

**Comment by ramonvoges** [comment]
+1

I would love to use (neo)mutt more frequently, but I always struggled with the UTF7/UTF8 issue. This wizard actually reduced the pain to setup mutt enormously. So I think adding the ability to convert the encoding would be much appreciated around the world.

Thanks for all the time and effort!

**Comment by LukeSmithxyz** [comment]
Closing the issue. mutt-wizard now uses isync, which avoids this particular problem with offlineimap.
