### ISSUE TITLE
log-on not successful

### ISSUE THREAD

**Issue by ZulluBalti** [LukeSmithxyz/mutt-wizard#862]
I have installed mutt-wizard using yay. And I'm trying to add a Gmail account using mutt wizard but I'm getting this error

``` log-on not successful```

I've 2 Factor Auth disabled but still getting the same error.

This is is my system details.

Linux zorch 5.18.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 09 Jun 2022 16:14:10 +0000 x86_64 GNU/Linux

**Comment by python-coding-404** [comment]
THE DAMN GMAIL AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHJSJGXYHSHIWIUJOOJDXOD;IAJWO;HDCPOID;JDCJFE

**Comment by python-coding-404** [comment]
DAMNNNNNNNNNNNNNNNN APPPPPPPPPPPPP PASSSWORDS ONLY WORRK ON DAMN 2 FACTOR AUTH

**Comment by python-coding-404** [comment]
NOW I HAVE TO USE DIFFRENT EMAIL AHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by LukeSmithxyz** [comment]
See the README. Gmail now requires you to set up an application password. You do not use your normal password and 2FA.
