### ISSUE TITLE
Protonmail support removed manual configuration doesn't work

### ISSUE THREAD

**Issue by Jocomol** [LukeSmithxyz/mutt-wizard#865]
Sadly the official support for protonmail was removed, I know protonmail bridge sucks but protonmail is still one of the best mail providers out there so in my opinion it should be readded as the manual configuration doesn't work:

`mw -a maill@protonmail.com -i 127.0.0.1 -I 1143 -s 127.0.0.1 -S 1025 -x "$password"`

Doesn't work, IP, port and password are correct. I've looked into the removed code but couldn't find anything else that has to be done or added.

**Comment by Jocomol** [comment]
Here is also the log of protonmail-bridge
`WARN[0010] Failed to add test credentials to keychain    error="timed out after 10s" helper="*keychain.SecretServiceDBusHelper"
WARN[0035] Failed to add test credentials to keychain    error="Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached" helper="*secretservice.Secretservice"
[2012:2012:0714/131626.448089:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 5.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[5480:5480:0714/132221.658607:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data for tabId: 5.  Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
ERRO[Jul 14 13:26:08.187] cannot read command: read tcp 127.0.0.1:1143->127.0.0.1:40518: read: connection reset by peer  protocol=IMAP
ERRO[Jul 14 13:29:37.583] cannot read command: read tcp 127.0.0.1:1143->127.0.0.1:54868: read: connection reset by peer  protocol=IMAP`

**Comment by LukeSmithxyz** [comment]
Check the commit where it was removed. You have to do this extra thing where you get a fingerprint for your Protonmail Bridge or something. I forget the specific, but the script would do this automatically.

Check https://github.com/LukeSmithxyz/mutt-wizard/commit/ef5bac2b55e3bd665d103eff4ea435ecaa9db22c for how the `tls_fingerprint` variable is set.
