### ISSUE TITLE
Sync actions to gmail

### ISSUE THREAD

**Issue by gpxlnx** [LukeSmithxyz/mutt-wizard#869]
Hi,

I'm a new user of mutt-wizard and initially I would like to thank you for your work.

I would like to know if there is a possibility to synchronize the actions done in neomutt with the gmail account?

Example read emails in neomutt and they are marked in gmail account as read.

Thanks

**Comment by ferdinandyb** [comment]
I read some tricks [here](https://usher.dev/posts/my-email-setup/) about doing this, I'm not sure it applies.
