### ISSUE TITLE
LARBS: Mod+F8, <$>, and cronjob methods don't work for syncing mail; however, <mw -Y> works

### ISSUE THREAD

**Issue by Michaelpv** [LukeSmithxyz/mutt-wizard#871]
Hello Folks,

Novice user here, thank you in advance for your patience. Issue is as described in the title. I am using mw with my Gmail account. Google recently took out the feature of "allow access from less secure sites" and the only way around this was to enable two-factor authentication and set up a Google "App password" to be used by neomutt. I also set up a separate app password for regular mutt which I have installed as well and was experimenting with (not sure if this matters to the issue). In order to get both of these programs to work, I had to enter in the app password when adding my gmail account with the mw command and after "set smtp_pass =" and "set imap_pass =" in the .muttrc file for mutt.

Thank you,

-Michael

**Comment by thecodsman** [comment]
I got my cronjobs to work by running `pacman -S cronie` then `systemctl enable cronie --now`
