### ISSUE TITLE
Error creating account

### ISSUE THREAD

**Issue by OctaviusTheCordial** [LukeSmithxyz/mutt-wizard#874]
Hello,

Has anyone encountered this during the account setup? :

"
user@computername:~$ mw -a email@domain.com
...
gpg: error retrieving 'email@domain.com' via WKD: Connection timed out
gpg: email@domain.com: skipped: Connection timed out
gpg: [stdin]: encryption failed: Connection timed out
"

I know my IMAP and SMTP server information is correct, because I'm using the same information on my phone and personal computer email clients and these work. I've also followed Luke's YouTube video he made of setting up mutt/neomutt in the terminal manually through mutt's config file and this has worked as well. But through the wizard its not working for some reason. 

Still learning the Linux terminology - what does "gpg", "WKD", and "[stdin]" mean? 

Respectfully,
Owen

**Comment by aldrinjenson** [comment]
Related to #855 and #168

**Comment by aldrinjenson** [comment]
This helped me fix the issue: https://www.maketecheasier.com/generate-gpg-keys-linux/
