### ISSUE TITLE
Getting "Log-on not successful"

### ISSUE THREAD

**Issue by Archie-2021** [LukeSmithxyz/mutt-wizard#877]
I can't add my email. I try to use `mw add` after install like you did and it just show the help info. If I use something like `mw -a <myemail>` it just ask for password for "pass" program and then says "Log-on not successful" . I am not sure if there is something wrong with installation or i just don't know how to initialize it. I have a gpg key that I used to initialize pass. should I only add and email that is used for gpg? 

i am new to linux and I am very confused, couldn't find any help on internet. Please add more info on Usage section of the readme.

**Comment by Alvinferdi990** [comment]
Not working for me for a rambler.ru email.

**Comment by t-391** [comment]
try to pass the "-f" flag to skip a log on check, then get into neomutt and use the "o" command and see if that works.

Example: `mw -a example@example.net -x "password" -f`

The password is the password to log into your email, not your gpg password.

A GPG prompt will be separate, if it's needed.

**Comment by Archie-2021** [comment]
> try to pass the "-f" flag to skip a log on check, then get into neomutt and use the "o" command and see if that works.
> 
> Example: `mw -a example@example.net -x "password" -f`
> 
> The password is the password to log into your email, not your gpg password.
> 
> A GPG prompt will be separate, if it's needed.

Thanks, that sort of works, I can add the account, but can't do stuff, It just fails. How I can check configurations? like imap and stuff like that. don't know what is the default for them.

**Comment by parin23** [comment]
@Archie-2021 You can Look for file `.mbsyncrc` in home folder. It might have configurations you are looking for.

**Comment by Archie-2021** [comment]
> @Archie-2021 You can Look for file `.mbsyncrc` in home folder. It might have configurations you are looking for.

Mutt-wizard is supposed to override these configuration files. I changed the email service it was trying to use and it works fine now. There are some options to input Imap to it but I couldn't figured it out how to set it with GMX. it is weird because I can manually set up that service to use mutt and mbsync.
