### ISSUE TITLE
Neomutt doesn't work properly without sudo (Artix + Runit)

### ISSUE THREAD

**Issue by emrakyz** [LukeSmithxyz/mutt-wizard#878]
Super+e gives a blank page but if I `sudo neomutt` then I can see my e-mails.

I feel the need for entering sudo for lots of things which was not the case with Arch + Systemd. Is there a way to change this? I removed the need for entering the passwd but most programs doesn't work without typing sudo.

**Comment by LukeSmithxyz** [comment]
You ran mw as sudo and installed the emails for the root user instead of your own. That's the improper usage obviously. This program should be run as a normal user.
