### ISSUE TITLE
Problem with sending mail.

### ISSUE THREAD

**Issue by remsforian** [LukeSmithxyz/mutt-wizard#881]
I recently used mutt wizard to set up neomutt, as I would quite prefer a cli to thunderbird (my current client). I was able to receve emails, but I get the error "Error sending message, child exited 68 (Host unknown.)". Not sure why this is happening, though it is a gmail server (though not the @gmaillcom domain). I know gmail can occasionally be weird with imap, though I have it set up through my account and put in the correct domains into mw. Thanks for any help!

**Comment by inktrap** [comment]
What is the generated `smtp_url`?

**Comment by remsforian** [comment]
> What is the generated `smtp_url`? In [this random config someone posted as a gist](https://gist.github.com/VladimirPal/9068b922c70a6b5e604c8d2eb099ddb7) it looks like this:
> 
> ```
> set smtp_url="smtps://mail.vpal@gmail.com@smtp.gmail.com:465/"
> ```
> 
> Any useful verbose/debugging output?
> 
> Also I guess you have to enable "less secure apps" in gmail aka disabling two factor authentication?

I have already enabled "less secure apps". Mutt-Wizard created a file called .msmtprc which looks like this (with my personal info redacted).
account [email adress]
host smpt.gmail.com
port 456
from [email adress]
user [email adress]
passwordeval "pass [email adress]"
auth on
tls on
tls_trust_file  /etc/ssl/certs/ca-certificates.crt
logfile /home/solmasters/.cache/msmtp/msmtp.log
tls_starttls off

**Comment by inktrap** [comment]
You typically have defaults in `.msmtprc` at the top.

For me they are:

```
defaults
auth	on
tls	on
tls_trust_file	/etc/ssl/certs/ca-certificates.crt
logfile	~/.config/msmtp/msmtp.log
```

And then I have

```
port 587
```

not `456`

Could you change that and then run msmtp directly?

Perhaps with debug/verbose?
Whats in ` logfile /home/solmasters/.cache/msmtp/msmtp.log`?
