### ISSUE TITLE
Posteo recommends using SSL/TLS (465) instead of STARTTLS (587)

### ISSUE THREAD

**Issue by tunnckoCore** [LukeSmithxyz/mutt-wizard#898]
Hey there Luke. Just watching your old videos, and thinking to start using more text-based programs.

I've seen that the domains list uses 587 for SMTP, while Posteo recommends using 465. Or am I not getting something right?

```
Outgoing mail server (SMTP):
with SSL/TLS encryption using port 465, or
with STARTTLS using port 587
```

https://posteo.de/en/help/how-do-i-set-up-posteo-in-an-email-client-pop3-imap-and-smtp

**Comment by LukeSmithxyz** [comment]
I'll change it. A lot of providers have moved from 587 to 465 just in the past years, so it's probably a hold-over from before. Most will work with both.
