### ISSUE TITLE
question: option choose imap or pop at installation?

### ISSUE THREAD

**Issue by jindam-vani** [LukeSmithxyz/mutt-wizard#904]
@LukeSmithxyz 
* i prefer pop to imap
* do we have choose to specify pop or imap 
dependencies download and installation?
* i dont want to add extra packages for pop
* i dont want to install dependencies related 
to imap

please enable **discussions** on repo

**Comment by LukeSmithxyz** [comment]
Read the manual. `-P` to add a pop account. `mpop` must be installed.

**Comment by Shane-XB-Qian** [comment]
actually it is `-p` (lower case 'p') which was changed from `-P` (upper case).
