### ISSUE TITLE
Cannot `go to trash`

### ISSUE THREAD

**Issue by CarlosLoboxyz** [LukeSmithxyz/mutt-wizard#926]
when i press the `gt` shortcut it does not send me to my trash folder, instead it complain about `Trash` not being a valid mailbox. I setup my gmail account using app-password, here is a look:

![Screenshot_20230326_184536-2](https://user-images.githubusercontent.com/86011416/227809850-201534b5-e469-4d1a-8c47-41f5486626fe.png)

**Comment by matthew-hennefarth** [comment]
I believe the Gmail trash is actually in [Gmail]/Trash. If you press 'c' followed by '?' to change directories like normal, you can see the name of all of the directories.

I ended up having to remap all of the `g` shortcuts to the correct location in my `~/.config/mutt/muttrc`.

```
macro index,pager gd "<change-folder>=[Gmail]/Drafts<enter>" "go to drafts"
macro index,pager Md ";<save-message>=[Gmail]/Drafts<enter>" "move mail to drafts"
macro index,pager Cd ";<copy-message>=[Gmail]/Drafts<enter>" "copy mail to drafts"
macro index,pager gj "<change-folder>=[Gmail]/Spam<enter>" "go to junk"
macro index,pager Mj ";<save-message>=[Gmail]/Spam<enter>" "move mail to junk"
macro index,pager Cj ";<copy-message>=[Gmail]/Spam<enter>" "copy mail to junk"
macro index,pager gt "<change-folder>=[Gmail]/Trash<enter>" "go to trash"
macro index,pager Mt ";<save-message>=[Gmail]/Trash<enter>" "move mail to trash"
macro index,pager Ct ";<copy-message>=[Gmail]/Trash<enter>" "copy mail to trash"
macro index,pager gs "<change-folder>=[Gmail]/Sent Mail<enter>" "go to sent"
macro index,pager Ms ";<save-message>=[Gmail]/Sent Mail<enter>" "move mail to sent"
macro index,pager Cs ";<copy-message>=[Gmail]/Sent Mail<enter>" "copy mail to sent"
```
