### ISSUE TITLE
XDG-urlview

### ISSUE THREAD

**Issue by matthew-hennefarth** [LukeSmithxyz/mutt-wizard#928]
For those who are interested in cleaning up their home directories:

urlview by default creates a config in ~/.urlview. 

[xdg-urlview](https://github.com/ozangulle/xdg-urlview) is a fork of the apparently unmaintained urlview which follows XDG standards. The config file lives in
- $XDG_CONFIG_HOME/urlview/urlview
- $HOME/.config/urlview/urlview
- $HOME/.urlview.

**Comment by LukeSmithxyz** [comment]
Okay thanks for the note.

The urlview capability in the system is *really* vestigial anyway and I might just remove it.

My terminal can grab urls automatically and feel like most others do so.
