### ISSUE TITLE
No config written

### ISSUE THREAD

**Issue by bashtux** [LukeSmithxyz/mutt-wizard#93]
I ran the config wizard, but no config was written.
The files were generated but .msmtprc and .offlinerc are completely empty and the personal files in .config/mutt/xyz are just filled with the names of the variables.

Might it be user error?? If yes, what could I have done wrong?

**Comment by LukeSmithxyz** [comment]
Did you clone the entire repository to `~/.config/mutt/` or did you just download the one script?

**Comment by bashtux** [comment]
I downloaded the whole thing, does the folder name matter which I give it?

**Comment by LukeSmithxyz** [comment]
Yes, it must be `~/.config/mutt/` as in the documentation. That's the issue.

**Comment by bashtux** [comment]
Ah no I put it there but had the name of the folder containing the script named differently.
But changed it now to the original and it still didn't work (all happening in .config/mutt/ )

**Comment by LukeSmithxyz** [comment]
Show me `ls ~/.config/mutt/autoconf/`.

Do you have GNU sed or are you using BSD or something?

**Comment by bashtux** [comment]
Ohno... *face->table* I misunderstood the path and thought it was .config/mutt/mutt-wizard-master/autoconfig

When I now moved the files into .config/mutt/ it is working well
Thank you for your immediate 

Regards Sam
