### ISSUE TITLE
Changing mail storage location in email@domain.com.muttrc  is not overriding default mail storage directory

### ISSUE THREAD

**Issue by longestmt** [LukeSmithxyz/mutt-wizard#938]
I am trying to use a mounted drive for mail storage so I modified the default `set folder` directory in the `~.config/mutt/accounts/email@domain.com.muttrc` file. When I run mbsync -a it still appears to be storing in the default `.local/share/mail/email@domain.com` directory is there another script that needs to be altered?

I did not receive a prompt during setup requesting where I would like my mail to be stored locally.

I am using a protonmail account.

**Comment by LukeSmithxyz** [comment]
Edit ~/.config/mbsync/config accordingly.

**Comment by longestmt** [comment]
> Edit ~/.config/mbsync/config accordingly.

Do I have to create this file? It doesn't exist even after running `mbsync -a`

**Comment by LukeSmithxyz** [comment]
On your machine, it might be ~/.mbsyncrc.
