### ISSUE TITLE
Unable to use `gs`, `gt` shortcuts to go to sent and trash emails respectively on gmail account

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/mutt-wizard#959]
Hi,

I have a gmail institutional account that I use for email and noticed when running neomutt, the binds `gs`, `gt`, etc. don't go to sent, trash emails respectively. I get the following error message: `/home/ashish/.local/share/mail/<EMAIL>/Sent is not a mailbox` when pressing `gs` for instance.

Upon inspecting the maildir folders, I notice that they've been kept at `~/.local/share/mail/<EMAIL>/[Gmail]/'Sent Email'` and `~/.local/share/mail/<EMAIL>/[Gmail]/Bin` respectively. Even though the account specific neomuttrc contains the lines:
```
set trash = "+Trash"
set record = "+Sent"
```

Not sure why isync labels the folders as such instead of "Sent" and "Trash".

**Comment by tjex** [comment]
I'd say you then need to modify the entries in the `<youremail>.muttrc`. 

e.g. 

`set record = "+[GMAIL]/Sent Email"`

If that doesn't work, then play around with the values. 

The `set record`, `set trash` etc is setting folder paths from the root folder of the account. 

So you need to make sure that the path in your `.muttrc` and the path in your file system match.
