### ISSUE TITLE
Jump to Junk folder in Hotmail

### ISSUE THREAD

**Issue by fcuk112** [LukeSmithxyz/mutt-wizard#96]
When typing gS in hotmail, neomutt does not jump to the Junk folder.  It works for Gmail though.

**Comment by LukeSmithxyz** [comment]
What is the name of Hotmail's junk/spam folder?

If it wasn't autodetected by the wizard, you can just automatically add the shortcut in in the account-specifc muttrc file in the `accounts/` directory.

**Comment by fcuk112** [comment]
The name is Junk.
Thanks for the quick response, I added it manually! ^_^
