### ISSUE TITLE
GPG Decryption Failed even though I have Generated a Key Pair

### ISSUE THREAD

**Issue by Mootikins** [LukeSmithxyz/mutt-wizard#98]
I continually get the "GPG Decryption Failed" error even though I have generated a key already and ensured that the key is installed with `gpg --list-key`.

Doing so immediately lists my key with the email that I used in the script.

I even read the mutt-wizard.sh file and tried running the command myself on personal files without any problems. I also ran the script with sudo to ensure it wasn't an issue of permissions.

**Comment by mrjoedang** [comment]
I have the same issue.

**Comment by chun-hao** [comment]
I have the same problem. In my case (ubuntu 18.04), gpg is in version 2.X. So replacing "gpg2" by "gpg" in the scripts: mutt-wizard.sh, credentials/imappwd.py, credentials/getmuttpass solves the problem.

**Comment by bepolymathe** [comment]
@chun-hao can you explain more... You created a symbolic link between gpg2 and gpg1 ? How ?

**Comment by loweryaustin** [comment]
From the manpage:
```
       --list-keys
              -k --list-public-keys List the specified keys.  If no keys are specified, then all keys from the configured public keyrings are listed.

              Never  use  the  output  of  this command in scripts or other programs.  The output is intended only for humans and its format is likely to change.  The --with-colons option emits the output in a stable, machine-parseable format,
              which is intended for use by scripts and other programs.

       --list-secret-keys
              -K List the specified secret keys.  If no keys are specified, then all known secret keys are listed.  A # after the initial tags sec or ssb means that the secret key or subkey is currently not usable.  We also say that  this  key
              has  been taken offline (for example, a primary key can be taken offline by exported the key using the command --export-secret-subkeys).  A > after these tags indicate that the key is stored on a smartcard.  See also --list-keys.
```
Looks like you are checking for Public Keys, which shows that you have one.


That doesn't necesarily mean that you have a private key. It will fail if you don't have a private key. Can you check that as well @Mootikins

**Comment by bepolymathe** [comment]
Ok, thank. The problem is solve.

**Comment by guhur** [comment]
Following idea from @chun-hao I solved the issue with:

```
sudo ln -s /usr/bin/gpg /usr/bin/gpg2
```

after checking that `gpg --version` provided me a 2.X version
